### ISSUE TITLE
Network Trace - Flag not being sent

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#100]
Here is the request being sent. https://millerwin7.esri.com/arcgis/rest/services/LeakLoggerPlanner/GPServer/Leak%20Logger%20Planner/submitJob?f=json&env%3AoutSR=102100&callback=dojo.io.script.jsonp_dojoIoScript1._jsonpCallback

config

{
  "highlighterDetails": {
    "imageData": "${appPath}/configs/IsolationTrace/imageData.gif",
    "height": 45,
    "width": 45,
    "timeout": 1000
  },
  "geoprocessing": {
    "url": "https://millerwin7.esri.com/arcgis/rest/services/LeakLoggerPlanner/GPServer/Leak%20Logger%20Planner",
    "inputs": [
      {
        "paramName": "Logger_Placement",
        "toolTip": "Logger Locations",
        "type": "Flag",
        "symbol": {
          "angle": 0,
          "xoffset": 0,
          "yoffset": 0,
          "type": "esriPMS",
          "url": "http://static.arcgis.com/images/Symbols/Basic/RedSphere.png",
          "imageData": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAGXRFWHRTb2Z0d2FyZQBQYWludC5ORVQgdjMuNS4xTuc4+QAAB3VJREFUeF7tmPlTlEcexnve94U5mANQbgQSbgiHXHINlxpRIBpRI6wHorLERUmIisKCQWM8cqigESVQS1Kx1piNi4mW2YpbcZONrilE140RCTcy3DDAcL/zbJP8CYPDL+9Ufau7uqb7eZ7P+/a8PS8hwkcgIBAQCAgEBAICAYGAQEAgIBAQCAgEBAICAYGAQEAgIBAQCDx/AoowKXFMUhD3lQrioZaQRVRS+fxl51eBTZUTdZ41U1Rox13/0JF9csGJ05Qv4jSz/YPWohtvLmSKN5iTGGqTm1+rc6weICOBRbZs1UVnrv87T1PUeovxyNsUP9P6n5cpHtCxu24cbrmwKLdj+osWiqrVKhI0xzbmZ7m1SpJ+1pFpvE2DPvGTomOxAoNLLKGLscZYvB10cbYYjrJCb7A5mrxleOBqim+cWJRakZY0JfnD/LieI9V1MrKtwokbrAtU4Vm0A3TJnphJD4B+RxD0u0LA7w7FTE4oprOCMbklEGNrfdGf4IqnQTb4wc0MFTYibZqM7JgjO8ZdJkpMln/sKu16pHZGb7IfptIWg389DPp9kcChWODoMuDdBOhL1JgpisbUvghM7AqFbtNiaFP80RLnhbuBdqi0N+1dbUpWGde9gWpuhFi95yL7sS7BA93JAb+Fn8mh4QujgPeTgb9kAZf3Apd2A+fXQ38yHjOHozB1IAJjOSEY2RSIwVUv4dd4X9wJccGHNrJ7CYQ4GGjLeNNfM+dyvgpzQstKf3pbB2A6m97uBRE0/Ergcxr8hyqg7hrwn0vAtRIKIRX6Y2pMl0RhIj8co9nBGFrvh55l3ngU7YObng7IVnFvGS+BYUpmHziY/Ls2zgP9SX50by/G9N5w6I+ogYvpwK1SoOlHQNsGfWcd9Peqof88B/rTyzF9hAIopAByQzC0JQB9ST5oVnvhnt+LOGsprvUhxNIwa0aY7cGR6Cp7tr8+whkjawIxkRWC6YJI6N+lAKq3Qf/Tx+B77oGfaQc/8hB8w2Xwtw9Bf3kzZspXY/JIDEbfpAB2BKLvVV90Jvjgoac9vpRxE8kciTVCBMMkNirJ7k/tRHyjtxwjKV4Yp3t/6s+R4E+/DH3N6+BrS8E314Dvvg2+/Sb4hxfBf5sP/up2TF3ZhonK1zD6dhwGdwail26DzqgX8MRKiq9ZBpkSkmeYOyPM3m9Jjl+1Z9D8AgNtlAq6bZ70qsZi+q+bwV/7I/hbB8D/dAr8Axq89iz474p/G5++koHJy1sx/lkGdBc2YjA3HF0rHNHuboomuQj/5DgclIvOGCGCYRKFFuTMV7YUAD3VDQaLMfyqBcZORGPy01QKYSNm/rYV/Nd/Av9NHvgbueBrsjDzRQamKKDxT9Kgq1iLkbIUDOSHoiNcgnYHgnYZi+9ZExSbiSoMc2eE2flKcuJLa4KGRQz6/U0wlGaP0feiMH4uFpMXEjBVlYjp6lWY+SSZtim0kulYMiYuJEJXuhTDJ9UYPByOvoIwdCxfgE4bAo0Jh39xLAoVpMwIEQyTyFCQvGpLon9sJ0K3J4OBDDcMH1dj9FQsxkrjMPFRPCbOx2GyfLal9VEcxstioTulxjAFNfROJPqLl6Bnfyg6V7ugz5yBhuHwrZjBdiU5YJg7I8wOpifAKoVIW7uQ3rpOBH2b3ekVjYT2WCRG3o+mIGKgO0OrlIaebU/HYOQDNbQnojB4NJyGD0NPfjA0bwTRE6Q7hsUcWhkWN8yZqSQlWWGECAZLmJfJmbrvVSI8taK37xpbdB/wQW8xPee/8xIGjvlj8IQ/hk4G0JbWcX8MHPVDX4kveoq8ocn3xLM33NCZRcPHOGJYZIKfpQyq7JjHS6yJjcHujLHADgkpuC7h8F8zEVqXSNC2awE69lqhs8AamkO26HrbDt2H7dBVQov2NcW26CiwQtu+BWjdY4n2nZboTbfCmKcCnRyDO/YmyLPnDlHvjDH8G6zhS9/wlEnYR7X00fWrFYuWdVI0ZpuhcbcczW/R2qdAcz6t/bRov4mONeaaoYl+p22rHF0bVNAmKtBvweIXGxNcfFH8eNlC4m6wMWMusEnKpn5hyo48pj9gLe4SNG9QoGGLAk8z5XiaJUd99u8122/IpBA2K9BGg2vWWKAvRYVeLzEa7E1R422m2+MsSTem97nSYnfKyN6/mzATv7AUgqcMrUnmaFlLX3ysM0fj+t/b5lQLtK22QEfyAmiSLKFZpUJ7kBRPXKW4HqCYynWVHKSG2LkyZex1uO1mZM9lKem9Tx9jjY5iNEYo0bKMhn7ZAu0r6H5PpLXCAq0rKJClSjSGynE/QIkrQYqBPe6S2X+AJsY2Ped6iWZk6RlL0c2r5szofRsO9R5S1IfQLRCpQL1aifoYFerpsbkuTImaUJXuXIDiH6/Ys8vm3Mg8L2i20YqsO7fItKLcSXyn0kXccclVqv3MS6at9JU/Ox+ouns+SF6Z4cSupz7l8+z1ucs7LF1AQjOdxfGZzmx8Iu1TRcfnrioICAQEAgIBgYBAQCAgEBAICAQEAgIBgYBAQCAgEBAICAQEAv8H44b/6ZiGvGAAAAAASUVORK5CYII=",
          "contentType": "image/png",
          "width": 18,
          "height": 18
        }
      }
    ],
    "outputs": [
      {
        "paramName": "Overview_Area",
        "type": "Overview",
        "panelText": "",
        "toolTip": "test",
        "summaryText": "",
        "displayText": "",
        "MinScale": 0,
        "MaxScale": 0,
        "exportToCSV": true,
        "saveToLayer": "",
        "symbol": {
          "color": [
            255,
            255,
            255,
            0
          ],
          "outline": {
            "color": [
              220,
              20,
              60,
              255
            ],
            "width": 1.5,
            "type": "esriSLS",
            "style": "esriSLSSolid"
          },
          "type": "esriSFS",
          "style": "esriSFSSolid"
        },
        "bypassDetails": {
          "skipable": false,
          "IDField": ""
        },
        "visible": true
      },
      {
        "paramName": "Overview_Area",
        "type": "Overview",
        "panelText": "",
        "toolTip": "test",
        "summaryText": "",
        "displayText": "",
        "MinScale": 0,
        "MaxScale": 0,
        "exportToCSV": true,
        "saveToLayer": "",
        "symbol": {
          "color": [
            255,
            255,
            255,
            0
          ],
          "outline": {
            "color": [
              220,
              20,
              60,
              255
            ],
            "width": 1.5,
            "type": "esriSLS",
            "style": "esriSLSSolid"
          },
          "type": "esriSFS",
          "style": "esriSFSSolid"
        },
        "bypassDetails": {
          "skipable": false,
          "IDField": ""
        },
        "visible": true
      },
      {
        "paramName": "Logger_Locations",
        "type": "Result",
        "panelText": "Snapped Loc",
        "toolTip": "Snapped Loc",
        "summaryText": "Snapped Loc",
        "displayText": "{LENMAIN}, {ASSET}, {STATUS}, {FACILITYID}",
        "MinScale": 0,
        "MaxScale": 0,
        "exportToCSV": true,
        "saveToLayer": "",
        "symbol": {
          "angle": 0,
          "xoffset": 0,
          "yoffset": 0,
          "type": "esriPMS",
          "url": "http://static.arcgis.com/images/Symbols/Basic/RedBeacon.png",
          "imageData": "iVBORw0KGgoAAAANSUhEUgAAAEAAAABACAYAAACqaXHeAAAAAXNSR0IArs4c6QAAAARnQU1BAACxjwv8YQUAAAAgY0hSTQAAeiYAAICEAAD6AAAAgOgAAHUwAADqYAAAOpgAABdwnLpRPAAACehJREFUeF7tWwlQVecVTl0imwZEeDtvAwRREDUZNxZRUJSomTSOqbumSZtoxCUZndEhrTGisdVpqqhEs7QmnTYmVrtlBARkVVblsRpRo5iAVtRpVGz9es7zXrzDaB4P37vvZeKZ+ebex73/f875/nP/5fw/TzzxWB4z4CoGfEjxOFcpdwe9o8mIIsJP3MEYV9iwhJTeJShcodwddL5LRoAwxh2McYUN+wUCnnOFcnfQ+ReBgNnuYIwrbPjzYwLu9QE/dQX77qBTjIAX3MEYWzakOKG3/ofwCcyxpdzO5y/S+6F2lrH5Og9V/yWkE/rYfLt7L3Cd3Pra7r1u8y0TvZFDsBB4lulwYef5m80iuNvkZTLZ1CrY57R5Bbf8UUFJDV2D7KQ4WGjxNLp+ROA+QMQuul9JSCIMsrNejiKOTm6cVXaWtft1bvlaQRlfbZGgo3feIBQTbgnl2NDvQxs9/5zwPKGvDQvZ+f8J9e2025seFmCnpSToH1APE7WZcEV0VqlQYFpiItYsW4rMzen4dPtvsX9LOv646W1sW5mKX8ycgbERQ+Dx5JNSck5R+QUPsVPa8rt76EuPi0lJOEO1+Etq+hndfy06/mxKCg58+gmunG0Gbn0HdNwGblwD2r4FLpwDvmoE6k4BFcfRceSfsOx6D+nz52BYkE5KxBGqL0KiY4okimR3XrSDSagnZBJ6C/i9aFjylCkoKShAp1xuw3/ysnFl93u4tGYFLv5yES6+sgAXXp6HS6uWom3zBrR/mImOwweAv32B9r0Z2L1gDnQD/UQi2qluHuJYjISThD/0uAkdVPApoR5Puh5i5729vbFzx45Ov++ca0bb9ndxJjke9SEq1Cr7w6LwoSujP2pVAnR+aIgw4MzUCWghgtr3UB0f7kHzhvWYNTxSGg1iR8dDXS8H+fHI1Rxm5zVaLQoLC+85f+cOLr+fgcZnhqJmkAcs6gGoNQaiLlj1YJiV9DwAFo0vLLqBaIoZhYurluH69s24mf4rpE2Mk5Lw6iNb7MAKuPeFRqOBxWK55/ulFpxbOBunyPEarS9qyWl7YCEyaigiLCYFml9IQWvaWnS8tRbpCbEiCZxI4X7A5cI9MTy9vFBSXGx1/vZXp9GUMBbVfv3IARUsZnWPUWNUEIEUDRPHo2XlUnxHfUVqdOfn8A3pdumEjCcsbAQyhG++o+UiGtl5f0/UmDUE9aODSDyp9UdD/BjqOJegdfEcxKqUYiRwUsVlwuM8JiYkWFv+7q1baF7wIiqp5U8Fa3CKnHcUThIJ1UEBaEiKsxKQN3USvPv0EUng5KrsoiSN13r37o2yoiIrAW3v70IFtTwbe5KcdzSqjUqcDNGicfpk/Hv2c3gtxCgSwKOP7MJDEabRWM/Scf4sLKMiUakeiGqTxmmoCqI+YeRQnJ85FQXxY+FNDUB23CE4fPlri9FSJuDz/futBFzathVlA71QRc47FUa1tf5acr4lKR4zFAFiFKy1ZbAjn/O6uyMwIABXaXp7l2Z4dZMTUKb0RSUZ53QYlKiOjsAFGhl+N9gsEsCrVNlkFrf+1MRJwM2buJ6bgwqTFuV6JV01zodBjcrBRjSOG4XsqCHw7NWLSeBFl59cDPyaCVizbJl1YXMpYweOB/ii3EgkyAGDBuVmHWpGRKJqeARCPfqJUTBSLgI4mYHd6enA9WtofnMVSgcNQBk5Lycqh4WhniIgxsdbJGB6TwkYQAV5LOW9ui0EnlxIszXivZhq+owJ2L9tG9D6LZpeWYJiioDjRICcKAsPRlNEKBL7dxIgbrCseIj9++jv6wk8ex1C6Ey2xNKPXHbKBhYJDFvT2R9v2Qx8fR6NLy0mAvzIeZ2sOEHzgIawYEy6HwGch2DJt+FHOz3/gBDYNWJ4Xs2tzHt1zFJXiNlb65bWR+9sBE43oX7xIhQSASUGnawoNRtQF2LCRG8vseHE/QVOkC4lvCZcFwq+TKNrJKF/V8ft/c0JTGxdsQKw1OD0iuUoIAKKiQA5UWrS04ijx9OeHiIB7LgsspoJ+Dnl8FBehrObNqJAFYAig5agkw3Hyfl80qfpa10TcFY4XBbvSUkiE/B0eDhufPkvfLNvH4pDQ1CgVaNQHyQbKkwGfEI6KRfHBJwjeMhFACdAr3L2tnznTlw7eBAVSUnIp5lhAREgCwx61JiMeMPfXwx/7phllYMcBRvmzsXtQ4fQuHo18pQKHKNM7jEiwdkoJAJOGA0Y7tH5/c+T1XtSxiMFBmvUaMncg5aMDJSOGY1cRSDyiQCngpyvoNbPVKlAp6s4Ai4TZJsGi0T3oxtOiWM7RcGNvXtRl5qKPK3uHoL0TsMxvYGm3CbEUBqO9RN48uYSmcsGqJ7yRU3aW2jZ+htUzJyJnEAFcnVByCUSHA5yvspoxibSITjfTldOzrhE+HxfHhsyIzISrRs34vS6dSiJi0e2QomjRMJRIsFh0OtRSi1/iOoNuJ8OS3WJ5xKlg+n+BpPwZnw8WtetR93y5SgaH4NslQY59DnkEAmPDgMKDSbkGYyIvt/xZZNetzhkyYsQa0imxU3AhddTYXnpZRQnTEKO3oQslRbZWj2ydYYeISvISJMrM3L1RsR6dS58eNzXuLr1pfp5b99KwqvRI1A/fyEa5i1EaXIK8iKjkR1kQJY6CFlERBYR0S2Q4zmEE4ZgfEHlRnp4it89Jz+i3MX5ZDJEXCTxAsRqZIxKjb8mTUHj87NQNW06CsfHIndYFLLNoThCTh0hEh4Kei62Orf82wEKBPTuTIE3U/3RgvMJdJU9GSol3rorRODh0Fd4wCuui/x3ztsvMYfg8LhYVCckojp2AoqfGYP8yBE4Gj4U2SFhyDIRIdTCWXozRYmJ5g9mlNLvPLruUGoQdz/kWc+XErLZef7baYKtQxpOCRbpyQzeovaWaFHT/cdiNPgQEcnUihuDB+OziCjkRAxH0ZAolIYORbE5DMXGUBouzfi71oi9Sh1e9xuEqH6d4c5O8tmf1C5e8FmBRkFHd06qOJQEqfPfdzghhrTyURfO21s/DU5gmvt5YLS3D+K8+yOWrrFePtSze0LVp6+4sBG/9RYqw7tPfMzmQdL1pIoskcCHmMQzOd09mcHpJ87b87DF09aHZZ466Bl/438izCdIT508rAWlJPCBCV+HNnWXyvT0+6rgwI4eKhpI5UYQOIEpzThxMiOMwAct7BUmoUqw66C9hbv7Pk84SgQlnBBxN+HF0AHBPk6KOlx4ssMhxglUR4mYvXXkwcblZFw1wVGnTzt95fB01BFZsVJnnRVWkQKG28sP6rS4M9h8TIDQaf0g/l/AGRFg3WIj8G7zj1J4r44J4PXDj1LSBALcZmkrdyvwt8/ZpEfeq5PbcEfp460s3qV1qfwf/MRU1Va7m0cAAAAASUVORK5CYII=",
          "contentType": "image/png",
          "width": 18,
          "height": 18
        },
        "bypassDetails": {
          "skipable": false,
          "IDField": ""
        }
      }
    ]
  }
}

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Can you please a provide the Global URL for the GP Service being used? We are not able to access the following GP Service URL at our end:

https://millerwin7.esri.com/arcgis/rest/services/LeakLoggerPlanner/GPServer/Leak%20Logger%20Planner

**Comment by MikeMillerGIS** [comment]
setting it up for you right now.  Will send all the details in an email.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are not able to reproduce this issue. At our end, flags are being passed as query string parameters. Following is the request being sent:

http://54.214.81.86/arcgis/rest/services/LeakLoggerPlanner/GPServer/Leak Logger Planner/submitJob?f=json&env%3AoutSR=102100&Logger_Placement=%7B%22geometryType%22%3A%22esriGeometryPoint%22%2C%22features%22%3A%5B%7B%22geometry%22%3A%7B%22x%22%3A-9811523.576150227%2C%22y%22%3A5128009.019254665%2C%22spatialReference%22%3A%7B%22wkid%22%3A102100%7D%7D%7D%5D%2C%22sr%22%3A%7B%22wkid%22%3A102100%7D%7D&callback=dojo.io.script.jsonp_dojoIoScript2._jsonpCallback


Can you please provide steps to reproduce this?

**Comment by MikeMillerGIS** [comment]
Not reproducible
