### ISSUE TITLE
make downloaded file names consistent

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#1002]
the names of the downloaded files are inconsistent:

![image](https://user-images.githubusercontent.com/6181441/34536447-025616ba-f07a-11e7-9c6d-914779e566b5.png)

Recommendation:

`<CSVFileName>__<Category>.csv`

**Comment by jmhauck** [comment]
@NikkiGolding this should no longer be the case.

**Comment by jmhauck** [comment]
This is resolved in the current codebase in devtopia
