### ISSUE TITLE
Duplicate: values flagged as different when they are the same

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#1004]
![image](https://user-images.githubusercontent.com/6181441/34540052-ec8b0666-f087-11e7-83ab-380b64e93ed5.png)

**CSV:** 
[MarylandHospitals_993.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601750/MarylandHospitals_993.zip)

**Fields in the CSV that are pushing into the target fields:**
OID
Num_beds

**Repro Steps:**
Used the widget to load the attached CSV data into a target service
Then did it again so that all records would be duplicates -- opened one and saw that even though the data are the same from the user's perspective, they are getting flagged as different

**Comment by aparveen** [comment]
Need to test.

**Comment by aparveen** [comment]
Couldn't replicate.
