### ISSUE TITLE
expected 4 new records but only got 3

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#1005]
With the attached CSV, i only get three items in my matched list, but the csv has four items. two of the items in the csv have the same address -- this is a scenario we need to account for in some way.  Two cases come to mind: 
- the csv has duplicate records
- the facilities are at the same address but different suite/unit numbers and maybe the way the address gets entered for locating it appears the same

[MarylandHospitals_NewOnly.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601829/MarylandHospitals_NewOnly.zip)

**Repro Steps:**

1. Upload the attached CSV and then geocode with single field address option -- FACADDR field
2. After adding to map, note that there are only three in the matched list, but expected 4
![image](https://user-images.githubusercontent.com/6181441/34541520-5b47e1c8-f08d-11e7-9601-235dfa12ab8e.png)

**Alternate Test 1**

1. Add suite numbers into the single line address making them unique -- then i get 4 items
![image](https://user-images.githubusercontent.com/6181441/34541661-ed44fef8-f08d-11e7-856b-cd833c7a2cec.png)

**Alternate Test 2**

1. Add a CSV with duplicate coordinates. In this case - all items are added even if the location information is duplicated
[FL_AG_sites.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601862/FL_AG_sites.zip)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo the call to the locator drops duplicate records. I do not believe this is a bug. Only thing I would know to do is test the address values prior to using the locator.

**Comment by aparveen** [comment]
Duplicate issue in devtopia to track this issue. https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12178
