### ISSUE TITLE
Edit item - Map zooms when I don't want it to

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#1006]
When reviewing items, the user will likely zoom the map in or out to help them assess whether changes are required, but when they click the edit button, they are zoomed to the initial extent defined for the item (?).  Instead, don't change the map extent when clicking the Edit button.  

**Repro steps**

1. With attached csv -- locate using coordinates
2. Set field info as necessary
3. Add to map
4. Pick an item from the matched list
5. change the map extent (eg zoom in to verify preferred location for this facility (on a building, at the appropriate entrance, etc)
6. Click to edit >> map is zoomed out and user may not have to zoom in again

**Preferred behavior:** the map extent is not changed when clicking the edit button

![auto_zoom_behavior](https://user-images.githubusercontent.com/6181441/34543144-4dcd1016-f094-11e7-9ad1-368328ab0687.gif)

**Comment by NikkiGolding** [comment]
@jmhauck  I am still seeing this behavior.

**Comment by jmhauck** [comment]
@NikkiGolding oops I should have looked closer. I was testing a workflow with dupliactes and it was set to only make the feature flash and not do the zoom so I thought I was not seeing this issue when stepping through some issues for our review yesterday. However, I do still see this for matched or un-matched features. I will update accordingly.

**Comment by jmhauck** [comment]
@NikkiGolding ready to be verified

**Comment by NikkiGolding** [comment]
verfied
