### ISSUE TITLE
Edit item: move location doesn't update coordinates

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#1007]
If a location was located with coordinates, after editing and manually moving the location, the coordinates in the location information section are not updated.

**Repro Steps**

1. With the provided csv, add to widget using coordinates to locate items
2. choose fields for field information
3. add to map
4. Review an item and click edit
5. Change the location of the point by dragging the point on the map >> note the coordinates in "Review address information" are not updated

![move_point_update_coordinates](https://user-images.githubusercontent.com/6181441/34543417-8b47ec26-f095-11e7-9bbd-ac977966fb7c.gif)

**Comment by jmhauck** [comment]
@NikkiGolding ready to be verified

**Comment by NikkiGolding** [comment]
Verified
