### ISSUE TITLE
Duplicate Features - Sync enabled unexpectedly

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#1009]
-[Webmap](http://stategovernment.maps.arcgis.com/home/item.html?id=2e0eabc48eed4c6aa4a75efcfc9c16f2)

- Widget Config: 

![image](https://user-images.githubusercontent.com/4106968/35007145-eb210446-fab5-11e7-89ec-8feb67197a62.png)

- Data:

 [MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1636425/MarylandHospitals.zip)

- Repro Steps:

1. Drag hospitals spreadsheet onto the widget 

2. Location Settings -  Locate using an address
3. Select Multiple Fields use the settings reflected below
![image](https://user-images.githubusercontent.com/4106968/35007259-5a97ac26-fab6-11e7-96dc-ea362b531195.png)
Note  All Seven Records are matched

3. Repeat the exact same workflow above

- Note1 duplicate feature is detected

- Select Review duplicate feature

- Enable editing
- select item type: is duplicate make changes

- Note Sync is enabled, yet none of the address information is exposed. In other words, the minumum criteria to expose sync (as i understand it) do not exist. 

 
![image](https://user-images.githubusercontent.com/4106968/35007864-00bb75d2-fab8-11e7-9383-5a94246796ab.png)

**Comment by jmhauck** [comment]
@NikkiGolding ready to be verified

**Comment by NikkiGolding** [comment]
Verified.
