### ISSUE TITLE
Network Trace - 2 polygon output parameters

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#101]
Not saving in config correctly
![image](https://cloud.githubusercontent.com/assets/2707285/6849665/fe564dda-d3aa-11e4-87d7-de2e48d42044.png)
 "outputs": [
      {
        "paramName": "Overview_Area",
        "type": "Overview",
        "panelText": "",
        "toolTip": "test",
        "summaryText": "",
        "displayText": "",
        "MinScale": 0,
        "MaxScale": 0,
        "exportToCSV": true,
        "saveToLayer": "",
        "symbol": {
          "color": [
            255,
            255,
            255,
            0
          ],
          "outline": {
            "color": [
              220,
              20,
              60,
              255
            ],
            "width": 1.5,
            "type": "esriSLS",
            "style": "esriSLSSolid"
          },
          "type": "esriSFS",
          "style": "esriSFSSolid"
        },
        "bypassDetails": {
          "skipable": false,
          "IDField": ""
        },
        "visible": true
      },
      {
        "paramName": "Overview_Area",
        "type": "Overview",
        "panelText": "",
        "toolTip": "test",
        "summaryText": "",
        "displayText": "",
        "MinScale": 0,
        "MaxScale": 0,
        "exportToCSV": true,
        "saveToLayer": "",
        "symbol": {
          "color": [
            255,
            255,
            255,
            0
          ],
          "outline": {
            "color": [
              220,
              20,
              60,
              255
            ],
            "width": 1.5,
            "type": "esriSLS",
            "style": "esriSLSSolid"
          },
          "type": "esriSFS",
          "style": "esriSFSSolid"
        },

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We investigated on this and found that, if there is more than one output parameter of polygon type in GP service, then all are set as "Overview" in the config.

This would no longer be an issue after the implementation of #95 (Redesign of Overview)

**Comment by MikeMillerGIS** [comment]
verified
