### ISSUE TITLE
Duplicate Features - Features arent being detected as duplicate

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#1010]
-[Webmap](http://stategovernment.maps.arcgis.com/home/item.html?id=2e0eabc48eed4c6aa4a75efcfc9c16f2)

- Widget Config: 

![image](https://user-images.githubusercontent.com/4106968/35007145-eb210446-fab5-11e7-89ec-8feb67197a62.png)

- Data:

 [MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1636425/MarylandHospitals.zip)

- Repro Steps:

1. Drag hospitals spreadsheet onto the widget 

2. Location Settings -  Locate using an address
3. Select Multiple Fields use the settings reflected below
![image](https://user-images.githubusercontent.com/4106968/35007259-5a97ac26-fab6-11e7-96dc-ea362b531195.png)
Note  All Seven Records are matched

3. Repeat the exact same workflow above

- Note only 1 duplicate feature is detected

**Comment by jmhauck** [comment]
@NikkiGolding ready to be verified

**Comment by NikkiGolding** [comment]
verified.
