### ISSUE TITLE
Feature Collection pop-up definition-re-evaluate what we expose

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#1011]
The feature collection popup information exposes all of the details for baseline attribute information, information we use for geocoding and our own internal information. We need to reevaluate what we want exposed. 

![image](https://user-images.githubusercontent.com/4106968/35008292-34ecbf0e-fab9-11e7-8b87-9cf66ac3cc14.png)

**Comment by aparveen** [comment]
This is already fixed.
