### ISSUE TITLE
Duplicate Feature Worfklow - Re-evaluate

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#1012]
Per Jess from #977 

after fixing a duplicate with "is duplicate make changes", the item isn't moved to a 'matched' list so that it can be submitted.

**CSV:** [MarylandHospitals_993.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601773/MarylandHospitals_993.zip)

**Repro Steps:**

1. submitted the attached csv to a target service, then loaded it into the widget again so that all items would be duplicated
2. open one of the duplicate items from the list
3. change action to "is duplicate make changes"
4. click to edit
5. make changes (seems like it doesn't matter what kind of change is made)
6. save changes
7. go back to main list screen >> notice that there is not a "matched" list and changes can't be submitted

![duplicate_list_mgmt](https://user-images.githubusercontent.com/6181441/34540751-86c84638-f08a-11e7-93aa-fbb2c1b5be31.gif)

Also noticed that if i change location information so that it needs to geocode a new address (from file for example), the point is located, but the map does not zoom to the new location.

**Comment by NikkiGolding** [comment]
Per John from #977 

We can discuss this more but since "is duplicate make changes" option was selected, on save the feature is flagged for an update call rather than adding a new feature to the service. The submit button is a problem as it should enable when one or more changes are made to the duplicate features like this rather than just when 1 or more features exist in the matched layer.

**Comment by jmhauck** [comment]
Can no longer reproduce
