### ISSUE TITLE
Unable to Submit Features

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#1013]
Using the schools csv, I am unable to submit any features. 

Webmap ids I tried and reproduced the behavior with several webmaps. ID below reflects one. 
2e0eabc48eed4c6aa4a75efcfc9c16f2

Use the multi field address workflow. Note all features are placed on the map. 
Click submit 
Error: Unable to locate features as reflected below

![image](https://user-images.githubusercontent.com/4106968/35308971-6bc5fed8-0067-11e8-9fea-89b84407c88f.png)

[SchoolsSmall.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1658130/SchoolsSmall.zip)

**Comment by jmhauck** [comment]
The popup that asks if the user would like to clear the settings used to occur when the back button was clicked from a particular page and the supporting code was in that page. When I made the recent updates to show this popup when the home button was clicked the supporting code was moved to the home page and I missed one spot where the underlying call to actually clear the settings was being used as a part of submitting the edits.

**Comment by NikkiGolding** [comment]
Verified.
