### ISSUE TITLE
Network Trace - Save to Layer not loading from configuration

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#1015]
https://github.com/Esri/solutions-webappbuilder-widgets/blob/dev/NetworkTrace/setting/outageSetting.js#L166

https://github.com/Esri/solutions-webappbuilder-widgets/blob/dev/NetworkTrace/setting/outputSetting.js#L423

 this.outputLayer.setValue(this.overviewConfig.saveToLayer);
to
 this.outputLayer.setValue(true);

**Comment by previnWong** [comment]
PR https://github.com/Esri/solutions-webappbuilder-widgets/pull/1016

**Comment by MikeMillerGIS** [comment]
- A resolution to a bug in which the Save To Layer check box was not correctly being set in the configuration page

**Comment by MikeMillerGIS** [comment]
verified
