### ISSUE TITLE
Edit-widget - allow interactive geometry editing

### ISSUE THREAD

**Issue by riccardoklinger** [Esri/solutions-webappbuilder-widgets#1026]
### Widget
Edit-widget

### Version of widget
ArcGIS JS API 3.26 current AGOL WAB

### Bug or Enhancement
Enhancement

### Repo Steps or Enhancement details
If I edit the geometry of a point using the edit widget the only possible way is to drag and drop an already drawn point on the map. this can be difficult and does not work for point features with missing coordinates. I want to simply click on the map to recreate the point geometry. Alternatively the input x/y option for point feature classes would be great. You already have the reshape option, so you could add another edit geoemtry option like "replace point", "redraw polygon" "redraw polyline"

**Comment by MikeMillerGIS** [comment]
The edit widget is not maintained through this repo.  This needs to be logged with Esri Tech Support.
