### ISSUE TITLE
Where does GeoLookup CSV go?

### ISSUE THREAD

**Issue by esridoyle** [Esri/solutions-webappbuilder-widgets#105]
Hi There

Ive deployed the GeoLookup Widget to this site http://esri-ireland.azurewebsites.net/webappbuilder/geolookup/ and I can successfully GeoEnrich a CSV. Problem is I don't get the CSV back. Where should I be looking for it?

Eamonn

**Comment by MikeMillerGIS** [comment]
If you open the table before the widget completes, the table does not appear in the attribute table.

**Comment by MikeMillerGIS** [comment]
@previnWong is this still an issue?

**Comment by esridoyle** [comment]
NO. It was a data/useability issue. Sorted.
