### ISSUE TITLE
Service feasibility - Business List Sorting

### ISSUE THREAD

**Issue by phuls** [Esri/solutions-webappbuilder-widgets#110]
The business list returned in the widget seems like there is no specific order. Could we provide a configuration option for how they should be sorted? Like alphabetically for business name or even by spending on current services?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @phuls 
Just a thought, instead of providing a configuration option, how about we provide buttons to sort in asc or desc order on top of business list ? The list can load results by default in either asc or desc order or as returned by service.

About the configuration option, we can provide an additional dropdown with title 'sort order' below the 'Field to be displayed in Business List' parameter with options to select between asc, desc and none.

Please let us know what you think of this.

**Comment by MikeMillerGIS** [comment]
Having sort buttons on the list makes sense, this would allow the user to control how they want to view the results.  @phuls @CTLocalGovTeam

**Comment by phuls** [comment]
@CTLocalGovTeam @MikeMillerGIS Works for me.  I have a feeling eventually users will request the option to view multiple fields in the list and sort by either.  For example, business name and how much they spend on services, but one field and asc or desc option on the widget will solve this issue.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS @phuls,
Please have a look at the mockup that illustrates our proposal for displaying the sort options for Business List.

![image](https://cloud.githubusercontent.com/assets/2959186/7535472/1d66827a-f5a3-11e4-8d04-467e761a6883.png)

We picked this up from a similar implementation in the chart widget configuration UI seen in the graphic below.

![image](https://cloud.githubusercontent.com/assets/2959186/7535490/536f979e-f5a3-11e4-810d-c128e6530cde.png)

Please let us know if this is ok.

**Note:**
Actually, do we need the 'None' option ? We think that we should just display "Asc" or "Desc" and by default it will always be "Asc". And also, we don't feel the need to make this configurable (as suggested earlier) too as its displayed in the UI.

**Comment by MikeMillerGIS** [comment]
I like the design and agree, none is not required, by default ascending should be used and it is not required to be configured.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement the sorting as shown in the mockup with 'Ascending' and 'Descending' options('None' is excluded), by default list is sorted in ascending order. We will include this change in next release.

**Comment by MikeMillerGIS** [comment]
verified
