### ISSUE TITLE
Service feasibility - Add or edit a field when exporting features to layer

### ISSUE THREAD

**Issue by phuls** [Esri/solutions-webappbuilder-widgets#111]
When you save the businesses or the route to a feature layer, can we add the option to edit a field for all the features being exported? If the features are being appended to a feature layer, I would like to know that certain businesses are associated with a route. So being able to edit a Project Name field would allow the end user to name the route, and give the same name to all the businesses along that route.

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam This was not part of the scope, can you please evaluate this request and determine if it is possible.

Change:
Attribute Inspector presented to for route layer - Same concept as overview layer in Network Trace
ID Generated for Route
If Businesses are being saved to layer, route ID is also set on those

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Yes, this is possible.

We can implement this change as follows

1. Provide field mapping configuration between route layer field and corresponding field in business results layer
2. Display attribute inspector for route layer
3. Add edited route layer field(from configured field mapping) to business layer field of businesses passed
4. Save the business and route layer

Please confirm.

**Comment by MikeMillerGIS** [comment]
confirmed

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We implement this and include the change in next release.

**Comment by MikeMillerGIS** [comment]
verified
