### ISSUE TITLE
Network Trace – Clicking on save to layer icon automatically saves the overview area

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#114]
After performing run trace analysis, when user clicks on save to layer icon, save to layer panel is displayed. But overview area is automatically saved on load of save to layer panel. Overview area should be saved only when user clicks on save button in save to layer panel. This will be consistent with save to layer of GP service output parameters.

Overview area is being saved automatically on load of save to layer panel because attribute inspector is being used to save various fields of Overview area layer. Attribute inspector requires Object ID of the feature (i. e. Overview area) to display various fields of Overview area layer. Please investigate alternative implementation approaches which would not have this limitation of attribute inspector.

**Comment by MikeMillerGIS** [comment]
resolved
