### ISSUE TITLE
Service Feasibility – Attribute Value lookup should have default 8 values when widget is being configured for the first time

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#116]
When the widget is being configured for the first time, attribute parameter value lookup should be auto-populated with following 8 values:
* Not used
* Prohibited
* Avoid_High
* Avoid_Medium
* Avoid_Low
* Prefer_High
* Prefer_Medium
* Prefer_Low

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have added the above mentioned options in attribute parameter value lookup and will include this change in next release.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
The value 'Not_Used' is no longer required. It is removed from current implementation.
User can achieve the same effect by unchecking the attribute parameter in config UI.

**Comment by MikeMillerGIS** [comment]
verified
