### ISSUE TITLE
Image Widgets - suitable to demonstrate and how to configure?

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/solutions-webappbuilder-widgets#118]
Are the image widgets suitable to test and demo? If so, how should they be configured? It's not obvious to me by looking at the config files.

@Rrivera5127 @conklinbd

**Comment by nfeuerstein** [comment]
@kerryrobinson - the Image Discovery widget is suitable to test and demo.  The other imagery widgets still need a bit of work, but if you're up for the challenge they can be tested and demo'd as well.

**Comment by conklinbd** [comment]
@kerryrobinson. I have moved the other widgets to a separate branch to make it more obvious which widgets are ready for testing.

**Comment by kerryrobinson** [comment]
Thanks.  Are there any instructions/guidelines on how to use the Image Discovery widget? Any configuration that needs to be made? I'm not sure if it's not working or if I just haven't configured it correctly.

**Comment by conklinbd** [comment]
@kerryrobinson there was a commit made today by @Rrivera5127 if you pulled the widgets prior to that commit you might be missing some files.

**Comment by geozimmy** [comment]
Is the imagery mensuration widget included in those "...other imagery widgets [that] still need a bit of work [?]"

**Comment by kerryrobinson** [comment]
@conklinbd OK, I'll download the latest, but a readme would be nice...

**Comment by nfeuerstein** [comment]
@geozimmy - yes, all imagery widgets in the repo aside from the Image Discovery widget are simply prototypes.  We will create a new branch of this repo for tools in prototype phase.
