### ISSUE TITLE
Network Trace - Isolated Valve Count

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#120]
@MikeMillerGIS 

The count of isolated valves is not accurate. Steps: run the isolation trace, place barrier on one of the valves, rerun trace, isolated valve counts in panel inaccurate (additionally the highlight feature was not updated even though no features were highlighted on the map.
![image](https://cloud.githubusercontent.com/assets/5611508/7263506/f45a3fe4-e836-11e4-86cf-d42d8d108a09.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice We have resolved this issue and included the fix in last release. 
@MikeMillerGIS

**Comment by clareprice** [comment]
@CTLocalGovTeam When a trace is run and then rerun, the number of valves count is not being updated
![image](https://cloud.githubusercontent.com/assets/5611508/7393916/4cd04268-ee45-11e4-9c15-6dfe2c4e30d8.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice Do you want us to show the count of valves including the skipped ones?

With reference to the graphic in the comment above, should it display the count as 3 instead of 2 ?

**Comment by MikeMillerGIS** [comment]
Yes, lets include all valves, regardless of status @CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will show the count of all the valves in the header regardless of status. We will include this change in next release.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, 
Update: The total valve count will be shown regardless of status in two places. For e.g., in the screenshot, the summary as well as valves will display 3 instead of 2. 
Please let us know if this is as expected.

![image](https://cloud.githubusercontent.com/assets/2959186/7798739/895d20a8-031b-11e5-8d23-f7abc670dfb5.png)

**Comment by MikeMillerGIS** [comment]
Correct

**Comment by MikeMillerGIS** [comment]
verified
