### ISSUE TITLE
Network Trace - Unable to save as CSV in Internet Explorer 10

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#121]
@MikeMillerGIS 

When using the network trace in IE 10, unable to export the features to a CSV. The options available to export the features are HTML and .txt. See screen shot when I select export isolated customers to csv
![image](https://cloud.githubusercontent.com/assets/5611508/7263729/15dc32ce-e839-11e4-92f6-4cf96d4dd674.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS As per our earlier discussion, we have observed that this is a default behavior in IE 10. This was the same behavior with the Attribute Table widget from where we referenced the code for “Export to CSV” functionality.	 
@clareprice

**Comment by clareprice** [comment]
@CTLocalGovTeam @MikeMillerGIS Verified the behavior is consistent with attribute widget. Closing
