### ISSUE TITLE
Service Feasibility - Webmap not valid issue

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#124]
Map does not have a point layer, widget should show an error message for "Access Point Layers". No checkboxes are generated if there's no point layer. (just trying with a different services with no point layer)
![image](https://cloud.githubusercontent.com/assets/2707285/7276721/bbff70a8-e8d9-11e4-9c35-1bbbbbc77ab4.png)

Should have similar result to this
access_point_issue2
![image](https://cloud.githubusercontent.com/assets/2707285/7276723/c11775a4-e8d9-11e4-896f-63cb8556d2df.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Configuration widget pulls webmap layer names to display options for business layer and access point layers. These are the required parameters, configuration widget will display a proper message on load if any of these two parameters have no options to display from the selected webmap. 

All other configuration parameters are validated while saving the configuration. Please confirm.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are awaiting further direction on this.

**Comment by MikeMillerGIS** [comment]
I agree, these layers are required and an error should be presented on saving and not letting the widget save.  The error message shown is incorrect.  It should state that access point layers are required, not businesses.  A business layer is selected in the above screen shot.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
The error message graphic shown above was probably meant only to serve as an example to convey that an appropriate message should be shown for access point layers similar to business layers. 

Just to confirm, do we need to display these error message on saving, and not during load of the widget configuration UI? Right now the 'no business' message is displayed on load, and no message is displayed for no access point layers on load. But messages for both are displayed on save.

Our understanding is that if business layer is not available in webmap the "No Business Layer available to continue" message to be displayed on load as well as on save.
If business layer is available, and there are no point layers available in webmap, then "No Access Point Layers available to continue"  message should be displayed on load as well as on save.

**Comment by MikeMillerGIS** [comment]
Yes, we can display the error message only on saving.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will remove the error messages on load.

The widget already displays following messages on saving,
* for no businesses "No Business Layer available to continue"  is displayed.
* no access points "Please select minimum one Access point Layers" (please see screenshot)

![12](https://cloud.githubusercontent.com/assets/2959186/7533137/73d1a3e0-f58c-11e4-8efe-869c758d31d5.PNG)


We will change the error message for no access points to "No Access Point Layers available to continue" on saving.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We have changed the error messages and will be providing it in 6/10 build.

**Comment by MikeMillerGIS** [comment]
verified
