### ISSUE TITLE
Service Feasibility - Configuration Issue

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#125]
If you select any the following checkboxes.  The drop downs to the right are blank.  When you try and save it like this, you get an error.
![tagetbusinesssave](https://cloud.githubusercontent.com/assets/11183838/7125903/cbc7f3da-e1e9-11e4-8357-5ace9044a982.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS When user selects the checkbox for business layer, configuration evaluates for target layer name while saving configuration. If the layer name is not available, its shows an error message.

When webmap has no ediatable layers, save to layer target options for business layer are empty. Similarly for route layer when webmap has no editable polyline layers, save to layer target options are empty. In either case, do you want us to hide the respective section if options are empty.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are awaiting further direction on this.

**Comment by MikeMillerGIS** [comment]
I think we can leave it as is.
