### ISSUE TITLE
Service Feasibility - Widget default size

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#128]
Widget size should be expanded alittle by default or elements in the widget should be reduced. spacing issue.
![widget_size](https://cloud.githubusercontent.com/assets/11183838/7127180/3c6c10ac-e1f5-11e4-8d51-4ac8919b5297.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS,

Just to confirm, the bullets 1, 2, 3 and 4 look equally spaced and the spacing is appropriate too.
Are you asking the buttons 'Find' and 'Clear' to have the same spacing as between the bullets?

**Comment by MikeMillerGIS** [comment]
The box is highlighting that there is a vertical scroll bar when the widget opens,  can the spacing between item 4 and the find/clear buttons be reduced to remove the scroll bar?

**Comment by CTLocalGovTeam** [comment]
We can reduce the spacing between item 4 and Find/Clear buttons. However, if the items are more than 4 nos, a scrollbar will be displayed. This will occur when user configures additional attribute parameter values.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS  We can reduce the spacing between item 4 and Find/Clear buttons. However, if the items are more than 4 nos, a scrollbar will be displayed. This will occur when user configures additional attribute parameter values.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are awaiting further direction on this.

**Comment by MikeMillerGIS** [comment]
Please reduce the space.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will reduce the space between item 4 and Find/Clear buttons. We will include this change in next release.

**Comment by MikeMillerGIS** [comment]
verified
