### ISSUE TITLE
Service Feasibility - Barriers not working

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#129]
Barriers don't seem to work.  Tried point and polygon.  NA result still show path through barriers and showed the business list.
![barriers](https://cloud.githubusercontent.com/assets/11183838/7127360/dbb5ef3c-e1f7-11e4-9969-d239d5861a0f.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are able to reproduce this issue. We will fix this and include the fix in next release.

**Comment by MikeMillerGIS** [comment]
verified
