### ISSUE TITLE
Network Trace - Error Message when text invalid

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#131]
@MikeMillerGIS 

"Invalid display text format in Select Businesses" error message. This message appear for all fields in the layer with the exception of OBJECTID. Fields with different characters and capitalization (besides all caps) needs to be supported for the display text. 
![image](https://cloud.githubusercontent.com/assets/5611508/7278694/ee36a752-e8cb-11e4-8c9f-3d3deb88b61b.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice @MikeMillerGIS We are analyzing this issue and will update soon.

**Comment by CTLocalGovTeam** [comment]
@clareprice We are not able to reproduce this with the latest code drop. Can you please confirm, if you are using the latest code drop because we have renamed the 'Outage' parameter to 'Overview' in Sprint 3 and the screenshot above still shows the label as 'Outage'.

**Comment by clareprice** [comment]
@CTLocalGovTeam Unable to repo this issue with latest code drop. Closing issue.
