### ISSUE TITLE
Network Trace - Unable to cancel creating app until task url set

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#133]
@MikeMillerGIS 

When configuring a network trace, the user is unable to cancel the creation of the widget until the task url has been set. This means that is the Task URL is invalid the user is unable to cancel or simply cancel because they chose the incorrect widget. The only option is to exit the widget, however other widgets in WAB allow the user to cancel as well as exit. 
![image](https://cloud.githubusercontent.com/assets/5611508/7282619/0163a2fc-e8e6-11e4-8f38-35d19cb9697e.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice @MikeMillerGIS We have resolved this issue and included the fix in last release.

**Comment by clareprice** [comment]
@CTLocalGovTeam @MikeMillerGIS Verified this issue. Closing
