### ISSUE TITLE
Network Trace - Create new widget no save cancel icons

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#134]
@MikeMillerGIS 

When the widget is create, there are no save or cancel buttons, they appear only when the user begins to type in the Task URL text box. By default all other widgets in WAB have these right when the widget in created.
![image](https://cloud.githubusercontent.com/assets/5611508/7282683/72f5c684-e8e6-11e4-9398-90201db10268.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice @MikeMillerGIS We have resolved this issue and included the fix in last release.

**Comment by clareprice** [comment]
@CTLocalGovTeam @MikeMillerGIS Verified this issue. Closing
