### ISSUE TITLE
Service Feasibility - Export Options Placement & Add Clear Button

### ISSUE THREAD

**Issue by phuls** [Esri/solutions-webappbuilder-widgets#138]
The placement of the export to layer button does make it clear that you can export the layer and businesses.  Since the button is in the header for Businesses Passed, I think its only for Businesses.  I think it should move below the list of Businesses.  The Export to CSV can stay.  We should also add a clear button on the results tab, that when pressed clears the results and takes you back to the Search tab.
![4-28-2015 4-15-24 pm](https://cloud.githubusercontent.com/assets/6557827/7382409/53e67298-edc3-11e4-8f89-9f6e43f32ee9.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, @phuls The clear button in the results tab would clear business results and also clear the graphics from map. It also resets the search tab to initial/default state. This behavior is same as clicking clear in the search tab. Thus both clear buttons, in search and results tab would behave exactly the same.

Is this Ok ?

**Comment by MikeMillerGIS** [comment]
Yes, the only difference with this clear is it would switch back to the other tab.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Can you please assign this issue to us.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement and include this change in next release.

**Comment by MikeMillerGIS** [comment]
verified
