### ISSUE TITLE
Network Trace - Save To Layer options

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#140]
If an output does not have the "Save to Layer" checked in the configuration, the layer should not appear in the widget. 
![image](https://cloud.githubusercontent.com/assets/5611508/7394136/a8bee9e8-ee46-11e4-9d07-1de64a70dd30.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice  We will investigate and fix this in the next release.
@MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
verified
