### ISSUE TITLE
OK / Cancel buttons not responding to mouse clicks on touch enabled device.

### ISSUE THREAD

**Issue by pjdohertygis** [Esri/solutions-webappbuilder-widgets#144]
Device: YOGA3, Windows 8.1 

When configuring some widgets, the OK and Cancel buttons will not respond to my mouse clicks, only a touch on the screen.

**Comment by conklinbd** [comment]
@pjdohertygis which widgets are you referring to specifically?

**Comment by pjdohertygis** [comment]
Actually, all of them : )

**Comment by conklinbd** [comment]
That sounds like a web app builder framework issue. We will try to raise with the core web app builder team. I am closing the issue for this repository.
