### ISSUE TITLE
Network Trace - Skippable checkbox not being checked when layer is set to skippable in config

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#145]
Enable Skippable on a layer
Click Ok
Open the config dialog again
Skippable is not enabled.

Reviewing the config, it is being saved, just not reloaded to config panel
 "bypassDetails": {
          "skipable": true
        }

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS we are analyzing this issue and will update soon.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are able reproduce this issue. We will fix this issue and include this in next release.

**Comment by MikeMillerGIS** [comment]
verified
