### ISSUE TITLE
Service Qualification - Export to CSV field mapping

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#147]
When export to CSV, field (specifically if an address field has a comma) are not being correctly mapped in the output. This does not occur with the export to CSV in web app builder's attribute table export to CSV. 

![image](https://cloud.githubusercontent.com/assets/5611508/7481014/de9d1348-f321-11e4-9756-550ac42ad802.png)

**Comment by CTLocalGovTeam** [comment]
@clareprice We have fixed this issue and will include the fix in next release

**Comment by MikeMillerGIS** [comment]
verified
