### ISSUE TITLE
Network Trace - Cannot validate existing configuration

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#148]
When a app is configured in another browser, say chrome, and launched in edit mode in FireFox.  The GP service url is not being validated

In chrome, I see these calls to the server
![image](https://cloud.githubusercontent.com/assets/2707285/7518230/b80710da-f4a7-11e4-8fef-bab39a321094.png)

These do not occur in Chrome.

I am using a local service that is registered with Portal
10.3
Firefox 37.0.2

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS,
Do you see this only when the gp service is SSL enabled? What's type of SSL certificate is being used on millerwin7.esri.com (CA signed, Domain, Self)?

We were able to reproduce this with firefox only when the security certificate was self signed and not trusted by the operating system (added as a permanent exception).
![image](https://cloud.githubusercontent.com/assets/2959186/7630270/fb9b6684-fa51-11e4-983a-0c71fc42e2b9.png)

**Comment by MikeMillerGIS** [comment]
It is a domain cert applied to portal.  That does make sense as firefox is picky about certs.  Is there anything to be done or just a known issue?

**Comment by mdomingue** [comment]
Mike,

   I think we have run into a similar problem requiring a CA Cert to be installed.

    /Signed/

Michael A. Domingue, LtCol
JFHQ-NH  J5/Geospatial Manager
Comm (603) 227-1417   DSN 684-9417
FAX (603) 227-1427   DSN 684-9247
Cell  (603) 568-4655

-----Original Message-----

**Comment by MikeMillerGIS** [comment]
Can you raise an error when there is a cert issue?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, it is not possible to identify if there is a cert issue as Javascript does not provide any means of validating certificates. The request to get gpservice info just times out. 

In such cases, whenever the gpservice is unreachable, either due to certificate issue or due to gpservice not running, we can show a message "Unable to load geoprocessing service". This will be sourced from NLS.

Is this is ok?

**Comment by MikeMillerGIS** [comment]
Yes

Sent from my Verizon Wireless 4G LTE DROID
On May 21, 2015 12:17 PM, CyberTech <notifications@github.com> wrote:

@MikeMillerGIS<https://github.com/MikeMillerGIS>, it is not possible to identify if there is a cert issue as Javascript does not provide any means of validating certificates. The request to get gpservice info just times out.

In such cases, whenever the gpservice is unreachable, either due to certificate issue or due to gpservice not running, we can show a message "Unable to load geoprocessing service". This will be sourced from NLS.

Is this is ok?
