### ISSUE TITLE
Service Feasibility - 

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#149]
For the list of attributeParameterValues, we need to set the default value based on what the service is providing.  Also need to display both the attribute name and parameter name.

![image](https://cloud.githubusercontent.com/assets/2707285/7523297/d0fcd446-f4c8-11e4-8b2b-781d4aefaef5.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, 

We can set the default values for attributeParameterValues based on what the service is providing. 

However, we feel it does not make sense to display both the attributeName and parameterName. 

We investigated [this sample routing app](http://54.214.226.84/routesamples/directions.html) that you shared with us initially. The approach followed in the sample app is:

1. In the overall logic that is used in sample routing app, it never makes use of attributes' datatypes
2. The service info provides datatypes only for attributeNames (Height Restriction). It does not provide datatypes for parameterNames (Vehicle Height).
3. It displays the lookup values  (prohibited, avoid_low,...) when `parameterName == Restriction Usage` for all attribute parameter names
4. It displays a number spinner when `parameterName != Restriction Usage`
5. For multiple occurrences of same attributeName, 
  * the parameterName 'Restriction Usage' is displayed with a dropdown of lookup values 
  * parameterNames other than 'Restriction Usage' is displayed with a number spinner and are displayed indented to the same attributeName. 
Please see the below graphic that illustrates this.

Please let us know your thoughts on this.

![image](https://cloud.githubusercontent.com/assets/2959186/7678857/235d669c-fd75-11e4-8c81-da8c86097d11.png)

**Comment by MikeMillerGIS** [comment]
So the second parameter is based on selecting a value for the first it seems, So first you would need to set height restriction to "Yes" and then you can apply a height restriction value.  We should use the same logic as shown in this app.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS That is correct. You would need to set height restriction to any one of the lookup values (Prohibited, Avoid,...), then you can apply a vehicle height value. 

We see two approaches to implement this. 
**Approach A:** The ideal and recommended approach to handle this gracefully is to derive the logic used in the sample app and then modify it to handle cases like [LengthToBusinessRatio](http://54.203.249.87:6080/arcgis/rest/services/A4TC/ServiceQualificationRoute/NAServer/Closest%20Facility), where there are no Restriction Usage parameters. We also need to display Vehicle Height as a sub-item of Height Restriction in config UI as well as widget UI. Dont need to display both attributeName and parameterName in config UI.

**Approach B:** A quick fix is to show min max value boxes in config for all parameters other than Restriction Usage. We can also display both, the attributeName and parameterName in config and widget. However, this will lead to the parameters `Height Restriction: Restriction Usage` and `Height Restriction: Vehicle Height (meters)` behaving independently and not related to each other.

We will provide a detailed description of **Approach A** in the next comment update shortly.

Implementing Approach B will take us 4 days approx. Implementing Approach A will take us longer, about two weeks.

Please confirm. Let us know if you prefer a short call where we could walk you through the approaches.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Here is a description of Approach A.

We have worked out a diagram to illustrate our understanding of how attribute parameter values should work in the widget. Please have a look.

![image](https://cloud.githubusercontent.com/assets/2959186/7702415/8cc0a4ae-fe4d-11e4-8f86-8c29c613ad0c.png)

The config UI would look like this.

![image](https://cloud.githubusercontent.com/assets/2959186/7705523/55ca78a2-fe62-11e4-93ce-50c4df4836b5.png)

Considering the configuration settings in the image above, the widget UI will not display Height Restriction as well as Vehice Height, as it is defaulting to value. It would display Vehicle Weight (with a slider) as a sub-item of Weight Restriction (displayed as dropdown with default value pre-selected). 

We also think that "Not Used" is not required in the list of lookup values, since the checkbox is achieving the same effect and the default value will be pre-selected in the dropdown.

**Comment by MikeMillerGIS** [comment]
I feel approach A is the correct approach.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, We see that there three types of parameters on restriction attributes [from the documentation](http://desktop.arcgis.com/en/desktop/latest/guide-books/extensions/network-analyst/using-parameters-with-network-attributes.htm)

1. Default Restriction Usage parameter (e.g., Oneway, Driving a Bus)
2. Parameters for modeling vehicle characteristics (e.g., Height Restriction & Vehicle Height)
3. Parameters on cost attributes (e.g. LengthToBusinessRatio)

We will be able to support all three types in the following manner in config UI for 'default to value' and 'allow user input' cases. (Please click to view image in full size)

![image](https://cloud.githubusercontent.com/assets/2959186/7724954/caf98562-ff13-11e4-87a8-098dd1300589.png)

**Comment by MikeMillerGIS** [comment]
Looks good.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We have implemented this and will be incorporating in 6/10 release.

**Comment by MikeMillerGIS** [comment]
verified
