### ISSUE TITLE
Service Feasibility - Two parameters with the same name

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#150]
When two parameters are the same name, the widget fails to load and the following error is logged in the console.

Error: Tried to register widget with id==Weight Restriction but that id is already registered {stack: (...), message: "Tried to register widget with id==Weight Restriction but that id is already registered"}
 "Error: Tried to register widget with id==Weight Restriction but that id is already registered

![image](https://cloud.githubusercontent.com/assets/2707285/7523411/8a0cbf5a-f4c9-11e4-804d-55186f7dfa60.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have fixed this issue and will include the fix in next release

**Comment by MikeMillerGIS** [comment]
verified
