### ISSUE TITLE
Service Feasibility - Boolean parameter types

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#151]
Boolean parameter types are being shown list of options - Avoid high, Avoid low, etc.  They should display true/false

![image](https://cloud.githubusercontent.com/assets/2707285/7523500/2861c178-f4ca-11e4-98dd-87c6ad73ade6.png)

![image](https://cloud.githubusercontent.com/assets/2707285/7523512/39bdbe54-f4ca-11e4-8a5e-59959c797125.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS As per our earlier discussions, we wanted to show attribute lookup options(`Prohibited, Avoid High, Avoid Medium, etc.`) for any data type other than integer/double. This is also specified in HLFS and user stories.

Moreover if you look at network dataset attribute for driving a bus, it says it is boolean, 

![image](https://cloud.githubusercontent.com/assets/2959186/7609635/7b68a5c2-f992-11e4-8d19-65b3bfd68687.png)

but if you look at the default attribute parameter value for driving a bus, it is `Prohibited`

![image](https://cloud.githubusercontent.com/assets/2959186/7609636/83c0e824-f992-11e4-81f1-2460aa002c27.png)

Please let us know your thoughts on this. Also, can we please label this issue appropriately.

**Comment by MikeMillerGIS** [comment]
Understood, as designed, closing
