### ISSUE TITLE
Network Trace - TOC and overview results

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#154]
It looks like that each run of the process is creating a new layer in the TOC.  This needs to be removed on clear or a rerun.

![image](https://cloud.githubusercontent.com/assets/2707285/7543719/b8ee80f8-f594-11e4-84e5-b4910f57eaed.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are not able to reproduce this issue. Are you able to reproduce this issue consistently ?

Can you please share the environment details.

**Comment by MikeMillerGIS** [comment]
A new layer is added after each configuration change.
@CTLocalGovTeam 
to repo
1:  Open WAB and Open TOC
2:  Configure Network Trace Widget
3:  Run Widget
4:  Open configuration panel again and save
5:  repeat

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are able to reproduce this issue now and will include the fix in next release.

**Comment by MikeMillerGIS** [comment]
verified
