### ISSUE TITLE
Network Trace - Add Unique ID field for skippable parameter in config UI

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#158]
@MikeMillerGIS, we need to add the unique id parameter for skippable layers, back in the config ui.

This was present in earlier sprints, and asked users to specify a unique ID field for skippable parameter. This parameter was removed, as we had thought of making use of the objectid field internally to identify skipped valves, hydrants etc. However, we are observing that the objectid(oid) values are re-generated for valves, hydrants,... every time the gpservice runs. This is leading to incorrect entities being identified as skipped, as oids do not match between successive runs. Hence, we are suggesting to add the unique id field parameter to be added back.

We will name this parameter "Unique ID Field"  as suggested in issue #73 and also ensure this is sourced from NLS. This will be included in the next release.

Please assign this ticket to us.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We wanted to update you on this that we have gone ahead and fixed this issue. As stated earlier we will make a code drop mid of this week that is on 6/4. Hope this works for you.

**Comment by MikeMillerGIS** [comment]
verified
