### ISSUE TITLE
Network Trace - Widget does not auto-minimize while adding a flag on mobile devices

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#159]
If widget is added to header, auto-minimize works fine.
If widget is added to 'tab' theme, or an in-panel placeholder, auto-minimize does not work. However, it works for 'foldable' theme.

We do not see a standard resolution for this that is applicable for all themes. Hence we recommend that we remove this feature. Please confirm.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

We are awaiting response on this. We'll not include this in the upcoming 6/4 delivery.

**Comment by MikeMillerGIS** [comment]
Leave as is.
