### ISSUE TITLE
Network Trace - Save to layer displays message "No layer selected to save" when there are no results to save

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#160]
@MikeMillerGIS 
If widget is configured with "Save to layer" enabled only for Overview and a trace does not return an overview area, then the Save button should not be enabled.
Currently, it is enabled and if you click Save to layer icon, it shows an empty panel, with save button. On clicking Save, it displays a message "No layer selected to save". 
When there are no results to save, the Save to Layer icon should not be displayed.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We wanted to update you on this that we have gone ahead and fixed this issue. As stated earlier we will make a code drop mid of this week that is on 6/4. Hope this works for you.

**Comment by MikeMillerGIS** [comment]
verified
