### ISSUE TITLE
Bomb Threat - UI gets distorted when facilities results are generated

### ISSUE THREAD

**Issue by AGOL007** [Esri/solutions-webappbuilder-widgets#166]
Steps to reproduce:
1.Add points on map and click on RUN, such that search results are generated.
2.Observe that UI distortion is seen in both modes CONFIG and LAUNCH mode.
 Refer Snapshot.
![image](https://cloud.githubusercontent.com/assets/12759725/8003687/4976fcfa-0b97-11e5-9991-5b33bd54a082.png)

**Comment by jrweakland** [comment]
@jofraley or @kgonzago - can you take a look at this in an upcoming sprint?

**Comment by kgonzago** [comment]
@jrweakland I'll take a look at it.

**Comment by jrweakland** [comment]
:+1:

**Comment by jrweakland** [comment]
@AGOL007

**Comment by AGOL007** [comment]
@jrweakland  Verified the issue working fine. 
Just a question please verify the below image is the UI fine with it ??

![image](https://cloud.githubusercontent.com/assets/12759725/8324440/2ab7f73e-1a6e-11e5-96d9-2d0e52ee3cfc.png)

**Comment by jrweakland** [comment]
@kgonzago
