### ISSUE TITLE
Bomb Threat - Info popup of features get opened on adding explosion locations

### ISSUE THREAD

**Issue by AGOL007** [Esri/solutions-webappbuilder-widgets#168]
Steps to reproduce:

Add the widget in webapp builder
1.Click on 'Draw explosion location'.
2.Click on map where features are present, observe that point gets added on map along with opening info window.

If a user just adds points in map why should an info window get open ? ?

**Comment by jrweakland** [comment]
@kgonzago - can we look at this in the next sprint?

**Comment by kgonzago** [comment]
@jrweakland yes. please add bugs/tasks to next sprint.

**Comment by kgonzago** [comment]
@AGOL007 Are popups being displayed on existing features or on a newly added point (explosion location)?

**Comment by AGOL007** [comment]
@kgonzago  Popups are displayed on existing features on map. When an explosion location is added  on it overlapping the feature .

**Comment by kgonzago** [comment]
@AGOL007 @jrweakland The functionality of adding multiple bomb locations has been implemented, users will probably still want to see popup templates after adding a bomb location or multiple bomb locations.

**Comment by jrweakland** [comment]
@AGOL007 - Please review and provide comments. Thanks!

**Comment by AGOL007** [comment]
@jrweakland  I suppose if the user add bombs on overlapping features popup templates for features should not be seen. I still see the issue in the latest commit refer below snapshot.

![image](https://cloud.githubusercontent.com/assets/12759725/9362623/2e591ca6-46bf-11e5-96b9-8d5c11308f7f.png)
