### ISSUE TITLE
Bomb Threat - Unable to add multiple point bomb locations on map.(Usability issue) 

### ISSUE THREAD

**Issue by AGOL007** [Esri/solutions-webappbuilder-widgets#169]
Steps:
1. Launch the widget, Select any option from dropdown.
2.Click on add point locations and point on map.
3.Observe that only one point can be added on the map.
If the user wants to add multiple point locations in a single goo for a single type, how should he do the same ???

**Comment by jrweakland** [comment]
@kgonzago - this would be a nice enhancement.

**Comment by kgonzago** [comment]
@jrweakland this enhancement will significantly affect the underlying code along with how results are presented in the Demographics and Facilities tabs of the widget. A discussion is needed and this task should be tabled for the next sprint.

**Comment by jrweakland** [comment]
@kgonzago - Agreed. I would like to discuss during sprint planning this week.

**Comment by jrweakland** [comment]
@AGOL007 - Please review and provide comments.

**Comment by AGOL007** [comment]
@jrweakland  Yes I have verified the functionality of adding multiple bombs, it looks good. 
Sorry for the late reply !!
