### ISSUE TITLE
Bomb Threat- Previous facilities results do not get clear,on generating new buffer containing no facilities.

### ISSUE THREAD

**Issue by AGOL007** [Esri/solutions-webappbuilder-widgets#171]
Steps to reproduce:

1.Add points on map and click on RUN, such that search results are generated(facilities).
2.Now without clearing the results, Add another point on map and click on RUN such the results (facilities) are not generated.
3.Now pan to the previous area where results were generated, observe that those are not cleared.

Refer snapshot attached:

![image](https://cloud.githubusercontent.com/assets/12759725/8055614/75904358-0ebe-11e5-8dce-72a5dfa4ff79.png)

**Comment by AGOL007** [comment]
@jrweakland  Hope that the above  steps are understood?
 Do you want any clarification on this issue ?

**Comment by jrweakland** [comment]
@AGOL007 - Looks pretty straight forward to me. @kgonzago please contact AGOL007 if you have any questions.

**Comment by AGOL007** [comment]
Sure
