### ISSUE TITLE
Bomb Threat- Feature highlight occurs for previous buffer.

### ISSUE THREAD

**Issue by AGOL007** [Esri/solutions-webappbuilder-widgets#172]
Steps to reproduce:

1.Add points on map and click on RUN, after buffer gets generated click on the buffer to open the info popup and observe the highlight.
2.Now without clearing the results, Add another point on map and click on RUN.
3.After buffer gets generated zoom out to the extent where previous buffer area and current buffer area can be seen.
4.Now hover the mouse cursor over the new buffer area.Observe that highlight for feature occurs at at the previous location.

Refer attached snapshot:- 

![image](https://cloud.githubusercontent.com/assets/12759725/8056981/fb170924-0eca-11e5-9e66-ed3ea3d13d81.png)

**Comment by kgonzago** [comment]
pull request #202 closes this issue
