### ISSUE TITLE
BatchEditor widget does not works with field OID lowercase character

### ISSUE THREAD

**Issue by fmoraux** [Esri/solutions-webappbuilder-widgets#173]
BatchEditor widget does not works with field OID lowercase character.

If I have layer of FeatureService with lowercase OID field, widget does not work (AttributInspector does not appear). Whereas with uppercase OID field widget work.

To operate the widget I have the correct "_generateHelperLayerFieldsInfos" function.
 
Instead of ==> if (field.fieldName === 'OBJECTID') 
Put ==> if (field.fieldName.toUpperCase() === 'OBJECTID') 

Regards,
FMoraux

**Comment by MikeMillerGIS** [comment]
Thanks for finding the bug,  added that line to the code.
