### ISSUE TITLE
Network Trace - Add Barriers text not fitting

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#175]
![image](https://cloud.githubusercontent.com/assets/2707285/8066302/ed60a7e2-0eb4-11e5-9caa-11270ff70b1b.png)

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/8068613/f3c0447c-0ec2-11e5-9584-7637b5f1ba4c.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by MikeMillerGIS** [comment]
verified
