### ISSUE TITLE
Network Trace - Time not visible when DateTime field has time enabled

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#176]
![dateformat](https://cloud.githubusercontent.com/assets/2707285/8089338/4d3f71dc-0f75-11e5-8808-d1d9da3e8cc5.png)
![notime](https://cloud.githubusercontent.com/assets/2707285/8089339/4d73c018-0f75-11e5-8440-0e06bd428657.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
This looks like an issue with attribute inspector.
The time field shows up only in ArcGIS Map Viewer. It does not show up when you enable time and use 
* Edit widget in Web AppBuilder and 
* When you use the ArcGIS Online Edit template. 

Please see screenshots.

![image](https://cloud.githubusercontent.com/assets/2959186/8177876/d458e8b4-1426-11e5-997c-27099d315084.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8177880/e0194cac-1426-11e5-966e-ce283944ba72.png)

**Comment by MikeMillerGIS** [comment]
You can activate it for the attribute inspector.  The old trace app has the process to do this, I will try to find the code.

**Comment by MikeMillerGIS** [comment]
layerFieldsToFieldInfos: function (layer) {
            var fieldInfo = null;
            if (layer.popupInfo != null) {
                if (layer.popupInfo.fieldInfos != null) {
                    array.forEach(layer.popupInfo.fieldInfos, function (fieldInfo) {
                        if (fieldInfo.format != null) {
                            if (fieldInfo.format.dateFormat != null) {
                                if (fieldInfo.format.dateFormat == "shortDateShortTime" ||
                                    fieldInfo.format.dateFormat == "shortDateShortTime24" ||
                                    fieldInfo.format.dateFormat == "shortDateLEShortTime" ||
                                    fieldInfo.format.dateFormat == "shortDateLEShortTime24")
                                {
                                    fieldInfo.format.time = true;
                                }
                                
                                
                            }
                        }
                    });
                    fieldInfo = layer.popupInfo.fieldInfos;
                }
            }
            if (fieldInfo == null) {
                fieldInfo = array.map(layer.layerObject.fields, function (field) {
                    return {
                        "fieldName": field.name,
                        "isEditable": field.editable,
                        "tooltip": field.alias,
                        "label": field.alias,
                        "format": { "time": true }
                    };
                });
            }
          
            return array.filter(fieldInfo, function (field) {
                return field.visible;
            });
        },
    });

**Comment by MikeMillerGIS** [comment]
The code I use to create the field infos for the layer inspector is above, you can see that it checks the field info and if time is set, it enables the time for the pop up by setting the fieldInfo.format.time = true

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Thanks for sharing. We have updated the network trace widget to use the code block you have shared. It works perfect.

We will update the same code for service feasibility  widget as well. Please confirm.

**Comment by MikeMillerGIS** [comment]
Please do

**Comment by MikeMillerGIS** [comment]
verified
