### ISSUE TITLE
Service Feasibility - Typo in label during widget config

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#178]
![feets](https://cloud.githubusercontent.com/assets/12817527/8093017/f610ef28-0f72-11e5-88ed-53bf5428211a.PNG)
![business](https://cloud.githubusercontent.com/assets/12817527/8093879/7730e72a-0f78-11e5-93bc-d9b302f8d228.PNG)

should be feet, businesses

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by pLeBlanc93** [comment]
verified
