### ISSUE TITLE
Service Feasibility - Typo in nls/strings.js

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#179]
![typo](https://cloud.githubusercontent.com/assets/12817527/8094093/b8783b88-0f79-11e5-8582-6fa1f83cd24b.PNG)

lines 49 & 52: should be "at least" and "search", respectively

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by pLeBlanc93** [comment]
verified
