### ISSUE TITLE
 Service Feasibility - inconsistent capitlization in config 

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#181]
![titlecase1](https://cloud.githubusercontent.com/assets/12817527/8096149/cafb4b56-0f88-11e5-9bbb-a2a19656170f.PNG)
![titlecase2](https://cloud.githubusercontent.com/assets/12817527/8096148/cafaf8e0-0f88-11e5-98a1-ec32cfe489bc.PNG)
![titlecase3](https://cloud.githubusercontent.com/assets/12817527/8096150/caff7488-0f88-11e5-82d8-6517f4f88076.PNG)

Most labels are in title case; some of these are not.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by pLeBlanc93** [comment]
verified
