### ISSUE TITLE
Service Feasibility - missing period in error message

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#182]
![area](https://cloud.githubusercontent.com/assets/12817527/8096496/9b82bb30-0f8c-11e5-9aa6-2bfa77a2d04e.PNG)

Needs period at end to be consistent with other error messages.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by pLeBlanc93** [comment]
verified
