### ISSUE TITLE
Service Feasibility - Wrong error message

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#183]
Message should state that no device can be found.  To repo, pan far south and click anywhere, run process.
![image](https://cloud.githubusercontent.com/assets/2707285/8097997/dc4860cc-0fb7-11e5-94d6-c7d442cf8276.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will change the message to "No devices were found within the search area.". We will include this in next release.

**Comment by MikeMillerGIS** [comment]
verified
