### ISSUE TITLE
Service Feasibility - Progress on Export to CSV

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#184]
When clicking Export to CSV on large datasets(3100 businesses), there is nothing showing that user that they need to wait.  The export took around 1 minute for me and I was not sure if it was working on not

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will update the code to display a loading indicator while exporting to CSV and will include the change in next release.

**Comment by MikeMillerGIS** [comment]
verified
