### ISSUE TITLE
Network Trace - typo in widget config

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#186]
![milli](https://cloud.githubusercontent.com/assets/12817527/8114484/b3523ad6-1029-11e5-9197-767c61fa140a.PNG)

should be milliseconds

Since there are units for time, should a label for pixel units be added to height/width?

**Comment by pLeBlanc93** [comment]
![to](https://cloud.githubusercontent.com/assets/12817527/8114874/6e04b21c-102c-11e5-8977-c94ab204c092.PNG)

case of "to" needs to be consistent throughout

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will fix this issue in next release.

**Comment by pLeBlanc93** [comment]
verified
