### ISSUE TITLE
Network Trace - long run button display text

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#187]
![display](https://cloud.githubusercontent.com/assets/12817527/8115024/80473dfe-102d-11e5-8f7f-986d532e6e8c.PNG)

button does not resize/input not allowed if the text is too long

**Comment by CTLocalGovTeam** [comment]
@pLeBlanc93 @MikeMillerGIS We will fix this issue and include the fix in next release.

**Comment by pLeBlanc93** [comment]
verified
