### ISSUE TITLE
Network Trace - image selection hint

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#188]
![image](https://cloud.githubusercontent.com/assets/12817527/8115172/59e3927e-102e-11e5-8369-36f15192e0eb.PNG)

It was unclear to me that a custom image could be uploaded until I accidentally clicked on it and the open dialog popped up. Adding Hint text to this effect would be useful.

Also, adding a way to reset so that the original .gif is selected might be helpful.

**Comment by CTLocalGovTeam** [comment]
@pLeBlanc93 @MikeMillerGIS We will add hint text for selecting an image in highlight image parameters. We will add this change in next release.

**Comment by pLeBlanc93** [comment]
verified
