### ISSUE TITLE
Service Feasibility - Export Business to Layer

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#190]
You trying to export the business the layer, get the following error
![image](https://cloud.githubusercontent.com/assets/11183838/8135156/cf821c56-10e9-11e5-9869-f9487c6bbf38.png)

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS We have fixed this issue and will include the fix in next release.

**Comment by MikeMillerGIS** [comment]
verified
