### ISSUE TITLE
Service Feasibility - Saving to Layer

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#191]
When performing Saving to Layer, The two buttons on top (Export to Layer and Clear) momentarily show and disappear.  They should not show at all.

![image](https://cloud.githubusercontent.com/assets/11183838/8135199/210c9e34-10ea-11e5-8273-139da9c1b5c3.png)

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS We will fix this issue and include this in next release.

**Comment by MikeMillerGIS** [comment]
verified
