### ISSUE TITLE
Service Feasibility - Inconsistent button colors

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#192]
Some buttons are dark gray, others are light gray.

![image](https://cloud.githubusercontent.com/assets/11183838/8135220/5a9fdf76-10ea-11e5-847a-33a8cd6c9fc0.png)

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS 
The Find and Clear buttons are actually disabled and hence light gray in color. The select location is a tool that needs to show that it is active, hence the dark gray color.

When you add a location on map, the Find and Clear buttons are enabled in dark gray color.

**Comment by MikeMillerGIS** [comment]
Yes, we should match the styles of the jimu-btn

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement this change in Network Trace widget also. Please confirm.

**Comment by MikeMillerGIS** [comment]
Yes, but if it will delay the release, we can mark as a known issue

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have already resolved this for Service Feasibility and we will be able to include this  for Network Trace; both widgets we plan to deliver on Tuesday June 23rd.

**Comment by MikeMillerGIS** [comment]
verified
