### ISSUE TITLE
Network Trace - Highlighter image full path in config

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#200]
After I configure and app and deploy it, the path the image is not correct.  Is there a way to encode the image and save it in the config?  

![image](https://cloud.githubusercontent.com/assets/2707285/8339068/f264eaa8-1a82-11e5-92d8-81b48a0a8849.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
For the default image, although it appears that the url is incorrect, the widget has logic to resolve the path to default image file. 
* It resolves the path to default image file by considering the part after `/webappbuilder/apps/7/`. 
* It also looks for `${appPath}`, if its present then its replaced by application path. This handles cases where the default image is changed.

Please let us know if this makes sense or you'd like this to be implemented differently.

**Comment by MikeMillerGIS** [comment]
ok, I think it is fine for now then, closing the issue
