### ISSUE TITLE
Network Trace - Settings - Default labels for output to Display Name specified in the service

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#204]
![image](https://cloud.githubusercontent.com/assets/2707285/8355814/7ea136ba-1b1f-11e5-8f7d-0e7bbef3a9c8.png)

**Comment by MikeMillerGIS** [comment]
Lets also remove adding the word Add from NLS and make it strictly display the display name in the widget
![image](https://cloud.githubusercontent.com/assets/2707285/8356749/2fbbd39c-1b25-11e5-9c18-80e5c802b5ad.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have removed the prefix 'Add'. However, earlier we were displaying 'Parameter Name' in front of the icons, instead we are now thinking of using 'Display Name' for this.

We are waiting for your approval on this before raising the pull request today.

**Comment by MikeMillerGIS** [comment]
yes, please only show the Display Name
