### ISSUE TITLE
Network Trace - Summary Text enhancement

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#207]
For the summary text, allow the user to select any field and perform stats on it such as Sum of length for lines.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

We can implement this by using a keyword e.g, 'Sum' for the stat operation followed by a colon followed by the fieldname inside curly braces.

![image](https://cloud.githubusercontent.com/assets/2959186/8476819/a1293a8e-20e2-11e5-8345-b785177c1ebe.png)

* This will be applicable only to numeric fields. 
* If used with non-numeric fields, an appropriate error message is displayed. 
* The hint text will be display all numeric fields available in the output layer (as its done in Display text), so users can quickly copy and paste it in the summary text box. 
* Which additional stat operations would you like to be implemented? Please let us know the keyword to use for them.
* We'll ensure the keywords are implemented to be case-insensitive
* If you'd like only sum to be implemented, then there is no keyword required, we could just look for a fieldname in curly braces and display the sum in its place

Please let us know what you think.

**Comment by MikeMillerGIS** [comment]
I am now thinking we need to remove the summary from each result and make a single location to build it.  So the admin can build the summary from the inputs and outputs.

Example:
{Count:flags} locations were placed.  To isolate this area, {Count:valves} are required to be closed.  {Count:Skip locations} valves were bypassed.  {Sum:mains:shapelength} feet of main are affected...

To make this easy to the user, can we have a form where the user sets up these variables maybe?  They can select the layer, the fields, the statistics in them?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Mike, we have created these wireframes to allow users to configure summary text in a single form. Please let us know if these make sense.

![image](https://cloud.githubusercontent.com/assets/2959186/8492998/cdcde542-2170-11e5-8771-17ce4597c823.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8493002/d496b5b6-2170-11e5-8f37-f54298e5431b.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8493003/d89e6faa-2170-11e5-8420-453acda2f530.png)

**Comment by MikeMillerGIS** [comment]
I think it is pretty straight forward and flexible.  I wonder if operators needs to be swapped with fields.  I approve of this design.

**Comment by MikeMillerGIS** [comment]
Can we default to two decimal places?
![image](https://cloud.githubusercontent.com/assets/2707285/10205081/34e8436e-678d-11e5-9e85-c85a36859025.png)

**Comment by MikeMillerGIS** [comment]
One minor issue:  SkipCount shows up for a layer that is not set as skipable.
![image](https://cloud.githubusercontent.com/assets/2707285/10522329/9c1aff0c-7342-11e5-89a5-5f7a0cf95de4.png)
@CTLocalGovTeam

**Comment by MikeMillerGIS** [comment]
Also, If I copy and paste this expression into the box, it says it is invalid, but if I manually create it, it is valid.
{Flags:Count} break locations entered.
{Isolating_Valves:Count} valves required to closed, {Isolating_Valves:SkipCount} skipped.
{Isolated_Customers:Count} meters and {Isolated_Hydrants:Count} hydrants will be out of service.
