### ISSUE TITLE
Network Trace - UX Update - Control to handle input parameters

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#208]
A better UI/UX to handle the inputs(flags and barriers and potentially other inputs feature sets).  
Each input would present a list of it features added
The user could select one and show it on the screen or remove it.  
This would support point, line and polygon feature sets.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Our understanding of this feature is that you would like to list all flags and barriers the user has added to the map. This list will be displayed somewhere in the widget with checkboxes to include/exclude in trace. They will have default labels e.g., Flag 1, Flag 2, Barrier 1, Barrier 2 etc. 

We are thinking of a tabbed interface with two tabs viz., inputs and results. The inputs tab will show all locations user has added to map. The results tab will display the results including the summary. 

Please let us know your thoughts on this.

Can you also please clarify what other potential feature sets are and how will user add them?

**Comment by MikeMillerGIS** [comment]
I think this makes sense.  A tab for inputs.  Each input will have its own list.  I also would like to explore instead of tabs maybe more of a page translation.  The main form has the inputs, say flags, when the user clicks it, the list of flags is shown with a back button.  More of a smart phone design in the widget.  Tabs are OK, but the design takes a lot of real estate.  I wonder since a widget is about the size of a phone, can we use a phone apps design strategy.

As for other input, just thinking about a scenario where the user will have flags, point barriers, polygon barriers, etc.  So we desgin then ui to allow us to add additional inputs

**Comment by MikeMillerGIS** [comment]
* page transition, not translation, can't edit comments on my phone

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Please have a look at these wireframes and let us know if these make sense.

![image](https://cloud.githubusercontent.com/assets/2959186/8480527/db3939c2-20fb-11e5-9437-dc592efa6926.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8480542/ec436daa-20fb-11e5-85ad-2e5b45210a1d.png)

![image](https://cloud.githubusercontent.com/assets/2959186/8480551/01343bcc-20fc-11e5-995a-23aef14632f5.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Deleted above comment. Posted screenshots meant for #207 here by mistake.

**Comment by CTLocalGovTeam** [comment]
We've kept tabs to differentiate the Inputs and Results as this will avoid a few clicks to go back and forth. The list that follows will show all input types and their respective counts.

![inputs](https://cloud.githubusercontent.com/assets/2959186/8500590/4588f294-21bb-11e5-85c9-9f9930da1477.png)

On clicking any of these, the user will be taken to a new page as shown below:

![input list](https://cloud.githubusercontent.com/assets/2959186/8500591/47db4146-21bb-11e5-80f7-25d508d73cda.png)

Let us know what you think.

**Comment by MikeMillerGIS** [comment]
I think we need to change the list from a check box list to a list with the option to delete.  Something like this
![image](https://cloud.githubusercontent.com/assets/2707285/9634505/0900affe-5160-11e5-9531-3b89cf769c73.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

This is a much cleaner UI than checkbox. We presume that the hyperlink is to highlight the item on map.

**Comment by MikeMillerGIS** [comment]
verified
