### ISSUE TITLE
Network Trace - UX Update - Results

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#209]
- A better experience to view the results.  I find the accordion panel hard to navigate and easy to get lost.  
- Option to not have an result list for a result, only show in the summary

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

**A better experience to view the results.**
Currently the accordion displays results for all output layers.
How about we show only one layer at a time. We could either 
* Provide a dropdown below the summary to choose which output layer to see its result set or 
* Transition to a new page when user clicks the accordion titles with a back button. The summary section wont move.

**Option to not have an result list for a result, only show in the summary**
For this we can provide a checkbox for each output in configuration UI

Please let us know what you think.

**Comment by MikeMillerGIS** [comment]
I like the page transitions idea, review my comments on https://github.com/Esri/solutions-webappbuilder-widgets/issues/208.  I think have the results focus on the summary and then tranistions to explore each result set.  The map can even be filtered to only show data in that result set(hide the other results)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

Similar to #208 UX for Inputs, the results mock-ups follow the same page transition pattern. Here the difference is that the summary is displayed in place of the input controls.

![results](https://cloud.githubusercontent.com/assets/2959186/8500596/5090efc0-21bb-11e5-9765-b0855ab60524.png)

And on clicking the result titles, the user is taken to the following page with the list of results:

![result list](https://cloud.githubusercontent.com/assets/2959186/8500606/528ec7d4-21bb-11e5-97d7-4fbd6915e3cb.png)

Let us know what you think about both these mock-ups.

**Comment by MikeMillerGIS** [comment]
They do clean the UI up.  Let me ask the team for feedback.

**Comment by gg7aph** [comment]
These look better - i like the option to push to feature service or csv...

**Comment by MikeMillerGIS** [comment]
verified
