### ISSUE TITLE
1.1 Release?

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#221]
Should we be creating a release of this repository for each release of WebAppBuilder, and including those on the Esri downloads site?

There is currently a V1 Batch Editor and a July 2015 release, but I would expect these to relate to versions of WAB and not points in time.

**Comment by conklinbd** [comment]
We will not do this based on each widget. We need to run this like the GP repo and the GeoEvent repository. @MikeMillerGIS and I can discuss this at UC and see how we want to handle it between us.

**Comment by joebayles** [comment]
:+1:

**Comment by MikeMillerGIS** [comment]
I do not think we should strictly tie releases to WAB releases.  If we are shipping widgets with the solution site release, we could have a release then.  I am also thinking each widget gets its own repo.

**Comment by joebayles** [comment]
If each widget gets it's own repo, I totally agree w/ you.

If we have a repo for all webappbuilder widgets, I maintain that we should have a benchmark release for each version of WAB, though I am OK w/ having them for new versions of individual widgets as well.

**Comment by joebayles** [comment]
I read your comment wrong, I think we're actually in agreement...

**Comment by joebayles** [comment]
Closing this issue, please reopen if anyone feels it's necessary.
