### ISSUE TITLE
Network Trace - Option to not auto zoom after trace

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#223]
When it is run, especially on a mobile device, don’t recenter the map.  It always puts it behind the widget that’s open and I have to pan to see the results it’s given me to where I just panned to place the point.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We are planning to add a configurable option "Auto zoom after trace" as a checkbox. We can place this in the "Other" tab/section. Please confirm.

**Comment by MikeMillerGIS** [comment]
confirmed

**Comment by MikeMillerGIS** [comment]
Is there a way to swap the check box to in front of the text so the text is not cut off?

![image](https://cloud.githubusercontent.com/assets/2707285/9960973/ed054b64-5deb-11e5-82cf-ae8791d2cf5b.png)

**Comment by MikeMillerGIS** [comment]
verified
