### ISSUE TITLE
Service Feasibility - Make Businesses optional

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#225]
Configuration Option to not select or require businesses.  The tool would only find the best route and display the route length

**Comment by HWest-Esri** [comment]
I don't think we even want it to be optional. As far as I know we don't want the salesperson to even have an option to see businesses or use them in the analysis - it simply gives him the shortest route that adheres to the network's criteria.

**Comment by MikeMillerGIS** [comment]
updated enhancement, this is a admin/configuration option

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Our understanding is that you want the business layer selection to be a non-mandatory option in the config UI. 
To address this, we can add a blank entry in the dropdown. If the administrator does not select any layer in the business layer dropdown then, the results panel of the widget will not display businesses passed box and list of businesses. 
Please confirm.

**Comment by MikeMillerGIS** [comment]
Yes, this sounds like a good option

**Comment by MikeMillerGIS** [comment]
Now that I test this, there are other options that refer to the business layer.  This seems odd when you do not select a business layer.  Can we add a section to hide/show the business layer dropdown and when checked the option to save business layer and the other options related to it?

Can we also change the name to SelectionLayer ?

**Comment by MikeMillerGIS** [comment]
Move to a Selection Layer Section the following
   Add a check box to enable this section???
   Selection Layer (currently call Business Layer) dropdown
   Field to be displayed in selection layer results list dropdown

Hide the following when the Selection Layer is not set or check box if used is not enabled
    Field to save business count
    Save To Target layer Businesses layer

@CTLocalGovTeam

**Comment by MikeMillerGIS** [comment]
Also move the Service area parameters into the Selection Layer section as those are only needed for selection of businesses.  The buffer is not needed when no selection layer is used.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

We have mocked up the suggested changes. Please have a look.

![image](https://cloud.githubusercontent.com/assets/2959186/9989885/161008ec-607a-11e5-85e5-9fe8f2766f97.png)

About the Target Layers section, we think it makes sense to let them be together. We can show/hide selection layer options depending on whether it is enabled or not. There's also a situation with "Field to save business count" and "Route-Business Attribute Transfer" options which needs the Route Layer to be checked. Hence, we suggest to retain them in their original place and show/hide them based on whether selection layer is enabled.

![image](https://cloud.githubusercontent.com/assets/2959186/9989904/3206bb7c-607a-11e5-9bd5-56c76ebe0f08.png)

Please let us know what you think.

**Comment by MikeMillerGIS** [comment]
That looks good.  I agree with your target layer conclusion

**Comment by MikeMillerGIS** [comment]
verified
