### ISSUE TITLE
Service Feasibility - Option to turn off Barriers

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#226]
Provide configuration option to hide the ability to draw barriers

**Comment by HWest-Esri** [comment]
This one I think would make a good option. Allows the salesperson some flexibility to accommodate specific customer requests.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We can add an 'Allow Barriers' checkbox in config UI. If left unchecked, then option to draw barriers will not appear in widget UI. Please confirm.

**Comment by MikeMillerGIS** [comment]
Confirmed

**Comment by MikeMillerGIS** [comment]
verified
