### ISSUE TITLE
Service Feasibility - Display a cost instead of route length

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#227]
Option to apply an equation to the cost instead of just cost

i.e. {Length} * 100 /23.5

**Comment by HWest-Esri** [comment]
This would be a great enhancement.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We are thinking of using the JavaScript eval() method to display cost instead of route length. The administrator can configure any arbitrary expression that includes the keyword/token `{Length}` in it.
We can validate the expression to see if it returns a number, else display a validation error message. 

Please let us know your thoughts on this approach.

**Comment by MikeMillerGIS** [comment]
That is fine

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 

![image](https://cloud.githubusercontent.com/assets/2959186/9578701/e1d7c680-5009-11e5-93f6-ba33ac71465e.png)

**Comment by MikeMillerGIS** [comment]
Since we are going to support an equation, we probably need to make these configurable.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Agree. Please have a look at the configuration items we have added and let us know if these look ok.

![image](https://cloud.githubusercontent.com/assets/2959186/9710782/8232b9a4-555b-11e5-9e16-146b117d17e8.png)

**Comment by MikeMillerGIS** [comment]
confirmws

**Comment by MikeMillerGIS** [comment]
With a cost, the units are being cut off, can we use two lines?
![image](https://cloud.githubusercontent.com/assets/2707285/9886777/0b22cb1e-5bba-11e5-9821-4f898be0cf5c.png)

**Comment by MikeMillerGIS** [comment]
Provide an option to show the label before or after the values

So the user can display the result the following ways
$18450.00
or
18450.00 Dollars

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We can add two radio options just below the "Route result unit label" option as shown below. Please confirm.

Result unit label position        () Before        - (x) After

After will be checked by default 

We will use two lines for result + unit label

**Comment by MikeMillerGIS** [comment]
Confirmes

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
verified
