### ISSUE TITLE
Service Feasibility - Hide Access Device list and select closest

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#228]
Configuration Option to not display list of access point layers and have the widget find the closest asset for the list of access point layers

**Comment by HWest-Esri** [comment]
I think that makes sense.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Our understanding is that we need to add an additional option in config UI to support this. 
It can be a checkbox named 'Allow user to select Access Point layer'. 
If left unchecked, it will find nearest asset from all selected access point layers in this list.
Would you like it checked by default?
Please confirm.

**Comment by MikeMillerGIS** [comment]
A checkbox that enables/disables the access point layer combo would work.  unchecked by default.

**Comment by MikeMillerGIS** [comment]
verified
