### ISSUE TITLE
Enable Sourcegraph

### ISSUE THREAD

**Issue by patrobinson81** [Esri/solutions-webappbuilder-widgets#229]
I want to use [Sourcegraph](https://sourcegraph.com) for solutions-webappbuilder-widgets code search, browsing, and usage examples. Can an admin enable Sourcegraph for this repository? Just go to https://sourcegraph.com/github.com/Esri/solutions-webappbuilder-widgets. (It should only take 30 seconds.)

Thank you!

**Comment by lfunkhouser** [comment]
@adgiles Was this inadvertently closed?

**Comment by adgiles** [comment]
Sorry I must have by accident somehow, do we know if its been addressed as its a couple of years old

**Comment by kgonzago** [comment]
@lfunkhouser @adgiles We can close this since we're moving to a repo per widget model.
