### ISSUE TITLE
Network Trace - Disable Valve

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#234]
@MikeMillerGIS @previnWong 

When disabling a valve in the trace, one is selected however all three valves are highlighted in the widget. Only the one point is added to the map
![image](https://cloud.githubusercontent.com/assets/5611508/8987965/8efac708-3698-11e5-9ddf-5efc38b676b1.png)

**Comment by MikeMillerGIS** [comment]
What field did you pick for the id of the valves? @clareprice

**Comment by clareprice** [comment]
@MikeMillerGIS ObjectID. Not an issue with Facility ID.

**Comment by MikeMillerGIS** [comment]
Cant use ObjectID, there is a note that states this, maybe we need to remove the object id field

**Comment by clareprice** [comment]
I think from a user experience, it would be best to remove the object id field. Unless they know then this issue may come up again.

**Comment by MikeMillerGIS** [comment]
verfiied
