### ISSUE TITLE
Network Trace - Overview Layer

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#235]
@MikeMillerGIS @previnWong 

Able to save the overview layer however, when going to save not prompted to input the outage details. No details saved to the layer, including the count of hydrants, valves, customers.
![image](https://cloud.githubusercontent.com/assets/5611508/8988607/0cc2a914-369c-11e5-9e93-d1255debfea3.png)

**Comment by MikeMillerGIS** [comment]
1.2 only?

**Comment by clareprice** [comment]
Correct

**Comment by previnWong** [comment]
I know during one of the betas for 1.2, the attribute "layerInfos" (1.1) got changed to "_layerInfos" (1.2).  WAB team was going to make a fix to handle both, will check if they got implemented or not.  That could be the source of the issue.

**Comment by clareprice** [comment]
@CTLocalGovTeam @MikeMillerGIS 

Verified fix. Closing issue.
