### ISSUE TITLE
Batch Editor - Next/Back Button 

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#237]
@MikeMillerGIS with 1.2 the Next/Back button appearance is affected.
![image](https://cloud.githubusercontent.com/assets/5611508/8989553/ac860dce-36a1-11e5-8f46-bb2901a5d4e0.png)

**Comment by previnWong** [comment]
changed the CSS class for the NEXT and BACK buttons.  will merge code EOD.
