### ISSUE TITLE
Batch Editor - configure page

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#238]
WAB - Dev 1.2
![method](https://cloud.githubusercontent.com/assets/12817527/9010970/1d9c134c-375f-11e5-95b4-b6f29b509ce6.PNG)

Should be *methods* to agree with the phrase "one of the".

Also, the radio buttons should be before the text, not after. Other widgets follow this convention for checkboxes, etc.

![option](https://cloud.githubusercontent.com/assets/12817527/9011194/84762ab6-3760-11e5-855e-95c29055c608.PNG)
Should be *options*.

![colon](https://cloud.githubusercontent.com/assets/12817527/9011289/2da8382c-3761-11e5-921c-e4ea05c0c8ac.PNG)

*Transparency* needs a colon to be consistent with others.

![field](https://cloud.githubusercontent.com/assets/12817527/9011384/d5e8efd6-3761-11e5-83d0-282e09b19986.PNG)

Should be *Field* to be consistent with other headers.

**Comment by previnWong** [comment]
Changed method to methods, option to options, and field to Field in the nls strings.  Moved radio buttons to be in front of the select method description.  The symbol chooser is a jimu dijit, so I'll have to create an issue with the core WAB team to fix.  Other changes will merge EOD.
