### ISSUE TITLE
Service Feasibility - configure page

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#239]
WAB - Dev 1.2

![colon2](https://cloud.githubusercontent.com/assets/12817527/9011667/7f250d68-3763-11e5-825c-e2add5a8e0f7.PNG)

Symbology selection throughout the page does not have consistent colon usage.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS @pLeBlanc93 

The colons are actually defined in the SymbolChooser jimu dijit. We cannot override the internals of this dijit.
