### ISSUE TITLE
Batch Editor - create widget error

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#241]
WAB - Dev 1.2
![widget](https://cloud.githubusercontent.com/assets/12817527/9013033/3fab3a3a-376e-11e5-992d-20df9e39da86.PNG)

Replicating this error is difficult as it only occurs sparingly after saving, launching the app, then clicking on the widget icon. So far, it seems like changing the web map fixes the issue temporarily. However, changing the theme causes it to fail again.

**Comment by previnWong** [comment]
code referenced "esri.bundle.toolbars.draw..." which was never dojo required within the widget.  changed it to
```
define([    'esri/toolbars/draw',...) function(draw)...
draw.addPoint = "Click to select in this area";
 draw.addShape = "Draw a shape to select features";
draw.freehand = "Press and hold to draw a shape to select features";
draw.start = "Draw a shape to select features";
```
