### ISSUE TITLE
Service Feasibility - invalid URL

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#242]
WAB - Dev 1.2
![t](https://cloud.githubusercontent.com/assets/12817527/9013742/b90cbfb2-3772-11e5-8947-4e88a982c428.gif)

This error message only happens sparingly during configuration.
It can be replicated by copy/pasting the service URL and then pressing the *Set* button. Acknowledging the error message and then *Set* button again works.

**Comment by CTLocalGovTeam** [comment]
@pLeBlanc93 @MikeMillerGIS 
We are unable to reproduce this issue. Can you please share the service url that you were using?

**Comment by MikeMillerGIS** [comment]
@pLeBlanc93 Is the URL you are attempting to use require authentication?

**Comment by pLeBlanc93** [comment]
@CTLocalGovTeam @MikeMillerGIS the URL I'm using is http://utility.arcgis.com/usrsvcs/appservices/l899ZNy23ry8eLos/rest/services/World/ClosestFacility/NAServer/ClosestFacility_World

It's the `closestFacility` service proxy that I authenticated on developers.arcgis.com

**Comment by CTLocalGovTeam** [comment]
@pLeBlanc93 Can you let us know the rate limit settings that is configured for this url?

@MikeMillerGIS we are seeing that only the first time, two requests are executed in rapid succession. The first one is to get server info and the second to get service info. We are suspecting the rate limit is set to a very small duration.

**Comment by MikeMillerGIS** [comment]
Going to close as this appears to be a service related issue, but if we discover it is not, we will reopen

**Comment by pLeBlanc93** [comment]
@CTLocalGovTeam @MikeMillerGIS 
In case this issue is run into again..... the rate limit is 1 per second, so yes, very small duration.
