### ISSUE TITLE
Network Trace - Barriers missing in Box controller

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#245]
WAB - Dev 1.2
![box](https://cloud.githubusercontent.com/assets/12817527/9014622/6a67f77c-3778-11e5-81c4-eec99dc108da.PNG)

**Comment by CTLocalGovTeam** [comment]
@pLeBlanc93, @MikeMillerGIS  
We are unable to reproduce this despite trying on WAB dev and WAB final version across all 7 themes.

**Comment by pLeBlanc93** [comment]
Barriers now appears in the box controllers.
