### ISSUE TITLE
Service Feasibility - UI issues with Dart theme

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#251]
@MikeMillerGIS ,

Dart theme overrides the text color on hover.

![123](https://cloud.githubusercontent.com/assets/2959186/9467242/e5bccbda-4b57-11e5-9922-7bc6adbf1851.gif)

Alignment of controls is broken.

![image](https://cloud.githubusercontent.com/assets/2959186/9466919/c2ef90b2-4b55-11e5-9a04-840b729f0401.png)

**Comment by MikeMillerGIS** [comment]
verified
