### ISSUE TITLE
Service Feasibility - Slider jitters

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#252]
@MikeMillerGIS ,

Slider thumb keeps moving when you click and hold on increment buttons. Observed on all themes.

![slider_jewellery_theme_issue](https://cloud.githubusercontent.com/assets/2959186/9467408/1d967ca8-4b59-11e5-8c43-c03fe8acbf28.gif)

**Comment by MikeMillerGIS** [comment]
verified
