### ISSUE TITLE
Service feasibility - Unable to change highlighter image

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#253]
@MikeMillerGIS ,

Highlighter image is expected to be rendered left aligned. However, it is shifted towards the center & on clicking does not open the file chooser dialog box. When user clicks on the expected position of the image it does open the file dialog box.

![image](https://cloud.githubusercontent.com/assets/2959186/9468539/cfcc9852-4b5f-11e5-84f5-51233cd68f18.png)

We have identified a fix for this issue & can club it with upcoming release if required.

**Comment by MikeMillerGIS** [comment]
Please include if possible

**Comment by MikeMillerGIS** [comment]
verified
