### ISSUE TITLE
Service Feasibility - WebMap layer filters not honored by Access point queries

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#258]
If a user defines a filter on the access points in the webmap, the querytask needs to include these in the query to find the closest.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

We analysed this issue and we will include its fix in the upcoming code drop.

**Comment by MikeMillerGIS** [comment]
verified
