### ISSUE TITLE
Network Trace - In IE9 Dart theme UI is distorted

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#260]
@MikeMillerGIS ,

![ie9issue](https://cloud.githubusercontent.com/assets/2959186/9629889/c1ada47a-5193-11e5-90b8-a4c69ef91571.png)

**Comment by MikeMillerGIS** [comment]
Display is not the same on IE as it chrome @CTLocalGovTeam 
Chrome:
![image](https://cloud.githubusercontent.com/assets/2707285/10204895/4e034b74-678c-11e5-9d3c-56fb8dad0baf.png)

IE9
![image](https://cloud.githubusercontent.com/assets/2707285/10204899/56a96894-678c-11e5-8f66-c9501ff3f315.png)

**Comment by MikeMillerGIS** [comment]
verified
