### ISSUE TITLE
Network Trace - Unable to change highlighter image

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#261]
@MikeMillerGIS ,

Highlighter image is expected to be rendered center aligned. However, it is shifted towards the left & on clicking does not open the file chooser dialog box. When user clicks on the expected position of the image it does open the file dialog box.

![hilitedimage](https://cloud.githubusercontent.com/assets/2959186/9630198/2eaecd68-5196-11e5-872d-7b2b6a3ec5ba.png)

**Comment by MikeMillerGIS** [comment]
Should we just change this to a standard symbol selector and get rid of the custom highlighter image?

Sent from my Verizon Wireless 4G LTE DROID

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

That's a good suggestion & design practice. However, to change to a standard symbol selector involves considerable efforts & impact at this stage. After analysing we identified & could easily rectify this problem on our end with a minimal modification. This issue is caused due to a minor css properties.

To be consistent we have resolved similar issue in Service Feasibility #253 which was included in last code drop.

**Comment by MikeMillerGIS** [comment]
@CTLocalGovTeam this is still an issue, I cannot change the image in network trace

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS ,

We have fixed it at our end & provide this in next code drop.

**Comment by MikeMillerGIS** [comment]
verified
