### ISSUE TITLE
Batch Attribute Editor - select by location AND attributes

### ISSUE THREAD

**Issue by DShokes** [Esri/solutions-webappbuilder-widgets#264]
At the moment I am unable to batch edit features in an area that also have specific attribute values. This is a problem for heterogeneous features clustered in groups across a large area. F
Take for example, a feature layer with city trees. Users are not able to batch edit just elm trees inside the polygon they draw.

**Comment by DShokes** [comment]
It would also be awesome to remove/add features to selection before performing the batch edit.

**Comment by MikeMillerGIS** [comment]
@previnWong Can the widget detect a selection set from another widget or a filter set?

**Comment by previnWong** [comment]
@MikeMillerGIS The widget does not use a selection set created outside of the widget.  This should be an enhancement to use a map selection set if available and editable.

**Comment by MikeMillerGIS** [comment]
@previnWong I was even thinking that the select from the batch editor would only select features in a selected set of records, so in the users example, they could run a query or filter to find all Elm trees, then use the lasso to update only the elm tress in a area.

**Comment by previnWong** [comment]
@MikeMillerGIS Ok, I think we expose 2 checkboxes or radios.  1) Update Selected Features and 2) Update subset from selection.

**Comment by previnWong** [comment]
Proposed UI design.
![image](https://cloud.githubusercontent.com/assets/11183838/9742931/55b35786-5618-11e5-9495-1a1988aa7e2c.png)

**Comment by MikeMillerGIS** [comment]
What happens if the selection set is generated while the widget is open?

**Comment by DShokes** [comment]
@previnWong, your design looks as though there would be a global selection set shared between widgets. It looks like the Select by Query widget would create the initial selection set. The popup would appear with updateable attributes defined by this widget. Then the Select by Area widget would have an option to remove features from the selection set. Once the user completes the shape, a new popup would appear with the fields defined by the 2nd widget. Does this sound accurate?

Another scenario involving trees would be editing all elms over a certain diameter (i.e. Species="elm" and Diameter>15). The Batch Attribute Editor Select by Query method only allows for 1 field to be used to filter and the operator can only be "equals". Perhaps this should be a separate issue.

Instead of a global selection set for multiple widgets what if the selection could be refined within the widget? The built in Query widget allows for attribute and spatial filtering at the same time. Could the Batch Attribute Editor widget also accomplish this?

Here is a rough outline of what it could look like for author and end user. 
![widget design](https://cloud.githubusercontent.com/assets/3903212/9754659/2e7d286c-5691-11e5-8120-70ccce26fe95.png)


I hope this is helpful!

**Comment by previnWong** [comment]
@DShokes Thanks for the clarification and the diagrams.  We will take the comments and formulate a solution for the issue proposed.  Will keep you updated.

**Comment by DShokes** [comment]
Any updates on multi-method and selection refinement capabilities?

**Comment by MikeMillerGIS** [comment]
Yes, we have added the filter capability to each layer in the dialog.  So you can use a combination of spatial and attribute selections to refine you selection set.  We are finalizing the UI and we are on schedule to have this widget included in the next release of ArcGIS Online and the Web AppBuilder.

**Comment by DShokes** [comment]
Awesome. Great work!

**Comment by DShokes** [comment]
This looks great! For the select by area workflow, is it possible to include the options of  "new selection", "add to selection", and "remove from selection"? One polygon may not suffice to select all features requiring attribute updates.

**Comment by previnWong** [comment]
@DShokes thanks for the comments that made this enhancement become reality and for such an early adoption of the new enhancements.  I'll take your additional comments and discuss them with the team to determine a plan of action.

**Comment by DShokes** [comment]
Awesome work @previnWong !  Thank you. This widget was the last thing missing for a number of workflows. One last question. As an alternative to the selected features popup, do you think an editable attribute table would fall within the scope of the Batch Attribute Editor?

**Comment by previnWong** [comment]
@DShokes We tried to keep the same editing experience as clicking a feature to edit in ArcGIS Online. Can you provide me a reason or workflow on how a table format would be preferred?

**Comment by DShokes** [comment]
Users would like to change attributes for groups of features, but the desired values  have slight variations. They are looking for spreadsheet-like editing of a field for the selected features. Similar to the editable table in Crowdsource Manager. 

For example, a user wants to enter numeric condition ratings for each selected feature. This rating is influenced by values of other fields, so it is important to see the attributes of every feature. The edit cursor would automatically advance to cell of the next feature. This would allow the user to type "1, {enter or down arrow}, 3, {enter or down arrow}, 1, {enter or down arrow}, 0" and so on. 

![batchtableedits](https://cloud.githubusercontent.com/assets/3903212/11257690/e3f9b0ca-8e18-11e5-98e6-fdde0b370f9a.JPG)

Another example would be subjectively rank 5 features in a number field with values 1 through 5. Table workflows would be much quicker for these situations. This would also open the opportunity to edit feature tables.

If many features need to be updated and the values are not the same, entering values in popups (which  unpredictably appear in new locations on the screen) becomes a slow task.  This is compounded when the values are determined by evaluating other field attributes found in the feature group.
