### ISSUE TITLE
Service Feasibility - Slider not visible in IE9 with Launchpad theme

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/solutions-webappbuilder-widgets#265]
@MikeMillerGIS ,

![image](https://cloud.githubusercontent.com/assets/2959186/9788657/c2cfb23e-57e8-11e5-89b7-03aa467fabf4.png)

We have identified a fix for this & can be easily resolved.

**Comment by MikeMillerGIS** [comment]
verfied
