### ISSUE TITLE
Network Trace - Cannot delete the last flag

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#270]
![image](https://cloud.githubusercontent.com/assets/2707285/9905727/9eec2b0c-5c54-11e5-9bd6-e300174ee1ef.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
This is as designed. At least one flag is required to run the trace. The add flag tool is active in this screen too, so you may add additional flags. 
Clicking the 'Clear' button will remove all flags.

**Comment by MikeMillerGIS** [comment]
Yes, but it what if I could want to keep  the barriers, but remove all the flags and create new ones.  Clear removes barriers and flags.  The trace is not run till you click run so why is there a check to prevent removing all flags

Sent from my Verizon Wireless 4G LTE DROID

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Agree. We will allow removal of all flags. When all flags are removed, the "Run" button will be disabled. Will include this in upcoming code drop.

**Comment by MikeMillerGIS** [comment]
verified
