### ISSUE TITLE
Service Feasibility - Field to save route result expression out

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#272]
We need the ability to save the result expressions value in a field, just like how the user can save the route length.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
We are planning to add another option as highlighted in the mockup below. Please confirm if this is ok.

![image](https://cloud.githubusercontent.com/assets/2959186/9990136/6cc6d4ac-607c-11e5-8a31-2f5edad18196.png)

**Comment by MikeMillerGIS** [comment]
Confirmed

**Comment by MikeMillerGIS** [comment]
verfied
