### ISSUE TITLE
Service Feasibility - Reorder Settings page

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#294]
This widget requires a NA service to work, this should be the first field to fill out in the settings page.  Right now, there are 7 other parameters you define before you get to the define the NA service.
For example, The Attribute lookup section has a hint to refresh the contents based on the Closest facility parameters which are after this section and not yet defined.

![image](https://cloud.githubusercontent.com/assets/11183838/10497381/4e518e44-727a-11e5-82c4-65f54cc77936.png)

**Comment by MikeMillerGIS** [comment]
I agree, @CTLocalGovTeam can we move the order, so the NA service is first?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS @previnWong 
We have mocked up the suggested order. Please have a look and let us know if this is what you had in mind.

![sf configuration](https://cloud.githubusercontent.com/assets/2959186/10545146/dc81f912-7444-11e5-862c-1925f5a3ae3b.png)

**Comment by MikeMillerGIS** [comment]
only change would be to move the Attribute lookup to underneath or inside Closest Facility section

**Comment by previnWong** [comment]
agreed.

**Comment by MikeMillerGIS** [comment]
verified
