### ISSUE TITLE
CI/KR Widget README.md instructions - folder names and paths could be clearer

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-webappbuilder-widgets#304]
CIKR Widget instructions says "In order to develop and test widgets you need to deploy the CI/KR directory to the stemapp/widgets directory in your WebApp Builder installation."

Two issues:
- [x] The CI/KR directory is actually called "CI_KR_Chart"
- [x] Where is the stemapp/widgets directory? Need more of the path.

I copied CI_KR_Chart to "arcgis-web-appbuilder-1.2\server\apps\2\widgets" - I did not immediately see a "stemapp/widgets" directory. This is the wrong place.
When the widget didn't show up in WebApp Builder I looked again and found the right location: \arcgis-web-appbuilder-1.2\client\stemapp\widgets

**Comment by dhagens** [comment]
Fixed with pull request #311
