### ISSUE TITLE
CI/KR Widget README.md includes typo

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-webappbuilder-widgets#305]
CIKR Widget README includes a typo:
"The Critical Infrastructure and Key Resources (CI/KR) widget allows users to determine affected instrastructure and demography based on user-selected location on the map."
"instrastructure" should be "infrastructure".

**Comment by jrweakland** [comment]
@BobBooth - Next time you can clone the repo, make the changes to the typo, and submitt a pull request to fix the issue instead of creating an issue and assigning to Dan.

**Comment by dhagens** [comment]
Fixed with pull request #311
