### ISSUE TITLE
CI/KR Widget README.md "Features" section could use minor edits

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-webappbuilder-widgets#306]
I would suggest:
•	Allows user to designate an affected area on the map
•	Displays affected location, demographic information, and facilities

**Comment by jrweakland** [comment]
This widget is for identifing CR/KR and the area does not need to be affected in order for the idividual to use the widget.

**Comment by dhagens** [comment]
Fixed with pull request #311
