### ISSUE TITLE
CI/KR Widget README.md does not explain what files must be updated

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-webappbuilder-widgets#307]
It would help to explain in the README what files must be updated to point to the two required feature services (demographics and facilities).
- [ ]  config.json has two URLs that the user would update to point to their services.
- [ ]  Widget.html needs the titles of the services updated (e.g. from "title="Texas State Parks"" to something that matches their data).
That may be all - Dan, is that correct?

**Comment by BobBooth** [comment]
Can the widget accept multiple feature services for different types of facilities? It would be nice to include a mention of that (say if I had services for a couple/few facilities) and indicate which files/sections would need updating.

**Comment by dhagens** [comment]
The widget currently works with only two feature services, a demographic service and an infrastructure service.  I will make note of this in the readme.

**Comment by dhagens** [comment]
I updated the code to read the title from the config.json file for each content pane so the only change required when changing services is the service URL and the associated title in the config.  No html change required.  I updated the readme with this info

**Comment by dhagens** [comment]
Fixed with pull request #311
