### ISSUE TITLE
Situation Awareness:  Add "Remove Incident" option in popup

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#317]
Like we have the "Set as incident" option on the bottom of the popup window, we want to add an additional option: "Remove Incident" that becomes available if the incident has already been saved back to the feature service.  Clicking the "Remove Incident" option should then delete that incident feature from the feature service.

**Comment by jmhauck** [comment]
I was not thinking about this all the way through when we talked the other day. We are past string freeze and this would require NLS updates.

**Comment by lindsayking** [comment]
Widget is back in Beta, we were able to go ahead and make string changes.  This change was implemented as a "Delete" button on the feature popup:
![image](https://cloud.githubusercontent.com/assets/4316336/10892712/ede43054-8159-11e5-8280-5506671a7cad.png)
