### ISSUE TITLE
Test Utilities Widgets to ensure they work in Web App Builder 1.0 Final

### ISSUE THREAD

**Issue by conklinbd** [Esri/solutions-webappbuilder-widgets#32]
Need to test the Utilities related widgets to ensure they work in Web App Builder 1.0 Final. 

- [ ] BatchEditor
- [ ] CostAnalysis
- [ ] GeoEnrich

**Comment by MikeMillerGIS** [comment]
2/3 tested

**Comment by MikeMillerGIS** [comment]
closing,
