### ISSUE TITLE
Situation Awareness: summary information display when map service all one layer

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#320]
Using webmap id:f8975f6992554259b35d116d3ba1ab3e, which has map services added to the map at the service level rather than as individual layers:

When the Situation Awareness widget is configured to display summary information, the panel is blank. No summary information displays.

(Webmap id:9db15b830b184db08b8896ab763a9b1f is configured with a lot of the same layers from the same map service, but added separately, and the summary information displays correctly.)

**Comment by previnWong** [comment]
Made a fix for this.  For map services, it loops through and maps feature layers.  The point to the feature layer was wrong.

**Comment by lindsayking** [comment]
Verified.
