### ISSUE TITLE
Network Trace - Flags as Barriers and vice versa

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#325]
During the config, flags can be set to type `Barriers` and barriers can be set to type `Flags`.

**flag as flag, barrier as barrier**:
![correct](https://cloud.githubusercontent.com/assets/12817527/10806725/292e1044-7d95-11e5-9dae-e95b2429a592.gif)

**flag as barrier, barrier as flag** (Note that although I'm choosing barrier, it is indeed a flag because the trace is allowed to run; if the barrier was a barrier, `Run` would be disabled; also note that `Input Locations` is populated; finally, note that the `Barriers` button is on top of `Flags`):
![incorrect](https://cloud.githubusercontent.com/assets/12817527/10806747/60fc9810-7d95-11e5-9bd0-ae3f5f70351b.gif)

Since config validation only permits one each of flags, barrier, and locations, changing these parameters does not work.
![param](https://cloud.githubusercontent.com/assets/12817527/10806791/d5200f56-7d95-11e5-89e1-74c17bde3e3d.PNG)

**Comment by MikeMillerGIS** [comment]
I am not sure we can fix this.  We probably can actually remove the type of flags and barriers and just allow the user to mark a input as the skip.  Then enhance the widget to create a button and label for each input.
