### ISSUE TITLE
ERG - Material menu empty

### ISSUE THREAD

**Issue by tylergotatie** [Esri/solutions-webappbuilder-widgets#353]
While building, the material menu has all the options and the widget can run. Once the app is deployed or launch the menu is empty. Without that menu the widget will not complete.

On further inspection, I'm seeing a 404 on the ERGChemical  and ERGPlacard Services when the widget is opened.

**Comment by conklinbd** [comment]
@kgonzago can you take a look at this?

**Comment by tylergotatie** [comment]
I'm getting an "esriJobFailed" msg in the console when ever the widget just spins and does not complete.

**Comment by kgonzago** [comment]
@conklinbd I'll take a look at it

**Comment by kgonzago** [comment]
@tylergotatie can you tell us more about the web server the app is deployed to? does it have access to the services that's specified in the config.json?

**Comment by tylergotatie** [comment]
Currently I am only testing this app on a laptop and have not deployed. The widget works in the builder but when the app is launched from the builder the widget does not complete. In that case I get the console msg that I mentioned.

**Comment by kgonzago** [comment]
@tylergotatie Have you tried downloading the app as a zip file and deploying it to your laptop? 

Also, I was thinking might be a proxy issue as well. Can you set one up?

**Comment by previnWong** [comment]
Here's a great article about setting up a proxy posted to chatter just today.
http://blogs.esri.com/esri/supportcenter/2015/10/28/setting-up-a-proxy-with-web-appbuilder-for-arcgis-developer-edition/

**Comment by kgonzago** [comment]
@previnWong perfect. thanks for sharing.

**Comment by tylergotatie** [comment]
Thanks for that article @previnWong 
I've already configured WAB to use the proxy I am behind, and as I said the widget works while in "builder mode" but as soon as I preview it by launching I get these errors.

**Comment by kgonzago** [comment]
@tylergotatie checking in with you on this issue. Do you still experience it after deploying the app?

**Comment by tylergotatie** [comment]
@kgonzago I will be deploying tomorrow, sorry for the delay.

**Comment by tylergotatie** [comment]
@kgonzago  I deployed the app and the ERG widget will only complete if Fiddler is running on the web server where the app is hosted. 

If fiddler is not running then the materials menu is blank.

**Comment by tylergotatie** [comment]
I am currently behind a proxy and getting this msg

"Unable to load /dotNetProxy/proxy.ashx?http://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/ERGByChemical/GPServer/ERG%20By%20Chemical?f=json status: 404"

**Comment by kgonzago** [comment]
@tylergotatie thanks for the info. will look into it.

**Comment by kgonzago** [comment]
@tylergotatie Please check out changes were pushed #361. It addresses the proxy issue.

**Comment by tylergotatie** [comment]
@kgonzago  is there a specific line or file in the widget where proxy information should be ?
I cannot get the it to use the correct proxy.ashx

Fix #361 has not fixed my problem yet

**Comment by kgonzago** [comment]
@tylergotatie if you have set up a proxy, you can add the proxy to the config.json of your app. For example, I have a DotNet proxy set up and have specified it in my config.json app 

```json
  "httpProxy": {
    "useProxy": true,
    "url": "/dotnetProxy/proxy.ashx"
  }
```

**Comment by tylergotatie** [comment]
I have follow this 
http://blogs.esri.com/esri/supportcenter/2015/10/28/setting-up-a-proxy-with-web-appbuilder-for-arcgis-developer-edition/

Should I be using "proxyURL" or just "url"

**Comment by kgonzago** [comment]
@tylergotatie Using what was outlined in that link you provided, here is what I have:

```json
  "httpProxy": {
    "useProxy": true,
    "alwaysUseProxy": false,
    "url": "",
    "rules": [{
      "urlPrefix": "http://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/ERGByChemical/GPServer/ERG%20By%20Chemical",
      "proxyUrl": "http://<machineName>/dotNetProxy/proxy.ashx"
      }]
  }
```

**Comment by tylergotatie** [comment]
okay I did that yesterday, after making the change I no longer got the 404, now it is identifying "esri.config.defaults.io.proxyURL" as not set, and mentions CORS.
My urlPrefix ended at the rest, so I will test the full string.

**Comment by kgonzago** [comment]
@tylergotatie are all request need to be performed via a proxy page? if so, this would suffice:

```json
  "httpProxy": {
    "useProxy": true,
    "alwaysUseProxy": false,
    "url": "http://<machineName>/dotNetProxy/proxy.ashx",
    "rules": []
  }
```

also, I added support for CORS in the widget.js. See #366

**Comment by tylergotatie** [comment]
The materials menu is still empty while I am the office network, I can get it to work elsewhere. 
I am getting this message in the console when the widget is launched.
"esri.config.defaults.io.proxyUrl is not set. If making a request to a CORS enabled server, please push the domain into esri.config.defaults.io.corsEnabledServers."

I have set the URL as you instructed in the previous comment, but I have no idea how to push the domain into esri.config.defaults.io.corsEnabledServers.

**Comment by kgonzago** [comment]
@tylergotatie anyway i can contact you directly?

**Comment by kgonzago** [comment]
@tylergotatie Closing this since it's an issue with your customer's network. But please keep us in the loop.
