### ISSUE TITLE
Batch Attribute Editor: Update Progress being Cutoff

### ISSUE THREAD

**Issue by DShokes** [Esri/solutions-webappbuilder-widgets#355]
The update progress column is getting cutoff when feature count reaches triple digits(see photo)
![progress cut off](https://cloud.githubusercontent.com/assets/3903212/11543883/9f441cbc-9904-11e5-8897-60c4c6a1972c.JPG)

**Comment by MikeMillerGIS** [comment]
Resolved, will be deployed in the june release
