### ISSUE TITLE
Projections

### ISSUE THREAD

**Issue by MoniCZ** [Esri/solutions-webappbuilder-widgets#357]
Hi,
I can't find any information regarding projection - in my application, I'm using a basemap in British National Grid (wkid 27700). Points in my CSV have x,y coordinates in the same projection, my polygon feature layer is in British National Grid as well.
I'm just wondering if this widget is only working in Web Mercator projection? My points are not being plot anywhere close to my map extent.

Thanks, Monika

**Comment by conklinbd** [comment]
@MoniCZ which widget are you refering to?

**Comment by MoniCZ** [comment]
I'm sorry, my bad - I'm referring to GeoLookup widget.
________________________________

**Comment by MikeMillerGIS** [comment]
That widget is now included with Web AppBuilder and is no longer managed in this repo.  Could you please log a support incident.
