### ISSUE TITLE
Network Trace - Make Feature Layer vs Copy Features in GP

### ISSUE THREAD

**Issue by raynerhoward** [Esri/solutions-webappbuilder-widgets#359]
The first time I run Trace Upstream (using both the ESRI tutorial data and my own data), it traces upstream and highlights features as expected.  The second time, after clearing results and placing another flag, it traces upstream and highlights features but they show up in Africa.  Each subsequent time it runs, highlighted (traced) features show up in Africa.  It happens from within Web AppBuilder and from within ArcMap when I run the hosted GP service stored on my ArcGIS Server.  No problems running the original tool from within ArcMap except that it wants a different output feature class name after the first run.

The output feature class the first time it is run is in the correct coordinate system (along with all the other data):

![clipboard03](https://cloud.githubusercontent.com/assets/3105035/11692170/8925281e-9e9e-11e5-8eac-1d4823f07417.png)

The second time upstream trace is run, the output is in Web Mercator Auxiliary Sphere:

![clipboard04](https://cloud.githubusercontent.com/assets/3105035/11692194/a75c152c-9e9e-11e5-8987-c48e53d02da9.png)

It was suggested that I use 'Copy Features' rather than 'Make Feature Layer' as the last step in the GP service.  I tried this and it no longer shows the highlighted (traced) features in Africa.  However, it takes much longer to run and for some reason Barriers are ignored.

Running 10.3.1 Desktop, AGS and Portal.  Running Web AppBuilder 1.2 Developer.Edition.

My original post in GeoNet:  https://geonet.esri.com/thread/169159

**Comment by MikeMillerGIS** [comment]
Rayner,
  I posted a response on geonet, please let me know if that fixes the issue.
