### ISSUE TITLE
511 - Update Feature Collection - HIGH

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#369]
Feature Collection needs to be read from the Item ID per the refresh interval

**Comment by jmhauck** [comment]
This is currently working for feature collections that are generated on the fly and doing some final verification for pre-generated feature collections but most of the code is already in place. This should be complete today.

**Comment by jessnoo** [comment]
5 Jan: Tested Feature Collection refresh this afternoon.  Main issue observed is it appears point layers were getting updated in a grouped feature collection, but lines and polygons were not.  In sample below, the Feature Collection has all geometries over north america with 30 features in each points, lines, and polys, but the app reports lines and polys with 20 and over asia... 

![image](https://cloud.githubusercontent.com/assets/6181441/12133410/1bf0036c-b3da-11e5-9112-564cc0c2cb37.png)

**Comment by jmhauck** [comment]
I know we were not seeing it with the initial tests this morning but after looking at the screen shot I was able to repro. The problem would only happen if clustering was enabled on one of the layers. This should be resolved with the commit later today.

**Comment by jessnoo** [comment]
verified with the 5 January merge.  Tested with Points, Lines, and Polys and 511 Sample Set datasets.
