### ISSUE TITLE
511 - Layer rendering/clean up

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#375]
-Utilize configured symbol for graphic rendering 
-Ensure config settings honored if icon is changed
-Cleanup layers that have been removed on re-configure
-Layer re-order on widget change - map specific
-Implement a destroy method to clean up added layers

**Comment by jmhauck** [comment]
The ones left here are "Cleanup layers that have been removed on re-configure" and "Implement a destroy method to clean up added layers".
