### ISSUE TITLE
511- Configuration Options 

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#377]
-Ensure that once settings have been saved they are persisted correctly

**Comment by jmhauck** [comment]
Additional testing is still required here. Have taken care of many of the situations but not all.

**Comment by lindsayking** [comment]
@jmhauck 

Here are scenarios where I am currently seeing settings that do NOT persist.

Custom Icon display in the set symbol panel
1) Open the configuration window for the widget.
2) Add a layer, and then open the Set Symbol dialog for that layer.
3) Under Icon Options, select the 'Upload Custom Icon' option and provide a custom icon for the layer.  Note that the custom icon displays under 'Upload Custom Icon' on the Set Symbol dialog.
4) Click OK to dismiss the Set Symbol dialog.
5) Back on the Configure 511 panel, click the edit button for the same layer to re-open the Set Symbol dialog.  Note that the previously-indicated custom icon does not display under 'Upload Custom Icon' on the Set Symbol dialog.
Note: If you click OK on the Configure 511 panel and then re-open the configuration window entirely, changes made on the Set Symbol panel do persist.

Display of the Refresh Interval box.  
1) Open the configuration window for the widget
2) Add a layer, then check on the Refresh box for that layer.  Note that the Refresh Interval box displays in the configuration window.
3) Set a desired refresh interval in the Refresh Interval box.
4) Finish making any other desired configuration changes, and click OK.
5) Re-open the configuration window.  Note that - even though the layer's Refresh option remains checked - the Refresh Interval box does not display in the configuration window.

**Comment by lindsayking** [comment]
Both of the above scenarios have been resolved.
