### ISSUE TITLE
511-  Cluster options

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#378]
implement cluster options = enabled/disabled and resulting changes from option change

**Comment by jmhauck** [comment]
Option is there and working for enabled/disabled. The main thing that is still missing at this point is to set defaults if they don't open the symbol options dialog. I do set defaults in the dialog but still need it to have a set of options when they don't actually open it that would prevent the widget from failing to load when no explicit option has been chosen by the user. I was thinking in this case clustering would not be enabled and the layers symbol would be used for display in the map and the panel.

**Comment by lindsayking** [comment]
Verified with commit https://github.com/Esri/solutions-webappbuilder-widgets/commit/2f94dbf9f3ee3972ab6aa468d348d705efc61e34.  If clustering is enabled/disabled in the configuration experience, it is honored in the app.  Cluster symbology is also honored.
