### ISSUE TITLE
511 - Service Support

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#379]
-Ensure map/stream/feature etc. are supported types
-Ensure symbol configuration is simple(r)

**Comment by jmhauck** [comment]
I would bet that we still have a few minor issues with this and I need to do some additional testing but in large the code for this should be in place and functioning as expected.

**Comment by lindsayking** [comment]
@jmhauck 

@jessnoo  and I discovered with your commit from Thursday afternoon, if map services are used (added to the map as all one layer, example map id:adbe12ce255948a0a827d5bb6d2b4e69), the layers display initially when the app loads but then they disappear when the widget is activated.  They do not display on the map as long as the widget is active.

**Comment by lindsayking** [comment]
@jmhauck 

With the latest commit (Tuesday afternoon), when using a webmap with map services added as sublayers under a single layer (e.g. webmap id:adbe12ce255948a0a827d5bb6d2b4e69):
1) configure the widget using all 10 layers as data sources for the widget
2) for each layer, click the edit icon to open the set symbol dialog
3) click OK in the set symbol dialog for each layer
4) click okay in the Configure 511 window and launch the app
5) note that when the widget is activated, the layers now display in the app, but 
* the point layers do not turn on/off in the map when they are turned off/on in the widget
* only 8 of the 10 configured layers display.  Load Restrictions and frequented Routes do not display in the widget on the right.

**Comment by lindsayking** [comment]
Question RE: Stream Services:  If a refresh interval is defined in the webmap for a stream layer, and a different refresh interval is indicated for the layer in the 511 widget configuration, how often should the layer refresh when the app is launched?

**Comment by jmhauck** [comment]
I'd think Stream Services should handle their own updates however they are configured outside of the widget. I was thinking about disabling the refresh checkbox for all layers except feature collections. I will also add text when you hover to indicate that option is only supported for feature collections.

**Comment by lindsayking** [comment]
With Tuesday afternoon's commit (https://github.com/Esri/solutions-webappbuilder-widgets/commit/40a61f9be907ed1e3930914fe5dafcbdebdaf09d), when using a webmap containing services added all as one layer, when I add and configure the layers as I'd like, and click OK and then reopen the configuration panel, only the icon/symbol configuration for the first layer listed in the webmap persists.

Steps to repro:
1) Using webmap id: adbe12ce255948a0a827d5bb6d2b4e69, configure the 511 widget with multiple layers.  Be sure to include the 'WorkZones - WidthHeight' layer, which is the first layer listed in the webmap.
2) Note how an icon automatically displays for each configured layer on the configuration panel.
3) Click OK on the configuration panel, then re-open Configure 511 panel by clicking the edit button on the 511 widget.
4) Note that only the 'WorkZones - WidthHeight' layer still has an icon next to it.  If this layer were not included, none of the layers would display an icon on the configuration panel at this point.
![image](https://cloud.githubusercontent.com/assets/4316336/12150718/2b7189d8-b460-11e5-9d29-bfc74e4e2f0e.png)


This appears to only be an issue for webmaps containing map services added as a single layer.  I am not able to repro this behavior with id:e27baf83b5de4c47ad3ba0c1bc0110b9 (map services added as individual layers).

**Comment by lindsayking** [comment]
@jmhauck  -  Thanks for the response RE: refreshing of stream services.

**Comment by jmhauck** [comment]
Please re-check this icon issue. I believe the change for the icon portion of #377 also impacted this. I don't repro with the current code.

**Comment by lindsayking** [comment]
@jmhauck I can still repro with https://github.com/Esri/solutions-webappbuilder-widgets/commit/913adec87a2f9650e3c7a150791b7a3d9c466a6f.

Will try with the latest commit ...

**Comment by lindsayking** [comment]
@jmhauck  I can repro with https://github.com/Esri/solutions-webappbuilder-widgets/commit/c6dd8708ecd29cd83c025ce6c29288edec4819a1 (Wednesday afternoon's commit).

**Comment by lindsayking** [comment]
@jmhauck  I can repro this behavior in FF and IE11, but not in Chrome.

**Comment by lindsayking** [comment]
Verified with commit https://github.com/Esri/solutions-webappbuilder-widgets/commit/2f94dbf9f3ee3972ab6aa468d348d705efc61e34.  Can no longer repro this issue in IE11 or Firefox.
