### ISSUE TITLE
511 - Automatically resize uploaded images - LOW

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#390]
When images are uploaded for the main panel image under “Options”, the images do not automatically resize.  Large images extend beyond the extent of the configuration panel:

![image](https://cloud.githubusercontent.com/assets/4316336/12185252/c13639ac-b54e-11e5-95e9-3a3dff1cd748.png)

And it overlaps with widget panel content when the app is launched:
![image](https://cloud.githubusercontent.com/assets/4316336/12185444/cba04166-b54f-11e5-8dc9-29d0f64b0e7c.png)

**Comment by lindsayking** [comment]
@jmhauck 

After talking with Jianxia about this, the Bookmark widget is a good example for how to resize an uploaded image, so we can use the Bookmark widget as a design example.  My understanding is the cropping component is already present in the developer edition, but it not supported in online.  Regardless, looking at how that widget does this is a good place for us to start here.

**Comment by lindsayking** [comment]
@jmhauck  -  Per our team discussion, we will scale down images that are too large to fit the image panel appropriately, but not scale small images up.  The size of the image panel will remain consistent, and only its presence/absence will be configurable.

**Comment by jmhauck** [comment]
@lindsayking ready to be verified

**Comment by lindsayking** [comment]
Now tracking this issue in devtopia.
