### ISSUE TITLE
511 - Drop-down arrow does not display if using long field names - LOW

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#392]
In the layer pick list, if layer names are too long (e.g. longer than approx 35 characters), the drop-down arrow does not display.

![image](https://cloud.githubusercontent.com/assets/4316336/12187430/c38277ae-b560-11e5-8a60-2783fc610f2f.png)

**Comment by lindsayking** [comment]
Obstruct the text in favor of displaying the drop down arrow.

**Comment by jmhauck** [comment]
Will show like this now: 
![image](https://cloud.githubusercontent.com/assets/2170893/12521075/9c673bae-c105-11e5-9b83-06e0256a5d2b.png)

**Comment by jmhauck** [comment]
@lindsayking ready to be verified in the WAB repo

**Comment by lindsayking** [comment]
@jmhauck  I am now seeing the drop-down arrow at all times, however, if the length of the layer names vary, the length of the drop-down boxes vary slightly.  This is most visible in Firefox and Internet Explorer.

Firefox:
![image](https://cloud.githubusercontent.com/assets/4316336/12556505/083c268c-c33b-11e5-9eec-6e7da6c023a2.png)


Internet Explorer:
![image](https://cloud.githubusercontent.com/assets/4316336/12556491/fafa8450-c33a-11e5-9885-a4bde4bf95f0.png)



Chrome, for comparison.  Note, the last box is only slightly shorter than the others in Chrome.
![image](https://cloud.githubusercontent.com/assets/4316336/12556476/ea465e04-c33a-11e5-9354-a1de72412df0.png)

**Comment by jmhauck** [comment]
@lindsayking ok...will take a closer look at this

**Comment by jmhauck** [comment]
@lindsayking ready to be verified

**Comment by lindsayking** [comment]
@jmhauck  -  Alignment issues are now fixed with latest commit from WAB repo.
