### ISSUE TITLE
511 - with Feature Collections, popup does not display for clustered features

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#393]
When the 511 widget is configured to use a feature collection as a data source, if clustering is enabled on a layer, the popup does not display for that layer.

* For single features that are not part of a cluster, clicking on the feature highlights the feature with a red dot, but the popup does not display.
* For features that are part of a cluster, clicking on the cluster highlights the individual feature locations with multiple red dots, but the popup does not display.
![image](https://cloud.githubusercontent.com/assets/4316336/12187647/6ccdaf76-b562-11e5-8960-4c7b28526b91.png)

In contrast, if the widget is configured with a hosted feature service as its data source, the popup displays:
![image](https://cloud.githubusercontent.com/assets/4316336/12187690/e244e6d4-b562-11e5-9cac-f96019996828.png)

To repro with feature collections:
1) Using webmap id:39701424006c4401b95e25c1ac52acd2, configure the 511 widget with multiple data layers, including the cameras layer
2) Enable clustering on the cameras layer 
3) Launch the application and activate the widget
4) Click on a cluster of camera features - note that red points display but no popup opens
5) Click on a single camera feature - note that it is highlighted with a red point but no popup opens

**Comment by jmhauck** [comment]
@lindsayking ready to be verified in the WAB repo

I also changed it so it would use the renderers symbol for a given graphic...we should discuss this. I thought it would be especially helpful if features with different symbols were in a single cluster feature but we could switch that back pretty easily if it's not desired.

**Comment by lindsayking** [comment]
@jmhauck   This looks good now with commit [9dea54ab4fc519a112df35f608b4ff694a45143f](https://devtopia.esri.com/john4818/arcgis-webappbuilder/commit/9dea54ab4fc519a112df35f608b4ff694a45143f) in the WAB repo.  Leaving this issue open temporarily until we discuss this approach with the team and confirm it is the desired behavior.

**Comment by lindsayking** [comment]
@jmhauck  -  Per our team discussion, let's continue to display the red dots for features that belong to a cluster rather than displaying based on the layer's symbology.

**Comment by lindsayking** [comment]
Now tracking this issue in devtopia.
