### ISSUE TITLE
511 - Make the presence of the image at the top of the widget optional - LOW 

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#396]
Make the presence of the image at the top of the widget optional.

![image](https://cloud.githubusercontent.com/assets/4316336/12212460/7d69396e-b61f-11e5-987e-68397c3ecc38.png)

**Comment by jmhauck** [comment]
@lindsayking ready to be verified

**Comment by lindsayking** [comment]
Now tracking this issue in devtopia.
