### ISSUE TITLE
511 - Widget does not honor outline width of 0 - LOW

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#397]
If a layer is configured through the 511 widget with clustering enabled, and the cluster symbol has an outline width of zero, that outline width is not reflected in the application when the widget is activated.

Steps to repro:
1) Configure the 511 widget with at least one point layer with features somewhat close together (e.g. windspeed or cameras)
2) Open the Set Symbol dialog for that layer and enable clustering
3) Select a cluster symbol with an outline width of zero (see screenshot below)

![image](https://cloud.githubusercontent.com/assets/4316336/12213184/148c98aa-b629-11e5-884f-7872028f782d.png)

4) Launch the app and activate the widget.  Note that as soon as the widget is activated, that layer is highlighted with a cluster symbol that has a massive black outline

![image](https://cloud.githubusercontent.com/assets/4316336/12213225/a5fa24d8-b629-11e5-867b-d130147820fa.png)

**Comment by jmhauck** [comment]
@lindsayking ready to be verified in the WAB repo

**Comment by lindsayking** [comment]
Verified with WAB repo.
