### ISSUE TITLE
511 - Honor symbol aspect ratio when using Symbol as Icon option

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#402]
When clustering is enabled and the "Use Symbol as Icon" option is selected, honor the aspect ratio of the symbol when displayed inside the cluster.

Currently, the symbol looks vertically 'squished' compared to the non-cluster symbol.  This is particularly evident when using the teardrop symbols.

![image](https://cloud.githubusercontent.com/assets/4316336/12245645/ac1a6f80-b85e-11e5-8179-a231c41e5397.png)

**Comment by jmhauck** [comment]
@lindsayking  As I was making changes to support the new size for the panel I made a change for this so it is ready to be verified as well.

**Comment by lindsayking** [comment]
Now tracking this issue in devtopia.
