### ISSUE TITLE
511 - Adjust widget width to meet WAB design guidelines

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#403]
@jmhauck 

After talking with Jianxia, the widget does not currently meet the standard WAB design guidelines.  The width of the widget is too narrow.  It should match the width described in the design guidelines.  The Layer Contents widget is a good example of what width and design guidelines to follow.

**Comment by jmhauck** [comment]
@lindsayking I changed the width to 360px. Also increased the height of each row, size of the icon in the panel, font size of the text and numerical values for count. I believe this should be good now.

**Comment by lindsayking** [comment]
This issue is now being tracked in devtopia.
