### ISSUE TITLE
511 - When custom symbol selected in Icon Options, clicking OK does not close Set Symbol window

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#405]
Steps to repro:
1) Configure the Info Summary widget with at least one data layer.
2) Click the edit button for that layer to open the Set Symbol dialog.
3) Select the "Upload Custom Icon" option under Icon Options.
4) Upload a custom icon.
5) Click OK on the Set Symbol dialog.  Note that clicking OK does nothing.  You must set the Icon Option back to "Use Symbol as Icon" in order to click OK and dismiss the Set Symbol window.

**Comment by jmhauck** [comment]
@lindsayking ready to be verified in the WAB repo

**Comment by lindsayking** [comment]
Verified with the WAB repo.
