### ISSUE TITLE
511 - Script - Simplify configuration experience, pre-configure hosted content

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#407]
To simplify the configuration experience, require that the Feature Service, Feature Collection, (and FGDB??) be published ahead of time and then use those items as script inputs.

Anticipated Configuration Parameters - needs to be validated:
![image](https://cloud.githubusercontent.com/assets/6181441/12458734/27c243f8-bf60-11e5-8a24-073cd6208d06.png)

**Comment by lindsayking** [comment]
This issue is now being tracked in devtopia.
