### ISSUE TITLE
511 - Script - Existing script doesn't overwrite Feature Service

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#408]
The existing script does a delete and then new publishing for the Feature Service.  This causes an issue where the Feature Service item definitions (like sharing) are lost.  The script should do an overwrite to the existing Feature Service --- or, we need to figure out how to maintain the sharing property on the service so that it doesn't go dark ...

**Comment by lindsayking** [comment]
This issue is now being tracked in devtopia.
