### ISSUE TITLE
Network Trace - Hint text alignment

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#410]
@MikeMillerGIS In the ouput configuration panel, the Hint for the skippable parameter on all outputs is not aligned with other Hint text. 

![image](https://cloud.githubusercontent.com/assets/5611508/12585809/7d52d782-c402-11e5-9b85-80d20e7e443c.png)

**Comment by MikeMillerGIS** [comment]
verified
