### ISSUE TITLE
Network Trace - Save to Layer dropdowns

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#411]
@MikeMillerGIS With 1.3 of Web AppBuilder the dropdowns arrows in the save to layer part of the widget are cut off. 
![image](https://cloud.githubusercontent.com/assets/5611508/12585882/ce9e0d14-c402-11e5-82f1-2e88a7d5318f.png)

**Comment by MikeMillerGIS** [comment]
verified
