### ISSUE TITLE
511 - Count values for point features are not updating correctly in widget panel

### ISSUE THREAD

**Issue by lindsayking** [Esri/solutions-webappbuilder-widgets#412]
When clustering is not enabled for point layers, incorrect count values display in the widget panel for those layers.

Steps to repro:
1) Using webmap id:f751d3bcf42c4f94bd6d2e51cd36f565, configure the Info Summary widget with multiple point and line layers
2) Do not enable clustering on any layers
3) Launch the app and activate the widget
4) Pan and zoom on the map.  Note that the count values for point features do not update (or if they do update, they are still incorrect).  This can most easily be seen by panning to an area outside of the study area where there are no features on the map.  Count values on the widget panel will still indicate there are features in the current extent.

Enabling clustering appears to fix this behavior.

**Comment by jmhauck** [comment]
@lindsayking have resolved this and it will be in the commit later today

**Comment by lindsayking** [comment]
Verified with commit https://devtopia.esri.com/john4818/arcgis-webappbuilder/commit/4bc17fbb81d7a0eaf56cfbeec8cb880f6addada9
