### ISSUE TITLE
Coordinate Widget not working

### ISSUE THREAD

**Issue by dhagens** [Esri/solutions-webappbuilder-widgets#416]
The coordinate widget located at http://pscltcentos.eastus.cloudapp.azure.com/coordinatetool/ is not working.  When modifying the input value, none of the outputs are being updated.

**Comment by MarkTorrey** [comment]
Can you give me some of the values you were using and if you were typing them in or pasting. I'll try and reproduce here.

**Comment by dhagens** [comment]
The tool is actually updating today, as opposed to the other day when nothing was updating.  We could probably close this issue and just open specific issues that I've found.  I want to talk with Lyle to see what he captured during the testing task, and to clarify that the issues I'm seeing are actually issues, although talking with Joe, it sounds like they are.

**Comment by topowright** [comment]
Please check to see if you can access the widget. @dhagens

**Comment by dhagens** [comment]
I am able to access the widget and everything is updating fine.
