### ISSUE TITLE
Support query filters for InfoSummary layers

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#421]
The fact that filters are not supported on Feature Collections is in large why we had pulled out this functionality as it was previously partially added at one point. The thought I had previously as to how we could get around this with where we are today would have involved some work at the jimu level (as the filter dijit obviously doesn’t support feature collections) so we could at least get the expression from the Feature Collection using the out of the box dijit for filters and then generate a new feature collection on the fly based on the expression. The main parent Feature Collection would still be used for updates and then subsequent updates to the Feature Collection that was generated on the fly.  Ultimately if Feature Collections could support filters we wouldn’t have to go through this somewhat convoluted workflow/workaround.

**Comment by lindsayking** [comment]
This issue is now being tracked in devtopia.
