### ISSUE TITLE
CoordinateTool - Create Ability to Have Custom Name for Each Coordinate Format in CT Widget

### ISSUE THREAD

**Issue by MarkTorrey** [Esri/solutions-webappbuilder-widgets#429]

**Comment by MarkTorrey** [comment]
If we are giving the user the ability to add multiple Coordinate Outputs of the same Coordinate Type, we should add the ability to have a custom name. Otherwise, there is not much of a use case. Why? If I add two DD Coordinates, and I customize one of them, the both DD coordinates update. Therefore, there is no unique benefit to having multiple coordinate outputs of the same type unless we can make each of them unique.

**Comment by topowright** [comment]
This issue was moved to ArcGIS/military-tools-webappbuilder#12
