### ISSUE TITLE
Geoenrich Widget Testing and Feedback

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#43]
1:  Icon, should we create a white flat icon like the others, just to match, if you agree, I will make one
2:  Name, I think we should use a different name.  Geoenrich is a term used in other areas.  I was thinking something like Spreadsheet Enrichment, Batch Location Lookup, …
3:  Default config and sample data:  Probably need something with a few point of the US and only the required fields.  
4:  Expose the X,Y/Lat Long fields in the widget configuration?  Should we let the user apply the fields to look for in the csv? 
5:  Multi Layers – Would be nice to be able to intersect multiple polygon layers, like the information lookup app.  This can be a v2 version though.  Just once something is released, changing the config can be a pain since it will need to be backwards compatabile
6:  Upload box – should we also have a box for the user to browse the file system and upload the file?  Not sure how the drag and drop works on a phone
7:  The drag and drop fails and does not report an error when the user does not drag a csv file(xlsx for instance)
8:  In MapCSV.js.validateItem I get a IsNan of Null error when I drag and drop

@MikeMillerGIS

**Comment by killpackb** [comment]
1 - yes
2 - DataLoookup?
3-  ok
4- good idea; version 2
5-yep, version 2
6-agreed. working on that now
7-looking into that; adding more validation and error trapping
8-same as 7

**Comment by killpackb** [comment]
1/14/15
* Fixed support for attribute table, and the legend respective to users builder settings
* validate drag and drop object; check for .csv - Message to user otherwise
* changed name to GeoLookup

**Comment by killpackb** [comment]
1/20/15

* checks for file size
* request threading

**Comment by MikeMillerGIS** [comment]
Redesign of widget checked in, closing issue and moving outstanding request to a new issue.
