### ISSUE TITLE
CT accepts 37.000 -109.0000 as input, clicking map, hitting Enter  pans map to eastern hemisphere.

### ISSUE THREAD

**Issue by pshowalter** [Esri/solutions-webappbuilder-widgets#430]
CT accepts "37.000 -109.0000" as input, and re formats as "37.000N -109.0000W". If I then click the map, and then hit Enter in Input box,  the map is panned to Eastern Hemisphere.  All output coordinates are also listed as Eastern.
![ct_west_goes_to_east](https://cloud.githubusercontent.com/assets/6842145/12897539/f1c36e42-ce75-11e5-8f7a-dc1e692872bc.png)

**Comment by MarkTorrey** [comment]
@pshowalter,  updates were pushed that should fix this. Can you try it again and let me know if you find any problems.

**Comment by pshowalter** [comment]
No problems.
