### ISSUE TITLE
Bomb Threat tool not working?

### ISSUE THREAD

**Issue by nixta** [Esri/solutions-webappbuilder-widgets#437]
I'm trying to use the Bomb Threat tool. However, the config panel's pulldowns are blank and I can't place the explosion location. There's an error in the browser console about not being able to reach:

https://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/EmergencyOperations/MapServer/0

However the [configured value](https://github.com/Esri/solutions-webappbuilder-widgets/blob/master/BombThreat/config.json#L47) is accessible:

http://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/EmergencyOperations/MapServer/0

How is the `http` being turned into `https` (is that a WAB 1.3 feature?) and can `https` be enabled on the service? Or am I doing something wrong and need to configure the widget in some way I haven't noticed yet? I was expecting to drop it in, launch, and be able to pick a bomb type.

Sorry if this is a silly question and I'm just missing something obvious.

Cheers,

Nick.

**Comment by ecaldwell** [comment]
@nixta Is the account you're using with WAB set to force SSL only? That would cause it to upgrade the request. Quickest way to check might be to see if your app is loading as `http` or `https` and try forcing `http`.

**Comment by nixta** [comment]
Thanks @ecaldwell. Doesn't seem to be the case. The org doesn't enforce SSL. However, WAB appears to redirect to HTTPS if I open it on plain HTTP. I wonder if that's because I entered my org as `https://geeknixta.maps.arcgis.com`.

**Comment by kgonzago** [comment]
@nixta Looks like you may be experiencing a mixed content error where your WAB is `https` and the widget relies on services with `http` protocol. If that's the case, you will need to set up a proxy: https://blogs.esri.com/esri/supportcenter/2015/10/28/setting-up-a-proxy-with-web-appbuilder-for-arcgis-developer-edition/

**Comment by nixta** [comment]
I was able to fix this by setting referring to my org with `http` rather than `https` when setting up WAB for the first time. I think the proxy option will work too but for now I'm up and running. Thanks all!
