### ISSUE TITLE
Network Trace - Buffer Distance

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#438]
In the overview section, even if the user does not want to set the overview as visible, a buffer distance is required before finalizing the configuration of the widget. In terms of UX it seems that is is creating an unnecessary step.

Thought? @previnWong @MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
It is still calculated for zooming and to store it,  we could allow a zero buffer

**Comment by MikeMillerGIS** [comment]
defaulted a value, so the user is not prompted to pick one
