### ISSUE TITLE
Enhanced Editor - Delete features

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#446]
Add a optional button to the attribute form that allows the users to delete the features

**Comment by camtran** [comment]
@MikeMillerGIS Please review. Thanks.

**Comment by MikeMillerGIS** [comment]
Button works, but if the service is slow, the page transitions and the feature is not deleted.  Add a progress indicator or dialog or lock up the form until the delete is complete.

Expose option to show delete button in configuration.

**Comment by camtran** [comment]
Implemented as requested. Please review. Thanks!

**Comment by MikeMillerGIS** [comment]
verified
