### ISSUE TITLE
Enhanced Editor - Allow user configuration whether reset prompts user

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#447]
When the user clicks reset, a prompt is show, expose this as a configuration option to allow for a stream lined transition if the user chooses so

**Comment by MikeMillerGIS** [comment]
Move to configuration dialog

**Comment by camtran** [comment]
When the user clicks reset, the fields on the attribute inspector form will be reset to their original values.  No prompt is shown. 

Added an option to show prompt when editing attributes and then click the cancel button.  If no prompt is selected, changes will be discarded. If prompt, then users have a chance to to save the changes in case they click the cancel button by mistake.  

Please review and let me know if any change is needed.  Thanks!

**Comment by MikeMillerGIS** [comment]
verified
