### ISSUE TITLE
Enhanced Editor - Rename layer in TOC and remove when widget closes/hides

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#448]
The layer added to the TOC to cache the editor should have a generic name pulled from the NLS.  Name ideas:

Editor Cache
Temp Edit Layer
Temporary Edit Layer
<Edit Layer >

**Comment by camtran** [comment]
Appends 'Editor Cache' to the layer name for local feature layer.  Please review. Thanks!

**Comment by MikeMillerGIS** [comment]
verified
