### ISSUE TITLE
Enhanced Editor - CSS clean up

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#449]
ensure buttons make the standard JIMU buttons of WAB

**Comment by camtran** [comment]
@MikeMillerGIS If the buttons you are referring to in this issue are the ones representing fields that are not nullable but editable then this issues is resolved; Otherwise please clarify.  Thanks.

**Comment by MikeMillerGIS** [comment]
The save, reset and clear buttons on the form.  There is a standard button look and feel that all widgets use

**Comment by MikeMillerGIS** [comment]
Use default styling and look at moving delete to the top right

**Comment by MikeMillerGIS** [comment]
verified
