### ISSUE TITLE
Enhanced Editor - Truncate field or use second line for long field names

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#453]
![image](https://cloud.githubusercontent.com/assets/2707285/13364491/17033036-dc9d-11e5-8884-f98517edf37b.png)

maybe use .... after X charactesr

**Comment by camtran** [comment]
Implemented. Please verify. Thanks.

**Comment by MikeMillerGIS** [comment]
Verified
