### ISSUE TITLE
Enhanced Editor - Implement snapping text to editor

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#454]
This is code from another app where it was added
this._defaultStartStr = esriBundle.toolbars.draw.start;
                    esriBundle.toolbars.draw.start = esriBundle.toolbars.draw.start +
                        "<br/>" + "(" + this.nls.pressStr + "<b>" +
                        this.nls.ctrlStr + "</b> " + this.nls.snapStr + ")";
                    this._defaultAddPointStr = esriBundle.toolbars.draw.addPoint;
                    esriBundle.toolbars.draw.addPoint = esriBundle.toolbars.draw.addPoint +
                        "<br/>" + "(" + this.nls.pressStr + "<b>" +
                        this.nls.ctrlStr + "</b> " + this.nls.snapStr + ")";

**Comment by camtran** [comment]
Done.

**Comment by MikeMillerGIS** [comment]
Verified
