### ISSUE TITLE
Enhanced Editor - After hiding, template picker is not visible

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#457]
Repo Steps:

1:  Open enhanced editor widget
2:  Open the editor widget
3:  Click enhanced editor
![capture-8](https://cloud.githubusercontent.com/assets/2707285/13365264/0d279e1c-dca2-11e5-9191-c92ad85db0eb.gif)

**Comment by camtran** [comment]
@MikeMillerGIS Please review. Thanks.

**Comment by MikeMillerGIS** [comment]
Is there a way to open the enhanced editor where it left off?  
1:  Open Enhanced Editor
2:  Select a record
3:  Open other widget
4:  Go back to enhanced editor and continue edits.

right now, when selection of other widget, you are prompted to save.  you can not go back to where you were

**Comment by camtran** [comment]
Implemented as requested. Please review. Thanks!

**Comment by MikeMillerGIS** [comment]
verified
