### ISSUE TITLE
Enhanced Editor - button locations

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#463]
Use default styling, without overrides.  Place the submit, reset and save on the bottom, place the delete on the top right

**Comment by camtran** [comment]
@MikeMillerGIS I think you meant placing the cancel, reset, and save buttons on the bottom.  Do you want them in that order? or Save, reset, cancel?  Thanks.

**Comment by MikeMillerGIS** [comment]
yes, sorry, was typing fast

Cancel | Reset | Save
