### ISSUE TITLE
Enhanced Editor - Change Save Preset Values to toggle button

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#464]
This option be an enabled/disable, can we use a switch, like what is in dojox
https://dojotoolkit.org/reference-guide/1.10/dojox/mobile/Switch.html

**Comment by MikeMillerGIS** [comment]
Button works, but we need to find a better styling.  What about something like these.
http://jsfiddle.net/davidelrizzo/DYJkG/

**Comment by camtran** [comment]
@MikeMillerGIS, After the meeting on 3/25, I replaced toggle buttons for both Edit Geometry and Use preset value with checkboxes, as suggested by Previn and Allison.  Can you take a look and let me know if I should proceed with changing it back to toggle button with different styling? Thanks.

**Comment by MikeMillerGIS** [comment]
Did you check that code in?  I still get a button, just has a check box in it

**Comment by previnWong** [comment]
We should just use a checkbox with a label or mess with jimu btn state (dark grey/light grey) to keep with the look and feel of WAB.

**Comment by camtran** [comment]
Yes, I checked the code in about an hour ago. It use checkbox with label, like this:

![image](https://cloud.githubusercontent.com/assets/14931280/14216757/5c874836-f7ff-11e5-8c8b-3d16b5c24ea9.png)

**Comment by previnWong** [comment]
@camtran when you select a different value from a drop down in one of the preset layers, the Use Preset Values checkbox gets unchecked automatically.

**Comment by camtran** [comment]
That's intended so that users has to click the checkbox to indicate they want to use the new value(s).  Please suggest a new workflow if you don't think this is desirable. Thanks.

**Comment by previnWong** [comment]
I think we should keep it remain checked/unchecked depending on manual action on the checkbox.  If the preset layers list is long even cause scrolling, and a user changes the value on one of the top presets, they might not know that the checkbox has become unchecked.

**Comment by camtran** [comment]
Redesigned so that the preset value check-box remains checked/unchecked.

**Comment by MikeMillerGIS** [comment]
Can you add some padding between the preset table and the checkbox.  also to the bottom of the form.

**Comment by camtran** [comment]
Implemented. Please verify. Thanks.

**Comment by MikeMillerGIS** [comment]
verified
