### ISSUE TITLE
Enhanced Editor - Preset value table

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#467]
1:  Change column Field Alias to Just Field
2:  Match table to attribute inspector, dijit input inner css

**Comment by MikeMillerGIS** [comment]
Can we right justify the preset value label or align with text boxes?

![image](https://cloud.githubusercontent.com/assets/2707285/14128848/a084c572-f5f2-11e5-9336-7568d96f8edf.png)

**Comment by camtran** [comment]
I think this should already be fixed with my recent check-in. Please let me know if it's not. Thanks.

**Comment by MikeMillerGIS** [comment]
Verified
