### ISSUE TITLE
Enhanced Editor - Support selection of multiple features

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#468]
Look at using the attribute inspector ability to cycle through records or build a custom one.  

just some thoughts:
![image](https://cloud.githubusercontent.com/assets/2707285/13712566/5fb95cec-e792-11e5-8dd7-51f467f453ea.png)

**Comment by camtran** [comment]
I used the default attribute inspector features.

**Comment by MikeMillerGIS** [comment]
Verified
