### ISSUE TITLE
Map Filter - Toggle layer visibility for layers in group

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#469]
If the layer is not visible on start up and selection of group, after clicking apply, toggle layers on,  If user clears filters, reset layers back to not visible.

Scenario:
I have two layers in my map, both are medium voltage.  One is gray, one is blue.  I want to use the blue one to highlght the feeder by name.  When the user opens the map, I would like to only see the gray feeder, but after entering a feeder name, like D2, the blue layer is shown with only feeder D2.

**Comment by previnWong** [comment]
implemented.
