### ISSUE TITLE
Bomb Threat widget - widget.js uses incorrect path to symbols in config file

### ISSUE THREAD

**Issue by kerryrobinson** [Esri/solutions-webappbuilder-widgets#47]
Running the widget on Web AppBuilder Dev 1.0.  

I was getting 'this.config.symbols is undefined' errors when clicking on the map to draw the explosion location.

I modified my local copy of widget.js to replace all 'this.config.symbols' references to 'this.config.bombThreat.symbols' and it worked.

**Comment by kgonzago** [comment]
@kerryrobinson thanks for catching that. I'll make the necessary changes to the code.
