### ISSUE TITLE
Enhanced Editor - Preset value field appears more than once

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#470]
If you select the same field in more than one layer, the aliases are combined, but it still appears to add the other field
![image](https://cloud.githubusercontent.com/assets/2707285/13759299/00563292-ea04-11e5-9c1e-f93709423531.png)

**Comment by camtran** [comment]
Fixed.  Please verify since I don't have test data. Thanks

**Comment by MikeMillerGIS** [comment]
Verified
