### ISSUE TITLE
Enhanced Editor - Support update Attributes Only

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#476]
Expose an option in the configuration where a layer can be set to update only.  In this mode, the layer will not allow the addition of new features.  Only selection and update of them.

**Comment by camtran** [comment]
The title and details of this item are not exactly the same. I implemented based on the description of this task, that is to add an option to allow only update (attributes and geometry).

**Comment by MikeMillerGIS** [comment]
Option is in config, but when I try to select a layer to update, it never shows the editor

**Comment by MikeMillerGIS** [comment]
looks like I cannot update any existing features

**Comment by MikeMillerGIS** [comment]
user error
