### ISSUE TITLE
Smart Editor - Highlight current record in Cyan when more than 1 is selected

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#479]
Need to visually show which feature you are on.  With both being yellow, cannot tell
![image](https://cloud.githubusercontent.com/assets/2707285/14128722/75a3f658-f5f1-11e5-9c17-8877c7c15f56.png)

**Comment by camtran** [comment]
Implemented so that the current feature of which attributes are displayed in the attribute inspector is highlighted in cyan and with a little thicker border.  This applies when there is 1 or more features selected so we have the same look and feel.

**Comment by MikeMillerGIS** [comment]
Can you change the polygon fill to Cyan

**Comment by MikeMillerGIS** [comment]
I guess I was not clear.  Can we make all selected features filled with yellow, then the currently active one filled with cyan so you can easily tell which one is selected?

**Comment by camtran** [comment]
Please review. Thanks.
