### ISSUE TITLE
Map Filter - Combobox on top of each other

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#480]
Chrome, default theme.  Widget placed in the header controller
![image](https://cloud.githubusercontent.com/assets/2707285/14129381/a79059bc-f5f7-11e5-82b3-0eee376da644.png)

**Comment by previnWong** [comment]
This happens when launch from toolbar.  doesn't seem to happen in widget pool.  WIll have to look into working for both.

**Comment by previnWong** [comment]
Implemented.  Handle CSS for different themes, different widget placement location, and on browsers Chrome, Firefox, and IE.  did not try on Safari.

**Comment by previnWong** [comment]
Layout changed from horizontal to vertical placement.  This overlap should not exist anymore.
