### ISSUE TITLE
Map Filter - Global ID and GUID fields not being queried correctly

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#484]
Using the cost analysis map, I tried to filter based on a project ID, 4e72c357-56a3-42e7-9b45-64792fe313c5.  The layers with text fields work, the project polygon using a GlobalID field does not.

**Comment by previnWong** [comment]
should be resolved.  changed the number/string determination logic.

**Comment by pLeBlanc93** [comment]
Verified filtering service territory polygon by GUID on 56fc643.

@previnWong, if you use the value radio button, the dropdown on GUID fields does not populate with the correct values. I'm not sure how GUIDs are stored internally, so that might be why.

**Comment by previnWong** [comment]
Fixed the GUID and GlobalID types for the value list.  filterparams dijit was seeing it as a number prior.

**Comment by pLeBlanc93** [comment]
Verified dropdown on 046bd59
