### ISSUE TITLE
Smart Editor - Presets not carrying over

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#488]
Defining preset values are not being carried over to the attribute inspector table.  Tried on 1.4 (devtopia) and 1.3 Dev Edition
![image](https://cloud.githubusercontent.com/assets/11183838/14180434/c92b7f68-f717-11e5-9678-56604a3dedfe.png)

![image](https://cloud.githubusercontent.com/assets/11183838/14180443/d002b0fe-f717-11e5-9dbf-38b7125b1b9d.png)

**Comment by camtran** [comment]
@previnWong Thanks for the feedback.  However I could not reproduce the issue. I also changed the toggle button to checkbox as requested.  Can you get the latest code and check if the problem still exists?  Thanks.

**Comment by previnWong** [comment]
@camtran downloaded the latest code and issue still persist.

**Comment by MikeMillerGIS** [comment]
Do those fields have edit template defaults?  Should the preset values override these?  That is where I experienced the issue.

**Comment by previnWong** [comment]
one of the two fields I used was part of the edit template.  I removed that one and only have the field that is not part of the edit template.  Same behavior. it doesn't carry over.

**Comment by camtran** [comment]
It works on me all the time. I will investigate the issue further when I'm back to the office. 
Regarding the question about whether the preset values should override edit template values, currently it's not.  I will implement it.

**Comment by camtran** [comment]
As mentioned before, I could not reproduce the problem. However since there's a change in the design for #464, please get the latest code and test it again. The preset values should override the default ones in the edit template.

**Comment by MikeMillerGIS** [comment]
This is not working for me. The edit templates are not being over written

**Comment by previnWong** [comment]
Same issue with latest build.
![image](https://cloud.githubusercontent.com/assets/11183838/14356157/9402d1ac-fc98-11e5-901d-4e043ff652a4.png)

**Comment by camtran** [comment]
Which browser do you use? I use chrome and could not reproduce the problem.

**Comment by MikeMillerGIS** [comment]
I use Chrome.  Previn, can you share you map so Cam can try it out?

**Comment by previnWong** [comment]
Cam here is the webmap id webmap=660dbcc02d364ecab58f51d3e29e2e9a  . or search "OverheadDetailedInspection Map" in public maps.

**Comment by camtran** [comment]
For the services that I use, edit templates are grouped under "templates"; however, they are grouped under "types" in the service that Previn uses.  

![image](https://cloud.githubusercontent.com/assets/14931280/14364121/53f84154-fcbc-11e5-9602-412eb6e6701e.png)

![image](https://cloud.githubusercontent.com/assets/14931280/14364146/6fb5d6e0-fcbc-11e5-8adb-97afbe01a6aa.png)

**Comment by camtran** [comment]
Changed to modify the attributes with preset values (if desired) when a new feature is created instead of modifying the templates.

**Comment by MikeMillerGIS** [comment]
working on text fields, not working on domains.  Can you verify that the domain code and not the display value is being applied?

**Comment by MikeMillerGIS** [comment]
I made a change to handle domains, please verify it does not break the other types

**Comment by MikeMillerGIS** [comment]
@camtran @previnWong can we make sure to test RangeDomains?

**Comment by camtran** [comment]
Range domain should also work now.

**Comment by MikeMillerGIS** [comment]
verified
