### ISSUE TITLE
Smart Editor - Feedback on save

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#489]
There is no indicator that the save worked.  Could we gray the button out if successful and reenabled once a change is made?

**Comment by camtran** [comment]
Yes, we can do that. Or should we use a progress bar, similar to when we delete a feature?

**Comment by MikeMillerGIS** [comment]
I like to disable the button, so the user does not click it again, but a progress bar would be good too

**Comment by camtran** [comment]
Disabling the save button and providing a progress bar when saving.

**Comment by MikeMillerGIS** [comment]
I am not seeing it, using chrome.  Save button is always enabled and no dialog

**Comment by camtran** [comment]
Ok. I saw the save button disabled in debug mode. I thought the applyEdit might have taken just a few seconds in release that I couldn't detect it. Will revisit. Thanks.

**Comment by MikeMillerGIS** [comment]
The save button should be disabled after clicking, only to reenabled after a attribute has changed.

On New Feature:  
Attribute form is shown with save button enabled
After Save, button is disabled
User changes an attribute
Save button is enabled

On Existing Feature:
Attribute form is shown with save button disabled
user changes geometry or attribute
Save button is enabled.

**Comment by MikeMillerGIS** [comment]
Maybe we could also look at what we did for batch attribute editor, where a message was displayed on the form and fades away after 2-4 seconds.

**Comment by camtran** [comment]
Save button is enabled/disabled using the described workflow.

**Comment by MikeMillerGIS** [comment]
verified
