### ISSUE TITLE
Smart Editor - Form size and template picker

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#493]
### Widget
Enhanced Edtior
### Version of widget
2.0 Beta, WAB 2.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
The current sizing of the template picker only allows for two items in a row.  Also as the picker grows in size, the attributes get pushed down, We need to set the max number of items to display at onces so the preset attributes do not get lost

![image](https://cloud.githubusercontent.com/assets/2707285/14216023/7cb43370-f814-11e5-82b5-7ef1f8134ed5.png)

**Comment by camtran** [comment]
Should we use the config to set the number of columns for the template picker?

**Comment by MikeMillerGIS** [comment]
No, how does the default editor do it?

**Comment by camtran** [comment]
The default editor set the number of columns to "auto"; however since grouping is set to true, I think it will use the default value of 3 columns.  I will do the same then.

**Comment by MikeMillerGIS** [comment]
If you compare the editor to smart editor there is some difference
![image](https://cloud.githubusercontent.com/assets/2707285/14268934/c6166b78-faad-11e5-8372-691fc938b6d5.png)
![image](https://cloud.githubusercontent.com/assets/2707285/14268938/d3a4dbe4-faad-11e5-8285-227299fdb68c.png)

**Comment by MikeMillerGIS** [comment]
Also, there is no scroll bar in the template picker

**Comment by MikeMillerGIS** [comment]
Current does not resize either
![image](https://cloud.githubusercontent.com/assets/2707285/14372088/62a503e6-fd0b-11e5-8660-9ed6f35c16d8.png)

**Comment by camtran** [comment]
Verified.

**Comment by previnWong** [comment]
resolved.
![image](https://cloud.githubusercontent.com/assets/11183838/14399938/c6de1014-fda6-11e5-90cf-0cd8479d9c49.png)
