### ISSUE TITLE
Smart Editor - Closing widget does not remove graphics

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#494]
### Widget
Enhanced Editor (Smart Editor)
### Version of widget
WAB 2.0
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
Draw an item on the map. Close the widget.  Graphic remains on the map and no way to clear except to open widget again and clear.  Is this expected behavior?
![image](https://cloud.githubusercontent.com/assets/11183838/14219013/9c956946-f80c-11e5-9af7-ea4684d7f639.png)

**Comment by previnWong** [comment]
discussed. Will have an option in settings to allow users to persist selection after widget is closed (in case user needs to jump around widgets).

**Comment by camtran** [comment]
Implemented as follows:
When some edits were made and the user close the widget, he will prompted to either save or cancel.  

Still need to test/work on cases where a new feature is created with invalid attributes and newly created feature does not have same symbol as the rest.

**Comment by MikeMillerGIS** [comment]
Need to test on a mobile device where you are forced to minimize the widget for map interaction
