### ISSUE TITLE
Smart Editor - Increase field alias width

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#495]
field names are cut off and there is room to fit the form better
![image](https://cloud.githubusercontent.com/assets/2707285/14269193/42a72f54-fab0-11e5-89de-beaa254b0387.png)

**Comment by MikeMillerGIS** [comment]
@previnWong @camtran Please review and if acceptable, close

**Comment by camtran** [comment]
Verified.
