### ISSUE TITLE
Map Filter - Widget size and popup change

### ISSUE THREAD

**Issue by DShokes** [Esri/solutions-webappbuilder-widgets#496]
### Widget

Map Filter
### Version of widget

1.0
### Bug or Enhancement

Bug
### Repo Steps or Enhancement details

I have two monitors with different resolutions. One is 1280x768 and the other is 1176x664. This small change makes a big difference. I also tested at tablet and phone dimensions.
![image](https://cloud.githubusercontent.com/assets/3903212/14304520/17525170-fb79-11e5-95bf-f8c088f9ab41.png)

Observations on responsiveness: 
- On smaller screens and when browser is not maximized, widget uses half the screen real estate and the popups change to the mobile type.  
- In most of the resolutions I checked, over half of the widget was white space. Perhaps the filter criteria container can expand based on the number of criteria?
- The buttons at the bottom can cover part of the filter criteria container when there are multiple criteria set.

As a side note, similar behavior is seen with the batch attribute editor. 
![image](https://cloud.githubusercontent.com/assets/3903212/14304794/abb27d48-fb7b-11e5-96cd-d020495b9460.png)

The difference being batch attribute editor breaks completely when the screen resolution forces the use of the mobile popup. Edits cannot be done because the BAE mobile popup lacks the details button to edit fields and click save. @previnWong has done a great job on both of these widgets. The batch attribute editor gets a ton of use in our office. Thank you. I'm hopeful that both widgets will function well in the future for our field workers with mobile devices.

**Comment by MikeMillerGIS** [comment]
@DStokes, can you log an enhancement on support.esri.com for the BAE and the screen resolution?  The responsiness of the app is part of the widget framework and not the widget.

 We will look into the map filter issue.

**Comment by MikeMillerGIS** [comment]
Sorry, was @DShokes

**Comment by DShokes** [comment]
@MikeMillerGIS, I will do that. Thanks.

**Comment by previnWong** [comment]
@DShokes thanks for the issue with the mobile pop up for Batch Attribute Editor.  We'll look into it. Don't forget to log a request with support.  In the meantime, there is a URL parameter (MobileBreakPoint), that you can pass in to override the pop up behavior in mobile to get the default one.  It was meant for users that embedded WAB into a webpage, the small embedded window forced the app into mobile mode.

Here's a link to the doc.  It's alittle bit of a trial and error to get the right number, but it works. You can use it as a work around for now.
http://doc.arcgis.com/en/web-appbuilder/manage-apps/app-url-parameters.htm#ESRI_SECTION1_01F86DEC2181416888D44A32D3096887

sample below
![image](https://cloud.githubusercontent.com/assets/11183838/14363141/92ac8a5e-fcb7-11e5-89a4-7b1ab43a1bf0.png)

**Comment by DShokes** [comment]
Awesome, I was unaware of mobileBreakPoint @previnWong. Adding the &mobileBreakPoint=200 to the AGOL items app url  did the trick!. The webpage height must have been less than 600px on my 1176x664 monitor. I've got an open case to log the enhancement.  Thanks you.

**Comment by AmrEldib** [comment]
One workaround is to use the browser's zoom to zoom out past the mobile view threshold.

**Comment by previnWong** [comment]
@DShokes we made several changes to Batch Attribute Editor today.  One of which is the mobile pop up.  It should show the pop up without the URL parameters.

**Comment by adgiles** [comment]
Closing issue as Batch Editor is now a core widget
