### ISSUE TITLE
ERG Widget- Persist graphic result

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#497]
Joe K. from the City of Chicago requested that we enable the results of the ERG widget to persist on the map. He'd like to use the results as context for a larger workflow with other widgets. However, when he closes the ERG widget the result graphic disappears. 

@WalterPotts

**Comment by kgonzago** [comment]
@NikkiGolding @WalterPotts Persisting the graphics after the widget is closed is a pretty simple fix. Joe doesn't want those graphics persisted as features in a feature service, right?

**Comment by NikkiGolding** [comment]
@kgonzago A graphic will be perfect. No need to persist as a feature service. Thanks!

**Comment by kgonzago** [comment]
@NikkiGolding I tested the existing ERG widget in both WAB v1.3 and v2.0 and the result graphics do persist on the map when the ERG widget is closed. Graphics also persist when the widget is minimized. Do you know the workflow Joe used where the graphics did not persist?

**Comment by NikkiGolding** [comment]
@kgonzago Thanks for looking into this. Let me dig a bit and get back to you.

**Comment by kgonzago** [comment]
@NikkiGolding Closing issue. re-open issue if customer can repro.
