### ISSUE TITLE
Map Filter - Better description for Operators

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#499]
### Widget
Map Filter
### Version of widget
V1.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Better representation of operators requested from internal solutions and comments from NYC health.  Will look into how to make it more descriptive yet keeping it visually appealing.

**Comment by previnWong** [comment]
Using mathematical expressions, not enough space throughout the themes to allow text without UI change.

**Comment by WalterPotts** [comment]
Please add text-based operators such as "contains" to find portion of text instead of the entire text (Parade instead of St. Patrick's Day Parade).
