### ISSUE TITLE
Smart Editor - Highlight selected template

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#500]
### Widget
Smart Editor 
### Version of widget
1.0 beta
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
When you select a template in the template picker, there is not indication of which template is selected.

In this screen shot, hydrant is selected.
![image](https://cloud.githubusercontent.com/assets/2707285/14371610/7959371e-fd07-11e5-9c52-be3352b27a92.png)

**Comment by camtran** [comment]
Verified.

**Comment by previnWong** [comment]
resolved.
![image](https://cloud.githubusercontent.com/assets/11183838/14399896/6a492c26-fda6-11e5-83c5-9934bfaa5050.png)
