### ISSUE TITLE
Smart Editor - Selection of other layers when selecting features for attribute editing

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#503]
### Widget
Smart Editor
### Version of widget
Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
When clicking on the screen to load the attributes for an existing feature, features from all feature layers at that location would be queried and selected.

**Comment by MikeMillerGIS** [comment]
I implemented a simple fix, but I think it would be best to connect and disconnect the mapclick event when a template is selected and unselected.  Can you make this change?

**Comment by MikeMillerGIS** [comment]
@previnWong @camtran Please verify and close

**Comment by camtran** [comment]
Verified.
