### ISSUE TITLE
Smart Editor - JSHint the code

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#504]
### Widget
Smart Editor
### Version of widget
Alpha
### Bug or Enhancement
Enhacement
### Repo Steps or Enhancement details
Code needs to be hinted and conform to standards.

**Comment by camtran** [comment]
Performed JSHint; no errors but a few warnings as in the snapshot below. 
![image](https://cloud.githubusercontent.com/assets/14931280/14576368/57e81926-031d-11e6-8086-e116677c8615.png)

About the unexpected use of '|' warnings, I checked our js api sample code and it uses a '|' as well  (https://developers.arcgis.com/javascript/jsapi/edit-amd.html#activate). So I'm not sure what to do about it. 

Mike, can you take a look at the setting.js regarding the duplicate key 'mapLayer' warning?  Thanks.

**Comment by MikeMillerGIS** [comment]
Wrapped lines in with: /*jslint bitwise: false*/ and /*jslint bitwise: true*/ as these are valid bitiwse comparisons

**Comment by MikeMillerGIS** [comment]
Resolved the dup key, closing
