### ISSUE TITLE
Smart Editor - Test webmap with additional layer types

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#505]
### Widget
Smart Editor
### Version of widget
Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
We need to test to ensure other layer types do not break the widget

#### Layer Types
Feature Collections with one layer
FC with more than one layer
Map Service
Tile Maps
Vector Maps
Tables

#### Field Types for presets
GUID
GlobalID
Range Domains
Date
DateTime(set in pop up config of layer)

**Comment by MikeMillerGIS** [comment]
## Vector tiles
  As a layer - Passed
  As a basemap - Passed

**Comment by MikeMillerGIS** [comment]
##Map Notes
As a layer created from the standard viewer, the layer is not present in either the editor or the smart editor - **Passed**

**Comment by previnWong** [comment]
here's a nice webmap to test to make sure it doesn't blow up smart editor.
![image](https://cloud.githubusercontent.com/assets/11183838/14467277/6a5ac2e2-008f-11e6-8b0f-bbf0508b0228.png)
