### ISSUE TITLE
Smart Editor - Preset Dates are one day off attribute dates

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#508]
### Widget
Smart Editor
### Version of widget
1.0Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
Using Sample:
http://esri.github.io/solutions-webappbuilder-widgets/SmartEditor/

Select Tap
Enter date on preset 
Place New Tap
Notice Date
At 4:15 EST
![image](https://cloud.githubusercontent.com/assets/2707285/14441037/ca1325ba-0000-11e6-83ab-629bcc727a35.png)

![image](https://cloud.githubusercontent.com/assets/2707285/14441032/c32794b6-0000-11e6-8c3e-173aa024d1b2.png)

**Comment by camtran** [comment]
changed to create a Date object using dojo.date.stamp.fromISOString.

**Comment by MikeMillerGIS** [comment]
verified
