### ISSUE TITLE
Smart Editor - Support Time format on date fields on the preset page

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#509]
### Widget
Smart Editor
### Version of widget
1.0Alpha
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
The attribute page support time on a date field with time formatted on the pop up.  Support the same on the Preset Attribute Page.

**Comment by camtran** [comment]
Added a time control.

**Comment by MikeMillerGIS** [comment]
Can we align the label to be in line with the date box, similar to the attribute inspector?

Att Inspector:
![image](https://cloud.githubusercontent.com/assets/2707285/14460693/dcfdd6f2-008c-11e6-98c0-b38b088a5ecf.png)

Preset value:
![image](https://cloud.githubusercontent.com/assets/2707285/14460701/eefdd974-008c-11e6-9339-6ff7ef450800.png)

**Comment by camtran** [comment]
Done.

**Comment by MikeMillerGIS** [comment]
verified
