### ISSUE TITLE
Smart Editor - Expose Option to Close or Remove on Save

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#511]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Feedback from internal save was they were expecting the form to revert back to the template picker on save.  Expose an option to remove record from selection set on save.  If the record was the only or last record, transition back to the template picker.

**Comment by MikeMillerGIS** [comment]
Looks like there is no easy way to remove an item from a feature layers selection set, so probably will have to run the select again against that one layer, but with a SQL query eliminating the ObjectIDs of the records already saved.

**Comment by previnWong** [comment]
once you press Close or Delete, it goes back to the template picker, but the template is still highlighted.  No way to get back to map action (pan, zoom, identify, etc)

**Comment by camtran** [comment]
I added the option to Remove on save.  

Per Previn's comment, should we deselect the template picker on Close or Delete?  Currently we can get back to map action by manually click on the template picker again.

**Comment by MikeMillerGIS** [comment]
I like having it selected, but fine with unselecting.  It is an easy change either way, maybe expose as an option?

**Comment by MikeMillerGIS** [comment]
If you would like to uncheck the template picker on save or delete, please add an issue so we can track it.  Template picker currently remains selected
