### ISSUE TITLE
Smart Editor - Display Information panel instead of template picker when all layers are in update only mode

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#512]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Configure Widget to have all layers update only.
The template picker is shown with text that feature creation is disabled for all layers.  Can we hide the feature template div and instead display a message, maybe even a table of the layers.  Something like
"The layers listed below support updating, please click on a feature to present the editign dialog"
![image](https://cloud.githubusercontent.com/assets/2707285/14466178/bc004270-00a3-11e6-9096-881efda7a74f.png)

**Comment by camtran** [comment]
The new text displayed inside the templatePicker as expected; However, the div with "Select a template to create features" text still appears.  We can hide it as well or perhaps hide the templatePickerMainDiv all together with the templatePicker and display a new div with a message. The second option allows us to add a table of layers later on.

**Comment by MikeMillerGIS** [comment]
I like the second option.

Sent from my Verizon Wireless 4G LTE DROID

**Comment by MikeMillerGIS** [comment]
verifies
