### ISSUE TITLE
Smart Editor - Prevent the configuration from closing and saving when no editable layers are selected

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#513]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
The configuration page allows you to click ok and save even when no editable layer is selected.  The ok should not accept this

**Comment by MikeMillerGIS** [comment]
On getConfig, return false if no editable layers are checked

**Comment by MikeMillerGIS** [comment]
I checked in a fix, please verify

**Comment by camtran** [comment]
verified.
