### ISSUE TITLE
Smart Editor - Layer break for Preset list

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#514]
### Widget

Smart Editor
### Version of widget

V1.0
### Bug or Enhancement

Enhancement
### Repo Steps or Enhancement details

Initial comments from Patterns & Practice.  If use presets from multiple layers, should have a break or heading separating them  to let users know which presets go with which.

**Comment by MikeMillerGIS** [comment]
But if the field is in multi layers, it is shown once.  Maybe we could do a tooltip or something to show which layer the field is in or a click on the field alias.

**Comment by MikeMillerGIS** [comment]
Lets discuss before we do this.

**Comment by MikeMillerGIS** [comment]
## Options
* Add Info pop up to field alias at runtime on preset fields
* Add option to Field List at config whether the field is combined with other same named fields or presented as unique for the layer, will require a new run time UI to handle each layer
* Click on field alias at runtime and transition to new page with layer list that have this field selected
* Present all fields per layer and evaluate a method to push a value to all the same, example Layer 1 has FLOOR, Layer2 has a FLOOR, at run time, I sent value of 1 in Layer 1 FLOOR field, it also gets added to Layer2 FLOOR field.
