### ISSUE TITLE
Smart Editor - Move Record navigation to the top

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#515]
### Widget
Smart Editor
### Version of widget
V1.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Initial comments from Patterns & Practice.  Move multiple record navigation to the top to be consistent with other navigation in AGOL and in case layer list is long.

**Comment by camtran** [comment]
It looks like this:

![image](https://cloud.githubusercontent.com/assets/14931280/14479323/20fb50ec-00d2-11e6-8aba-769618868db9.png)

**Comment by MikeMillerGIS** [comment]
That looks good, makes it a lot easier to cycle features.
