### ISSUE TITLE
Smart Editor - move the progress dialog to a div on top of the form

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#516]
### Widget
Smart Editor
### Version of widget
Alpha 1.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
When the widget is floating on the screen and you click delete, the progress bar is hidden at the bottom, can we move it to a div that will be shown on top of the form?  This will lock the form from a user click, which is good and make it visble.  Can we also move to an animate gif?
![loading](https://cloud.githubusercontent.com/assets/2707285/14481916/5469fc7a-0105-11e6-8fcf-985a6839d6a9.gif)

**Comment by camtran** [comment]
Implemented.

**Comment by MikeMillerGIS** [comment]
verified
