### ISSUE TITLE
Map Filter - persist def queries set at map level

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#521]
### Widget
Map Filter
### Version of widget
1.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Add checkbox in settings to allow persisting of any def filters that are set at the map level.
In the dialog box, `Reset` will revert to these def queries, not wipe them.

**Comment by previnWong** [comment]
Implemented.  user has option to persist existing def filter from map and append to this filter.
