### ISSUE TITLE
Map Filter - add message on invalid layers

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#524]
### Widget
Map Filter
### Version of widget
1.0
### Bug or Enhancement
Enhancement/Bug
### Repo Steps or Enhancement details
1. Create new app
2. Do **not** select a a different web map.
3. Configure widget, adding group as needed
4. Widget is created with nothing in it.
Repeat from 2. with a map containing tile layer to see similar results.

Settings dialog should either immediately warn on open that there are no valid layers or warn on close that the row in the group table is empty.

![empty](https://cloud.githubusercontent.com/assets/12817527/14547461/ba2babfe-0262-11e6-86ed-72ba1549bbd8.gif)

**Comment by previnWong** [comment]
Verified. warning message appears, unable to add widget.
