### ISSUE TITLE
MapFilter - Rename 'Group Name' to 'Filter Set Name'

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-webappbuilder-widgets#526]
### Widget
![image](https://cloud.githubusercontent.com/assets/3836616/14566852/1ee2930e-02e6-11e6-8bca-03bd2fc6a577.png)

Please rename it so its not confused with ArcGIS online Group names.

**Comment by previnWong** [comment]
renamed to "Filter Set Name:"
