### ISSUE TITLE
Map Filter - Use domain Radio button toggles on adding more layers 

### ISSUE THREAD

**Issue by skrishn** [Esri/solutions-webappbuilder-widgets#540]
### Widget
Map Filter
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
1. Open map filter widget configuration 
1. Choose a layer with fields that has domain. 
2. Choose the field name with domain
3. Select the 'Use Domain' radio button
4. Add another layer and repeat 1,2,3
5. Notice the radio button toggles (it gets deselected from the first layer)

**Comment by previnWong** [comment]
All layers now have a "Use Value" radio so any layer can have a pick list of value, not just domains fields.
