### ISSUE TITLE
Smart Editor: Popup window only shows newly modified attribute value(s) after saving an edit with 'Remove feature from selection on save' turned off.

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#541]
### Widget
Smart Editor

### Version of widget
1.0 Alpha

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
In config, turn off the option: Remove Feature from Selection on Save.
1. select an existing feature, modify an attribute, click Save.
2. select the same feature, the popup window will only show the newly edited attribute value.

**Comment by camtran** [comment]
Resolved.

**Comment by MikeMillerGIS** [comment]
verified
