### ISSUE TITLE
Smart Editor: The navigation toolbar of the attribute inspector overlapping the layer name when the Delete button is hidden.

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#546]
### Widget
Smart Editor

### Version of widget
1.0 alpha

### Bug or Enhancement
Enhancement

### Repo Steps or Enhancement details

In widget settings, uncheck the 'Show Delete Button' option.

Open Smart Editor widget.
Identify an area with a few features close together.
Select a feature (multiple features should be selected).
The attribute inspector appears with the navigation toolbar on top. It looks fine with the delete button presents. But in this case when the Delete button is hidden, it's overlapped with the layer name.

![image](https://cloud.githubusercontent.com/assets/14931280/14686153/67593048-06ec-11e6-9bf1-1caf7489e2e5.png)

**Comment by MikeMillerGIS** [comment]
I made some changes, can you check to see if it is any better.  Since moving the delete button down and the navigation buttons up

**Comment by MikeMillerGIS** [comment]
Does this work?  If so, please close
![image](https://cloud.githubusercontent.com/assets/2707285/14722072/c0df9206-07d7-11e6-9da8-9e3a1ecbcb4f.png)

**Comment by camtran** [comment]
Verified.
