### ISSUE TITLE
Smart Editor: 'Edit Geometry' checkbox on the attribute inspector should be hidden for features from layers with 'Disable Geometry Editing' turned on in the widget settings.

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#549]
### Widget
Smart Editor
### Version of widget
1.0 alpha
### Bug or Enhancement
bug
### Repo Steps or Enhancement details

In the widget settings, check the 'Disable Geometry Editing' for a test layer.

Open Smart Editor.  Select a feature from the test layer.
The attribute inspector appears. Browse to the bottom. 
The Edit Geometry checkbox is there. It should be hidden.

* Note: When it's fixed, make sure it also works with the case when multiple features from different layers (including layers with Disable Geometry Editing turned off) are selected.

**Comment by camtran** [comment]
Tested with the recent build. If there is only one feature from the layer with 'disable geometry editing' turned on, the Edit Geometry option is hidden.  (good).

However, when several features from different layers (some with 'disable geometry editing' turned off), the Edit Geometry option always appears (The option won't show for the first time if that's the first feature in the selection set but subsequently it always appears.)

![image](https://cloud.githubusercontent.com/assets/14931280/14690732/66f688f6-0702-11e6-9440-77246aa5cd03.png)

![image](https://cloud.githubusercontent.com/assets/14931280/14690752/820d2910-0702-11e6-90ce-b71cb9f8da81.png)

**Comment by MikeMillerGIS** [comment]
Please verify

**Comment by camtran** [comment]
Verified.
