### ISSUE TITLE
Smart Editor: Delete button - when to hide?

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#550]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details

I have a layer of which delete features is one of its supported operations.
In the widget settings, I made sure the Allow Delete option is unchecked.

Open the widget, select a feature belongs to this layer.
The Delete button appears next to the Save button.

Should the delete button be hidden? if not then perhaps the Allow Delete option in widget settings should be read only?

**Comment by MikeMillerGIS** [comment]
Please verify and close

**Comment by camtran** [comment]
Verified that the delete button displays when the 'Allow Delete' option is checked. Works with selecting multiple features belong to a collection of layers that have a mixture of this option (checked and unchecked).
