### ISSUE TITLE
Smart Editor: The Save button in the attribute inspector is enabled when selecting an existing feature.

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#551]
### Widget
Smart Editor
### Version of widget
1.0 Alpha
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details

Open Smart Editor.  
Select an existing feature.
The save button is enabled.  

Not sure if this is a new change in the workflow. There was an issue requesting that the Save button should be disabled until user make a change.

**Comment by MikeMillerGIS** [comment]
good catch, resolution checked in

**Comment by camtran** [comment]
Verified.
