### ISSUE TITLE
Smart Editor: unable to set rules against more than 1 field

### ISSUE THREAD

**Issue by gg7aph** [Esri/solutions-webappbuilder-widgets#552]
v2.0.1

As soon as I attempt to set rules against a second field, the rules against my first field disappear - No matter which way I do this, or with saving my work at every step. It appears I can only have rules against one field.

**Comment by MikeMillerGIS** [comment]
The process checks the rules in order, what ever rule is satisfied first is performed, not all.

**Comment by MikeMillerGIS** [comment]
please verify and close
