### ISSUE TITLE
Smart Editor: Rule validation failing

### ISSUE THREAD

**Issue by gg7aph** [Esri/solutions-webappbuilder-widgets#553]
v 2.0.1

Establish rule whereby FLOW (Number) > 0 it still fails to validate and allows me to save values of 0.

**Comment by MikeMillerGIS** [comment]
There is no validation as part of this widget.  Only the ability to hide, disable or required.  Do you want to request the ability to have field validation outside what is defined in the GDB? @gg7aph

**Comment by MikeMillerGIS** [comment]
please verify and close
