### ISSUE TITLE
Smart Editor: Widget fails to allow reopening

### ISSUE THREAD

**Issue by gg7aph** [Esri/solutions-webappbuilder-widgets#554]
v 2.0.1

Selecting the widget, then a feature allows for editing. However, closing the widget then re-opening fails to allow me to select a feature to edit and simply opens the features popup.

**Comment by MikeMillerGIS** [comment]
That is the current process.  Once you select a feature, you have to close the attribute inspector to select another feature for editing.  This allows you to explore the map will editing.

Please close if this resolved the issue and if not, lets log an enhancement to allow the selection of new feature for editing while editing,
