### ISSUE TITLE
Smart Editor: the 'Use preset values..' checkbox and the preset value table should be hidden when no preset value defined for all layers that are editable and support feature creation.

### ISSUE THREAD

**Issue by camtran** [Esri/solutions-webappbuilder-widgets#555]
### Widget
Smart Editor
### Version of widget
1.0 alpha
### Bug or Enhancement
bug
### Repo Steps or Enhancement details

In widget settings, have 2 editable layer.
One of the layer is set to 'Update Only.  Allow fields with preset values for this layer.
Uncheck preset for all fields in the other layer.

Open Smart Editor widget, the 'Use preset values..' checkbox and the preset value table header show although there is no preset value field/row.

![image](https://cloud.githubusercontent.com/assets/14931280/14726908/d60d5d72-07da-11e6-9a33-4ab001519ad9.png)

**Comment by MikeMillerGIS** [comment]
Please verify

**Comment by camtran** [comment]
Verified.
