### ISSUE TITLE
Map Filter - apply before saving

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#572]
### Widget
Map Filter - advanced
### Version of widget
alpha
### Bug or Enhancement
- Should user be allowed to save if expression was never applied?
- Is it possible to save inputs without applying first?

### Repo Steps or Enhancement details
1. Open widget
2. Add any value to textbox **Do not apply!**
3. Save to disk, noting values are not written
4. Apply filter
5. Save to disk, noting values **are** written

![save](https://cloud.githubusercontent.com/assets/12817527/14962390/6fe1262e-1053-11e6-854e-f3e40756a781.gif)

**Comment by previnWong** [comment]
We'll keep it like that for now.  If a user does not APPLY, saving the file with have no value.  Only last applied values will be keep when saving.  We'll change if we get more customers asking or getting confused by this.
