### ISSUE TITLE
NetworkTrace - Save to Layer 

### ISSUE THREAD

**Issue by brookphillip** [Esri/solutions-webappbuilder-widgets#576]
### Question

I have no option in the dropdown when trying to select a Target Layer as output during widget configuration. Where is the dropdown pulling from?

Is this the right place to be posting this question?

**Comment by MikeMillerGIS** [comment]
You need to use Web App builder Dev edition 1.3 or 2.0.  What version are you using?

**Comment by brookphillip** [comment]
I'm on 1.3. I had 2.0 installed, but the release notes hadn't mentioned compatibility. I can go back to 2.0. if needed. 
BTW, i'm using the data from WaterDistributionNetworkA4W.zip provided by the water solutions team. I ran and published the gp tool, tiled and published the water features from the IsolationTrace.mxd, and published the features with full feature access from the OutageDetails.gdb.

**Comment by MikeMillerGIS** [comment]
Updated readme to reflect 2.0 edition

**Comment by brookphillip** [comment]
ok. quick question while i have you here, and sorry for the complete noobiness of the question:
Am I going to have to configure a web adaptor in order to get this working under a firewall?

**Comment by brookphillip** [comment]
Just installed 2.0. Having the same problem. 
I'm imagining the Target Layer should be a list of features from the OutageDetails.gdb, correct?

**Comment by brookphillip** [comment]
I'm very sorry to have wasted your time. I accidentally added the map image service url of the outagedetails instead of the feature service url. Anyway, thank you for your valuable time.

**Comment by MikeMillerGIS** [comment]
Did you include those layers in the map?

**Comment by brookphillip** [comment]
yep. we're all good to go, now. i've launched the app, and it's working fine. Thanks again.
