### ISSUE TITLE
Template visibility doesn't refresh when layer visibility changes

### ISSUE THREAD

**Issue by chris-fox** [Esri/solutions-webappbuilder-widgets#579]
### Widget
Smart Editor
### Version of widget
1.0
### Bug
Bug
### Repo Steps

1. Load a map with some layer's visibility turned on and some off

1. Open the Smart Editor and the visible templates reflect the layers that are currently visible.

1. Open the layer list widget and turn on and off some layers

1. Go back to the Smart Editor and the templates haven't updated to display the templates for the now visible layers.

**Comment by MikeMillerGIS** [comment]
The template picker is recreated if the widget is closed and opened and the layers that where used to create it are different than the current set of layers visible

**Comment by MikeMillerGIS** [comment]
@chris-fox please verify and close

**Comment by chris-fox** [comment]
verified
