### ISSUE TITLE
Skip Locations user input

### ISSUE THREAD

**Issue by brookphillip** [Esri/solutions-webappbuilder-widgets#581]
### Widget
Network Trace
### Version of widget
Feb 2016
### Bug or Enhancement
Bug ? Enhancement?

I don't actually see a feature template to input "Skip" locations. The  GP tool is published with with the option to allow user defined skip locations, and "SkipLocations" is an input with a symbol preview in the widget configuration, but in the application, there is now way to skip valves besides just putting in two flags.

I understand the widget functions the same, but I was hoping to use the flags as a permanent record for water leaks. I've set up my version of your model to write a copy of the flag location to another feature class I have as "Main Leaks". The way the widget is currently functioning will not exactly allow me to use the Main Leaks as ideally as possible. 

Either way, thanks for this widget. It's pretty awesome.

**Comment by MikeMillerGIS** [comment]
You need to set the valves layer as Skippable, this will let you click an icon on a valve to skip it.

Would you like to add the option to export the flags to a layer like the other results?  Just return the flags as a result in the GP service.  Any result can be mapped to a layer for saving

**Comment by brookphillip** [comment]
oh, I see now. I had it configured to be skippable, but I didn't know how to do it in the app. And it makes sense this way too. Guys won't know they need to skip it until after they've run the model and determined they can't find a particular valve on the ground.

As for the flags as a result in the GP Service, I currently have your model modified to make a copy of the flag, but what you're suggesting sounds better. That way, they wouldn't submit until they're sure they got it right. It would minimize duplicate points for the same leak. That would be great.

**Comment by MikeMillerGIS** [comment]
The next release we have enhanced the model to return the flags and barriers, as well as the lines
