### ISSUE TITLE
Map Filter - radio button config

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#584]
### Widget
Map Filter
### Version of widget
fed2687
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details

1. Add a new map filter widget
2. Note how the radio button displays
3. Choose a layer/field that has a domain set
4. Note how the radio button displays differently
![radio](https://cloud.githubusercontent.com/assets/12817527/15157259/a5b0f16a-169f-11e6-82d8-36665368c2b7.gif)

**Comment by previnWong** [comment]
I'll remove the domain check.  I changed it to have a radio option for any and all field.  if it's not a domain, it will show a value pick list, if it's a domain, it is have a domain drop down.  no radio chosen, it will just be a plain textbox.  still have to clear the radio when the field is changed.

**Comment by pLeBlanc93** [comment]
verified on cb29f08
Radio button display is constant and clears when the field is changed.
