### ISSUE TITLE
Map Filter - duplicate group names

### ISSUE THREAD

**Issue by pLeBlanc93** [Esri/solutions-webappbuilder-widgets#585]
### Widget
Map Filter
### Version of widget
fed2687
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details

1. Add two groups with the same name
2. Configure them with different presets (e.g., `equals` and `not equal`)
3. Save and open the widget
4. Attempt to change groups -- it's not possible to access the second one.

I'll add some logic into the configuration to disallow duplicate group names.

**Comment by previnWong** [comment]
let me check in my code, I've made a bunch of changes before you start this.

**Comment by pLeBlanc93** [comment]
@previnWong let me know if #586 conflicts with your most recent code. My branch got of out of sync forwards/backwards somehow.

**Comment by pLeBlanc93** [comment]
verified with on cb29f08
