### ISSUE TITLE
remove references to 'tailcoat' from all readmes

### ISSUE THREAD

**Issue by jgravois** [Esri/solutions-webappbuilder-widgets#59]
since [ArcGIS/tailcoat](http://github.com/arcgis/tailcoat) isn't a public repository, it would be a good idea to remove references to the projects [landing page](http://arcgis.github.io/tailcoat/) from the main readme for this repository (and the readmes for individual widgets)

**Comment by ngoldman** [comment]
+1 tailcoat is not for public consumption.
