### ISSUE TITLE
Enhancement - Disable editing on layer network trace

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#606]
### Enhancement details

With the June update, the TraceID field is now included. When saving the outage area layer this field is editable and allow a user to input any values. Would be good to disable the editing of this field.
![image](https://cloud.githubusercontent.com/assets/5611508/15615971/f6aab2aa-23f5-11e6-8811-68bdb28792b3.png)

**Comment by clareprice** [comment]
@MikeMillerGIS

**Comment by MikeMillerGIS** [comment]
Can you just disable the field in the webmap?

**Comment by clareprice** [comment]
Editing disabled and display enabled. Was still able to write out to an non-editable field. Seems like a bug that could still edit a non-editable field.

**Comment by MikeMillerGIS** [comment]
resolved - 
![image](https://cloud.githubusercontent.com/assets/2707285/20203257/d2384a82-a793-11e6-8d06-40da17ad7e96.png)
