### ISSUE TITLE
ElevationProfileTable widget fails to load in WAB 2.1

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-webappbuilder-widgets#607]
### Widget
ElevationProfileTable
### Version of widget
I believe it's 1.2
### Bug or Enhancement
Possible Bug
### Repo Steps or Enhancement details
This may be related to installing the widgets in WAB 2.1.

Steps:
1. Downloaded zip file from Master branch
2. Copied widget folders to the client/stemapp/widgets
3. modified list.json
4. Added widgets based off their folder name

ElevationProfileTable widget fails to load, icon is not present.

I left ElevationProfileTable still listed in list.json.
I renamed ElevationProfileTable folder to ElevationProfile

Now it appears to work.

**Comment by kgonzago** [comment]
Documentation updated to reflect new changes for WAB 2.1
