### ISSUE TITLE
Smart Editor - Smartform expressions not working for "Date Modified" and "Date Created" fields

### ISSUE THREAD

**Issue by mart8749** [Esri/solutions-webappbuilder-widgets#608]
When creating an expression with "Date modified" or "Date Created" fields, results do not show.

Example: 
Hide "Ancilliary Role" WHEN "Date Modified" is 06/03/16. (DOES NOT WORK)
Hide "Ancillary Role" WHEN "MANUFACTURER" is 'esri' (DOES WORK)

I have tried various expressions with "Date Modified" and "Date Created" fields; none have worked so far.

**Comment by MikeMillerGIS** [comment]
Can you share the map so I can repo.  I was not able to repo it on my dataset.

**Comment by MikeMillerGIS** [comment]
nevermind, found the bug, good find!  Will fix it

**Comment by mart8749** [comment]
Ok. I will keep bug hunting.  I plan to look through batch attribute editor, smart editor and group filter.  Let me know if you need me to work on something else.
