### ISSUE TITLE
Batch Attribute Editor - Pop-up menu "zoom to" button error

### ISSUE THREAD

**Issue by mart8749** [Esri/solutions-webappbuilder-widgets#609]
When selecting a feature with the batch attribute editor, a pop-up menu appears with a "zoom to" hyperlink in the bottom right-hand corner.  Clicking this link directs the user to the feature which was previously selected within the general web app interface, not the feature selected within batch attribute editor.

**Comment by MikeMillerGIS** [comment]
@mart8749 I made a fix to resolve this.
