### ISSUE TITLE
SmartEditor - Add geometry to features without it

### ISSUE THREAD

**Issue by zjankovsky** [Esri/solutions-webappbuilder-widgets#610]
### Widget
SmartEditor

### Bug or Enhancement
Enhacement

### Repo Steps or Enhancement details
Can SmartEditor widget add geometry to features, which has NULL/Not set geometry?
Customer has a point feature class with features. Some features has a geometry and some features doesn't have a geometry (they have NULL geometry). Web AppBuilder users should by able to select a feature with NULL geometry (e.g. from attribute table, or with a query) and draw the new geometry to selected feature.

**Comment by MikeMillerGIS** [comment]
No this is not possible

**Comment by zjankovsky** [comment]
Thanks for the reply.
Why? It is not possible to select the feature without geometry? Or any other reason?
Or simply it is not implemented, and there is no plan for implementation?

**Comment by MikeMillerGIS** [comment]
I am not sure how we would even select a feature without a geometry.  I have always heard that shapeless records are a bad thing to have too.  

No plans to implement a tool for this

**Comment by riccardoklinger** [comment]
This makes sense to me and a customer also wants this feature. You can select it using the attribute table widget.  could also be implemented in the edit widget itself. 
Usage scenario: 
user has items which needs to be places on a map. So the whole attributes are set but we need to add a point to a feature.

**Comment by riccardoklinger** [comment]
Currently it is stating:

![grafik](https://user-images.githubusercontent.com/7377897/47008311-5b9b1a80-d13a-11e8-8f08-29c038e7c101.png)
The error is simply wrong as a feature class has a geometry (point geometry) Yet, the coordinates are not known.
