### ISSUE TITLE
Smart Editor - Smartform Hide error with "contains" parameter

### ISSUE THREAD

**Issue by mart8749** [Esri/solutions-webappbuilder-widgets#615]
When creating expression which hides a field based on a CONTAINS parameter in another field, the field will disappear and will not reappear even when the value is changed back.  For example:

OutageDetail - Isolated Customers
HIDE "Account Number" if "Location Description" CONTAINS "gar"

The field, "Account Number" will disappear regardless of the input value for "Location Description".  The Field will also permanently disappear even when the input value is changed/refreshed.

Please see smart editor test_1 in Solutions DEV Ext to access these pre settings and data.

**Comment by previnWong** [comment]
@MikeMillerGIS.

**Comment by MikeMillerGIS** [comment]
found the issue and will be resolved in next AGO release, thanks!
