### ISSUE TITLE
Smart Editor - Freeze error

### ISSUE THREAD

**Issue by mart8749** [Esri/solutions-webappbuilder-widgets#616]
When an expression is called for in the smart from, and the user immediately moves the cursor to another text box, the browser may freeze and the cursor will re-locate to an area outside the dialogue box.  These freeze errors are sporadic.  I experienced the error 6 times, during 3 hours of testing.
Tested in Edge

**Comment by MikeMillerGIS** [comment]
moving to internal repo where code is managed
