### ISSUE TITLE
Miles are incorrect for elevation profile in Elevation profile table widget 

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#618]
Major and minor tick marks for unit Miles on x-axis are incorrect for elevation profile in Elevation profile table widget.

**Comment by joebayles** [comment]
@kgonzago - If you switch measurements, the issue persists (kilometers, feet). Additionally, you can switch between them, but once you click measure for the first time, it switches back to the default miles. If you go back and change it again, works as intended (stays w/ the selected measurement).

**Comment by csmoore** [comment]
This issue was moved to ArcGIS/defense-solutions-proofs-of-concept#6
