### ISSUE TITLE
ERG - materials/chemicals services unavailable

### ISSUE THREAD

**Issue by tylergotatie** [Esri/solutions-webappbuilder-widgets#619]
ERG Widget

Version - current, v1.2

Services used by the widget are currently Unavailable and showing a 503 error
[Chemical Service URL](http://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/ERGByChemical
)
[Placard Service URL](http://arcgis-emergencymanagement-2057568539.us-east-1.elb.amazonaws.com/arcgis/rest/services/COP/ERGByPlacard/GPServer/ERG%20By%20Placard)

**Comment by nenge** [comment]
is there timeline on this one?

**Comment by kgonzago** [comment]
@tylergotatie and @nenge We will no longer hosts these services. SD files for the GP services will be made available in the [ERG](https://github.com/Esri/solutions-webappbuilder-widgets/tree/master/ERG) repo instead.

**Comment by kgonzago** [comment]
@tylergotatie and @nenge The SD files are now in the ERG [services](https://github.com/Esri/solutions-webappbuilder-widgets/tree/master/ERG/services) folder.
