### ISSUE TITLE
Network Trace - Skip locations categorized as flag locations

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#621]
### Bug

After running an isolation trace and selecting valves to disable the location in the details panel (using the barrier symbol), the features are being added as skip locations and categorized as a flag location. Additionally, the flag location count is off and counting these locations twice in the out and output information.
### Repo Steps or Enhancement details
- Configure the isolation trace widget and launch the application
- Run the trace adding in one flag location
- View the isolating valve details and select valves barriers
- Rerun the isolation trace.
- In the output panel the results out one break location but multiple flag inputs 
  ![image](https://cloud.githubusercontent.com/assets/5611508/18396060/79896d88-7676-11e6-8872-ab06dfc2ef91.png)

**Comment by MikeMillerGIS** [comment]
Yes, the skip locations are technically flags, the model uses them to generate a large number of flags, so I guess we need to remove these in the model

**Comment by MikeMillerGIS** [comment]
Resolved in new model that is going beta, closing
