### ISSUE TITLE
Network Trace - CSS Internet Explorer

### ISSUE THREAD

**Issue by clareprice** [Esri/solutions-webappbuilder-widgets#622]
### Bug

In IE 11 the default values are cut off when configuring the widgets
![image](https://cloud.githubusercontent.com/assets/5611508/18396363/13b559de-7678-11e6-9f29-97091ca3edcb.png)
http://52.26.253.224:6080/arcgis/rest/services/UpstreamTrace/GPServer/UpstreamTrace
![image](https://cloud.githubusercontent.com/assets/5611508/18397215/0c9f60b4-767c-11e6-9752-d95878ccfe86.png)
### Repo Steps or Enhancement details
- Create and begin to configure the widget
- Browse to min/max scales and see the default of zero is cut off
- Update the value from the default and the number now appears correctly.

**Comment by MikeMillerGIS** [comment]
spent an hour trying to solve this, it is a dojo/ie issue, going to mark as known issue and close.
