### ISSUE TITLE
Service Feasibility - No ROUTEID field as specified in help doc

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#628]
### Widget

Service Feasibility
### Version of widget

1.0
### Bug or Enhancement

BUG in doc or layer?
### Repo Steps or Enhancement details

In the help doc, states to choose ROUTEID
![image](https://cloud.githubusercontent.com/assets/11183838/18562993/b79a27de-7b3a-11e6-8f1b-d11c64d1ac0c.png)

No ROUTEID in sample map
![image](https://cloud.githubusercontent.com/assets/11183838/18563015/c8419586-7b3a-11e6-8976-c21fc4721bea.png)

**Comment by clareprice** [comment]
Updated doc a while back. Closing.
