### ISSUE TITLE
GeoLoookup  - Not Finishing Lookup (enrichment)

### ISSUE THREAD

**Issue by killpackb** [Esri/solutions-webappbuilder-widgets#63]
I've hosted the latest cut of the GeoLookup widget here: http://ec2-23-21-102-227.compute-1.amazonaws.com/GeoLookup/. It requires a login to the South Florida Telecom AGOL. When I use this spreadsheet - http://utilitysales.esri.com/geoenrich/data/customers.csv - the widget works, but cannot get through the all records, it hangs and/or is super slow at around 90 count. the csv contains 148, its the one we use in the older demo application. no console errors. strange. old app, same feature service - it completes it in 5 seconds. browser locks up after a while. 

![image](https://cloud.githubusercontent.com/assets/6979905/6138500/df1abb56-b13e-11e4-8c43-9ff2a1383859.png)

**Comment by MikeMillerGIS** [comment]
@previnWong

**Comment by previnWong** [comment]
Seems like you are already doing the correct thing with the featureSelection.
A possible alternative:
The first option off the top of my head, what if we take one enrich layer at a time, load all the geoms into an array as graphic. Then just do “contains” validation on it on the client side.  The graphic would have the attributes to it and we don’t go back to the server multiple times.  Then destroy the enrich graphic layer.

**Comment by MikeMillerGIS** [comment]
I am not sure, if the Feature Service has Millions of geometry, we do not want to pull these locally.
