### ISSUE TITLE
Bomb threat Service?

### ISSUE THREAD

**Issue by tylergotatie** [Esri/solutions-webappbuilder-widgets#632]
### Widget

Bomb threat widget
### Version of widget

current
### Bug or Enhancement

The readme for the bomb threat widget references the ERG config.json and states that services are needed for the tool. Is this true, the included services do not seem to be relevant and the config is preconfigured with the agol geometry service.

**Comment by kgonzago** [comment]
@tylergotatie 
README.md was updated to reflect the error of referencing the ERG config.json. 

The Bomb Threat widget relies on the ERG.sd and EmergenyOperations.sd which are the same services the ERG widget uses. The ERG.sd is poor choice for a file name and can easily be confused (will change file name soon). 

As for the geometry service, the widget is pointing to the one that's on AGO, but you can supply your own custom geometry service in the config.json.
