### ISSUE TITLE
Grid Zone Designator and 100K Grid Square Identifier Overlap

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#635]
_From @joebayles on July 28, 2016 13:53_

At different scales, the Grid Zone Designator (GZD) and 100,000m Grid Square Identifier render in different spots. It's possible at larger scales for them to overlap.
![image](https://cloud.githubusercontent.com/assets/5016557/17214650/d7824ad6-548e-11e6-9d5e-e1ee23ab5925.png)
![image](https://cloud.githubusercontent.com/assets/5016557/17214657/db607560-548e-11e6-9f0b-89b28ddaa800.png)

Suggest that they are always rendered together.

_Copied from original issue: ArcGIS/Grid-Overlay#2_

**Comment by lfunkhouser** [comment]
Verified as fixed using WAB Dev Edition 2.6
