### ISSUE TITLE
Rotate/Deconflict labels

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#636]
_From @joebayles on August 10, 2016 18:50_

Offer the option to rotate longitudinal labels, and deconflict labels that overlap in the corners (see below).

![image](https://cloud.githubusercontent.com/assets/5016557/17566499/7a6a5d5e-5ef0-11e6-9a56-9d15af708e5a.png)

@kgonzago 

_Copied from original issue: ArcGIS/Grid-Overlay#4_

**Comment by topowright** [comment]
This is what it looks like now: 

![image](https://user-images.githubusercontent.com/5488313/30285401-dbbabed0-96d2-11e7-99c3-c3aff2ab516d.png)

**Comment by topowright** [comment]
This is the exact spot that was identified in the first version. 

![image](https://user-images.githubusercontent.com/5488313/30285685-a9e01936-96d3-11e7-838f-c79a3a1835de.png)

**Comment by lfunkhouser** [comment]
To fix the view of a specific location pan the map to center the area of interest to be the center point on the map.
