### ISSUE TITLE
Latitude/Longitude Grid

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#637]
_From @joebayles on August 10, 2016 18:47_

Would be useful to have a lat/long grid as well.

@kgonzago 

_Copied from original issue: ArcGIS/Grid-Overlay#3_

**Comment by lfunkhouser** [comment]
The Grid Overlay widget was designed to support MGRS grids. Adding additional grids such as lat, long will depend on feedback from the customer. @nfeuerstein
