### ISSUE TITLE
1 Km labels should not have the preceding zero

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#639]
_From @jeffbaranyi on September 22, 2016 14:40_

Per Al Studt, 1 Km labels should not have the preceding zero

See https://mappingsupport.com/p/gmap4.php?usng=11S_MT_8215_6975&tilt=off&z=13&t=h for an example

_Copied from original issue: ArcGIS/Grid-Overlay#8_

**Comment by kgonzago** [comment]
_From @hogpilot on September 30, 2016 19:30_

I'm not sure I understand what you're saying.  Can you attach a screenshot of what you're asking to change?

When 1Km labels are labeling something <10km, it will need a preceding zero (e.g. 11S  MT  0498  0348).  See attached screenshot from the link you provided.

![image](https://cloud.githubusercontent.com/assets/2762204/19004207/f742f9f0-8711-11e6-97fb-0bb0f7ee3238.png)

**Comment by lfunkhouser** [comment]
with new fixes in WAB DE 2.5 this is no longer an issue. If this is still an issue @jeffbaranyi please comment in WAB repo.
