### ISSUE TITLE
ERG Improvements to support facilities management customers

### ISSUE THREAD

**Issue by rwmajor2** [Esri/solutions-webappbuilder-widgets#647]
### Bug or Enhancement

Expand Emergency Response Guide widget to better support military customers and facility management
### Repo Steps or Enhancement details

In working with military customers responsible for facilities management and base incidents, it would be good to expand this tool.  I am documenting a specific customer and use case, but I know this functionality could be used broader.
New tools:
1.  Drop Pt. on map - this adds a point to an editable Feature Service (for persistent).  It also automatically buffers the indicent by 300 ft. and changes any buildings status to Cordoned.  A "secondary" buffer is added to the cordonpoly layer.
   1a.  Alternatively, add by Building ID from a drop down list; I am thinking this must query the FeatureService and get a list of Building IDs to select from.  I assume this adds point on Building center.
2.  Add additional buildings to active incident - if there are additional buildings that fall outside the 300 ft buffer but want to include in the cordoned area, add these buildings by dragging a box.
3.  Edit Multiple Bldg Status
4.  Add Blockade to active incident
5.  Add Safe Route
6.  Add Plume from KML/Shapefile - in this case, these files are being computer by external algorithms and imported via this method.

These new tools can be driven off of a published Map Service/Feature Service that includes the following layers:

![image](https://cloud.githubusercontent.com/assets/3799165/19431521/12df40e8-9459-11e6-9846-16e07fa967c4.png)

Once an incident is dropped on the map, there are additional capabilities that are desired based on this active incident:
1.  Edit incident info - ability to change name, details, and status (Pending by default, Active, Inactive)
2.  Delete incident - clears incident and return buildings' status to all clear
3.  Add cordon to this incident - name, size, primary check on/off
4.  View building report - view buildings affected in a grid - facility, status
5.  View blockages report - grid of blockages associated with incident to include name, roads, details, blockage type
6.  Activate Entire Event - push to the primary viewer as an active incident that others will now see

**Comment by csmoore** [comment]
This issue was moved to ArcGIS/defense-solutions-proofs-of-concept#5
