### ISSUE TITLE
ReadMe for Grid Overlay should be cleaned up

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#650]
### Opening paragraph of the readme has confusing wording, recommend cleaning up to read

"The U.S. Military Grid Reference System (MGRS) is an alpha-numeric system, based upon the Universal Transverse Mercator (UTM) and Universal Polar Stereographic  map projections, for identifying positions. An MGRS coordinate consists of a zone designation, alphabetic 100,000-meter grid square designator, and numeric coordinates within the 100,000-meter grid square."

**Comment by kgonzago** [comment]
@dfoll Can you verify when you get a chance?

**Comment by lfunkhouser** [comment]
NA because this widget no longer lives in this readme.
