### ISSUE TITLE
Grid Overlay has no help for deploying the widget for Web AppBuilder

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#651]

**Comment by kgonzago** [comment]
@dfoll Deployment topic is part of the [README.md](https://github.com/Esri/solutions-webappbuilder-widgets/blob/master/GridOverlay/README.md). Is that sufficient?

**Comment by lfunkhouser** [comment]
This is no longer an issue because this widget is an out of the box widget.
