### ISSUE TITLE
GRG Widget - Schema.gdb contains extraneous feature classes

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#655]
### Widget

GRG
### Version of widget

0.1.0
### Bug or Enhancement

The Desktop_toolbox\GRG\data\schema.gdb contains the following extraneous feature classes:
- DrawCell
- GRGCanvas
- GRGPointTarget

The only feature class that is needed is CanvasAreaGRGScript
### Repo Steps or Enhancement details

Delete the extraneous feature classes.
@adgiles FYI.

**Comment by kgonzago** [comment]
@elinz This workflow is now obsolete since the new GRG widget is now entirely client-side with drawing grids and persisting them has hosted feature layers.
