### ISSUE TITLE
GRG Widget - CanvasAreaGRGScript should be renamed

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#656]
### Widget

GRG
### Version of widget

0.1.0
### Bug or Enhancement

Feature class should be named to better descript what it's used for, maybe something like, GRGGrid
### Repo Steps or Enhancement details

@adgiles FYI

**Comment by kgonzago** [comment]
@elinz Closing this since new GRG widget doesn't rely on GP services.
