### ISSUE TITLE
GRG Widget - Should the GP toolbox and template schema be relocated to another repo

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#657]
### Widget

GRG
### Version of widget

0.1.0
### Bug or Enhancement

Should the GRG Tools.tbx and the schema.gdb be stored in the GRG Widget?
### Repo Steps or Enhancement details

@adgiles FYI

**Comment by kgonzago** [comment]
@elinz Closing this since GRG widget doesn't rely on GP services anymore.
