### ISSUE TITLE
GRG Widget - tasks don't execute when published to a single gp service

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#658]
### Widget

GRG
### Version of widget

0.1.0
### Bug or Enhancement

The "Create Area GRG", "Create Point GRG", and "Delete GRG" tools will execute successfully if each tool is published as a separate GP service; however, they will not execute if the tools are published to a single GP service.

Receive error:
cannot open '\server\arcgisserver_directories\arcgissystem\arcgisinput\Test\GRG.GPServer\extracted\v101\Military.sde\GRGGrid'
### Repo Steps or Enhancement details

@adgiles FYI

**Comment by kgonzago** [comment]
@elinz GP service is no longer needed in the new GRG widget.
