### ISSUE TITLE
GRG Widget - redesign gp tools do user does not have to edit python scripts to set the feature class

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#659]
### Widget

GRG
### Version of widget

0.1.0
### Bug or Enhancement

Currently the user is required to edit each Python script to set the path to the enterprise feature class where the output gridded reference grid features are written to. 
### Repo Steps or Enhancement details

Redesign the tools so that the user does not have to edit the Python scripts. One possibility is to add a tool parameter to store the path to this enterprise feature class; the path could then be set when the widget is configured. This would require that the widget design is modified to allow the user to set this path in the configuration page.

@adgiles FYI

**Comment by kgonzago** [comment]
@elinz Closing this since new GRG widget doesn't rely on GP services anymore.
