### ISSUE TITLE
GRG Widget - Deselect Canvas Area and Cell Width

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#662]
### Widget

GRG
### Version of widget

1.0
### Bug or Enhancement

Enhancement
### Repo Steps or Enhancement details

Currently, if you select the Canvas Area or Cell Width button and then decide that you want to pan to another part of the map, you have to finish drawing a sample Canvas Area and then pan around, and reselect the Canvas Area tool when you've decided you want to draw again. I think being able to turn the Canvas Area and Cell Width buttons on and off would be a useful enhancement.

![image](https://cloud.githubusercontent.com/assets/13024357/19666089/36137bca-99fd-11e6-81d3-36d3f9a232f2.png)

**Comment by kgonzago** [comment]
@Dbarnes1 This has been addressed in the new GRG client-side widget
