### ISSUE TITLE
Elevation profile table - Does not appear in widget list of WAB

### ISSUE THREAD

**Issue by cuevasgonzalez** [Esri/solutions-webappbuilder-widgets#663]
Hi,

I am trying to implement the Elevation profile table in a web app but I cannot make it work. I have followed the instructions but I cannot find the list.json file. The last step to implement the widget says to add "ElevationProfileTable" entry to <Web App Builder location>/stemapp/widget/list.json. Am I doing something wrong? The Elevation Profile Table widget does not appear in the list of widgets (Choose widget).

Besides, I have a couple of questions/requests: 

1. I think it would very useful to be able to select any raster file in the web app and not only elevation. I mean, would it be possible to create profiles from any raster file available in the web app? 

2. Is there any possibility to save/export the results of the profile? I would like to export the table with the X, Y, M, Z values so I can use them later or create graphs using other software. 

Many thanks for these useful widgets!
Maria

**Comment by kgonzago** [comment]
@cuevasgonzalez I am assuming you are trying to integrate this widget into WAB 2.1. The steps listed in the README is meant for WAB 2.0 and we will need to update that for WAB 2.1. 

You can create your own profile service and have this widget consume it. Have a look at this link of creating your own profile service: https://blogs.esri.com/esri/arcgis/2014/08/26/setting-up-your-own-profile-service/

Saving/exporting is on the enhancement list but we do not have a timeline of tackling it just yet. 

Also, I recommend using the elevation profile dijit that is part of the JS API: https://developers.arcgis.com/javascript/3/jsapi/elevationprofile-amd.html. It offers more functionalities than the elevation profile table.
