### ISSUE TITLE
Failed to publish feature layer to a 10.3.1 portal for ArcGIS

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#668]
The GRG widget is not able to publish to a 10.3.1 portal for ArcGIS. 

Error that is received by the user when attempting to publish the GRG feature layer: 
"ERROR: Error in opening workspace from sde connection string" error

The feature layer is created in portal, but the layer is empty. The error mentioned above happens on the client side

**Comment by Dbarnes1** [comment]
@elinz fixed this issue by validating the license for ArcGIS Data Store, I was able to verify. I can now publish feature layers and view them in the test portal.
