### ISSUE TITLE
GRG - Labels no longer appear when you create a GRG

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#669]
### Widget
GRG
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
When deploying the widget to my instance of Web AppBuilder Dev Edition, I am able to create a GRG from both point and draw tool, but regardless of what settings I use for labeling I can't get the labels to appear. @elinz and @joebayles have reproduced this issue as well. @kgonzago is looking into this but I'm putting up here to track. @adgiles fyi.

**Comment by joebayles** [comment]
Does https://github.com/Esri/solutions-webappbuilder-widgets/pull/649 contain a fix for this?

**Comment by Dbarnes1** [comment]
@joebayles good question. I'm not sure what is contained in that PR.

**Comment by adgiles** [comment]
Dan you need to change the map options in the main config.json in the root folder of the application from "mapOptions": {}, to "mapOptions": {"showLabels": true}, 

This is a limitation of the web appbuilder that there is no configurable option for this. I have put a request up on ideas:

https://geonet.esri.com/ideas/12811-allow-the-configuration-of-map-options-settings-within-wab

**Comment by MikeMillerGIS** [comment]
Not sure the exact issue, but could you get the label layer and enable it?
   var labelLayer = this.map.getLayer("labels");
        if(labelLayer) {
          labelLayer.show();
        }

**Comment by kgonzago** [comment]
@MikeMillerGIS The GRG widget uses the LabelClass which requires the `showLabels` to be enabled in `mapOptions` of the config.json. The WAB Dev team is aware of this issue and fold in `showLabels` on the next release.

**Comment by Dbarnes1** [comment]
@adgiles thanks for the info! Closing

**Comment by elinz** [comment]
@Dbarnes1 @adgiles @kgonzago Testing this right now. But have a problem with the json structure now in the config.json file.

**Comment by kgonzago** [comment]
@elinz Can you elaborate more on your issue?

**Comment by elinz** [comment]
@kgonzago Yes, once I edited the config.json, I can no longer open the map. Get error "Unexpected string in JSON at position 5304". Is there a help page you can point me to for the "mapOptions" property?

**Comment by elinz** [comment]
@kgonzago Here is the structure:
![image](https://cloud.githubusercontent.com/assets/4635490/20312695/488a4d20-ab09-11e6-89e7-e0655ae6b1cb.png)

**Comment by elinz** [comment]
@kgonzago Haha. User error. Forgot to insert a comma on the line above the "showLabels".
