### ISSUE TITLE
Set symbology and labeling on hosted feature service to match graphics created by widget

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#670]
### Widget
GRG
### Bug or Enhancement
The hosted feature service saved by the widget should have symbology and labeling set to match the graphics created by the widget. I don't think of this as an enhancement, but a bug because if the grid displays in the web app an certain way, I would expect the hosted feature service to look the same way without the user having to manually set the symbology and labeling.

**Comment by kgonzago** [comment]
@elinz Agreed. The settings configuration page for the new GRG widget will allow the user to change color of the grid (polygon fill and outline). Do you think users would want to change the text symbol of the cell labels?

**Comment by elinz** [comment]
@kgonzago I think we should allow them to change the text symbol as well.

**Comment by elinz** [comment]
@kgonzago Was the new settings configuration page for setting symbology and text symbol going to be worked on for this sprint or future work? If current sprint we need to add an asana task.

**Comment by kgonzago** [comment]
@elinz thanks for adding the task to asana.

**Comment by adgiles** [comment]
Is this still valid? It seems to be ok for me, can somebody please verify.

@NatalieCampos @dfoll @ACueva @topowright

**Comment by nfeuerstein** [comment]
Needs to be verified, but removing the verify tag because it's confusing the waffleboard experience. We should probably look into that.

**Comment by Dbarnes1** [comment]
I can verify that this has been fixed, closing out.
