### ISSUE TITLE
GRG - Hexagons

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#673]
### Widget
Gridded Reference Graphic

### Version of widget
1.1

### Bug or Enhancement
Enhancement

### Repo Steps or Enhancement details
Customer has requested a hexagonal grid. Suggest incorporating that into a future version.
http://www.mattpalmerlee.com/resources/ht/js/HexagonTools.js

### FYI
@adgiles @kgonzago

**Comment by adgiles** [comment]
@joebayles @nfeuerstein @kgonzago 

Fix applied in the following branch:  

https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag_GRG_hex_grid/GRG

can someone verify and merge if ok

**Comment by topowright** [comment]
I have verified this enhancement.
