### ISSUE TITLE
Circle does not draw correctly along the international date line

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#679]
### Repo Steps or Enhancement details
Circle draws a line along the international date line when circle crosses the international date line
![image](https://cloud.githubusercontent.com/assets/5488313/20741540/c9f3fb3c-b67f-11e6-8a7c-548e6a7a0780.png)

**Comment by adgiles** [comment]
@topowright 

Lyle, issue resolved please verify

**Comment by Dbarnes1** [comment]
@topowright verified. closing.
