### ISSUE TITLE
GRG Widget Configuration Page does not load

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#680]
### Repo Steps or Enhancement details

I have attempted to use the GRG widget the hosted version of WebApplication Builder on our Portal. I am able to add the widget to the application; however, I am not able to load the configuration page: 

![image](https://cloud.githubusercontent.com/assets/5488313/20816265/52320dfc-b7d6-11e6-8367-82c43d3c00cb.png)

**Comment by topowright** [comment]
@kgonzago

**Comment by kgonzago** [comment]
@topowright I am unable to reproduce it with the latest build of MTA. Can you verify if issue still persists when you get a chance?

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/24008719/a352e6a6-0a2f-11e7-9f0e-acd7805aeea6.png)


verifying and closing.
