### ISSUE TITLE
Distance and Direction WAB widget: densify geometry for lines, circles, ellipses, and Range to match ArcMap/Pro

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#688]
### Widget
Distance and Direction
### Repo Steps or Enhancement details
The following range rings were created using the following parameters:
Center Point (DD): 55.77 37.56
Number of Rings: 5
Ring Interval: 500 Km
Number of Radials: 6
See the following screenshot:
https://cloud.githubusercontent.com/assets/4635490/20906776/c2321770-bafe-11e6-82db-a4ada6760dea.png

(Note: the radials are incorrectly drawn as non-geodetic geometry)

The geometry shape in my opinion should be densified to match the geometries created to ArcMap and ArcGIS Pro to provide a more accurate and pleasing appearance of the graphics.

The following shows the same rings in ArcMap:
https://cloud.githubusercontent.com/assets/4635490/20906812/e9caf7de-bafe-11e6-83cc-0a27e8362cef.png

**Comment by adgiles** [comment]
@lfunkhouser @nfeuerstein @elinz @kgonzago 
Is the the same issue as https://github.com/Esri/solutions-webappbuilder-widgets/issues/689
If so fixed.

**Comment by elinz** [comment]
@adgiles @kgonzago @lfunkhouser @nfeuerstein No, issue #689 is not the same as this. So this issue still needs to be fixed. Thanks.

**Comment by elinz** [comment]
@nfeuerstein @adgiles @kgonzago Tested on 10 Jan 2017 15:25 build of widget. Density of lines, circles, and ellipses look good. However, there was no change in density to range rings. Assigning back to @adgiles and @kgonzago 
![image](https://cloud.githubusercontent.com/assets/4635490/21834608/488e98a6-d76b-11e6-863e-a241be384efd.png)

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles Ellipse looks good
![image](https://cloud.githubusercontent.com/assets/4635490/21933474/68bddc5e-d95a-11e6-82d1-a47905ac59c6.png)

Also re-tested lines, circles and ellipses. Closing issue.
