### ISSUE TITLE
Distance and Direction WAB widget: Radials are not geodetic when creating range rings

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#689]
### Widget
Distance and Direction
### Repo Steps or Enhancement details
The following range rings were created using the following parameters:
Center Point (DD): 55.77 37.56
Number of Rings: 5
Ring Interval: 500 Km
Number of Radials: 6
![image](https://cloud.githubusercontent.com/assets/4635490/20939657/7ba46398-bba4-11e6-923e-7d8e17eef443.png)

Creating in ArcMap creates the following correct radials:
![image](https://cloud.githubusercontent.com/assets/4635490/20939673/850bdcf4-bba4-11e6-889a-f82435a2ebb5.png)

**Comment by adgiles** [comment]
@elinz Fixed please check

**Comment by elinz** [comment]
@adgiles When a fix needs to be verified can you please assign the issue to the person who opened the issue and set the label to verify. It makes it much easier to filter the issues in GitHub that need to be verified. Thanks.

**Comment by elinz** [comment]
@adgiles I downloaded this widget from the master branch and tested. The radials are not being generated correctly. The radials are intersecting the rings at the wrong locations.

![image](https://cloud.githubusercontent.com/assets/4635490/21268736/c11092cc-c364-11e6-935c-289de359f94e.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21268764/e194f59c-c364-11e6-972d-bb884bc6b2d5.png)

Assigning back to you.

**Comment by adgiles** [comment]
@elinz @kgonzago 
redesigned how the code was creating the radials should be fixed now, please can someone check

**Comment by elinz** [comment]
@adgiles @kgonzago I will verify.

**Comment by elinz** [comment]
@adgiles @kgonzago @nfeuerstein The radials are now being drawn correctly, see screenshot below:
![image](https://cloud.githubusercontent.com/assets/4635490/21778886/0d672aac-d65a-11e6-9412-f4c2e4f8abb6.png)

The positional of where the rings and radials are drawn is slightly different that what the ArcMap addin creates. I think about 6 miles, which at this point I believe is do to the density of the vertices. See issue #688 

I will close this issue.
