### ISSUE TITLE
Distance and Direction WAB widget: parameter label on "Range" tab in inconsistent with ArcMap and ArcPro parameter

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#690]
### Widget
Distance and Direction

### Repo Steps or Enhancement details
"Ring Interval" parameter is labeled "Distance Between Rings" on ArcMap and ArcGIS Pro add-ins. Should change parameter label to be consistent across all tools. Recommend following ArcMap/ArcGIS parameter labels.
![image](https://cloud.githubusercontent.com/assets/4635490/20941953/d9810c56-bbad-11e6-8b58-ad077ada08c7.png)

**Comment by adgiles** [comment]
@elinz @kgonzago Fixed

**Comment by kgonzago** [comment]
Verified.
