### ISSUE TITLE
Distance and Direction WAB widget: change name of "Range" tab to match tab name in Pro and ArcMap

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#691]
### Widget
Distance and Direction

### Repo Steps or Enhancement details
The "Range" tab on the Distance and Direction WAB widget is called "Rings" in the ArcMap and ArcGIS Pro add-ins. Would recommend changing tab name from "Range" to "Rings" to be consistent with the add-ins.

![image](https://cloud.githubusercontent.com/assets/4635490/20942000/217b747e-bbae-11e6-912b-de1e2bc35e15.png)

**Comment by adgiles** [comment]
@elinz @kgonzago Fixed

**Comment by kgonzago** [comment]
@elinz Please verify when you have a moment.

**Comment by elinz** [comment]
@adgiles @kgonzago Downloaded the master branch of repo, "installed" widget", and tested that the tab is now called "Rings". Fix has now been verified. Closing issue. Thank you.
