### ISSUE TITLE
Distance and Direction WAB widget: uses same icon as the "My Location" widget

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#692]
### Widget
Distance and Direction

### Repo Steps or Enhancement details
The Distance and Direction widget uses the same icon as the "My Location" widget. Recommend using a different icon that would make more sense for this widget and wouldn't confuse the user.
![image](https://cloud.githubusercontent.com/assets/4635490/20942039/60a40c60-bbae-11e6-8af9-e76afc3e20fb.png)

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles Verified fixed in build 17 Jan 2017 05:11. Closing issue.

![image](https://cloud.githubusercontent.com/assets/4635490/22029185/9ba7b748-dc8e-11e6-96cb-0408c8ae0ee1.png)
