### ISSUE TITLE
Distance And Direction WAB widget: increase dialog height to fit all controls

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#693]
### Widget
Distance And Direction
### Repo Steps or Enhancement details
Can we increase the height of the widget dialog so that all the controls for the Lines and Ellipse tabs are accessible without scrolling down? This would make it easier to use the widget; there is only one parameter and a button on both tabs that need to fix within the default size of the dialog.
![image](https://cloud.githubusercontent.com/assets/4635490/20942092/b0fbe71e-bbae-11e6-8dfe-8b6c2199312d.png)

**Comment by elinz** [comment]
@kgonzago We should also increase the width of the widget dialog as the Range tab is hidden. Users may not realize that this tab exists.

![image](https://cloud.githubusercontent.com/assets/4635490/20992177/4eb9c960-bc97-11e6-871d-40392f67d55a.png)

**Comment by Dbarnes1** [comment]
@kgonzago @elinz just adding my support of this enhancement, particularly in regards to width, in reviewing the doc for this widget I'm having to go back and create doc for using Radials because I missed it the first time.

**Comment by kgonzago** [comment]
@Dbarnes1 @elinz Resizing the widget can be achieved in the WAB app's config.json. Here is a doc link that explains how to do it: https://developers.arcgis.com/web-appbuilder/api-reference/widget-on-screen-configuration.htm. A user also asked the same question on GeoNet: https://geonet.esri.com/thread/121509. I recommend we add how to resize the widget to the widget's doc.

**Comment by Dbarnes1** [comment]
@kgonzago I can add that to the doc for the widgets. Thanks for the link.

**Comment by kgonzago** [comment]
Closing this since it will be addressed in our docs.
