### ISSUE TITLE
Distance And Direction WAB widget: Label for major/minor axis are being truncated

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#696]
### Widget
Distance and Direction - Ellipse
### Bug or Enhancement
Major axis is 3,349,295.5114 feet but label only set to 3349
Minor axis is 1,972,350.3406 feet but label only set to 1972

![image](https://cloud.githubusercontent.com/assets/4635490/20992697/b25d91d8-bc9a-11e6-880d-813673399be3.png)

**Comment by adgiles** [comment]
The reason why the number is being truncated is because the string.replace is only removing the first comma. When the number is large and contains more commas the number will be truncated: Use the /g flag to tell the replace to do all instances.

Change:
'MINOR': parseFloat(dojoDomAttr.get(this.minorAxisInput, 'value').replace(",",''),2),
to
'MINOR': parseFloat(dojoDomAttr.get(this.minorAxisInput, 'value').replace(/,/g,''),2),

**Comment by adgiles** [comment]
@elinz @kgonzago fixed can somebody check and close issue

**Comment by elinz** [comment]
@adgiles @kgonzago I'll test.

**Comment by elinz** [comment]
@adgiles @kgonzago I download the master branch of this repo and tested and I can no longer create an ellipse. 

When I attempt to enter numeric values in the major/minor axis' and orientation angle textboxes I receive the error "The value entered must be numeric." for the axis' textboxes...
![image](https://cloud.githubusercontent.com/assets/4635490/21205891/79c0e504-c213-11e6-974d-0b8dc3d906c1.png)

and I receive the error "The value entered is not valid." when I enter a numeric value in the Orientation Angle control. I now notice that the angle control has changed. This used to be a textbox but now this has increment controls to increase and decrease the angle and no longer allows you to enter a fractional value.
![image](https://cloud.githubusercontent.com/assets/4635490/21205954/e1ed94c4-c213-11e6-94b9-aaaec63edaad.png)

Was the change in orientation angle control intentional?

Assigning the issue back to @adgiles

**Comment by adgiles** [comment]
@elinz 

I have changed the controls to allow decimal places, it made sense in my head not to allow, but on rethinking of course you may want to add a decimal place for distances such as kilometres (e.g. 11.5)

**Comment by elinz** [comment]
Verified fixed. Closing issue.
