### ISSUE TITLE
Distance And Direction WAB widget: Ellipse Center Point parameter does not have "Set Coordinate Format String" control

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#697]
### Widget
Distance and Direction

### Version of widget
Build 06 Dec 2016 13:31 (manual build)

### Bug or Enhancement
Lines, Circle and Range tools have this control as shown below:
![image](https://cloud.githubusercontent.com/assets/4635490/20992909/023958a8-bc9c-11e6-921e-d1c6f050f12f.png)

However, the Ellipse Center Point parameter does not have this control. Any control that can accept coordinates should have this control.
![image](https://cloud.githubusercontent.com/assets/4635490/20992916/18945788-bc9c-11e6-8cea-25c0a93c3dec.png)

**Comment by nfeuerstein** [comment]
@dhagens was this fixed and can be moved to verify?

**Comment by elinz** [comment]
@nfeuerstein Installed latest widgets. Control has been added. I'm testing it now.

**Comment by elinz** [comment]
@nfeuerstein @dhagens Tested with widget dated 22 Dec 2016 13:08 and control has been added and I've verified that it's working. Closing issue.
