### ISSUE TITLE
Distance And Direction WAB widget: Ellipse Axis Unit is ignored; ellipse units always uses feet or meters

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#698]
### Widget
Distance And Direction - Ellipse tool
### Version of widget
Widget Jenkins build 20161208 05:03
### Bug or Enhancement
Unit drop-down control has not effect. Ellipse unit appears to always be feet or meters

![image](https://cloud.githubusercontent.com/assets/4635490/21019157/58ce2fee-bd24-11e6-82bd-76ce60beb17a.png)

### Repo Steps or Enhancement details

**Comment by adgiles** [comment]
@elinz @kgonzago fixed can somebody check and close issue

**Comment by kgonzago** [comment]
verified.
