### ISSUE TITLE
Distance and Direction WAB widget: created ellipses are not geodetic

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#699]
### Widget
Distance and Direction - Ellipse
### Version of widget
Widget built 08 Dec 2016 05:03
### Bug or Enhancement
Here is the ellipse drawn in the widget:
![image](https://cloud.githubusercontent.com/assets/4635490/21021942/9f964e42-bd2f-11e6-859d-bb7b87a05ce9.png)

Here is the ellipse correctly drawn in ArcMap addin:
![image](https://cloud.githubusercontent.com/assets/4635490/21021970/bf1dd7f8-bd2f-11e6-8e15-7f9fef41b7e2.png)

### Repo Steps or Enhancement details

**Comment by elinz** [comment]
@kgonzago The fix for this issue and #107 and #695 were fixed in the master branch of this repo (i.e. https://github.com/Esri/solutions-webappbuilder-widgets) however, Jenkins is building from the Dev branch of https://github.com/Esri/military-tools-webappbuilder.git. Is the Jenkins build being made from the wrong repo or are the fixes being made to the wrong repo?

**Comment by adgiles** [comment]
After investigation it appears that the geodesicDensify function that we are running on the created ellipse creates geodesic lines between each vertex of the ellipse and not on the whole geometry. We are currently using 60 points to create the ellipse so there is not a noticeable difference.

With Kevin's help we dug into the core javascript code, and a geodesic circle is not created by just apply the geodesicDensify function to standard polygon geometry but uses the following function:

 _createGeodesicCircle: function (center, radiusMeter, numberOfPoints) {
      var alpha = 0,
        toRad = Math.PI / 180,
        pts = [],
        pt, geodesicCircle;
      while (alpha < 2 * Math.PI) {
        pt = geodesicUtils._directGeodeticSolver(center.y * toRad, center.x * toRad, alpha, radiusMeter);
        pts.push([pt.x, pt.y]);
        alpha += Math.PI / (numberOfPoints / 2);
      }
      //close the polygon
      pts.push(pts[0]);
      //under wkid 4326
      geodesicCircle = new Polygon(pts);
      return geodesicCircle;
    }

in tern this function calls another function (geodesicUtils._directGeodeticSolver) for each point it creates:

 //direct and inverse geodesic solver algorithm is based on http://www.ngs.noaa.gov/PUBS_LIB/inverse.pdf
  //http://en.wikipedia.org/wiki/Vincenty's_formulae
  function _directGeodeticSolver( /*radians*/ lat, /*radians*/ lon, /*radians*/ alpha, /*meters*/ s) {
    var a = 6378137,
        b = 6356752.31424518,
        f = 1 / 298.257223563, // WGS84 ellipsoid params
        sinA = Math.sin(alpha),
        cosA = Math.cos(alpha),
        tanU1 = (1 - f) * Math.tan(lat),
        cosU1 = 1 / Math.sqrt((1 + tanU1 * tanU1)),
        sinU1 = tanU1 * cosU1,
        sigma1 = Math.atan2(tanU1, cosA),
        sinsqAlpha = (cosU1 * sinA) * (cosU1 * sinA),
        cosSqAlpha = 1 - sinsqAlpha,
        uSq = cosSqAlpha * (a * a - b * b) / (b * b),
        coef1 = 1 + uSq / 16384 * (4096 + uSq * (-768 + uSq * (320 - 175 * uSq))),
        coef2 = uSq / 1024 * (256 + uSq * (-128 + uSq * (74 - 47 * uSq))),
        sigma = s / (b * coef1),
        sigmaP = 2 * Math.PI,
        sinSigma, cosSigma, cos2SigmaM, deltaSigma;
    while (Math.abs(sigma - sigmaP) > 1e-12) {
      cos2SigmaM = Math.cos(2 * sigma1 + sigma);
      sinSigma = Math.sin(sigma);
      cosSigma = Math.cos(sigma);
      deltaSigma = coef2 * sinSigma * (cos2SigmaM + coef2 / 4 * (cosSigma * (-1 + 2 * cos2SigmaM * cos2SigmaM) - coef2 / 6 * cos2SigmaM * (-3 + 4 * sinSigma * sinSigma) * (-3 + 4 * cos2SigmaM * cos2SigmaM)));
      sigmaP = sigma;
      sigma = s / (b * coef1) + deltaSigma;
    }
    var temp = sinU1 * sinSigma - cosU1 * cosSigma * cosA,
        lat2 = Math.atan2(sinU1 * cosSigma + cosU1 * sinSigma * cosA, (1 - f) * Math.sqrt(sinsqAlpha + temp * temp)),
        lambda = Math.atan2(sinSigma * sinA, cosU1 * cosSigma - sinU1 * sinSigma * cosA),
        coef3 = f / 16 * cosSqAlpha * (4 + f * (4 - 3 * cosSqAlpha)),
        adjustedLon = lambda - (1 - coef3) * f * Math.sqrt(sinsqAlpha) * (sigma + coef3 * sinSigma * (cos2SigmaM + coef3 * cosSigma * (-1 + 2 * cos2SigmaM * cos2SigmaM))),
        lat2Deg = lat2 / (Math.PI / 180),
        lon2Deg = (lon + adjustedLon) / (Math.PI / 180),
        pt = new Point(lon2Deg, lat2Deg, new SpatialReference({
          wkid: 4326
        }));
    return pt;
  } 

I am afraid this math is somewhat above me and this issue may have to go back to the core team

**Comment by nfeuerstein** [comment]
@kgonzago @adgiles has it been determined whether or not we can support geodetic circles with this widget?  Are lines and ellipses geodesic?

**Comment by kgonzago** [comment]
@nfeuerstein Circles, line and range rings are geodesic but ellipses are not at the moment. It's a limitation in the API for now.

**Comment by kgonzago** [comment]
@nfeuerstein we will need to doc this limitation in our documentation.

**Comment by kgonzago** [comment]
@Dbarnes1, can this limitation be added to our docs?

**Comment by Dbarnes1** [comment]
@kgonzago I'll make sure it gets added, I'm assigning this issue to me so I don't forget.

**Comment by Dbarnes1** [comment]
@kgonzago limitation has been added to Ellipse topics in Distance and Direction Widget doc, assigning to @dfoll to verify that is the proper place to document this limitation.

**Comment by elinz** [comment]
@lfunkhouser @Dbarnes1 @kgonzago Assigning this back to @dfoll to verify addition to documentation.

**Comment by dfoll** [comment]
looks to me like @Dbarnes1 made these changes in two places in the documentation (under both ellipse topics). verified.

![image](https://cloud.githubusercontent.com/assets/5322669/21830444/94497672-d751-11e6-8bee-03765d100c0b.png)
![image](https://cloud.githubusercontent.com/assets/5322669/21830447/996e2c1a-d751-11e6-8286-2b7e5389f16f.png)
