### ISSUE TITLE
Distance and Direction WAB widget: unit conversions are being performed on Lines and Ellipse tools

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#700]
### Widget
Distance and Direction - Lines and Ellipse tools
### Version of widget
Widget built 08 Dec 2016 05:03 Jenkins build
### Bug or Enhancement
On the Lines tool dialog, if you set a Length or the Angle value and then change the units of measure, the length and angle values are converted to the selected unit.

For example, if I enter in 10000 feet and 90 degrees...
![image](https://cloud.githubusercontent.com/assets/4635490/21023425/5946c5d8-bd35-11e6-8e90-69b9ac60ffb1.png)
and then change the units to miles and mils, the length and angle values are converted to miles and mils  as shown below...
![image](https://cloud.githubusercontent.com/assets/4635490/21023483/8a6f923e-bd35-11e6-8dd4-ec0c0fbab45b.png)

The same thing is occurring on the ellipse dialog. For example, I enter 10000 and 5000 meters for major and minor axis, respectively and 90 degrees for orientation angle...
![image](https://cloud.githubusercontent.com/assets/4635490/21023609/1661d022-bd36-11e6-922d-cda2036eb97f.png)
and then change the units to miles and mils, and the axis' and angle values are converted to miles and mils as shown below...
![image](https://cloud.githubusercontent.com/assets/4635490/21023641/3a946040-bd36-11e6-9e56-81a879724cbc.png)

When users change units we should not be converting the values. As I user, if I am manually entering values, I already have a particular unit in mind. So if I open the tool and want to change length for example to 1000 (because I want to enter 1000 kilometers). I would type in 1000 into the textbox and then change the units to Kilometers. Problem is that now the tool has converted 1000 to 1508.0350 which is incorrect and now I have to go back and reenter 1000.

NOTE: ArcMap is making no automatic unit conversions.

I'm marking this as a bug and not an enhancement because this lead to incorrect graphics being created and the user may not notice that the values have been automatically changed on them.

### Repo Steps or Enhancement details

**Comment by adgiles** [comment]
@elinz @kgonzago 

Fixed please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Verified that this issue was fixed in build 11 Jan 2017 09:51. I texted all input controls that had an associated units control on for Lines, Circle, Ellipse, and Rings. Closing issue.
