### ISSUE TITLE
The GRG widget cannot be added via web app builder on our development portal

### ISSUE THREAD

**Issue by MaryClawson** [Esri/solutions-webappbuilder-widgets#701]
The work flow is to create a web map and save using a web app and then chose webapp builder tab, then open the widgets tab and select from pick 1 which has GRG at the end of the list, but when you click on it, it never loads.

**Comment by elinz** [comment]
@MaryClawson @topowright The title for this issue is extremely long. Please move the title info the description of the issue and create a simplified title. Thanks.

**Comment by topowright** [comment]
Being that this is not a supported workflow I am going to un assign myself.

**Comment by kgonzago** [comment]
not a supported workflow. closing.
