### ISSUE TITLE
Distance and Direction WAB widget: A selected tool needs to be deselected between change of tabs

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#704]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

When changing tabs within the widget any selected tool needs to be deselected otherwise you end up drawing multiple graphics at once

![bug](https://cloud.githubusercontent.com/assets/3740334/21177207/0aeaba5a-c1e2-11e6-805e-1917bf621417.png)

**Comment by adgiles** [comment]
@kgonzago 

Fixed please verify all functioning correctly

**Comment by joebayles** [comment]
Verified.
