### ISSUE TITLE
Distance and Direction WAB widget: How to stop drawing when using interactive Rang Ringes

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#705]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

When drawing Range rings using the interactive option there is no way to stop drawing, the only way I have found is to select the tool again but then it is waiting for a new point to be placed

**Comment by nfeuerstein** [comment]
Does double-clicking work like it does in ArcMap/Pro?

**Comment by adgiles** [comment]
Yes sorry, Kevin informed me of that earlier. May the tooltip should inform the user as it not obvious

**Comment by adgiles** [comment]
My Bad on checking again the tooltip is changed after the first circle is drawn
