### ISSUE TITLE
Coordinate Conversion: dialog "snaps" back to original position when size of browser is altered

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#706]
### Widget
Coordinate Conversion
### Version of widget
14 Dec 2016
### Bug or Enhancement
If I move the widget interface to another location within the browser and then change the size of the browser, the widget moves back to the original opened position.

### Repo Steps or Enhancement details
1. Create a web app with the coordinate conversion widget.
2. Save the app and Launch the app.
3. Alter the size of the browser, for instance, maximize the browser to fit the computer monitor. The widget will move back to it's original location under the widget button.

**Comment by adgiles** [comment]
@elinz 

This happens with all widgets including the ones out of the box on all the themes where you can place widgets on the map area (not within a header controller group):

- Billboard Theme
- Foldable Theme
- Jewelry Box Theme
- Launchpad Theme

I don't recommend we start change core functionality

**Comment by topowright** [comment]
This does not seem to be something that we need to fix based on the comments above.
