### ISSUE TITLE
Coordinate Conversion: tooltip for format input control should be changed from "Format Output" to "Format Input"

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#707]
### Widget
Coordinate Conversion
### Version of widget
14 December 2016
### Bug or Enhancement
![image](https://cloud.githubusercontent.com/assets/4635490/21195170/8e5f6b7e-c1e7-11e6-8b71-457f22e421c5.png)

**Comment by elinz** [comment]
After further review, I don't believe this control should exist for the Input coordinate. See issue #717.

**Comment by elinz** [comment]
Ignore my previous comment that I don't believe this control should exist. It indeed is used when you specify input coordinates by clicking on the map. The tooltip should still be changed to "Format Input".

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
