### ISSUE TITLE
NetworkTrace Widget - Name

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#71]
Name of widget on the file system is Network Trace, the name in the builder is Isolation Trace.  Please rename the widget in the builder to Network Trace

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will make the necessary changes in the next release

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS This is currently under implementation and we will deliver this in next release along with revised Save to Layer functionality

**Comment by MikeMillerGIS** [comment]
verified
