### ISSUE TITLE
Distance and Direction: revert the Orientation Angle control for Ellipses back to textbox

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#713]
### Widget
Distance and Direction
### Version of widget
15 Dec 2016
### Bug or Enhancement
The Orientation Angle control type was changed so users can increase/decrease value by clicking up/down arrows on control (see screenshot below). The was changed for some reason. It used to be a textbox. It needs to be changed back to a textbox. 1) All the other controls on the widget use textboxes 2) ArcMap and ArcGIS Pro use textboxes. We need to ensure consistency across widgets and addin as much as possible.
![image](https://cloud.githubusercontent.com/assets/4635490/21232731/91c85d10-c2a1-11e6-90cd-6259a6d03e70.png)

**Comment by adgiles** [comment]
@elinz 
Reverted back to text box, also put logic in to change validation rules when the angle type is switched between degrees/mils i.e. max value is either 360/6400

**Comment by elinz** [comment]
@adgiles Downloaded the widget from the master branch and tested. The message text for indicating an out of bounds value has an extraneous word "than". 
![image](https://cloud.githubusercontent.com/assets/4635490/21270842/3a26a8ce-c36d-11e6-8ebc-9b3034c81b59.png)
![image](https://cloud.githubusercontent.com/assets/4635490/21270858/43ccd510-c36d-11e6-9269-d182f347bbb9.png)

Assigning back to you.

**Comment by adgiles** [comment]
@elinz removed the extra word

**Comment by elinz** [comment]
@adgiles Verified. Closing this issue.
