### ISSUE TITLE
Holistic Testing - Coordinate Conversion - WAB 2.1

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#714]
_From @adgiles on November 4, 2016 17:59_

I think the name of this widget is confusing as the widget does not perform any coordinate conversion it is simply doing coordinate notation and I suspect it will only work with a base map that is projected in WMAS (srid 102100) or Geographics (srid 4326).

For instance if you use a base map projected in British National Grid the widget display incorrect values:

Ordnance Survey Open Background:
https://www.arcgis.com/home/item.html?id=592dfeed67874e818bde90b0043011f0

## Expected Behavior
If the widget is supposed to perform coordinate conversion then the user input should be sent a geometry service to perform the projection  

## Current Behavior
Widget is trying to notate value that are incorrect

## Possible Solution
Use a geometry service to perform coordinate conversion

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#45_

**Comment by nfeuerstein** [comment]
@Dbarnes1 is this, as well as the ArcMap and Pro add-ins, fully documented in a way that the user understand that the tool is only converting notation, not datums?

**Comment by Dbarnes1** [comment]
@nfeuerstein yes.
 This is the first sentence of the overview topic for coordinate conversion in both the widget, arcmap, and pro (the word notation is key):

Coordinate Conversion allows users to input coordinates and quickly convert them between several common coordinate notation formats; including Universal Transverse Mercator (UTM), Degrees Minutes Seconds (DMS), and Military Grid Reference System (MGRS), and more.

**Comment by nfeuerstein** [comment]
Addressed through documentation.
