### ISSUE TITLE
Coordinate Conversion: losing positional accuracy between coordinate formats

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#715]
**This is an extremely important bug**
### Bug or Enhancement

The widget is not maintaining the same input coordinate positional accuracy in the output values for DD, DDM, and DMS.

For example, I enter 44.608559N 033.528627E for the Input value.  See screenshot below:
![image](https://cloud.githubusercontent.com/assets/4635490/21235609/546b52aa-c2ac-11e6-97ba-e7f831c15adb.png)

The input value is 44.608559N 033.528627E; (6 decimal places lat/long). Which using the calculator at [NGA](http://msi.nga.mil/MSISiteContent/StaticFiles/Calculators/degree.html) to determine the length of a degree of latitude and longitude at 45 degrees, I calculate that storing a coordinate down to 6 decimal places will allow a location to be stored down below a 1/10 of a meter (i.e. 0.11 meters of latitude and 0.08 meters of longitude). See snapshot of my spreadsheet below:
![image](https://cloud.githubusercontent.com/assets/4635490/21207152/4afad2c2-c21b-11e6-81ed-63eda986e410.png)

However, the default formatting for DD, DDM, and DMS do not allow us to output the coordinate down to the same accuracy.
- The output for DD displays out to 2 decimal places, only gets us down to approx. 1,111 meters of latitude and approx. 788 meters of longitude (see screenshot above).

- The output for DDM displays the decimal minute out to 2 decimal places, which based on my calculations, gets us down to approx. 18 meters of latitude and approx. 13 meters of longitude.
![image](https://cloud.githubusercontent.com/assets/4635490/21207370/cf26a2fa-c21c-11e6-9c59-a7f04465d590.png)

- The output for DMS displays seconds out to a single decimal place, which based on my calculations, gets us down to approx. 3 meters of latitude and 2 meters of longitude.
![image](https://cloud.githubusercontent.com/assets/4635490/21207446/eccca002-c21c-11e6-9762-e6477a8ba3f2.png)

The default configuration of the output coordinate formats should not store a less accuracy position then the user has entered. If the user wants to add custom formats and change the number of decimal places that's fine, but out of the box, the widget must calculate the same positional accuracy

Another example, would be the user entering the MGRS coordinate down to the meter, such as 36TWQ4194739604 (Sevastopol location specified above) and asking for DD, DDM, or DMS as the output. We are not providing the same coordinate back to the user.

**Comment by elinz** [comment]
The format of the input coordinate needs to altered as well. The screenshot above shows a DD coordinate that I pasted into the input textbox that has 6 decimal places, however, if you choose to interact with the map to obtain the coordinate, the widget only captures out to 2 decimal places for the input, which approx. equates to 1.1 Kilometers on the ground.

For more info see the following issues for the coordinate conversion Pro and ArcMap addins:
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/157
https://github.com/Esri/coordinate-conversion-addin-dotnet/issues/158

The resolution was to change the default format for DD, DDM, and DMS output:
- Changed the default DD format to display up to 6 significant digits, but always display at least one significant digit:
![image](https://cloud.githubusercontent.com/assets/4635490/21787122/3fb677de-d67c-11e6-85ff-410a712b6b87.png)

- Changed the default DDM format to display up to 4 significant digits, but always display at least one significant digit: 
![image](https://cloud.githubusercontent.com/assets/4635490/21787129/51479000-d67c-11e6-8940-32b20c8f50f9.png)

- Changed the default DMS format is set to display up to 2 significant digits, but always display at least one significant digit:
![image](https://cloud.githubusercontent.com/assets/4635490/21787140/61c27080-d67c-11e6-9ac6-cd3cef501219.png)

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles Verifed on build 13 Jan 10:31. Closing issue.
