### ISSUE TITLE
Holistic Testing - Visibility Widget - WAB 2.1

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#716]
_From @adgiles on November 4, 2016 17:0_

Is this widget complete as I do not see any configuration options for adding an underlying elevation service, when I click the settings button I get the following error:

Uncaught TypeError: Cannot read property 'inputCoordinate' of undefined

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Version used:
* Environment name and version (e.g. Chrome 39, node.js 5.4):
* Operating System and version (desktop or mobile):
* Link to your project:

_Copied from original issue: Esri/military-tools-for-arcgis#37_

**Comment by lfunkhouser** [comment]
_From @topowright on December 12, 2016 7:56_

The visibility widget now has a configuration page: 

![image](https://cloud.githubusercontent.com/assets/5488313/21091800/727c903a-bffd-11e6-9d24-3809ae973a98.png)

@adgiles please verify.

**Comment by lfunkhouser** [comment]
_From @topowright on December 12, 2016 7:58_

Just for clarity the gp service should be the one that sets the elevation layer. the widget just needs to point to the gp service.

**Comment by kgonzago** [comment]
Verified. Widget does have a configuration page.
