### ISSUE TITLE
Coordinate Conversion: UTM coordinate is not being calculated correctly

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#718]
### Widget
Coordinate Conversion
### Version of widget
15 December 2016
### Bug or Enhancement
The UTM easting and northing are correct, but not the zone.
### Repo Steps or Enhancement details
Enter: 34KGE3581934434
The UTM value is calculated as: 34S 735819 7934434 but should be 34K 735819 7934434
![image](https://cloud.githubusercontent.com/assets/4635490/21237261/09d957b2-c2b3-11e6-8c91-12ac95c29f12.png)

**Comment by elinz** [comment]
Another example, enter:  45.0N 100.0W
The output UTM is calculated as 14N 421184 4983436 but should be 14T 421184 4983436
![image](https://cloud.githubusercontent.com/assets/4635490/21663435/069369d4-d295-11e6-9c19-9014b84fc9ed.png)

**Comment by adgiles** [comment]
@elinz @nfeuerstein @kgonzago 

Eric,

The AGS Geometry Service provides two ways of outputting UTM grid zones:

- UTMNorthSouth:
       Outputs UTMZone number followed by a north/south latitude indicator then grid eg: 34S 735819 7934434 
- UTMDefault:
      Outputs UTMZone number followed by 100-km square letter then grid eg: 34K 735819 7934434

The tool is using UTMNorthSouth so the output is correct but maybe confusing to the user, it is probably worth changing the tool to use UTMDefault does everybody agree or was the tool specifically designed in this way?

**Comment by nfeuerstein** [comment]
This is what NGA has to say about UTM:

- Since the above expresses two possible positions on the earth, the hemisphere may also be specified, e.g. “580817mE, 4251205mN, Zone 15, Northern Hemisphere” (Figure 4).
- Many systems abbreviate the above, representing the hemisphere as a single letter, “N” for northern hemisphere, and “S” for southern hemisphere, e.g. “15N 580817 4251205”.
- CAUTION: IN MANY SYSTEMS, THE LETTER AFTER THE ZONE NUMBER DESIGNATES A LATITUDINAL BAND, NOT A HEMISPHERE.

It seems to me that the North/South designation should be default if the latitudinal band/grid zone designation warrants a caution note.

**Comment by lfunkhouser** [comment]
@Dbarnes1 @dfoll This needs to be added to the documentation explaining hemisphere vs zone and this tool uses hemisphere

**Comment by elinz** [comment]
@adgiles @nfeuerstein @dfoll @Dbarnes1 The widget is using UTMNorthSouth, however, the ArcMap and ArcGIS Pro addins are using UTMDefault. If we're going to leave the widget as UTMNorthSouth then the ArcMap and ArcGIS Pro addins have to be altered to use the same, otherwise we are not consistent across our tools. 

The site http://earth-info.nga.mil/GandG/coordsys/grids/utm.html which I believe @nfeuerstein is referencing states that many systems use N and S and many systems use the latitudinal band for UTM. While they do mark the use of latitudinal band with a caution, they also have the same caution when they discuss MGRS. Nobody ever raises a concern about us using latitudinal bands with MGRS (I've never seen MGRS coordinates noted with N and S; I've only seen MGRS with latitudinal bands). Therefore, I'm inclined to have the widget changed to use UTMDefault.

Whatever we decide we should add a note in the documentation for UTM, MGRS and probably USNG.

**Comment by nfeuerstein** [comment]
I agree with the need for consistency across our tools here.  Earlier this morning we discussed adding a second UTM option, so that the user could choose between UTM N/S and UTM GRID, or show both if they so please.  This is the best case scenario, but outside what we can accomplish in the next few days.  I was under the impression that ArcMap/Pro were calling hemisphere identification as well...but since they are not we should change the widget to use UTMDefault as @elinz suggested.  @adgiles @Dbarnes1 @dfoll

**Comment by elinz** [comment]
There are other options we have to consider to expose for uses to set for future releases with regard with coordinates such as whether to round or not round MGRS. I'm sure there are others. But all left for a future discussion :)

**Comment by adgiles** [comment]
@nfeuerstein @elinz 

Added the ability to have UTM shown with the 100 Km Zone numbers (UTM (Z)) or Hemisphere Letter (UTM (H)).

Documentation will need updating to reflect this change

**Comment by elinz** [comment]
@adgiles 
- When I configured the web app I selected UTM as one of the outputs, however in the web app the UTM output control is configured for DD
![image](https://cloud.githubusercontent.com/assets/4635490/21942933/eb677b1e-d983-11e6-989a-87d9e4c27bf5.png)

![image](https://cloud.githubusercontent.com/assets/4635490/21942936/efcdd9e6-d983-11e6-858a-71e3a92472ec.png)


- When the Coordinate Conversion widget is opened the UTM output doesn't contain a value:
![image](https://cloud.githubusercontent.com/assets/4635490/21943214/1c577a0c-d985-11e6-8cce-1a3a681ba66b.png)

- Naming the the UTM latitude option as "UTM (Z)" is confusing as Z is used to indicate the Zone. It would make more sense to use "UTM (B), i.e. B for latitude band". Then use B in the formatting dialog as the character for latitude band (see below).

- There is no formating character for UTM (latitude band) after the Z. UTM (Z):
![image](https://cloud.githubusercontent.com/assets/4635490/21943299/802be2e8-d985-11e6-9be4-08ae5783d59a.png)
There is the formatting character H for the UTM hemisphere entry:
![image](https://cloud.githubusercontent.com/assets/4635490/21943645/0b4702b2-d987-11e6-8efd-8330f2f826b7.png)

Reassigning to @adgiles

**Comment by nfeuerstein** [comment]
@adgiles, please revert so that the widget uses just UTM (latitude band) - this keeps it consistent across arcmap, pro, and the widget.

**Comment by adgiles** [comment]
Widget now only supports UTM with latitude band, please verify

**Comment by elinz** [comment]
@adgiles @nfeuerstein Verified on build 16 Jan 2017 05:11 that code was reverted and now the UTM calculates output as UTM with latitude band and not hemisphere designators.

Tested with the following DD inputs and widget created the following correct output:
34KGE3581934434 -> 34K 735819 7934434
45.0N 100.0W -> 14T 421184 4983436
45.0N 100.0E -> 47T 578815 4983436
45.0S 100.0W -> 14G 421184 5016563
45.0S 100.0E -> 47G 578815 5016563

Closing issue.
