### ISSUE TITLE
Coordinate Conversion: "Copy All" button does not include the input coordinate

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#719]
### Widget
Coordinate Conversion
### Version of widget
15 December 2016
### Bug or Enhancement
When you click on "Copy All" button, see screenshot below. The input coordinate is not copied with all the output coordinates. If you're copying all the coordinates, you want to know what the input coordinate is associated with all the output values.
![image](https://cloud.githubusercontent.com/assets/4635490/21237995/1996fc7e-c2b6-11e6-9cba-525e56bb6ec7.png)

Clicking "Copy All" button using the coordinate shown in the screenshot above and pasting into a text files gives the following:
18.67S 023.24E
18° 40.08'S 23° 14.14'E
18° 40' 4.8"S 23° 14' 8.6"E
407FY19
34KGE3581934434
34K GE 35819 34434
34S 735819 7934434

In ArcMap and ArcGIS Pro addins, clicking "Copy All" will give you the following, where the first line is the input coordinate:
34KGE3581934434
18.67S 23.24E
18° 40.08'S 23° 14.14'E
18° 40' 4.8"S 23° 14' 8.6"E
407FY19
34KGE3581934434
34KGE3581934434
34K 735819 7934434

**Comment by adgiles** [comment]
Fix please verify

**Comment by elinz** [comment]
@adgiles Verified fixed on build 16 Jan 2017 10:41. Closing issue.
