### ISSUE TITLE
Distance and Direction WAB widget: Range rings drawn interactivley get drawn to the graphics layer incorrect

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#720]
### Widget
Distance and Direction WAB widget

### Version of widget
2.1 & 2.2

### Bug or Enhancement

When you draw a range ring interactively it creates a geodesic circle, it then looks like this circle gets the geodesic function applied again when added to the graphics layer

### Repo Steps or Enhancement details

Use the interactive option on the Rings tab to draw a circle that is high or low in latitude (near a pole). Looks ok when drawn but when double clicked and drawn to the map it looks like the geodesic circle gets corrupted.

![1](https://cloud.githubusercontent.com/assets/3740334/21263848/ef1a60cc-c390-11e6-99ce-4a5baa20ec7e.png)
![2](https://cloud.githubusercontent.com/assets/3740334/21263849/f0e33d0c-c390-11e6-9d97-4b6151aa3235.png)

**Comment by adgiles** [comment]
@kgonzago 

When drawing the circles from the clicked locations the radius of the circle was being determined using the geometry engine distance function which returns a planar distance instead of a geodesic length. I changed the function to use geodesicLength instead which seems to have fixed the issue.

Please can you do an independent check

**Comment by kgonzago** [comment]
@adgiles will do.

**Comment by kgonzago** [comment]
verified.
