### ISSUE TITLE
Graphic Labels are not rendered for Distance and Direction widget in WAB 2.2

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#724]
_From @kgonzago on November 4, 2016 18:51_

In WAB 2.2, the labels are not rendered after a line is created. This applies to circles, ellipses and range rings.

_Copied from original issue: Esri/military-tools-webappbuilder#111_

**Comment by kgonzago** [comment]
The labels are rendered accordingly after a line, circle, ellipse and/or range ring is created. A user will need to add `showLabels` in the `mapOptions` of the app config.json file and set that parameter to `true`.
