### ISSUE TITLE
Allow user to copy information from graphic label created in Distance and Direction Widget

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#725]
_From @kgonzago on November 4, 2016 18:47_

The D&D widget renders graphic labels after a shape is drawn. The labels have information about the shape that was created (ex: length, angle, radius). Provide the ability to copy/past those labels.

_Copied from original issue: Esri/military-tools-webappbuilder#110_

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#447
