### ISSUE TITLE
Line in Distance and Direction widgets needs to be an arrow

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#726]
_From @kgonzago on November 4, 2016 18:45_

render an arrow to indicate direction the line has been drawn.

_Copied from original issue: Esri/military-tools-webappbuilder#109_

**Comment by Dbarnes1** [comment]
Looks like this has been fixed: 
![image](https://cloud.githubusercontent.com/assets/13024357/21369559/612ee506-c6bc-11e6-8c6e-bf1248c68def.png)

Not sure where the pr was for this but it's definitely drawing a line now.
