### ISSUE TITLE
Coordinate Conversion "Unable to determine input coordinate type"

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#727]
_From @mfunk on October 3, 2016 18:56_

Type (not paste) in the following coordinates for Mexico City: _19.4326 N, 99.1332 W_ and we get the error: "Unable to determine input coordinate type".

![image](https://cloud.githubusercontent.com/assets/3093182/19049661/3885c5c8-8960-11e6-8c3e-5e3f59d031c8.png)

The coordinates are valid in Google Maps:
![image](https://cloud.githubusercontent.com/assets/3093182/19049719/6c6b1dd4-8960-11e6-85aa-325371690a36.png)

_Copied from original issue: Esri/military-tools-webappbuilder#108_

**Comment by adgiles** [comment]
Again similar to #749 i have fixed this issue but all the regular expressions need a thorough review

@mfunk please verify

**Comment by nfeuerstein** [comment]
1. Copy over reg ex being used in Pro and ArcMap into the widgets
2. All documentation for coordinate notation support is consistent

**Comment by kgonzago** [comment]
@nfeuerstein @lfunkhouser @mfunk 

I discussed this with @adgiles and we determined it isn't as easy as we thought it would be. The RegEx used in the add-in are compartmentalized into a C# class per notation. The widget will need to be refactored to mimic that code structure, and that can be quite an effort. As it stands, the widget will handle most conversion scenarios but will fall short of mimicking what's available in the add-in.

**Comment by elinz** [comment]
@nfeuerstein @lfunkhouser @mfunk @adgiles Based on the last comment, implementing the same RegEx expressions in the addins in the widget may not happen this release, so I'm currently testing build 16 Jan 10:41 against the know coordinate notations handled by arcmap/pro addins, i.e. hemisphere designators, coord-pair-separators, etc. and seeing what differences there are.

**Comment by nfeuerstein** [comment]
Fixed.  Needs to be verified.

**Comment by Dbarnes1** [comment]
verified that this is now working. closing out. ![image](https://cloud.githubusercontent.com/assets/13024357/22032651/2a9190ea-dc9a-11e6-8bff-f6dcbfe04ee3.png)

**Comment by elinz** [comment]
@nfeuerstein Going to create a new separate issue so that we can address the change in RegEx in the widget to match the addin in the future.
