### ISSUE TITLE
Ellipse rotation not drawn in IE and Firefox

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#729]
_From @mfunk on August 16, 2016 16:9_

I'm testing the Ellipse (semi, interactive draw on map) where I'm selecting a center point, then drawing the major axis end point about 65-ish degrees from north away, then drawing the minor axis. This works fine in Chrome...
![image](https://cloud.githubusercontent.com/assets/3093182/17706356/90d964aa-6390-11e6-9edd-a5f1134b6462.png)

But this isn't the case in Internet Explorer, where the final, ellipse drawn is drawn almost perpendicular to latitude line:
![image](https://cloud.githubusercontent.com/assets/3093182/17706476/0ca0c2a4-6391-11e6-91db-d859627dcc11.png)

... Firefox has the same problem:
![image](https://cloud.githubusercontent.com/assets/3093182/17706479/0fd46e1c-6391-11e6-8ec5-74f95685decb.png)

_Copied from original issue: Esri/military-tools-webappbuilder#106_

**Comment by lfunkhouser** [comment]
_From @adgiles on December 12, 2016 14:14_

@mfunk @nfeuerstein 

I cannot replicate this issue:
IE: 11.0.9600.16384
FF: 50.0.2

![ie](https://cloud.githubusercontent.com/assets/3740334/21102187/f7388672-c074-11e6-95e0-106c32f5e930.png)
![ff](https://cloud.githubusercontent.com/assets/3740334/21102190/fa6662c4-c074-11e6-9509-8fb246d8e15b.png)

**Comment by adgiles** [comment]
@mfunk @nfeuerstein Please can you confirm if this is still an issue or can this be closed?

**Comment by joebayles** [comment]
Works for me too...
![image](https://cloud.githubusercontent.com/assets/5016557/21872464/81446af6-d81d-11e6-90ff-183c347f1c0d.png)
![image](https://cloud.githubusercontent.com/assets/5016557/21872465/841689da-d81d-11e6-9140-d7f88e7a5922.png)

... and a bonus, Microsoft Edge!
![image](https://cloud.githubusercontent.com/assets/5016557/21872536/cb874f66-d81d-11e6-8376-08b0d5117ac4.png)

**Comment by joebayles** [comment]
Verified.
