### ISSUE TITLE
Isolation Trace - Skippable Field

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#73]
![image](https://cloud.githubusercontent.com/assets/2707285/6485729/aad181ec-c253-11e4-956c-2c3fda98bfe7.png)

Rename Skippable field to Unique ID Field

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS The display text is coming from NLS file. We will change the value of the corresponding NLS parameter to "Unique ID Field" in the next release

**Comment by MikeMillerGIS** [comment]
not an issue anymore
