### ISSUE TITLE
Range ring dialog units not matching label results

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#730]
_From @mfunk on August 15, 2016 14:48_

In testing range ring labels in the widget, I'm seeing a difference between the unit selected in the dialog (kilometers) and the units of the resulting labels (meters). For example, as I type **200** for the interval and select **kilometers** for the units I'm expecting to see labels for 200, 400, 600, 800, 1000 for the 5 rings. However I'm actually getting 200000, 400000, 600000, 800000, 1000000.

![image](https://cloud.githubusercontent.com/assets/3093182/17668041/6c65c78c-62bc-11e6-8a7e-148232eb6d77.png)

I'm not sure if this is as-designed, that output will always be meters, or not. Can anyone verify?

_Copied from original issue: Esri/military-tools-webappbuilder#105_

**Comment by adgiles** [comment]
@mfunk I cannot replicate this issue please can you confirm is still exists if not please close

**Comment by mfunk** [comment]
@adgiles As of today's widgets in Jenkins (build 1097) i'm not seeing any labels at all:

![image](https://cloud.githubusercontent.com/assets/3093182/21894727/1b5366e8-d895-11e6-8d6e-6282b5c94399.png)

But I'm also seeing other weird things too:
1) Lines now showing multiple arrowheads (at each shape point???) with no labels:
![image](https://cloud.githubusercontent.com/assets/3093182/21894849/8812470e-d895-11e6-8865-b24a14c19297.png)

2) No labels for circles or ellipses either.

Not sure if this could be interim weirdness in the builds, a network gremlin in my system, or something else. Need me to log these separately?

**Comment by mfunk** [comment]
Fixed with "showLabels":true

![image](https://cloud.githubusercontent.com/assets/3093182/21899622/ba61f564-d8a5-11e6-9c40-b4a2d8baf00b.png)
