### ISSUE TITLE
Distance and Direction widget - Line  - Distance and Bearing - Angle is being drawn CCW from North

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#732]
_From @pshowalter on August 2, 2016 15:48_

@MarkTorrey It is unexpected that when drawing a line using "Distance and Bearing", when typing in angles (45,90, 270, 300) that a positive angle value will be rendered Counter Clockwise from North.  This is opposite of behavior when drawing the line interactively, and noting the angle reported when completing the line.

![image](https://cloud.githubusercontent.com/assets/6842145/17335035/87aa4100-58a6-11e6-9303-e517ec5099a4.png)

_Copied from original issue: Esri/military-tools-webappbuilder#93_

**Comment by lfunkhouser** [comment]
_From @pshowalter on August 26, 2016 13:54_

- Works for Meters and Feet.
- Issues with this tool when using **Distance and Bearing** with Kilometer, Miles, Nautical Miles.  Green point disappears and no line is created.  
- Blue text label on red line hard to read.

**Comment by kgonzago** [comment]
This issue was resolved with [PR](https://github.com/Esri/military-tools-webappbuilder/commit/283e7adf198d4d2a0a7aee509ec4fdbc9b274f62)
