### ISSUE TITLE
Coordinate Location icon should be a configurable symbol

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#734]
_From @MarkTorrey on June 24, 2016 15:28_

The icon used to display the current coordinate on the map is hard to small and hard to visualize against different basemaps (i.e. imagery). This needs to be updated to use standard map symbology symbol that can be adjusted by the user in the widget settings. @mcalamito  @topowright 

_Copied from original issue: Esri/military-tools-webappbuilder#81_

**Comment by adgiles** [comment]
@elinz @Dbarnes1 

I have updated the config for this widget can somebody verify

**Comment by Dbarnes1** [comment]
@adgiles verified. closing.
