### ISSUE TITLE
Create GitHub Pages

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#735]
_From @kgonzago on May 2, 2016 14:17_

create github pages to showcase the coordinate conversion and distance and direction widgets.

_Copied from original issue: Esri/military-tools-webappbuilder#36_

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 2, 2016 15:52_

Coordinate Conversion Widget for 2.0 is listed on the Coordinate Conversion page: http://solutions.arcgis.com/defense/templates/coordinate-conversion/

Distance and Direction Widget is not mentioned or listed on the Solutions Pages: http://solutions.arcgis.com/defense/templates/distance-direction/ however, there is a download for it at 2.0: http://appsforms.esri.com/products/download/index.cfm?fuseaction=download.all#ArcGIS_for_Defense

**Comment by lfunkhouser** [comment]
_From @Dbarnes1 on December 6, 2016 15:40_

@nfeuerstein with the December release this issue will be resolved, there is documentation waiting in solutions dev for Distance and Direction and Coordinate Conversion: http://solutionsdev.arcgis.com/defense/help/distance-direction/workflows/ellipse-awab/

**Comment by lfunkhouser** [comment]
Closing this issue. Verified that the solutions website documentation is now live and include documentation for Distance and Direction and Coordinate Conversion widgets.

**Comment by kgonzago** [comment]
FYI the GitHub pages have been updated to showcase latest widget development: http://esri.github.io/solutions-webappbuilder-widgets/
