### ISSUE TITLE
Rate of travel needs to reflect the changes to the other add-ins

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#736]
_From @topowright on April 11, 2016 6:56_

The rate of travel for the drop down on the Distance Calculator should look and calculate like this: 
1. Miles per/sec
2. Miles per/hour
3. Meters per/sec
4. Meters per/hour
5. Kilometers per/sec
6. Kilometers per/hour
7. Feet per/sec
8. Feet per/hour

_Copied from original issue: Esri/military-tools-webappbuilder#8_

**Comment by topowright** [comment]
Verified
