### ISSUE TITLE
Circle Drawing Radius Distance When Diameter Distance is Selected in Dropdown

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#737]
_From @mcalamito on April 7, 2016 19:29_

If I change the Radius dropdown to Diameter and use the Distance Calculator, the circle still draws the calculations based on Radius from center point as opposed to diameter.

_Copied from original issue: Esri/military-tools-webappbuilder#5_

**Comment by elinz** [comment]
@kgonzago I'm reopening this issue.

Distance Calculations should never be performed based on diameter. No mater what the user selects from the "From" pameter, the distance calculation should be based on radius. When users perform a Distance Calculation they want to know how far something can travel from the center point outward based on time and rate, which is the radius. This fix should be reverted.

**Comment by adgiles** [comment]
@elinz  the tool should be behaving the way you describe please verify

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to verify. @ACueva @dfoll @NatalieCampos @topowright

**Comment by topowright** [comment]
I am working on this issue.

**Comment by topowright** [comment]
@kgonzago @lfunkhouser this is still an issue. The issue is a circle half the size should be drawn when a user changes the inputs from radius to diameter. My screen shot just shows one circle; however, they are calculated the same way, which is the reason why it only looks like one. I am testing from our build location, which might be an issue. I am going to test directly from repo download and make sure I get the same result.

**Comment by topowright** [comment]
This is what the widget dialog looks like however; they create the same output on the map: 

![image](https://cloud.githubusercontent.com/assets/5488313/25642499/123fb582-2f4f-11e7-8bae-6be7e03383b5.png)

![image](https://cloud.githubusercontent.com/assets/5488313/25642524/3eb6010c-2f4f-11e7-8cb6-1b42ca16a635.png)

**Comment by topowright** [comment]
The numbers in the box dynamically update and they are correct, but the same graphic is drawn.

**Comment by topowright** [comment]
This is done and verified.
