### ISSUE TITLE
Allow the Ability to Input Coordinate and Then Input Distance Calculator Parameters to Draw Circle

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#738]
_From @mcalamito on April 7, 2016 19:23_

I currently have to enter in Distance Calculator parameters, paste in coordinates/click on the Center Point Coordinate icon, and click on the map in order to get a Circle to draw. 

_Copied from original issue: Esri/military-tools-webappbuilder#4_

**Comment by lfunkhouser** [comment]
_From @nfeuerstein on December 8, 2016 3:28_

Hitting Enter on your keyboard creates the circle.  This should be documented.

**Comment by nfeuerstein** [comment]
@Dbarnes1 @dfoll @NatalieCampos is this documented?  Hitting Enter to create the circle.

**Comment by dfoll** [comment]
@nfeuerstein the stuff i wrote has it just as one of the steps "press enter" i would not want to speak for the other two, without them saying exaxtly how they wrote their stuff

**Comment by Dbarnes1** [comment]
@dfoll @nfeuerstein I wrote the same step down for arcmap and wab, modeling the doc after Dereks

**Comment by Dbarnes1** [comment]
verified that the functionality is working properly and matches the documentation, closing out.
