### ISSUE TITLE
Distance and Direction - Drop-down for different line types should be removed. 

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#740]
### Widget
Distance and Direction

### Bug or Enhancement
Bug: Widget doesn't support Great Elliptic or Loxodrome line types, but the Dropdown is still present. The drop-down should be removed. 

### Repo Steps or Enhancement details
Open distance and direction widget and navigate to the lines tab:

![image](https://cloud.githubusercontent.com/assets/13024357/21369761/464a7b96-c6bd-11e6-84ae-61ac51cad142.png)

**Comment by kgonzago** [comment]
@Dbarnes1 can you verify when you have a moment?

**Comment by Dbarnes1** [comment]
![image](https://cloud.githubusercontent.com/assets/13024357/21435165/19fa749e-c82d-11e6-881e-3d5769260acf.png)
@kgonzago verified, closing.
