### ISSUE TITLE
Coordinate Conversion does not handle coordinates entered in Long Lat order

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#741]
### Widget
Coordinate Conversion

### Version of widget
21 Dec 2016 09:22
### Bug or Enhancement
The Coordinate conversion addin for ArcMap and ArcGIS Pro handles both Lat Long and Long Lat. The widget should handle both Lat Long and Long Lat as well.

**Comment by adgiles** [comment]
Doc for pro states:

Degree-based formats must always be specified in the order latitude first (Y coordinate) then longitude (X coordinate). Specify hemisphere with +,-,N,S,E, or W. These can be mixed within a single latitude-longitude pair. If omitted, a value is assumed to be positive (N for latitude or E for longitude).

https://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

**Comment by elinz** [comment]
@adgiles Correct. Pro and ArcMap only handle Lat Long. The request to support Long Lat order was due to Coordinate Conversion addins being changed to handle Long Lat, therefore, all our tools (whether addins or widgets) should support Long Lat.

**Comment by adgiles** [comment]
@elinz @kgonzago 

Fixed please verify

**Comment by elinz** [comment]
Verified fixed on build 31 Jan 2017 13:46 Pacific. Closing issue.
