### ISSUE TITLE
Distance and Direction - Line tool: starting/ending point parameters do not handle coordinates entered in Long Lat order

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#742]
### Widget
Distance and Direction
### Version of widget
21 Dec 2016 09:21
### Bug or Enhancement
All tools that allow user to type in coordinates should allow users to enter Lat Long or Long Lat.

Allows Lat Long...
![image](https://cloud.githubusercontent.com/assets/4635490/21409583/ef6504d0-c78f-11e6-9974-a0e618f424b6.png)

Does not allow Long Lat...
![image](https://cloud.githubusercontent.com/assets/4635490/21409588/f80c19c0-c78f-11e6-922a-6cc7a9feb526.png)

**Comment by adgiles** [comment]
Doc for pro states:

Degree-based formats must always be specified in the order latitude first (Y coordinate) then longitude (X coordinate). Specify hemisphere with +,-,N,S,E, or W. These can be mixed within a single latitude-longitude pair. If omitted, a value is assumed to be positive (N for latitude or E for longitude).

https://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

**Comment by elinz** [comment]
@adgiles Correct. Pro and ArcMap only handle Lat Long. The request to support Long Lat order was due to Coordinate Conversion addins being changed to handle Long Lat, therefore, all our tools (whether addins or widgets) should support Long Lat.

**Comment by adgiles** [comment]
Fix applied in dev branch. Please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Tested with build 31 Jan 2017 13:46 Pacific.

Implementation does not conform to how Coordinate Conversion handles Long Lat, in that when you enter coordinate (either by cut/paste or typing) in Long Lat order, the tool changes the coordinate order to Lat Long. The Coordinate Conversion widget does not change the order to Lat Long; it leaves it in the order that the user has entered the value. The DD tools should not alter the order of the coordinates and leave it as the user has entered. Changing the order makes it cumbersome for the user, because if they want to QC the value they now have to be mindful that the tool changed the coordinate order and make a mental adjustment. In addition, the tools should all function the same if they are doing the same thing. 

Assigning issue back to @adgiles

**Comment by adgiles** [comment]
@elinz 

Updated please verify correct behavior

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
