### ISSUE TITLE
Coordinate Conversion- Add New Notation button doesn't work

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#746]
### Widget
Coordinate Conversion

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
From the configuration page, I'm able to configure the output notations, but once I get into the widget itself and try to click the Add New Notation button, nothing happens. I'm expecting an add new notation window but the button just isn't working. 

This is the button I'm referencing in the widget: 
![image](https://cloud.githubusercontent.com/assets/13024357/21431638/e80b607a-c81c-11e6-94b7-f856d83ee41c.png)

**Comment by kgonzago** [comment]
@Dbarnes1 A new output notation is created at the bottom of the existing list of notations when you click on the add button. I can see that it's a bit deceiving when nothing happens. Adding a notation window will require some work but can be accomplished in our next release. For now, can you note it in the widget doc? Thanks.

**Comment by Dbarnes1** [comment]
this is noted in the widget doc

**Comment by adgiles** [comment]
When a new notation is added it is now placed at the top of the output table and a tooltip is displayed:

![image](https://cloud.githubusercontent.com/assets/3740334/25846901/ae7f8830-34ab-11e7-8958-aadf64b0c36b.png)

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Verified.  New functionality is working.  Adding "Affects documentation" tag as there is a new tool tip created after successfully adding a new notation.  This may or may not affect documentation.
![2017-05-09_13-55-47](https://cloud.githubusercontent.com/assets/3093940/25872364/3d3454c6-34bf-11e7-8616-261db4958839.png)
@lfunkhouser Suggest we create a new column/label for items that are functionality verified yet still need documentation?  I realize it's not "done", just makes it easier to track the items that still need doc review/updates.

**Comment by ACueva** [comment]
FYI @topowright @dfoll @NatalieCampos 
I've updated the documentation.  Could one of you PE's please review and make changes as needed? Thanks.
Topic is located here:
/ArcGIS Solutions/ArcGIS for Defense/Military Tools for ArcGIS/Web AppBuilder/topics

Old wording:
1. 	Click the Add New Notation button in the Input section of the widget.
A box appears at the bottom of the Output section.

New wording:
1. Click the Add New Notation button in the Input section of the widget.
A  tool tip callout appears, notifying you a new notation box has been added. 
A notation box appears at the top of the Output section.

**Comment by ACueva** [comment]
@dfoll reviewed these changes.  Marking Done.
