### ISSUE TITLE
Coordinate Conversion is automatically correcting invalid input coordinates

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#749]
### Widget
Coordinate Conversion
### Version of widget
04 Jan 2017 05:15
### Bug or Enhancement
The widget is automatically correcting invalid input coordinate. For example, if I enter the following coordinate:
45 15 80N 100 30 00W
Where the seconds is incorrect for the latitude, the widget modifies the input coordinate so it's a valid coordinate. See the screenshot below. The widget has converted the 80 seconds to 1 minute 20 seconds and set the output to 45 16 20N.
![image](https://cloud.githubusercontent.com/assets/4635490/21647982/453dce02-d251-11e6-919b-4a34f965f345.png)

While technically correct, we should not be correcting the input value. This can be dangerous as we've "moved" the coordinate to a location that the user may not have intended.

I found this issue because I fat fingered the input value as I was typing in the value, the widget calculated the output values and I didn't notice that the widget correct the value. It was only when I was double-checking some coordinates that I noticed this. If someone typed or copied/pasted an invalid value then the widget should not output any values; it should clear all the output coordinate textboxes. This will act as an indicator that something is wrong and the user should double-check the input value.

**Comment by adgiles** [comment]
@nfeuerstein @elinz 

I have worked on the regular expression to prevent the coordinates with over 59 minutes or seconds as being recognized as a valid DMS entry. I think this addresses this issue for DMS but I suspect there may be more issues with the regular expresssions if full testing on all coordinate types is conducted.

For interest the pattern I am now using for the DMS regular expression is:

^(?!9[1-9])?([0-8]?\d?|90)[\s]*[°]?[\s]*([0]?[0-9]|[0-5]\d){1}[\s]*['"]?[\s]*[0]?[0-9]?[0-5]\d(\.\d+)?[\s]*['"]?[\s]*[NnSs]?[\s]*(180|((1[0-7]\d)|([0]?[0]?[1-9]?\d)))[\s]*[°]?[\s]*([0]?[0-9]|[0-5]\d){1}[\s]*['"]?[\s]*[0]?[0-9]?[0-5]\d(\.\d+)?[\s]*['"]?[\s]*[WwEe]?[\s]*

This will only test for DMS entered in Lat Long order and is getting quite unwieldy, it may be worth rethinking how we are doing this validation for future releases.

Eric please verify this addresses this issue

**Comment by elinz** [comment]
@nfeuerstein Yep. Ran a new build so I can test :)

**Comment by nfeuerstein** [comment]
1. Revert reg ex - keep it for next release.
2. Document handling of coordinates with examples.  80 seconds will be resolved as 1 minute 20 seconds.

**Comment by adgiles** [comment]
@nfeuerstein 

Reverted back to original regex

**Comment by elinz** [comment]
@adgiles Assigning this issue back to you.

**Comment by elinz** [comment]
@adgiles @nfeuerstein Verified that the change was reverted back by entering an incorrect value, 45 15 80N 100 30 00W and it output 45° 16' 20.00"N 100° 30' 0.00"W.

Only thing left for this issue to to add a note in the documentation, something to the affect:

"WARNING: Coordinate Conversion will attempt to auto correct invalid input coordinates if it can be resolved it to a valid coordinate. For example, entering the value 45 15 80N 100 30 00W, where 80 seconds North is invalid will output 45° 16' 20.00"N 100° 30' 0.00"W (i.e. interpreting 80 seconds as 1 minute 20 seconds."

Assigning doc task to @Dbarnes1.

**Comment by Dbarnes1** [comment]
@elinz I'll tackle this

**Comment by elinz** [comment]
@Dbarnes1 Thank you.

**Comment by Dbarnes1** [comment]
Included in Known Issues list. removing affects documentation tag.

**Comment by adgiles** [comment]
Fix applied in dev branch. Please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Here are the test cases I used. I found some issues. See those below marked "ERROR". Assigned back to @adgiles 

## DMS

### Seconds
- [ ] ERROR: 45 15 59.999N 100 30 00W -> Widget performs auto correct and converts this to: 45° 16.0000'N 100° 30.0000'W
- [ ] ERROR: 45 15 00N 100 30 59.999W -> Widget performs auto correct and converts this to: 45° 15.0000'N 100° 31.0000'W

### Minutes
45 00 00N 100 60 00W -> Widget does not perform auto correct.
45 60 00N 100 00 00W -> Widget does not perform auto correct.

### Degrees
91 00 00N 100 00 00W -> Widget does not perform auto correct.
90 00 00N 181 00 00W -> Widget does not perform auto correct.

## DDM

### Minutes
- [ ] ERROR: 45 59.999N 100 00.00W -> Widget auto corrects DDM
![image](https://cloud.githubusercontent.com/assets/4635490/22489797/6617fc6e-e7ce-11e6-8256-1999d078710a.png)

- [ ] ERROR: 45 00.00N 100 59.999W -> Widget auto corrects DDM
![image](https://cloud.githubusercontent.com/assets/4635490/22489863/b9116c2a-e7ce-11e6-8111-b990e56d7213.png)

### Degrees
91 00.00N 100 00.00W -> Widget does not perform auto correct.
45 00.00N 181 00.00W -> Widget does not perform auto correct.

## DD

### Degrees
91N 100W -> Widget does not perform auto correct.
90.1N 100W -> Widget does not perform auto correct.
45N 181W -> Widget does not perform auto correct.
45N 180.1W -> Widget does not perform auto correct.

**Comment by adgiles** [comment]
@elinz @kgonzago 

These look like a rounding issue on the server, the FromGeoCoordString does not have any options for rounding or number of places:

![image](https://cloud.githubusercontent.com/assets/3740334/22505635/750bdd8e-e874-11e6-94f2-4b973d83de15.png)

For DDM it appears anything over 59.993 minutes (.994 .995 .996 .997 .998 .999) gets round up to the next degree.

For DMS it appears anything 59.996 seconds (.997 .998 .999) gets round up to the next minute.

How is that for consistency!!!!

Not sure what we can do with this one apart from accept it, we are talking around 6 - 36ft ground difference for DDM and around 0.08 - 0.24ft  ground distance for DMS

**Comment by kgonzago** [comment]
@topowright @NatalieCampos @ACueva @dfoll Can you doc this as a known limitation? Once done, please close out this issue.

**Comment by ACueva** [comment]
Per @lfunkhouser we'll keep this item living in the same document section as a "Known Issue".
