### ISSUE TITLE
Network Trace - Config/Widget Area Name = Summary panel 

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#75]
The label you use for Area output becomes the summary panel title.  Can we set the summary panel settings somewhere else?  Maybe have a section for the summary panel where the user can chose the name?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We can place the display text for Summary panel at either of the following two places:
1. In Others panel of configuration UI
2. In NLS file of widget

Please confirm

**Comment by MikeMillerGIS** [comment]
NLS file is fine.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have implemented this in V0.3

**Comment by MikeMillerGIS** [comment]
verified
