### ISSUE TITLE
Coordinate Conversion: default formatting for USNG doesn't match MGRS and Pro/ArcMap addins

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#751]
### Widget
Coordinate Conversion
### Version of widget
04 Jan 2017 13:38
### Bug or Enhancement
The default formatting for USNG shouldn't have any spaces in the output value; i.e. same formatting as MGRS default output. The USNG output in Coordinate Conversion Pro and ArcMap add-ins do not include any spaces. Also ArcMap identify tool does not embed spaces in the USNG coordinate value.
![image](https://cloud.githubusercontent.com/assets/4635490/21663557/c914d308-d295-11e6-8c26-0001170c79ba.png)

**Comment by adgiles** [comment]
Fixed please verify

**Comment by elinz** [comment]
@adgiles Verified on build 16 Jan 2017 05:11. There is no longer a space between the latitude band and the 100k grid designator.

@dfoll @Dbarnes1 This is no longer a known issue; removed label. Don't know if there is a doc change that needs to be made. Added the affects doc label.

**Comment by Dbarnes1** [comment]
@elinz this was never documented as a known issue, removing affects documentation tag, closing out.
