### ISSUE TITLE
Doc-Coordinate Conversion: include section/appendix that lists the supported notation formats

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#752]
### Widget
Coordinate Conversion
### Bug or Enhancement
We need to add a section or appendix to the widget  .pdf that describes all the supported notation formats.
We can format it similar to how the Pro/ArcMap help topics are formatted. We need to document because the widget doesn't support all the notations that are supported in Pro and ArcMap.

http://pro.arcgis.com/en/pro-app/tool-reference/data-management/supported-notation-formats.htm

http://desktop.arcgis.com/en/arcmap/10.3/tools/data-management-toolbox/supported-notation-formats.htm

**Comment by elinz** [comment]
@nfeuerstein @Dbarnes1 FYI. Waiting for step 1 in comment https://github.com/Esri/solutions-webappbuilder-widgets/issues/727#issuecomment-272499800 to be completed, so that we can validate that the behavior is the same as the Pro and ArcMap addins. If the same, then we can use almost all of the pro and ArcMap notation topic for the Widget notation topic.

**Comment by nfeuerstein** [comment]
@dhagens can you send the reg ex for coordinate notations to @adgiles? Once this done, the team will verify and doc will reflect that notation support is the same across pro, arcmap, and widgets.

**Comment by dhagens** [comment]
I believe @kgonzago and @adgiles looked at the regex and confirmed that we will not be able to integrate the regex for his release.

**Comment by nfeuerstein** [comment]
Closing in favor of this one; https://github.com/Esri/solutions-webappbuilder-widgets/issues/794
