### ISSUE TITLE
Distance and Direction: the Set Coordinate String icon disappears when cursor is placed over it

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#754]
### Widget
Distance and Direction
### Version of widget
09 Jan 2017
### Bug or Enhancement
![image](https://cloud.githubusercontent.com/assets/4635490/21779226/8809db8c-d65b-11e6-9257-92e0dbce5b75.png)

When I move the cursor so it's on top of the icon, the icon disappears...
![image](https://cloud.githubusercontent.com/assets/4635490/21779248/a49dbd18-d65b-11e6-9e3e-51a3f11a4990.png)

This issue occurs on all the tools, Lines, Circle, Ellipse, and Rings.

**Comment by adgiles** [comment]
@elinz @kgonzago 

Eric, I cannot replicate this issue tried using the following browsers:

- Chrome Version 55.0.2883.87
- Firefox Version 50.1.0
- IE Version 11.0.9600.16384

if you check your network traffic when you hover over do you see a request for the following image:

{your URL}/widgets/DistanceAndDirection/images/setting_default.png

and do you get the image returned?

**Comment by elinz** [comment]
@adgiles @kgonzago I can't replicate this today. I'm going to closing this issue.
