### ISSUE TITLE
Visibility widget won't load if there is no published GP service- needs warning

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#755]
Visibility Widget

If you deploy the visibility widget to an app in webappbuilder, you won't see anything except the widget page endlessly loading if you don't have the required GP service. An enhancement would be a warning saying that you need to add the service.

![image](https://cloud.githubusercontent.com/assets/13024357/21779961/abd0d586-d65e-11e6-9231-a6530f7a0a7c.png)

**Comment by BobBooth** [comment]
@Dbarnes1 - I ran into this too.

**Comment by nfeuerstein** [comment]
@Dbarnes1 is the process of adding the service documented?

**Comment by Dbarnes1** [comment]
@nfeuerstein this workflow is indeed documented, but I'm going to run through it again to see if we need to adjust any of the steps now that @mfunk was able to successfully publish the gp service

**Comment by Dbarnes1** [comment]
the configuration page has solved this issue- closing.
