### ISSUE TITLE
Distance and Direction- Circle creation from coordinates doesn't happen with "enter." Also no zoom

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#756]
When I am in the circle tab for the distance and direction widget, and I enter a coordinate pair and click "enter/return," I expect the map to zoom to the place where I can view a preview of the circle. This doesn't happen. In fact, in order to get the circle preview to appear, I have to click away from the box to get this to appear.

To replicate:
- Navigate to circle tab in distance and direction.
- Create circle from radius or diameter, doesn't matter.
- add center point 35, 5 (north algeria) and click enter. You'll see nothing happens
- click away from the center point box and manually zoom to the location. You'll see the circle preview appear. This should happen when you click enter and the zoom should happen automatically.

**Comment by BobBooth** [comment]
@Dbarnes1 - I am seeing something similar with the ellipse tab.
I set a center point using MGRS: 
17TMF8018623395
Type in values for major and minor axis, set units (miles)
Set the angle and hit Enter - no ellipse created.

**Comment by BobBooth** [comment]
@dfoll @Dbarnes1 - the doc indicates that this workflow should work.
Create ellipses from known coordinates
Create circles from known coordinates

**Comment by Dbarnes1** [comment]
@bobbooth the ellipse issue has been more specifically documented @elinz here: https://github.com/Esri/solutions-webappbuilder-widgets/issues/728 

Thanks for pointing out the doc element. If these bugs don't get fixed in time for release, the doc will have to be specifically rewritten to accommodate them.

**Comment by adgiles** [comment]
@Dbarnes1 @kgonzago @BobBooth 

Dan I have fixed this issue and made sure it is consistent across all 4 tabs (Lines,Circle,Ellipse,Rings). On hitting enter the point is added and the map pans to center on that coord (I haven't put a zoom on this as the user could find it irritating if the map zooms in, then they have to zoom back out to perform next action).

**Comment by Dbarnes1** [comment]
@adgiles I've been able to verify the workflow and it makes sense along with the documentation. closing.
