### ISSUE TITLE
Doc typo - missing space between words Distance and Direction widget

### ISSUE THREAD

**Issue by BobBooth** [Esri/solutions-webappbuilder-widgets#757]
Distance and Direction (Doc) on page 12 "Configure the distance and direction widget" there needs to be a space between The and confic and in step 5 and Save and config.json in step 7.
theconfig.json
Saveconfig.json and refresh the application to view labels within the widget.

**Comment by BobBooth** [comment]
Fixed.

**Comment by Dbarnes1** [comment]
verified. closing
