### ISSUE TITLE
Distance and Direction Rings tab: upon enter, Center Point should appear and zoom

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#758]
Currently, when navigating in the rings tab and adding a coordinate pair to the Center Point box, I expect to click enter and see the map zoom to this location and see a circular preview. However, I can only see a center point when I click away from the map, and I can't get the zoom to work at all. 

To reproduce: 
navigate to rings tab
enter specific coordinate pair as center point (33, 6 is in Algeria) and click enter. You'll see nothing happen.
Click on a subsequent box and you'll see the center point appear.

**Comment by adgiles** [comment]
@Dbarnes1 @kgonzago 

Dan I have fixed this issue and made sure it is consistent across all 4 tabs (Lines,Circle,Ellipse,Rings). On hitting enter the point is added and the map pans to center on that coord  (I haven't put a zoom on this as the user could find it irritating if the map zooms in, then they have to zoom back out to perform next action).

**Comment by Dbarnes1** [comment]
this has been fixed, except for: 
![image](https://cloud.githubusercontent.com/assets/13024357/21820430/709ed9c4-d724-11e6-8534-695d1053ab60.png)

Not sure why (UNKNOWN) is appearing in the UI. Assigning back to @adgiles to take a look. @kgonzago fyi.

**Comment by adgiles** [comment]
@Dbarnes1 

Issue fixed please can you verify

**Comment by Dbarnes1** [comment]
@adgiles verified: 
![image](https://cloud.githubusercontent.com/assets/13024357/21853142/c1af2656-d7ca-11e6-827d-1bab6b907852.png)

closing
