### ISSUE TITLE
Visibility's Viewshed service script not producing expected results.

### ISSUE THREAD

**Issue by mfunk** [Esri/solutions-webappbuilder-widgets#759]
### Widget
Visibility

### Version of widget
WAB 2.2/ArcMap 10.4.1

### Bug or Enhancement
Using a local, projected (World Azimuthal Equidistant) raster dataset (TIF) as a source elevation dataset. I can run the tool without warning or errors, but:
1) The tool does not produce a viewshed, only fullwedge and wedge datasets.
2) The features produced are about 1600 miles from the location of their input Observers.
![image](https://cloud.githubusercontent.com/assets/3093182/21786406/8bf8bcbe-d678-11e6-8036-11fdde785576.png)

DTED source used is from https://github.com/Esri/military-tools-geoprocessing-toolbox/tree/dev/testdata/Elevation/Source/SRTM30M

### Repo Steps or Enhancement details
1) Open ArcMap (I used 10.4.1)
2) Project n36.dt1 to *World Azimuthal Equidistant* using **Project Raster**. My output was *n36prj.tif*.
3) Open **Viewshed** from \stemapp\widgets\Visibility\gpservices\Viewshed\Viewshed.tbx
4) Select single observer point, use default parameters, click **OK**.

![image](https://cloud.githubusercontent.com/assets/3093182/21786652/e6542580-d679-11e6-8931-729c4df3d6db.png)

```
Executing: Viewshed "Feature Set" 3000 40 120 20 1000 in_memory\viewshed in_memory\wedge in_memory\fullwedge
Start Time: Mon Jan 09 14:45:45 2017
Running script Viewshed...
Completed script Viewshed...
Succeeded at Mon Jan 09 14:45:46 2017 (Elapsed Time: 0.81 seconds)
```

5) So the tool produces three output feature classes: viewshed, wedge, and fullwedge.
Viewshed is emtpy:
![image](https://cloud.githubusercontent.com/assets/3093182/21786816/ca0737c2-d67a-11e6-8d5b-2f5ff80a35ff.png)

Wedge and fullwedge have one result each:
![image](https://cloud.githubusercontent.com/assets/3093182/21786835/e5398d42-d67a-11e6-94c1-2bc8bca5c22c.png)

![image](https://cloud.githubusercontent.com/assets/3093182/21786978/7d6350f8-d67b-11e6-8ce5-43241e1b0d7f.png)

However the resulting wedges are nowhere near the surface, and therefore not near the selected observer location.

**Comment by Dbarnes1** [comment]
@mfunk I was getting the same results while testing today.

**Comment by mfunk** [comment]
Assuming it's something in the .PY I'm going to check it out. @kgonzago  which branch should I pull from to work on a fix for Visibility widget?

**Comment by kgonzago** [comment]
@mfunk Master branch.

**Comment by mfunk** [comment]
Making a few changes and so far tool output looks good. Still need to test as a service, then see if it works in the widget.

- 'projecting' input points to same SR as elevation.
- symbology (.LYR) for all three output layers.
- Error if input surface is NOT projected.

![image](https://cloud.githubusercontent.com/assets/3093182/21821120/2f260064-d727-11e6-83d1-bf3ff8d1078f.png)

**Comment by mfunk** [comment]
@kgonzago needs to merge #769, but afterwards I'd like @Dbarnes1 to verify the fix once it is done.
