### ISSUE TITLE
Distance and Direction WAB widget: End Point coordinate on the line tab does not format like all other coordinate boxes

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#761]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

The end point coordinate text box does not behave the same as the start point text box (or other coordinate boxes in the widget). It does not format the input coordinate

![1](https://cloud.githubusercontent.com/assets/3740334/21808237/4da5151c-d73a-11e6-9e3a-411f4fb5c7a5.png)

**Comment by kgonzago** [comment]
@Dbarnes1 Can you verify when you get a chance?

**Comment by adgiles** [comment]
@Dbarnes1 @kgonzago 

I can verify this is working correctly now.

Closing Issue
