### ISSUE TITLE
Distance and Direction: Ellipse tool - major/minor axis not modified after units is changed

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#762]
### Widget
Distance and Direction
### Version of widget
10 Jan 2017 05:53
### Bug or Enhancement
The major and minor axis are not altered when user modifys the unit's value. So it creates an incorrect ellipse.

### Repo Steps or Enhancement details

- Enter in a center point and hit return (temp black center point circle is drawn):
![image](https://cloud.githubusercontent.com/assets/4635490/21820111/4724d608-d723-11e6-9b3f-67615bbd622f.png)
Note: in this case the unit is set to kilometers

- Type in a major axis value, for example 750 (the major axis of length 750 kilometers is drawn)...
![image](https://cloud.githubusercontent.com/assets/4635490/21820154/7ca9fe20-d723-11e6-8969-a086fc409ad2.png)

- Type in a minor axis value, for example 250 (the minor axis of length 250 kilometers is drawn)...
![image](https://cloud.githubusercontent.com/assets/4635490/21820306/fd73782e-d723-11e6-995c-596a1cf26ab2.png)

- Now change the units from kilometers to miles...note that the major and minor axis' are not redrawn based on the current unit of measure...
![image](https://cloud.githubusercontent.com/assets/4635490/21820362/32a7bbae-d724-11e6-9bdb-599335bf6453.png)

- The user may not notice that the axis' were not updated to match the change in units so they proceed to enter in an orientation angle, hit return and the ellipse based on incorrect parameters is now created...
![image](https://cloud.githubusercontent.com/assets/4635490/21820425/69c841da-d724-11e6-96c8-f1dedfecb9cc.png)

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles @kgonzago Verified that this issue was fixed in build 11 Jan 2017 09:51
