### ISSUE TITLE
PDF for Web AppBuilder needs an introduction

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#763]
pdf for Web AppBuilder needs an introduction similar to the pdfs for ArcGIS Pro and ArcMap

recommend starting from one of those and tailoring the info to be applicable to Web AppBuilder

**Comment by dfoll** [comment]
added the introduction to the map that includes deploying the widgets and did some light updates to the section that deals with the visibility gp service, but @mfunk and @Dbarnes1 are still working on trying to make that work, so there may be changes to that still

**Comment by Dbarnes1** [comment]
@dfoll I'm going to go ahead and close this as I think it looks good, any changes made to the widgets will be specified in their respective topics and wont impact the intro.
