### ISSUE TITLE
Distance and Direction WAB widget: Line created using Distance & Bearing only ever gets created in meters

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#765]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

On the line tab of the distance and direction widget if you create a line using distance and bearing the units of measure ignored and the line is only ever created in meters

### Repo Steps or Enhancement details

navigate to lines tab
change the from select box to 'Distance and Bearing'
enter specific coordinate pair as start point (1, 1) and click enter.
change the length units to kilometers
enter 500 as the length value
enter a bearing angle and hit enter

line is created but it is 500 meters not kilometers

**Comment by adgiles** [comment]
@kgonzago 

looking at the code, in the createManualGraphicDistanceAndBearing function the radius of the circle is set by getting the length input value but does not do any conversion if the unit value is not meters:

var l = this.lengthInput.get('value');

this needs to be converted to meters:

var l = this.dt._utils.convertToMeters(this.lengthInput.get('value'), this.lengthUnitDD.get('value'));

**Comment by adgiles** [comment]
@kgonzago @elinz 

Bug fixed can somebody do an independent check

**Comment by elinz** [comment]
@adgiles @kgonzago Verified that this issue was fixed in build 11 Jan 2017 09:51
