### ISSUE TITLE
Distance and Direction WAB widget: Circle labels only ever show meters

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#766]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

When drawing circles the label that gets created is only ever displayed in meters and not converted to the units in use

![1](https://cloud.githubusercontent.com/assets/3740334/21849834/bf57ee44-d7ff-11e6-9d05-d83fe894ed9a.png)

**Comment by adgiles** [comment]
@kgonzago 

Fixed please verify. Also took this opportunity to ensure the unit values are added on to the labels, so if a user is drawing multiple geometries with different units they can see visually see the difference

**Comment by ACueva** [comment]
Verified.
