### ISSUE TITLE
Distance and Direction WAB widget: Cannot create multiple circles without clearing previous

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#767]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

When using the circle tab you cannot draw subsequent circles without clearing the graphics first

**Comment by adgiles** [comment]
@kgonzago 

Fixed please verify

**Comment by joebayles** [comment]
Verified.
![image](https://cloud.githubusercontent.com/assets/5016557/21872265/5e0b1324-d81c-11e6-9af9-1ede37b5ee6f.png)
