### ISSUE TITLE
Distance and Direction WAB widget: Line created using Distance & Bearing in Mils is incorrect

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#768]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

On the line tab of the distance and direction widget if you create a line using distance and bearing with the angle units set as mils the number is multipled by 17.777777778 which is the formula for converting degrees to mils. This should not be applied 

### Repo Steps or Enhancement details

navigate to lines tab
change the from select box to 'Distance and Bearing'
enter specific coordinate pair as start point (45, 45) and click enter.
change the angleunits to mils
enter 500 as the length value
enter a bearing angle of 1600 and hit enter

The line is created with an angle of 2844.44 mils

**Comment by adgiles** [comment]
@kgonzago 

Fixed please verify

**Comment by ACueva** [comment]
Verified.
