### ISSUE TITLE
Distance and Direction WAB widget: Creating a circle manually using diameter causes the browser to freeze

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#770]
### Widget

Distance and Direction WAB widget

### Version of widget

2.1 & 2.2

### Bug or Enhancement

On the circle tab of the distance and direction widget if you create a circle manually using 
Create Circle From 'diameter' the browser freezes

### Repo Steps or Enhancement details

navigate to circles tab
change the Create Circle From select box to 'diameter'
enter specific coordinate pair as start point (45, 45) and click enter.
change the radius to 5000 and press enter

Browser freezes

**Comment by adgiles** [comment]
Fixed please verify

**Comment by Dbarnes1** [comment]
@adgiles I was able to verify that this workflow now works properly: 

![image](https://cloud.githubusercontent.com/assets/13024357/21897241/db2467bc-d89d-11e6-81f2-4ed21726d8bb.png)


closing
