### ISSUE TITLE
Distance and Direction - Rings tool creates incorrect output when number of radials is set to 0

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#772]
### Widget
Distance and Direction
### Version of widget
build 11 Jan 2017 09:51
### Bug or Enhancement
When "Number of Radials" is set to 0, the widget creates radials:
![image](https://cloud.githubusercontent.com/assets/4635490/21864793/3f701460-d7f8-11e6-9341-ab77d74496ff.png)

Radials are optional for Rings so entering a value of 0 is valid. In comparison here is the output from the Pro addin using the same parameters:
![image](https://cloud.githubusercontent.com/assets/4635490/21864855/77aa9fe4-d7f8-11e6-9b38-fbabe2c98ad1.png)

### Repo Steps or Enhancement details
To repo:
Enter 40N 120W for Center Point. Hit return.
Set Number of Rings to 2
Set Distance Between Rings to 750 kilometers
Set Number of Radials to 0. Hit return.

**Comment by adgiles** [comment]
@elinz 

Fixed please verify

**Comment by elinz** [comment]
@adgiles Verified fixed in build 12 Jan 2017 09:50. Now when 0 is specified as Number of Radials, no radials are created. Closing issue.
