### ISSUE TITLE
Distance and Direction - Creating lines based on distance and bearing always creates a line longer then length parameter value

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#773]
### Widget
Distance and Direction
### Version of widget
build 11 Jan 2017 09:51
### Bug or Enhancement
When creating lines from distance and bearing the created line is always longer then what the user specified.

In the screenshot below, I set the length to 1000 km, but the labeled line states line is longer then 1000 km. Also tested all the other length units and behavior is the same for all units.
![image](https://cloud.githubusercontent.com/assets/4635490/21866412/fa258780-d7fe-11e6-9327-eb9ae0b57274.png)

Another verification that the length is longer, is that I created a circle with 1000 km radius centered at 1,1 and the arrow head of the line extends past the circle 
![image](https://cloud.githubusercontent.com/assets/4635490/21866848/a83bf4ca-d800-11e6-9591-9f492a3cc542.png)

### Repo Steps or Enhancement details
1. From line tool, select "Distance and Bearing"
2. Set Start Point to 1, 1 and hit return.
3. Set Length to 1000 kilometers.
4. Set Angle to 90 degrees and hit return.
The label on the created line is longer then 1000 kilometers. Also verified with the Measure widget.

**Comment by adgiles** [comment]
@elinz @nfeuerstein @kgonzago  

I have fixed the length issue, the logic in the way the line was being created was not robust enough. Essentially a geodesic circle was created with the radius being the required line length. A line was then created using the center point and the first point of the circle (due north). This line was then rotated using the angle value which is **incorrect** as a geodesic circle will not be exactly round. 

I changed the logic to create a circle with the amount of points required (360 for degrees or 6400 for mils). I then create the line from the center point to the corresponding point in the circle for the angle required. No rotation needed and the point is in the correct geodetic location.

This highlighted another issue that the arrow endpoint on the line is essentially a triangle marker symbol rotated to the required angle for the line. This means the end of the line is actually the center of the triangle and not at its point. the arrow symbol is created using:

arrow1: "m0.5,50.5c0,0 99.5,-41 99.5,-41c0,0 0.5,81.5 0.5,81.5c0,0 -100,-40.5 -100,-40.5z",

I am not sure how you change this to butt join the line. For now i have changed the end symbol to a cross, is this acceptable?

![1](https://cloud.githubusercontent.com/assets/3740334/21886106/3dad4aac-d8b2-11e6-8ddf-f4a2cb67de01.png)

**Comment by elinz** [comment]
@adgiles @nfeuerstein @kgonzago I'm okay with using the cross if everyone else is. I think it's better to change it from an arrow since the arrowhead was extending past the correct length. With the cross at least it meets with other graphics. For example, I drew a line and circle so they intersect and now the line doesn't extend past the edge of the circle...
![image](https://cloud.githubusercontent.com/assets/4635490/21899605/abda598c-d8a5-11e6-9e4c-4aa80dd0e872.png)
