### ISSUE TITLE
Distance and Direction: should we remove the Ellipse tab if ellipses are not geodetic?

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#774]
@nfeuerstein Question for you...

### Widget
Distance and Direction
### Version of widget
build 11 Jan 2017 09:51
### Bug or Enhancement
The ellipses created by the widget are not geodetic (https://github.com/Esri/solutions-webappbuilder-widgets/issues/699) and a note about this has been placed in the .pdf. 

When we thought Pro couldn't create geodetic lines we were going to remove the Lines tab from the Pro addin, so why aren't we removing the Ellipse tab from the widget? Seems dangerous to me to leave this tool in the widget.

**Comment by nfeuerstein** [comment]
@elinz is it just the ellipses that aren't geodetic or, circles and lines too?

**Comment by elinz** [comment]
@nfeuerstein Lines, Circles and Rings are geodetic.

**Comment by nfeuerstein** [comment]
We should comment out/remove ellipses if they cannot be geodetic.

**Comment by elinz** [comment]
@kgonzago The Ellipse tab from the Distance and Direction widget needs to be removed.

**Comment by elinz** [comment]
@Dbarnes1 FYI. Affects documentation.

**Comment by nfeuerstein** [comment]
War Room: Keep Ellipses.  Add a note "non-geodetic feature" note to widget.  

Future: Use GP service to create geodetic ellipses.

**Comment by dfoll** [comment]
added a bullet to "implementation notes" at the beginning of distance and direction in widget to say that ellipses in the distance and direction widget are not geodetic, it also says this in the step in the doc about creating ellipses

**Comment by adgiles** [comment]
Added the following warning note to the ellipse widget UI:

![1](https://cloud.githubusercontent.com/assets/3740334/21925443/61e80e02-d975-11e6-8702-d2134a6fc5f7.png)

**Comment by elinz** [comment]
@nfeuerstein @dfoll @adgiles 
Tested latest build 13 Jan 2017 05:12
- Verified that the Warning note was added to the widget UI.
![image](https://cloud.githubusercontent.com/assets/4635490/21934106/0a13bb6c-d95d-11e6-9ae3-7adfc229476a.png)

- Verified that comment was made in Implementation Notes in military_tools_for_arcgis_web_appbuilder.pdf
![image](https://cloud.githubusercontent.com/assets/4635490/21934179/528fd466-d95d-11e6-8cb6-2ea93c8091db.png)

- Verified that a note was added to the "Create ellipses interactively" section:
![image](https://cloud.githubusercontent.com/assets/4635490/21934256/a2965d0e-d95d-11e6-8a64-e3b11231c659.png)

- Verified that a note was added to the "Create ellipses from know coordinates":
![image](https://cloud.githubusercontent.com/assets/4635490/21934284/b6e514b2-d95d-11e6-9c2d-26fb5d738ac4.png)

This issue has been fully addressed for this release. Closing issue.
