### ISSUE TITLE
Visibility - Button Icon

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#777]
### Widget
Visibility

### Version of widget
1.0.0

### Bug or Enhancement
Change the button

### Repo Steps or Enhancement details
There are several icons better suited for visibility than a book, I've circled some suggestions.

![image](https://cloud.githubusercontent.com/assets/5016557/21869748/e5880d2a-d80d-11e6-9651-9fb9cbc2186e.png)

I'd say this is Version-Next but not high-priority, based on how easy it is to change.

FYI @nfeuerstein

**Comment by adgiles** [comment]
I have amended the Near Me icon for visibility as per images:

![2](https://cloud.githubusercontent.com/assets/3740334/21983166/ba2880a0-dbe7-11e6-93ce-b44d370886ad.png)
![1](https://cloud.githubusercontent.com/assets/3740334/21983167/bb9771e4-dbe7-11e6-9760-9fe40650afc8.png)

Everybody happy with that?

**Comment by kgonzago** [comment]
@adgiles thanks for the new icon. Verified.
