### ISSUE TITLE
Visibility - Default Service URL

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#778]
### Widget
Visibility
### Version of widget
1.0.0
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
When first adding the widget to the app, the configuration window appears and automatically populates with the airc2.esri.com visibility URL. Suggest that this be left blank, and identified as a required input.
![image](https://cloud.githubusercontent.com/assets/5016557/21870133/cbb69f22-d80f-11e6-978d-f8f6f1ab007d.png)

FYI @nfeuerstein 

Also... in case anyone is wondering, the Visibility label is misspelled. I'll fix it now.
![image](https://cloud.githubusercontent.com/assets/5016557/21870146/d82df444-d80f-11e6-8be5-adb606c1b792.png)

**Comment by mfunk** [comment]
@kgonzago 
We need to add an Elevation Service URL parameter in the config and pass that to the GP service (as second parameter).

**Comment by kgonzago** [comment]
@joebayles can you verify?

**Comment by joebayles** [comment]
I can verify that it no longer defaults, however, it allows you to proceed without a service. I'll leave that to @nfeuerstein to decide if that makes or breaks us.

**Comment by joebayles** [comment]
NM, I see it shows you default value.
