### ISSUE TITLE
Network Trace sample

### ISSUE THREAD

**Issue by friendde** [Esri/solutions-webappbuilder-widgets#78]
Is sample code available? I dont see the project files on the Github repository. Thx. Looking forward to using this widget.

**Comment by MikeMillerGIS** [comment]
It is in development and the current code base is in the dev branch.  It is not complete and/or released yet.

**Comment by friendde** [comment]
Thanks.  Just spoke to Pat Dolan a few minutes ago at Link about this. Sounds like a widget will be available this year. Thanks for providing the widget,  been wanting network trace in the field for a long time. I like the web deployment model for AGOL.

**Comment by MikeMillerGIS** [comment]
The widget is based off this app if you want to take it for a test drive - http://solutions.arcgis.com/utilities/water/help/web-isolation-trace/

**Comment by friendde** [comment]
Thank you.
