### ISSUE TITLE
Distance and Direction: Lines and Ellipse tools missing units of measures

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#780]
### Widget
Distance and Direction
### Version of widget
12 Jan 2017 09:50
### Bug or Enhancement

- Lines tool missing Meters in Length units control.
- Ellipse missing Yards in Axis Unit control.

**Comment by nfeuerstein** [comment]
@elinz what is listed?  kilometers and feet?

**Comment by elinz** [comment]
@nfeuerstein 
For Lines it currently has: Feet, Kilometers, Miles, Nautical Mile, and Yards
For Ellipse it currently has: Feet, Meters, Kilometers, Miles, and Nautical Miles

Trying to keep the units the same for each of the tools. At a future release we will also have to modify so the units are listed in the same order on each tool and spelled the same some use Nautical Mile others use Nautical Miles.

**Comment by elinz** [comment]
@nfeuerstein @adgiles Verified on build 13 Jan 2017 07:13
Lines now has meters. Ellipse now has Yards. Also unit order was updated and spelling, so units on all tools are now the same and in the same order.
Lines:     Feet, Kilometers, Miles, Meters, Nautical Miles, Yards
Circle:    Feet, Kilometers, Miles, Meters, Nautical Miles, Yards
Ellipse:   Feet, Kilometers, Miles, Meters, Nautical Miles, Yards
Rings:    Feet, Kilometers, Miles, Meters, Nautical Miles, Yards

Closing issue.
