### ISSUE TITLE
Distance and Direction Display issue

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-webappbuilder-widgets#781]
### Widget
Distance and Direction WAB widget

### Version of widget
2.1 & 2.2

### Bug or Enhancement

Distance and Direction widget gives some weird results with large length values.

### Repo Steps or Enhancement details

navigate to lines tab
change the from select box to 'Distance and Bearing'
enter specific coordinate pair as start point (45, 45) and click enter.
change the length unit to kilometers
enter 20 as the length value

This works.

Change the length value to 20,000 kilometers

![1-12-2017 2-32-25 pm](https://cloud.githubusercontent.com/assets/3093940/21911110/fd2b3620-d8d3-11e6-9493-ebc82da3e768.png)

**Comment by adgiles** [comment]
@ACueva 

I am not surprised that the tool is giving strange results as the length you are using is longer than the worlds circumference and the geometry engine probably cannot handle it (Have a look at the circle tab and try and draw a circle that is too large).
 
The options we have are:

- Leave it and expect that the users will have some sense when using the tool
- Put a constraint on the input box that doesn't allow such large numbers

@nfeuerstein please advice

**Comment by nfeuerstein** [comment]
Moved milestone to "after-next"

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#446
