### ISSUE TITLE
Coordinate Conversion creating invalid GARS output

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#783]
### Widget
Coordinate Conversion
### Version of widget
13 Jan 2017 10:31
### Bug or Enhancement
Entered: 19 0.819N 86 18.5156W
Output GARS: 1889C3K ->The output should be 188KC39

**Comment by elinz** [comment]
FYI. I did double-check this in GeoTrans. The correct output in GARS should be 188KC39 as noted above.

**Comment by nfeuerstein** [comment]
@adgiles if this is not able to be fixed, we need to remove GARS from the output options.

**Comment by nfeuerstein** [comment]
@pHill5136 if GARS is not supported in Pro, it needs to be removed from the output options.

**Comment by nfeuerstein** [comment]
We do not fully support GARS at this release.  @adgiles please remove GARS from the output options in the widget.  @pHill5136 please remove GARS from Pro and ArcMap.

**Comment by Dbarnes1** [comment]
GARS removed from support doc.

**Comment by kgonzago** [comment]
GARS option has been removed from ArcMap and Pro add-ins as well as from the CC and DD widgets.

**Comment by adgiles** [comment]
@kgonzago 

The logic to how the string is formatted is wrong, currently it is: 

//XYQK
          var s = withFormatStr.replace(/X/, r.lon);
          s = s.replace(/Y/, r.lat);
          s = s.replace(/Q/, r.quadrant);
          s = s.replace(/K/, r.key);

stepping through the example input above '188KC39' would be as follows:

XYQK
188YQK
188KCQK
188KC3K
1889C3K (**incorrect**: note here the fact the latitude value had K in it, it is this instance that gets changed) 

simple fix is to reverse the order the string is made:

//XYQK
          var s = withFormatStr.replace(/K/, r.key);
          s = s.replace(/Q/, r.quadrant);
          s = s.replace(/Y/, r.lat);
          s = s.replace(/X/, r.lon);

XYQK
XYQ9
XY39
XKC39
188KC39

**Comment by adgiles** [comment]
@nfeuerstein 

I have a copy of the widget with GARS back in and working if you want to include as part of this release

**Comment by kgonzago** [comment]
@adgiles Thanks for the fix. It was removed since those options were also removed from the ArcMap and Pro add-ins. We will fold your fix into the next release.

**Comment by joebayles** [comment]
Moved to After Next per the conversation above FYI @nfeuerstein and @lfunkhouser

**Comment by adgiles** [comment]
addressed in branch:  https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag-CoordinateConversion-Dev

Please verify

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.

**Comment by NatalieCampos** [comment]
@nfeuerstein This (Gars) has been added though it seems like it is version after next.  

Do we want to move it back (remove it)? or Leave it in?

Please note it will effect documentation and was not added to the add-in.  I think conservatively it will only effect the Supported Formats documentation.

**Comment by nfeuerstein** [comment]
@NatalieCampos if the documentation updates are minimal, let's try to keep the support for GARS in this release.

**Comment by elinz** [comment]
@nfeuerstein Seems odd that we would have GARS support in the widget, but not support it across the product (i.e. not in the add-ins).

**Comment by nfeuerstein** [comment]
@elinz - we should support it in the add-ins as well, but that shouldn't limit us from moving forward with the widgets. The same user will not bounce around from desktop to application so there should be little, if any, effect on user experience.

**Comment by elinz** [comment]
@nfeuerstein Ok. That makes sense.

**Comment by NatalieCampos** [comment]
Documentation was added to the widgets supported format topic.  Closing issue.
