### ISSUE TITLE
json config file need to be updated to reflect the UTM z/h

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#787]
### Widget
Coordiante Conversion 
### Version of widget
1/14/17 @1:40pm
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
1.  When configuring the app, just UTM is an option.  
![image](https://cloud.githubusercontent.com/assets/5116835/21959144/624bdfe6-da73-11e6-9430-13b2b6696e2d.png)
2. When initially using the app the UTM box will not be populated.  
3.   When  adjusting the setting there is a UTM(h) and a UTM(z) option.  These are properly populated once added.  
![image](https://cloud.githubusercontent.com/assets/5116835/21959166/f2cc81a6-da73-11e6-8db5-5880aa92f029.png)

**Comment by adgiles** [comment]
No requirement for this now as we have reverted back to a single instance of UTM output as per request in #718
