### ISSUE TITLE
distance and direction contains artifact from drawing.  

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#788]
### Widget
Distance and Direction
### Version of widget
1/14/17 @1:40pm
### Bug or Enhancement
Artifacts remain on the screen when trying to use the DD Circle tab and the Distance Calculator.  See the graphic below.  
![image](https://cloud.githubusercontent.com/assets/5116835/21959488/bb094402-da7d-11e6-88cf-259068f68c0b.png)

**Comment by adgiles** [comment]
@NatalieCampos 

Natalie, bug addressed can you please verify

**Comment by NatalieCampos** [comment]
verified.
