### ISSUE TITLE
Network Trace enhancement request - pinch pipe

### ISSUE THREAD

**Issue by friendde** [Esri/solutions-webappbuilder-widgets#79]
I know it's early and you have alot to work on... future enhancement request is to place a point on the pipe that represents a pinch and then trace downstream to report effected customers.

We are replacing pipe to polyethylene and all new pipe is poly too. So we pinch more than close valves and therefore effects less customers.

**Comment by MikeMillerGIS** [comment]
This is just the widget.  How you configure the model to do the trace is up to you.
