### ISSUE TITLE
Unable to configure Visibility widget

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#790]
### Widget
Visibility
### Version of widget
1.0
### Bug or Enhancement
Cannot confgure the Visibility widget with a working gp service.

This shows my results in ArcMap using the steps outlined in the doc. 

1. The picture shows two results. 

        - Results from running the tool locally
        - Results from the gp service
![image](https://cloud.githubusercontent.com/assets/5488313/21965178/48459244-db0f-11e6-955b-45c945ee1f96.png)
 
![image](https://cloud.githubusercontent.com/assets/5488313/21965158/dce098c8-db0e-11e6-9f8d-1bd290ba65d8.png)

I copied the following URL in the widget configureation step: 

https://fqdn/ags/rest/services/Test/ViewshedTestWidget/GPServer

**Comment by kgonzago** [comment]
@topowright 

I can't hit your service. Also, the URL for the GP service should be:
https://fqdn/ags/rest/services/Test/ViewshedTestWidget/GPServer/Viewshed

Also, please configure your GP service to be synchronous instead of asynchronous.

**Comment by adgiles** [comment]
@kgonzago @topowright 

Kevin I think there was an issue with line 155 of the widget.js:

"Elevation_URL": this.config.elevationService.url,

I have removed this line as its not required and tries to reference a object that does not exist.

Just to check also make sure your service is shared with everybody as the widget does not do any token authorization.

Please verify its now working

**Comment by kgonzago** [comment]
@adgiles Good catch and verified.

**Comment by topowright** [comment]
I have verified that this works start from finish.
