### ISSUE TITLE
Doc - Coordinate Conversion: make sure doc reflects UTM uses latitude band

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#791]
### Widget
Coordinate Conversion
### Version of widget
16 Jan 2017 05:11
### Bug or Enhancement
Widget was changed so output UTM uses latitude band instead of hemisphere designator

For more info, see: https://github.com/Esri/solutions-webappbuilder-widgets/issues/718#issuecomment-272927657

**Comment by dfoll** [comment]
@topowright @lfunkhouser

**Comment by Dbarnes1** [comment]
@dfoll @elinz I made sure that this is under the widget coordinate support doc for UTM. We state that: To input a UTM coordinate to Coordinate Conversion, spaces must be embedded between the UTM Zone/Latitude Band (ZZB)

**Comment by elinz** [comment]
@dfoll @Dbarnes1 Verified the following in web app .pdf build 18 Jan 2017 12:25...
![image](https://cloud.githubusercontent.com/assets/4635490/22082895/83c45aaa-dd7e-11e6-90ef-54f9f364973c.png)
Closing issue.
