### ISSUE TITLE
Coordinate Conversion: creating invalid MGRS and USNG coordinates

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#792]
### Widget
Coordinate Conversion
### Version of widget
16 Jan 2017 05:11
### Bug or Enhancement
Was clicking on the map at various location and found that the USNG output is transposing the latitude band and 100k grid designators.

- Invalid USNG:
Clicked location: 38.714088N 168.046875W
Widget output USNG:  02QHS5676789190
Widget should output USNG: 02SQH5676789190 (MGRS output is correct)
It transposed the latitude band and 100k grid designators.

- Invalid USNG:
Clicked location: 32.132204N 097.734375W
Widget output USNG: 14PAS1937755791
Widget should output USNG: 14SPA1937755791 (MGRS output is correct)
It transposed the latitude band and 100k grid designators.

- Invalid MGRS and USNG:
Clicked location: 31.234721N 090.703125W
Widget output MGRS: 15R57890Q18762Y
Widget output USNG: 15R57890Q18762Y
Widget should output the following coordinates for MGRS and USNG: 15RYQ1876257890
It transposed the easting and northing and split the 2 character 100k grid designator and placed them at end of easting and northing.

- Invalid USNG:
Clicked location: 37.329398N 085.781250E
Widet output USNG: 45UBS9202832111
Widget should output the following USNG: 45SUB9202832111
It transposed the latitude band and 100k grid designators.

**Comment by adgiles** [comment]
@elinz issue probably similar to that in #783 I will look at it first think tomorrow

**Comment by adgiles** [comment]
@elinz 

My suspicions were correct, widget amended output now the following:

![1](https://cloud.githubusercontent.com/assets/3740334/22014750/158ed0f2-dc97-11e6-9a57-791bc78f6e31.png)
![2](https://cloud.githubusercontent.com/assets/3740334/22014751/171c249c-dc97-11e6-8b4f-926fbcdf344c.png)
![3](https://cloud.githubusercontent.com/assets/3740334/22014753/1898efa8-dc97-11e6-92fe-289985c9a5b0.png)
![4](https://cloud.githubusercontent.com/assets/3740334/22014755/1a1251c6-dc97-11e6-9d48-b737a090efeb.png)

**Comment by elinz** [comment]
@adgiles Verified fixed on build 17 Jan 05:11. Closing issue.
