### ISSUE TITLE
Coordinate Conversion: add support to output UTM using latitude band as well hemisphere

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#793]
### Widget
Coordinate Conversion
### Bug or Enhancement
See #718 for more info.

**Comment by adgiles** [comment]
addressed in https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag-CoordinateConversion-Dev

Please verify

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to verify.

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Verified.  Working per the examples listed in issue:
https://github.com/Esri/solutions-webappbuilder-widgets/issues/718

![2017-05-11_9-09-55](https://cloud.githubusercontent.com/assets/3093940/25959779/aca7d880-3629-11e7-855c-e811251cad44.png)

![2017-05-11_9-12-22](https://cloud.githubusercontent.com/assets/3093940/25959860/fb5cb09a-3629-11e7-905e-9e8d39e951f9.png)

This is fixing previous incorrect behavior.  I do not believe this should not affect documentation. @dfoll @topowright @NatalieCampos  Do you guys know if this affects documentation?

**Comment by adgiles** [comment]
@ACueva 

Where are the two screenshots above from? the UTM(H) values should only have the letters N or S

**Comment by ACueva** [comment]
@adgiles The screenshots were taken from this morning's build.

**Comment by adgiles** [comment]
@ACueva can you confirm the UTM(H) values?

**Comment by ACueva** [comment]
Confirming latest build:
![2017-05-11_9-53-56](https://cloud.githubusercontent.com/assets/3093940/25961639/ca98dee2-362f-11e7-8ba9-1a5df741bd6c.png)

Widget Configuration:
![2017-05-11_9-55-19](https://cloud.githubusercontent.com/assets/3093940/25961683/f8fa979e-362f-11e7-8e26-01c48d599cfe.png)

Using Input 34KGE3581934434
![2017-05-11_9-56-46](https://cloud.githubusercontent.com/assets/3093940/25961742/37488286-3630-11e7-9516-cfa837fd8aa5.png)

**Comment by ACueva** [comment]
@adgiles The changes took, looks good now.
![2017-05-11_10-41-09](https://cloud.githubusercontent.com/assets/3093940/25963526/71e0856e-3636-11e7-9449-ceffa3d8cd69.png)

**Comment by ACueva** [comment]
Verified there is no known issue in our documentation.  Closing issue.
