### ISSUE TITLE
Distance and Direction - Auto Fill of Line End Point

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#795]
### Widget

Distance and Direction

### Version of widget

All versions

### Bug or Enhancement

When dynamically creating a line using the draw tool the coordinate for the end point is automatically calculated as you move the mouse. In order for this to be calculated a call on the Geometry Service is fired.

Although this seems to be fine on my machine with a local instance of Server running I wonder how this will perform on a Server with multiple instances of the widget hitting it or a network with constrained bandwidth. 

As an example a move of the mouse from one side of the screen to the other can generate 100+ requests.

Should the widget only populate the End Point coordinate once the line has finished drawing?

**Comment by kgonzago** [comment]
@adgiles We initially had a client-side (open source) solution for coordinate conversion but noticed slight discrepancies between what was implemented and geometry service. We decided to go with using the geometry service to eliminate those discrepancies. I agree with you to only populate the end point once the line is generated in hopes to reduce the chattiness between client and server.

**Comment by adgiles** [comment]
I have put a comment in the code (LineFeedback.js line 218) that explains to a developer what is required to revert this change on their set up if they want the endpoint to automatically update on mousemove. It clearly states use with caution.

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Confirmed with @lfunkhouser that there's no need to document this in our documentation.  Should there be a request for this functionality we can refer them to this issue.

This is the code mentioned in LineFeedback.js line 218

```
        /**
         * if your network & ArcGIS Server can support a high volume of requests, and you want the end point coordinate to update as
         * the mouse moves then uncomment the line below (use with caution and conduct internal test before making public)
        **/         

        //this.set('currentEndPoint', end);
