### ISSUE TITLE
Coordinate Conversion: modify RegEx in widget to use RegEx from Pro/ArcMap addins

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#797]
### Bug or Enhancement
We need the addins and widget to parse the input coordinate string the same way.
See https://github.com/Esri/solutions-webappbuilder-widgets/issues/727#issuecomment-272920738 for more info.

@nfeuerstein Going ahead and setting milestone to version after next.

**Comment by topowright** [comment]
@lfunkhouser I do not think this is an issue anymore being that this widget is a part of the core WAB product. Closing this issue.
