### ISSUE TITLE
DD - creation of features difficult 

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#798]
### Widget
DD
### Version of widget
1/17/16@9:17 am
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
1.  Create multiple features. 
2.  As multiple features are added.  The creation of feature is not happening when clicking rapidly.

**Comment by adgiles** [comment]
@NatalieCampos 

Natalie can you expand please, which tab are you on (line, circle, ellipse, ring). An when you say clicking rapidly what do you mean?

**Comment by NatalieCampos** [comment]
Give me a call and I can show you

**Comment by adgiles** [comment]
I have just tried replicating the issue on my machine and cannot reproduce.

The only thing I think it may be is the time its taking the geometry service to populate the coordinate box
can you get somebody else to check on your network, and if they experience the same behavior, can you check the network response times on the geometry calls?

**Comment by ACueva** [comment]
@adgiles I'll assist @NatalieCampos

**Comment by NatalieCampos** [comment]
@ACueva is this something you can help look at?

**Comment by ACueva** [comment]
@NatalieCampos I believe this is expected behavior.  It's making a call to the arcgisonline Geometry service.  Any lag would be network related.
