### ISSUE TITLE
Coordinate Conversion supports hemisphere prefix for DMS, but not DD or DDM

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#801]
from @elinz: 

Widget supports hemisphere prefix [N|S|E|W] for DMS, but not for DD or DDM. We should fix this.

**Comment by adgiles** [comment]
Fixed please verify

**Comment by Dbarnes1** [comment]
@topowright and I updated the doc for this issue, it still needs verification in the widget. removing affects doc tag.

**Comment by elinz** [comment]
@adgiles @Dbarnes1 Verified fixed in build 18 Jan 2017 12:25. Also verified that all web app builder .pdf degree based formats show that hemisphere prefix is supported. Closing issue.
