### ISSUE TITLE
Doc - Coordinate Notation section - clean up comments under "Degree-based formats"

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#802]
### Repo Steps or Enhancement details
![image](https://cloud.githubusercontent.com/assets/4635490/22085828/a216cdce-dd8a-11e6-8ecd-1635601fd0cf.png)

![image](https://cloud.githubusercontent.com/assets/4635490/22085712/1da9e5c6-dd8a-11e6-8471-9d01c60eed97.png)

**Comment by nfeuerstein** [comment]
@elinz has this been verified?

**Comment by elinz** [comment]
@nfeuerstein I will with new build. the previous build was missing the widget .pdf. Now it exists.

**Comment by elinz** [comment]
@nfeuerstein Verified fixed in web app builder .pdf in build 19 Jan 2017 13:18 #1155. Closing issue.
