### ISSUE TITLE
Coordinate Conversion - Enhance the configuration settings

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#805]
### Widget

Coordinate Conversion

### Version of widget

2.2

### Bug or Enhancement

I think it would be worth considering adding the ability to set the default format for each notation in the settings page. This way the administrator of an organization can set up how they would like their format to be instead of the user having to set it every time.

It could look something like:
![untitled1](https://cloud.githubusercontent.com/assets/3740334/22113878/a5b0cdf6-de5f-11e6-8df4-116f7c499b36.png)
:

**Comment by adgiles** [comment]
@elinz @Dbarnes1 

I have updated the config for this widget can somebody verify

**Comment by Dbarnes1** [comment]
@adgiles verified, however I'm not closing this yet as it will affect documentation. I'm also noticing that support has been added back in for GARS and GEOREF. Has anyone verified that these coordinate formats now work with the rest of the tool?

**Comment by elinz** [comment]
@adgiles @Dbarnes1 @kgonzago I haven't verified the GARS and the addition of GEOREF or the UTM hemisphere/latitude band changes because I wanted to wait for planning for the next release of Military Tools to make sure the product owner wanted these changes for the next release.

**Comment by elinz** [comment]
@adgiles @Dbarnes1 @kgonzago In fact, even this change should be discussed in release planning.

**Comment by Dbarnes1** [comment]
I'll hold off on documentation until we discuss in release planning.

**Comment by Dbarnes1** [comment]
@adgiles I'm revisiting the configuration page for coordinate conversion and I'm finding the UI confusing. Why are there 3 columns, where the third is simply the edit icon that really references what is going on in the second column? And the titles are "Edit Default Format" and "Edit Format." Why not just have the edit default format column and you can click on the default formats to change them, therefore being able to get rid of the third column. I might be missing something here. 

![image](https://cloud.githubusercontent.com/assets/13024357/24008983/b25d4136-0a30-11e7-8993-b9807b153974.png)

**Comment by kgonzago** [comment]
@Dbarnes1 Good question. This table element is a SimpleTable dijit offered in WAB. The default behavior of the on hover event is to display the edit controls. We will need to change the CSS quite a bit if we went with your suggestion. What if the "Edit Format" column was changed to "Actions" instead? Will that eliminate the confusion?

**Comment by Dbarnes1** [comment]
@kgonzago that would definitely help, although whatever UI changes seem relatively low priority, so I'll go ahead and add that tag.

**Comment by adgiles** [comment]
I have change the column names to be 'Default Format' and 'Edit Format' :

![image](https://cloud.githubusercontent.com/assets/3740334/25847394/e157c27a-34ad-11e7-9768-683949195286.png)

Yes I could have just made the Default Format value editable but I wanted to add the action to ensure that the notation is checked before allowing the value to be changed, this prevents the user changing the value and automatically assuming that the notation has now been turned on
