### ISSUE TITLE
Distance and Direction: Enhance the configuration settings

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#806]
### Widget

Distance and Direction

### Version of widget

2.2

### Bug or Enhancement

I think it would be worth considering adding the ability to allow the user to set which tabs they would like in the widget this would make it more flexible for the user. They may for instance just want a tool that does distance and direction or range rings and not all four tabs.

It could look something like:

![picture1](https://cloud.githubusercontent.com/assets/3740334/22114294/da5704d4-de60-11e6-9ae1-80495bcea33a.png)

**Comment by adgiles** [comment]
Enhancement complete please verify

**Comment by dfoll** [comment]
@adgiles could we have a quick talk about this one? i was going to verify, but it wasn't obvious to me how this works.

**Comment by adgiles** [comment]
This is complete closing
