### ISSUE TITLE
Doc - Coordinate Conversion - Supported Notation Formats has invalid MGRS coordinates

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#807]
@nfeuerstein FYI.

### Repo Steps or Enhancement details

All of the MGRS coordinates in the doc are using invalid Zone/Lat Band, 100k grid designator. There was a typo added when the xmetal topic was written.

All MGRS coordinates in doc that start with...
115WC

Should be change to 11SWC

people are going to try and cut and past from the doc as they try things out, so we should correct this.

**Comment by Dbarnes1** [comment]
@elinz this has been fixed, will set to verify once we publish to build.

**Comment by elinz** [comment]
Verified on final 1172 build. Closing issue.
