### ISSUE TITLE
Coordinate Conversion is not allowing coordinates to be pasted into the input box

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#808]
### Widget
Coordinate Conversion
### Version of widget
Build 1169
### Bug or Enhancement
When you paste coordinates into the input box and press enter, nothing happens
### Repo Steps or Enhancement details

from a newly opened instance of the app you created that has the coordinate conversion widget

set your input coordinates to MGRS formatted as "22J BR 05020 41930"

paste in some MGRS coordinates formatted the same way, for example "11S LT 82016 72096" (should be in the greater LA area)

press Enter.... nothing happens
upon pressing Enter, we should be zooming and flashing crosshairs

**Comment by dfoll** [comment]
@lfunkhouser @nfeuerstein  please review and assign.... this seems pretty critical to me.... feel free to have someone else verify this is a bug and not some fluke for me first

**Comment by dfoll** [comment]
@kgonzago i know we worked on this together, so you saw a lot of it with your own eyes, but going through the doc, this is the section in particular that seems to repeatedly start throwing all sorts of stuff in the console window....

Change the display of input coordinates
The input coordinates can be changed to a number of predefined coordinate formats.
1. Click the Format Output button in the input section.
2. In the Set Coordinate Format String dialog, click the coordinate type drop-down list and select a coordinate type from the list.
3. Customize the coordinate format by adding characters, spaces, or removing components of the string.
4. Click the Add check box to add a +/- prefix to positive and negative numbers.
5. Click Apply.
... it's once you hit apply that everything starts going all crazy ... hope maybe this helps a little

**Comment by kgonzago** [comment]
@dfoll can you verify?

**Comment by dfoll** [comment]
looked at this fix. now when you paste something in and press enter it pans to that point and just formats the input to have no spaces in it. i think this is ok, as if you need to see the coordinates you just inputed in a different notation, you can format one of the outputs to have the notation you need to see it in, i doubt there are many people doing that exact workflow

**Comment by dfoll** [comment]
calling it good

**Comment by ACueva** [comment]
Have these changes made it into our Final Build folder?

**Comment by ACueva** [comment]
Verified this is working in Final_1172.  It is Not flashing cross hairs.  Not sure if this is as designed.  If so recommend we log another issue for next release. @dfoll

**Comment by dfoll** [comment]
reopening because i only tested by downloading directly from the repo,

**Comment by dfoll** [comment]
i updated the documentation to take out the flashing cross hairs

**Comment by adgiles** [comment]
This fix has now caused issues with a number of the other inputs as the code has been changed to strip out spaces from the input yet spaces are required in other inputs to distinguish the different element parts of the coordinate (i.e. DMS with using notation: 17 40 44.09 172 58 7.50) . Out of the inputs the following now do not work:

DMS in this sort of format (17 40 44.09 172 58 7.50)
MGRS (if in polar region - fix was done but reverted)
UTM (expecting UTM using Hemisphere not Latitude band)
DD in just number format with a space separator (i.e 68.152483 091.582031)

There is probably more but as you can see, what is a simple fix for one coordinate type has knock on effects for the others.

Please also ensure if the code is being changed in the coordinate conversion widget the same needs to be applied to the distance and direction widget.

@nfeuerstein please provide guidance on what you want doing with this
