### ISSUE TITLE
Visibility: Can't open the Viewshed toolbox in ArcMap

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#809]
### Repo Steps or Enhancement details
In ArcMap 10.3.1, I navigate to FINAL\Web AppBuilder Developer Edition\Geoprocessing\Viewshed\Viewshed.tbx

Double-clicking does not open the toolbox.

**Comment by kgonzago** [comment]
@elinz Is this widget related?

**Comment by elinz** [comment]
@kgonzago no, gp service. but didn't know what the repo was for the gp tools

**Comment by mfunk** [comment]
Ah. Crap. All ArcMap testing was 10.4.1... so tool fixes in 10.4.1.
Toolboxes are NOT backwards compatible.

**Comment by kgonzago** [comment]
@elinz PR #810 with new toolbox to support 10.3.1.

**Comment by elinz** [comment]
@kgonzago @mfunk I copied the new toolbox that was placed in the FINAL folder and copied local, however, I still can't open the toolbox in ArcMap 10.3.1

**Comment by elinz** [comment]
@mfunk saved the .tbx to 10.2.x format and now I can open the toolbox in ArcMap 10.3.1. The .tbx file in the FINAL build folder has been updated.

Closing this issue.
