### ISSUE TITLE
Distance and Direction - no tool tips on "Set Coordinate Format String" and "Map Point" tools 

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#813]
@nfeuerstein FYI.

### Repo Steps or Enhancement details
For Lines, Circle, Ellipse, and Rings tabs, we don't have tool tips on the "Set Coordinate Format String" and "Map Point" tools...
![image](https://cloud.githubusercontent.com/assets/4635490/22166648/fd993078-df16-11e6-869f-a7b779777aad.png)

**Comment by adgiles** [comment]
Fix applied in this branch:

https://github.com/Esri/solutions-webappbuilder-widgets/tree/ag-DistanceAndDirection-dev

Please verify

**Comment by lfunkhouser** [comment]
Assigning to MT PEs @topowright @ACueva @dfoll @NatalieCampos

**Comment by ACueva** [comment]
Got this one.

**Comment by ACueva** [comment]
Verified.  Tool tips show up.
