### ISSUE TITLE
Distance and Direction - Circle - Distance Calculator create incorrect results if "From" set to Diameter

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#815]
### Repo Steps or Enhancement details
If Radius is set as "Create Circle From". The widget creates correct output.
![image](https://cloud.githubusercontent.com/assets/4635490/22167716/0bb057da-df1d-11e6-9200-e6ee2d8d38ea.png)

If Diameter is set as "Create Circle From". The widget creates incorrect output. The widget should have created a circle with a diameter of 360.
![image](https://cloud.githubusercontent.com/assets/4635490/22167760/4d2097ca-df1d-11e6-9909-4bd6f97dbca9.png)

@Dbarnes1 Assigning you this issue to put in the Known Issue list.

**Comment by Dbarnes1** [comment]
@elinz its in the known issues.

**Comment by elinz** [comment]
Verified on final 1172 build. Closing issue.

**Comment by ACueva** [comment]
Reopening issue from a doc standpoint.  Known issues section lists:
When creating circles using the distance calculator, if you create the circle from diameter, you will get incorrect results. https://github.com/Esri/solutions-webappbuilder-widgets/issues/815

I'll be removing that known issue shortly:
Mindjet location:
/General/ArcGIS Solutions/ArcGIS for Defense/Distance and Direction/Web
