### ISSUE TITLE
Distance and Direction - Ellipse tool does not create correct Full ellipse when typing in coordinates

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#816]
### Version of widget
Final 1172 (20 Jan 2017)
### Repo Steps or Enhancement details
A correct ellipse is created when Ellipse type is set to Semi and you type in the following Center Point and Axis' values:
Center Point: 0 0
Major 3000
Minor 1500
Units: Kilometers
Using the measure tool, the width of the ellipse is 6000 kilometers and height 3000 kilometers.
The tool labels the ellipse with the semi major axis and semi minor axis values.
![image](https://cloud.githubusercontent.com/assets/4635490/22169970/72f703f2-df2d-11e6-9682-12e371ba5ecd.png)

Now set the Ellipse type to Full and enter the same parameters; an incorrect ellipse is created.
Center Point: 0 0
Major 3000
Minor 1500
Units: Kilometers
Using the measure tool, the width of the ellipse is 6000 kilometers and height 3000 kilometers. It creates the same exact ellipse as when you set the type to semi (ignore the current labeling. Its not setting the values in the labels to match the ellipse that was created). The tool should have created an ellipse that's 3000 kilometers wide and 1500 kilometers high.
![image](https://cloud.githubusercontent.com/assets/4635490/22170028/13b0e1fa-df2e-11e6-93a3-9e87257f517d.png)

NOTE: this was added to the known issues doc for the 1.0 release of Military Tools.

**Comment by adgiles** [comment]
@elinz 

When I asked @kgonzago what was the difference between a semi ellipse and a full ellipse the answer was just that the label of the major axis was either the diameter for a full or radius for a semi, no change in the actual size of the ellipse being created, so the tool is correct for how it was designed to work.

**Comment by elinz** [comment]
@adgiles That's only when you interactively create an ellipse (fyi: labeling for major and minor should change; current tool only changes the major label). When you type in the center point and axis values and the user selects full, the values entered are the length of the major and minor axis (i.e. total width and height of the ellipse). In the case described above, the ellipse should be half the distance in both the major and minor axis'. This is how the Pro and ArcMap addins work.

**Comment by elinz** [comment]
@adgiles We will have to get together and discuss this full vs semi ellipse stuff so that the widget and addins are all working the same way. There has been a lot of confusion about this. I entered this issue after talking with @mfunk to make sure I understood how ellipses should be created.

**Comment by Dbarnes1** [comment]
revisiting these issues as I was testing the wab widgets disconnected, and I think @elinz is right, there is a difference between creating the ellipse dynamically with the map point tool, and manually entering parameters. The ellipse treats the manually entered full major and minor axis as semi, and an ellipse twice the size of the parameters entered will be created as a result. The major full axis label will also be twice the parameter entered. However, the minor full axis will maintain the correct label.

**Comment by adgiles** [comment]
Issue should be addressed please can somebody verify

@NatalieCampos @dfoll @topowright @ACueva

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Ran tool using examples listed above.  Working properly now.
Semi now gives accurate results.
![2017-05-11_14-07-55](https://cloud.githubusercontent.com/assets/3093940/25972048/52f177a4-3653-11e7-978c-adedc72d703a.png)

DOCUMENTATION CHANGES
Removed the following line :
When creating full ellipses by typing in Center Point and Axis values,  invalid ellipses are created; the Axis values are doubled and the labels are invalid. <xref href="HTTPS://GITHUB.COM/ESRI/SOLUTIONS-WEBAPPBUILDER-WIDGETS/ISSUES/816" cid="1ssSab">https://github.com/Esri/solutions-webappbuilder-widgets/issues/816</xref>
from:
/General/ArcGIS Solutions/ArcGIS for Defense/Distance and Direction/Web
