### ISSUE TITLE
 Distance and Direction - Add "+/-" prefix on DDM causes incorrect values

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#818]
### Widget

 Distance and Direction

### Version of widget

All Versions

### Bug or Enhancement

If you turn on the ability to add a "+/-" prefix on to the DDM format the prefix is added to the front of the minutes not the degrees: 

![image](https://cloud.githubusercontent.com/assets/3740334/22248815/4fb1f254-e238-11e6-90c0-1f401c775d8f.png)

**Comment by adgiles** [comment]
fixed please can somebody verify

**Comment by elinz** [comment]
Verified fixed on build 31 Jan 2017 13:46 Pacific. Closing issue.
