### ISSUE TITLE
Distance and Direction - Add "+/-" prefix on DMS has no affect to the output value

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#819]
### Widget

Distance and Direction

### Version of widget

All versions

### Bug or Enhancement

Adding "+/-" prefix on DMS has no affect on output value

![image](https://cloud.githubusercontent.com/assets/3740334/22248911/b6052404-e238-11e6-9cf0-6dadb9f78300.png)

**Comment by adgiles** [comment]
fixed please can somebody verify

**Comment by elinz** [comment]
Verified fixed on build 31 Jan 2017 13:46 Pacific. Closing issue.
