### ISSUE TITLE
Distance and Direction - Remove the ability to add "+/-" prefix on notations that do not support

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#820]
### Widget

Distance and Direction

### Version of widget

All versions

### Bug or Enhancement

Remove the ability to add "+/-" prefix on notations that do not support, such as:

MGRS
USNG
GEOREF
GARS
UTM

**Comment by adgiles** [comment]
fixed please can somebody verify

**Comment by adgiles** [comment]
@elinz 

Enhancement added please verify

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
