### ISSUE TITLE
Distance and Direction - Rings - Allow user to create unequally spaced rings through keyboard

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#822]
### Widget
Distance and Direction 
### Repo Steps or Enhancement details
We allow the user to interactively create unequally spaces rings...
![image](https://cloud.githubusercontent.com/assets/4635490/22343647/be51af6c-e3ad-11e6-8bca-d17f52ed037f.png)

It would be very useful to be able to create unequally spaces rings through the keyboard. For user input the user could enter a delimited list of distances, for example...
![image](https://cloud.githubusercontent.com/assets/4635490/22343732/0906af30-e3ae-11e6-9822-5bf13eaeb057.png)

**Comment by adgiles** [comment]
@elinz 

Updated please verify that it behaves as expected

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to verify. @dfoll @topowright @ACueva @NatalieCampos

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Tested and this sort of works.  I say this because this works:

![2017-05-02_16-10-11](https://cloud.githubusercontent.com/assets/3093940/25642955/e2e25738-2f51-11e7-82e6-79170c33865c.png)

If we add spaces to the entry, it no longer works:

![2017-05-02_16-11-17](https://cloud.githubusercontent.com/assets/3093940/25642995/00c6112c-2f52-11e7-94d0-bfca397cf844.png)

IMO the second would be what a user would enter.
@nfeuerstein @lfunkhouser thoughts?

**Comment by ACueva** [comment]
@kgonzago

**Comment by topowright** [comment]
@ACueva had an issue with this tool not calculating properly. Here is an example of what is happening: 

![image](https://cloud.githubusercontent.com/assets/5488313/25643260/93ef00d4-2f53-11e7-9ba3-a9610bb2f518.png)

**Comment by topowright** [comment]
Here is another example of this tool calculating it incorrectly: 

![image](https://cloud.githubusercontent.com/assets/5488313/25643333/14b77d68-2f54-11e7-850d-f2138af40469.png)

**Comment by topowright** [comment]
This tool would work if we changed the name of the tool from distance between names to distance from origin. This is per @ACueva logic of what this tool could be vs. looking at what it is not.

**Comment by topowright** [comment]
@kgonzago @nfeuerstein @lfunkhouser

**Comment by lfunkhouser** [comment]
Dev work is required either way. 

Including an option to draw rings based on distance from origin would require a UI enhancement. This would give the user an option to select either draw rings based on distance between rings (as currently designed) or draw based on distance from origin (how it is currently behaving). 

If we plan to include this enhancement, it is not working as expected and would require dev work.

My recommendation is to revert this change and add to planned work for a future release. 

FYI @nfeuerstein

**Comment by kgonzago** [comment]
@lfunkhouser I would suggest we stick with what's implemented and change the label to "Distance from Origin". We then tackle "Distance between Rings" functionality in the next iteration. Thoughts?

**Comment by topowright** [comment]
changing the label is not possible because it will affect the other workflow that is already in place.

**Comment by ACueva** [comment]
@nfeuerstein @lfunkhouser If this item is to be addressed this version, PE's will need to sequence diagram and plan for these changes.  Please confirm these changes should be incorporated into this release.

**Comment by adgiles** [comment]
Here is my suggestion, the current widget UI look similar to:

![1](https://cloud.githubusercontent.com/assets/3740334/25999418/f1758d74-371c-11e7-97c4-27a02bfa3f00.png)

I recommend adding a drop down with the following 4 creation types (Interactively | Fixed |
Origin | Cumulative). Then change the UI depending on the choice:

![2](https://cloud.githubusercontent.com/assets/3740334/25999472/24ebf0bc-371d-11e7-9ca2-071b3e96f8fe.png)
![3](https://cloud.githubusercontent.com/assets/3740334/25999475/280a7c3c-371d-11e7-8d08-d01b1cdb8ed3.png)
![4](https://cloud.githubusercontent.com/assets/3740334/25999479/2a3fecda-371d-11e7-9ad7-9a24ef37e322.png)
![5](https://cloud.githubusercontent.com/assets/3740334/25999489/36f3abe2-371d-11e7-9ce7-a4bdfc1f0aee.png)

For Origin and Cumulative the UI element is like a table that allows distances to be added or removed similar concept as the Multl Ring Buffer in desktop

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#445
