### ISSUE TITLE
Coordinate Conversion: no longer output USNG value

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#827]
### Widget
Coordinate Conversion
### Version of widget
31 Jan 2017 13:46 Pacific
### Bug or Enhancement
The tool no longer output a USNG value.

![image](https://cloud.githubusercontent.com/assets/4635490/22491957/ccdb7c34-e7db-11e6-819c-f714cc3bc0ca.png)

**Comment by adgiles** [comment]
@elinz 

Sorry Eric not sure what happened there, all fixed, please verify

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
