### ISSUE TITLE
Coordinate Conversion: Add support for comma seperated decimals

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#828]
### Widget

Coordinate Conversion

### Version of widget

All Versions

### Bug or Enhancement

Many countries use a comma instead of a decimal point:

https://en.wikipedia.org/wiki/Decimal_mark

Currently the widget will not support this, the regular expressions need up dating to support commas

**Comment by adgiles** [comment]
@elinz 

Enhancement Added. please verify

**Comment by lfunkhouser** [comment]
Assigning to MT PEs to verify. @ACueva @dfoll @topowright @NatalieCampos

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Verified this is working.  This functionality also works the same as ArcMap.  I also tested this on ArcGIS Pro.  It does not work.  Logging another issues to address the ArcGIS Pro issue.

**Comment by lfunkhouser** [comment]
This should be added to the Release Notes - adding ```Affects Documentation``` label and putting in the ```backlog``` for a PE to pick up.

**Comment by NatalieCampos** [comment]
the following was added to the **Supported Notation Formats-Widgets** documentation

![image](https://cloud.githubusercontent.com/assets/5116835/26370122/ba2e48b4-3fab-11e7-97a8-fc0e03e854c8.png)
