### ISSUE TITLE
Distance and Direction - Ellipse: Can no longer create ellipses by keying in coordinates/axis length

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#829]
### Widget
Direction and Direction
### Version of widget
06 Feb 2017
### Bug or Enhancement
When I key in the Center Point coordinate, axis major and minor, and the angle an ellipse is not created. I've made sure to hit return after I enter each parameter.

![image](https://cloud.githubusercontent.com/assets/4635490/22657138/3c738e34-ec4a-11e6-8ff0-590026dffcc5.png)

**Comment by adgiles** [comment]
@elinz 

Sorry copy/paste error, should be fixed now, please verify

**Comment by elinz** [comment]
@adgiles Verified fixed. Closing issue.
