### ISSUE TITLE
Grid Overlay does not load

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#830]
### Widget
Grid Overlay
### Version of widget
1.0
### Bug or Enhancement
When attempting to use the widget it will not load as an option in the widgets avaiable to a new app. 
### Repo Steps or Enhancement details
Add the widget to WAB siteapp
Create a new app
Add a new widget to the new app

**Comment by kgonzago** [comment]
@topowright What version of WAB are you using?

**Comment by topowright** [comment]
I have tried this on version 2.2 @kgonzago

**Comment by topowright** [comment]
When I add the widget from the dev branch I get this message when adding it to the WAB: 

![image](https://cloud.githubusercontent.com/assets/5488313/23578701/dace8fa6-0091-11e7-8d4b-79f8ed4187c7.png)

If I add the widget that i received from @joebayles I get this message an the widget works. 

![image](https://cloud.githubusercontent.com/assets/5488313/23578736/685f065c-0092-11e7-995c-d97389c3f931.png)

**Comment by topowright** [comment]
@kgonzago @Dbarnes1 @elinz would you be willing to take a closer look and test to see if you get the same thing I did?

**Comment by topowright** [comment]
This is an issue based on the folder structure on how it is being stored in the repository. 

![image](https://cloud.githubusercontent.com/assets/5488313/23578849/deb50d9a-0094-11e7-863a-b0121c665044.png)

This is the only widget that has a folder structure that does not allow  you to drag and drop the top level folder for the widget. Not sure if we need the folder contributorGuide-JsDoc stored in the widget directory. @joebayles can you give some in sight on this folder?

**Comment by topowright** [comment]
I am changing this from a bug to a question.

**Comment by joebayles** [comment]
@topowright now that I'm thinking about it, I am pretty sure when I downloaded it there was something I had to do with the folder content, like bring it up a level. I can look at it more if you want.

**Comment by kgonzago** [comment]
@topowright You're spot on with the folder structure and widget not loading correctly. The actual grid overlay widget is embedded here: https://github.com/Esri/solutions-webappbuilder-widgets/tree/dev/GridOverlay/wab/widgets. Copy the GridOverlay folder from that location into your stemapp folder of WAB 2.2 and widget should be available during configuration of an app.

**Comment by topowright** [comment]
@joebayles @kgonzago thanks guys for looking at this. My main reason I kept this open was to ask the question, which I do not think was clear before. 

Do we need all of the other content with this widget? 

Why do we need to keep this folder?
https://github.com/Esri/solutions-webappbuilder-widgets/tree/dev/GridOverlay/contributorGuide-JsDoc
If we do not need to keep this folder then this widget can be the same as all of the others.

**Comment by kgonzago** [comment]
@topowright The jsdoc is needed given the grid overlay has a lot of properties for a developer to configure. Each property has it's own jsdoc page. It may be somewhat overkill but the are a lot of moving parts to this widget a developer can configure or enhance. The additional doc we provide will only benefit a developer. 

Also, given the multi levels of folder structure for this widget, a quick suggestion is add additional info to the readme about the folder structure and jsdoc.

**Comment by joebayles** [comment]
@kgonzago Is there any reason that the jsdoc needs to live in that folder as opposed to everything else? Then at least it would work as intended, and the README can point them to the additional doc.

**Comment by kgonzago** [comment]
@joebayles jsdoc can be anywhere and have the readme point to it. We just thought it would be easier to have everything packaged together (jsdoc and widget). Do you have a suggestion on where jsdoc can be?

**Comment by joebayles** [comment]
I think in the widget would be fine...

**Comment by topowright** [comment]
I am currently making these changes in the following branch: 
https://github.com/Esri/solutions-webappbuilder-widgets/tree/lw-grid-overlay-issue%23830

**Comment by topowright** [comment]
This issue needs to be verifed in the following pull request: https://github.com/Esri/solutions-webappbuilder-widgets/pull/853

**Comment by topowright** [comment]
The changes have been made and this can be tested by someone else before we merge the changes.

**Comment by topowright** [comment]
This was merged by @kgonzago
