### ISSUE TITLE
Distance and Direction: Distance Calculation should label based on units specified in Distance Calculation parameters

### ISSUE THREAD

**Issue by elinz** [Esri/solutions-webappbuilder-widgets#831]
### Widget
Distance and Direction

### Version of widget
1.0 release of Military Tools for ArcGIS

### Bug or Enhancement
Perform distance calculation where center point is on New York City, time is 24 hours, rate is 60 miles per hour, which equals 1440 miles.

The widget labels the output graphic based on the Radius/Diameter units instead of the units set in the Rate parameter. For this example, I specified the rate as "Miles / Hour" so the labeled units should be Miles.

Also when you perform distance calculations the output should be labeled as "Radius" no matter if the "From" parameter is set to Radius or Diameter.

![image](https://cloud.githubusercontent.com/assets/4635490/23075646/1d619be8-f4f2-11e6-8627-1286261df965.png)

@kgonzago FYI.

**Comment by adgiles** [comment]
@elinz 

The label is set using the units specified by the user in the drop downs. When the distance calculator is used it converts the calculated distance to the correct figure in the distance input box.

So for example if I have the units set to meters and the create circle from radius, and I use the distance calculator to work out 2 hours at 10 kilometres per hour, the units will automatically be filled in as 20,000 meters, and this value and radius will be used for the label:

![1](https://cloud.githubusercontent.com/assets/3740334/23122280/80f3d426-f75b-11e6-904f-73b232ea55fb.png)

if I have the units set to meters and the create circle from diameter, and I use the distance calculator to work out 2 hours at 10 kilometres per hour, the units will automatically be filled in as 10,000 meters, and this value and diameter will be used for the label:

![1](https://cloud.githubusercontent.com/assets/3740334/23122352/c29af5ee-f75b-11e6-85b4-a3bac2b6b191.png)

I personally think this is how the widget should behave

**Comment by elinz** [comment]
@adgiles @kgonzago @nfeuerstein We'll need to discuss this further and make a final decision.

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#444
