### ISSUE TITLE
Visibility Widget: Add Coordinate Input Control for setting the observer location

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#833]
### Widget

Visibility Widget

### Version of widget

All Versions

### Bug or Enhancement

For consistency across widgets a user should be able to input an observer location using the coordinate control as per the distance & direction and coordinate conversion widgets.

**Comment by adgiles** [comment]
Redesign of widget UI complete to incorporate this enhancement and #835 

Can somebody verify @ACueva @dfoll @NatalieCampos @topowright

**Comment by NatalieCampos** [comment]
@adgiles I seem to be able to copy coordinates into the Center Point dialog.  Closing.

**Comment by NatalieCampos** [comment]
@lfunkhouser , @nfeuerstein  adding the  version next tag for tracking purposes.
