### ISSUE TITLE
Visibility - Add Measurement Configuration Options

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#835]
### Widget
Visibility

### Version of widget
1.0

### Bug or Enhancement
Enhancement

### Repo Steps or Enhancement details
- [ ] Give the ability to edit the minimum and maximum observer height
- [ ] Give the ability to edit the minimum and maximum range
- [ ] Give the ability to change the units of measure

These are based on feedback from the FedGIS conference. Use cases include visibility from higher towers and other air-based platforms. Ideally, these would be selected in the widget configuration menu and possibly edited in the widget itself.

**Comment by topowright** [comment]
@kgonzago The items that have been identified could be what we show in the upcoming webinar. What are your thoughts?

**Comment by kgonzago** [comment]
@topowright Good idea. We could dedicate 10-15mins to tackle one of those enhancements.

**Comment by adgiles** [comment]
I suggest in order to address this issue and #833 we need to look at the UI of this widget, maybe instead of using the Horizontal and Vertical sliders for the range and height we revert back to input boxes:

![picture1](https://cloud.githubusercontent.com/assets/3740334/25853028/40b3194e-34c3-11e7-80e8-f1f49e23438f.png)

Any thoughts?

**Comment by kgonzago** [comment]
@adgiles The UI looks good. 

@topowright @NatalieCampos @ACueva @dfoll What are your thoughts?

**Comment by joebayles** [comment]
@kgonzago @adgiles: I agree. The three boxes on the left are input, right?

**Comment by adgiles** [comment]
Yep, restricted to numerics

**Comment by adgiles** [comment]
Redesign of widget UI complete to incorporate this enhancement and #833 

Can somebody verify @ACueva @dfoll @NatalieCampos @topowright

**Comment by ACueva** [comment]
@adgiles Ideally we'd want you to wait on the Product Engineers to drive the design.  I'll schedule a meeting with the PEs to review your changes and provide changes/requirements as needed.

**Comment by adgiles** [comment]
@ACueva 

Understood, but the initial enhancement request posted by @joebayles above and #833 were both posted 3 months ago, can we really be waiting this long to implement fairly simple changes?

**Comment by ACueva** [comment]
@joebayles Isn't on the military tools team.  He should be treated like an outside stakeholder, nothing more.

Part of making sure we put out quality products is for the product engineers to take an active role in what is being developed.  This entails the product engineers taking the lead in deciding what goes on with all aspects of the military tools products.  At the end of the day we are the ones that have to answer to customers and management.  

As far as 3 months to decide, we as product engineers don't decide priority.  This is up to @nfeuerstein and @lfunkhouser.  I do admit that this is a newer process we are implementing so I understand the push back.  I also realize that this can be seen as restricting the work you'll be able to work on, especially if you're waiting for the product engineers to give you the green light before you can get started.  However, in the long run, having us product engineers driving the development process should help with the quality of the product we release.

**Comment by NatalieCampos** [comment]
@adgiles The new design look good. However, we have additional changes.  We have uploaded a design diagram to box.  Please review it.  @ACueva will schedule a meeting to review necessary changes.

**Comment by ACueva** [comment]
@adgiles showed me some of the changes made.  I'll test these changes and log any issues as needed.

**Comment by ACueva** [comment]
Changes look good.  Will consider this issue done.  Any additional bugs/enhancements will be logged as separate issues.

Moved back to in progress as UI changes will need to be documented.

**Comment by NatalieCampos** [comment]
The widet documentation was updated and sent to @ACueva for review.  Closing issue.
