### ISSUE TITLE
Distance and Direction- Lines - Distance and Bearing - No zoom to output

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#838]
I'd like to see the Distance and Direction widget zoom to the output of lines created via distance and bearing. If I'm at a very small scale and then input a distance of only 1000 meters, I'd like to see the map zoom into my output. This functionality already exists in the add-ins, and in the widget for zooming to the output of circles created with the distance calculator, and non-interactive range rings.

**Comment by adgiles** [comment]
@Dbarnes1 

Dan, issue addressed please verify

**Comment by Dbarnes1** [comment]
@adgiles it looks like the map is zooming to the output from distance and bearing. But it is also zooming to output from interactive map point tool as well. I don't think that is expected, because it doesn't zoom to other shapes created interactively, nor does that happen in Pro or ArcMap.

**Comment by NatureMike** [comment]
I have two questions.   Is there a demo site where we can try this widget, and does it let you draw a line and then see the distance and bearing of that line?  Thanks.

**Comment by kgonzago** [comment]
@NatureMike Here's a try-it-live [site](http://esri.github.io/solutions-webappbuilder-widgets/) and yes to your second question

**Comment by adgiles** [comment]
I cannot replicate the comment created by @Dbarnes1 on Feb 23 can somebody verify this is still an issue

@NatalieCampos @topowright @dfoll @ACueva

**Comment by ACueva** [comment]
I'll look into this one.

**Comment by ACueva** [comment]
Verified zoom functionality appears to be working properly.
