### ISSUE TITLE
Bomb Threat widget needs a configuration page and documentation

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#839]
### Widget
Bomb Threat widget
### Version of widget
Using WAB 2.2 not sure if the widget has been released
### Bug or Enhancement
Enhancement 
### Repo Steps or Enhancement details
Add the widget to an app and access the configuration page.

**Comment by topowright** [comment]
![image](https://cloud.githubusercontent.com/assets/5488313/23224486/7ea5f544-f8e3-11e6-8fea-d14cde176e73.png)
The sample layer is no longer available.

**Comment by csmoore** [comment]
These instructions now exist: https://github.com/ArcGIS/defense-solutions-proofs-of-concept/tree/master/widgets/BombThreat#instructions
