### ISSUE TITLE
Network Trace - Better text or grouping to explain field mapping in outage configuration

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#84]
We need some text to explain what this section is doing.  

![image](https://cloud.githubusercontent.com/assets/2707285/6740155/55851e26-ce54-11e4-9171-d7b66ed76b61.png)

**Comment by MikeMillerGIS** [comment]
- Ideas:
    - Make this a group
    - Title with Save Summary Options
    - Add a description:  Select a field to store a summary of the output parameters and select the output parameter.  Currently only the count of items is supported.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement this and will be delivered in the next release

**Comment by MikeMillerGIS** [comment]
verified
