### ISSUE TITLE
ERG Configuration

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#842]
### Widget
ERG
### Version of widget
WAB 2.2
### Bug or Enhancement
Configuration page does not have a point where a user can enter the service end points
### Repo Steps or Enhancement details
Add the widget to the siteapp/widgets folder
Add widget to an App
Attempt to configure the widget
![image](https://cloud.githubusercontent.com/assets/5488313/23493223/fa3aeb34-febe-11e6-8ba7-5f92a68f2c17.png)

**Comment by kgonzago** [comment]
@topowright Were you able to click on, for example, the "Geoprocessing Services Parameters" header which expands and displays the section for GP services?

**Comment by topowright** [comment]
![image](https://cloud.githubusercontent.com/assets/5488313/23520516/33ae2680-ff30-11e6-91f1-5f58d63cfe12.png)

**Comment by topowright** [comment]
Kevin just found the issue while looking at my instance of the widget. Seems to be an array issue.

**Comment by topowright** [comment]
@kgonzago I was not able to expand the dialog on the configuration page for each of the service inputs.

**Comment by kgonzago** [comment]
@topowright Issue fixed. Please verify when you get a chance.

**Comment by topowright** [comment]
@kgonzago this widget now allows me to configure the widget. Verified the fix.
