### ISSUE TITLE
GRG widget does not honor color change for text color of labels

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#846]
### Widget
GRG Widget
### Version of widget
1.0
### Bug or Enhancement
BUG
### Repo Steps or Enhancement details
Open up the config page and attempt to change the color using this rgb color code: 
#FFFF00

![image](https://cloud.githubusercontent.com/assets/5488313/23627054/0359587e-0264-11e7-8330-8a2f338c997d.png)

After hitting okay and accepting the config change open the config page back up and the change is not being honored. 
![image](https://cloud.githubusercontent.com/assets/5488313/23627096/2f477358-0264-11e7-9815-b4802f8aba40.png)

**Comment by topowright** [comment]
@kgonzago The config file seems to be getting overwritten when the app is still being configured. I think this needs to be documented better. We could state that this is the last thing that you would do before deploying the app. I will trace my steps to find out what I did that made the config file of the app to be overwritten. 

Bottom line is the color is honored by the config file. Its the MapOptions label that is overwritten sometime in setting up the app.

**Comment by kgonzago** [comment]
@topowright I was able to repro the issue. Looking into it now.

**Comment by kgonzago** [comment]
@topowright issue fixed. please verify.

**Comment by topowright** [comment]
@kgonzago The widget now honors the new color set by the user; however, each time I access the label panel in the configuration dialog it resets to black. If I do not access that panel and I save the color then is honored. I would think we would want the color chosen.

**Comment by topowright** [comment]
@kgonzago do you agree with my last statement or is my workflow off?

**Comment by kgonzago** [comment]
@topowright Was able to repro. Will look into it.

**Comment by adgiles** [comment]
@topowright is this still an issue as I cannot reproduce anymore

**Comment by topowright** [comment]
@adgiles as of a month ago it was. It looks like @kgonzago was looking into it. I can install the latest build and see if it might have been fixed and just overlooked for comments and testing.

**Comment by topowright** [comment]
@adgiles I feel like there is still an issue with the way a user would have to set the color in the configuration page and I thin the main reason for this is because the color selector square default setting selection tool shows up in the upper right of the color box. Here is an example of this:

**Comment by topowright** [comment]
@nfeuerstein I am not sure if this is something that you want to move to the current work that is being done on GRG. I am going to remove the version after next tag because this does not apply to Military Tools.

**Comment by nfeuerstein** [comment]
@topowright - this is a good example of why we need some reorganization of our GitHub repos. This is the web appbuilder repo and we should be able to work on Military Tools "version-next" and other widgets "version-next" at the same time. I do understand that it's confusing though...because they're in the same repo.

**Comment by adgiles** [comment]
@topowright

I think you are experiencing the same issue referenced here #834,, this issue is a known limitation in Chrome. Apparently it doesn't exist in IE nor FF. According to the WAB dev team, it's a bug in the dojox/widget/ColorPicker, core Dojo bug.

I suggest we doc this as a known limitation

**Comment by topowright** [comment]
Being that this issue is being addressed via the web app builder team it is no longer an issue that we need to track.
