### ISSUE TITLE
GRG Widget cell size in creation

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#847]
### Widget
GRG Widget
### Version of widget
1.0
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
We have attempted to create a graphic that covers an area that should have each grid be 100 X 100; however, this is what we get. 

![image](https://cloud.githubusercontent.com/assets/5488313/23636454/4c5a03c2-028a-11e7-9339-ad86d81aa64b.png)

**Comment by topowright** [comment]
Same size issue with hexagonal grid:

![image](https://cloud.githubusercontent.com/assets/5488313/23636834/a9c6d9de-028c-11e7-8f36-53abeff4b401.png)

**Comment by kgonzago** [comment]
@topowright issue confirmed. Will get with gigz on this.

**Comment by topowright** [comment]
Here is an example when creating a grid further away from the equator: 

![image](https://cloud.githubusercontent.com/assets/5488313/23684882/1a5f40b8-0356-11e7-863d-fff7f996f216.png)

Talking to some other people in Solutions (@MikeMillerGIS and @pLeBlanc93  )there is a thought that it could be a difference in using planar measurements and not geodesic measurements.

**Comment by topowright** [comment]
Here is the measurement of a 1000m grid using the geodesic measurement in ArcGIS Pro: 
![image](https://cloud.githubusercontent.com/assets/5488313/23684998/b0a133ce-0356-11e7-97cd-fbaf8cbdd37d.png)

**Comment by ChrisBuscaglia** [comment]
@topowright We had a very similar problem when applying planar buffers (with Public Notification) and ground measurements (using Parcel Drafter) on web-mercator basemaps.  Could it be that the measure tool is actually reporting planar measures?

**Comment by kgonzago** [comment]
@topowright Confirmed: The measurement widget (which relies on esri/dijit/Measurement) by default measures in geodesic mode. The grg widget will need to generate geodesic grids.

**Comment by topowright** [comment]
@ChrisBuscaglia  and I used ParcelDrafter to make a 100m x 100m square, then added it to the app's basemap. Unfortunately the GRG built a less-than-100m square grid. So the Measure widget is correct, GRG is not.

![image](https://cloud.githubusercontent.com/assets/5488313/23716491/5144442c-03e5-11e7-8da1-59848b4be87c.png)

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/solutions-grg-widget#5
