### ISSUE TITLE
GRG widget default values do not match

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#849]
### Widget
GRG Widget
### Version of widget
1.0
### Bug or Enhancement
Bug The default measurements for cell widget and cell height do not match. One has a comma and one does not. 
### Repo Steps or Enhancement details
Add the widget to an app
Launch the app and open the widget
![image](https://cloud.githubusercontent.com/assets/5488313/23722069/d2caf0a0-03f8-11e7-8b63-9043e979caaa.png)

**Comment by adgiles** [comment]
Fixed can somebody ( @ACueva @dfoll @NatalieCampos @topowright  ) please verify

**Comment by kgonzago** [comment]
@adgiles I'll verify.

**Comment by kgonzago** [comment]
@adgiles Verified. Closing.
