### ISSUE TITLE
Network Trace - Change text next to Add Flag

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#85]
This text should be configurable.  as well as the Add Barrier text
![image](https://cloud.githubusercontent.com/assets/2707285/6740243/f6626e48-ce54-11e4-96eb-10f09c9563f8.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS The text strings "Add Flags" and "Add Barriers" are already configurable in the NLS strings file. NLS string tag for "Add Flags" is `flagHeading: "Add Flags"` and for "Add Barriers" is `barrierHeading: "Add Barriers"`. We have done this to support internalization.

Please let us know if this resolves the issue

**Comment by MikeMillerGIS** [comment]
Since the user may be placing anything, not just flags, in my test example yesterday it was sensors.  Can we just display the name of the input.  So if the gp input was Sensors, the text would be Add Sensors.  Add would come from the NLS, the rest from the parameter name or title.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement this and will be delivered in the next release.

The first part of the label, i.e. "Add" will be coming from separate NLS string tags for Flags as well as Barriers. This would enable the Admin to configure separate labels for Flags and Barriers (e.g. "Add Flags" and "Draw Barriers").

The second part of the label would be parameter name of input parameter from the GP service

**Comment by MikeMillerGIS** [comment]
This is still an issue, the widget says Add Flag, but my parameter name is TracePoint.  
![image](https://cloud.githubusercontent.com/assets/2707285/7395104/db6d8704-ee65-11e4-8fd8-da0bdf66093a.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are able reproduce this issue. We will fix this issue and include this in next release.

**Comment by MikeMillerGIS** [comment]
verified
