### ISSUE TITLE
Using the GRG widget to create a predefined amount of rows and columns

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#850]
### Widget
GRG Widget
### Version of widget
1.0
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
LAPD and Homeland Security Advisory Council (HSAC) http://www.hsacouncil.org/ would like to use the GRG widget to create a grid over a predefined area such as a neighborhood. They would want the grid to match the street network. If I had a area covering a area that was three streets by five streets it would be a 3 x 5 grid.

**Comment by lfunkhouser** [comment]
This issue was moved to ArcGIS/solutions-grg-widget#4
