### ISSUE TITLE
Distance and Direction - Lines - No option for Great Elliptic or Loxodrome, assumed default is Geodetic

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#851]
### Widget

Distance and Direction

### Version of widget
1.0 for WAB 2.2

### Bug or Enhancement

In order to maintain consistency with the add-in, we should allow the widget to draw not only geodetic lines, but loxodrome and great elliptic lines as well. Like the add-in, we should enable this via a drop down or other simple user interface.

### Repo Steps or Enhancement details
I can't find any option for doing this surfaced in the widget UI, so I'm assuming it hasn't been implemented yet.

**Comment by kgonzago** [comment]
@Dbarnes1 Those types of lines are not available, a limitation of the JS API for now.

**Comment by Dbarnes1** [comment]
@kgonzago thanks, adding known issue

**Comment by kgonzago** [comment]
@Dbarnes1 closing out.
