### ISSUE TITLE
Distance and Direction - Ellipse tool does not create correct Full ellipse when using map point tool.

### ISSUE THREAD

**Issue by Dbarnes1** [Esri/solutions-webappbuilder-widgets#852]
### Widget
Distance and Direction

### Version of widget
1.0 for WAB 2.2

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
When drawing a full ellipse dynamically, I expect the labels to represent the full major and minor axis, which are the diameters of the two axes of the ellipse. Currently, when I draw an ellipse using the Full drop down on the distance and direction widget, I get a full label for major axis, and a semi label for minor axis. I figured this out using the measurement widget:

![image](https://cloud.githubusercontent.com/assets/13024357/24046302/577ee544-0adf-11e7-8ec9-e7e65a655d02.png)

This is similar to this issue in that it talks about inaccuracies in ellipse labeling in distance and direction widgets:https://github.com/Esri/solutions-webappbuilder-widgets/issues/816

**Comment by adgiles** [comment]
Issue should be address please can somebody verify

@NatalieCampos @dfoll @topowright @ACueva

**Comment by ACueva** [comment]
I got this one.

**Comment by ACueva** [comment]
Verified.
Behavior is now Semi Ellipses return the radius length for both Major and Minor axis. 
Full Ellipses return the diameter length for both Major and Minor axis.

Unknown if this affects documentation.  Adding label.

**Comment by ACueva** [comment]
This is not listed as a known issue.  It does not appear to affect documentation.  Removing label and closing.
