### ISSUE TITLE
Network Trace - Config should use the entire panel

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#86]
![image](https://cloud.githubusercontent.com/assets/2707285/6740333/885e303e-ce55-11e4-8cfe-24edb03f52d0.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Can you please share the screen resolution on which you are facing this issue?

We are not able to reproduce this on 1366X768 screen resolution. Following is the screenshot:

![untitled](https://cloud.githubusercontent.com/assets/2959186/6820154/9738b1a6-d2f1-11e4-8676-15d14f780fb6.png)

**Comment by MikeMillerGIS** [comment]
1920x1200

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Thanks. We will try to reproduce this on 1920X1200 screen resolution and will resolve this.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have fixed this issue. Following are the screenshots on 1920X1200 screen:

Input Panel:
![1](https://cloud.githubusercontent.com/assets/2959186/6964135/09443a5e-d964-11e4-9452-ba111c66385b.png)

Output Panel:
![2](https://cloud.githubusercontent.com/assets/2959186/6964146/0fc44af4-d964-11e4-8a2b-b16b647c4da1.png)

Outage Panel:
![3](https://cloud.githubusercontent.com/assets/2959186/6964152/1578628c-d964-11e4-8dd0-f722babcd089.png)

**Comment by MikeMillerGIS** [comment]
verified
