### ISSUE TITLE
Distance and Direction default pane omits "Rings" tab

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-webappbuilder-widgets#860]
### Widget
Distance and Direction
### Version of widget
Build 05-02-2017_1418
### Bug or Enhancement
Bug?
### Repo Steps or Enhancement details
Note size of pane:

![2017-05-02_14-34-38](https://cloud.githubusercontent.com/assets/3093940/25640473/8ac4e32a-2f44-11e7-98a6-b73ae354f560.png)

This is how it looks with the missing pane:

![2017-05-02_14-35-51](https://cloud.githubusercontent.com/assets/3093940/25640529/b0001bdc-2f44-11e7-9cf5-3238b03ec7b3.png)

**Comment by ACueva** [comment]
FYI @nfeuerstein, @lfunkhouser

**Comment by topowright** [comment]
@ACueva I am not getting this same experience. What is your screen resolution set to? My screen resolution is set 

![image](https://cloud.githubusercontent.com/assets/5488313/25642071/50af21e8-2f4c-11e7-8eec-69c7fd500620.png)

**Comment by ACueva** [comment]
I'm also at 1920 x 1080.  Let me deploy this app to see if the behavior changes.  I noticed this while creating the application.
The other question is, should we consider this an issue.  I'm sure there are going to be users operating at a lower resolution.

**Comment by topowright** [comment]
yeah. I saw the same issue you are seeing. I think that this is due to the design. I wonder what could change to support the four tab approach.

**Comment by kgonzago** [comment]
@ACueva @topowright Two ways to accomplish this: 

1. The width and height of each widget can be set in the main config.json of the deployed WAB app (easiest approach) 
2. In the code, determine form factor resolution and set width and height accordingly (requires additional coding).
3. Build in intelligence into CSS files to handle lower resolution in form factor (ideally the best route but requires work).

**Comment by NatalieCampos** [comment]
@lfunkhouser, @nfeuerstein @topowright 

This issue can possibly fixed by reducing the white /grey space of the tabs themselves.  Sort of like we would adjust the cell width to fix text in excel.  Is this possible @kgonzago ?

**Comment by topowright** [comment]
Moving the tabs to the side the widget could also help if we are not able to do what @NatalieCampos stated above.

**Comment by ACueva** [comment]
Going to look into this issue.

**Comment by adgiles** [comment]
Amended the widget CSS to remove the padding around the labels which in turn reduces the overall widths of the tabs allowing them all to fit in. Have checked in all templates and seems to be working

**Comment by ACueva** [comment]
I'll verify this one.

**Comment by ACueva** [comment]
Verified.  Should not affect documentation.  Marking as Verified and closing issue.
![2017-05-09_13-50-17](https://cloud.githubusercontent.com/assets/3093940/25872150/93f8d0bc-34be-11e7-8036-68bc29471377.png)
