### ISSUE TITLE
Implement a drop down to support different workflows for Range Rings

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#861]
### Widget
Distance and Direction
### Bug or Enhancement
Currently we need to support multiple workflows for creating Range Rings: 

Allow users to create unequally spaced rings from origin through keyboard 
https://github.com/Esri/solutions-webappbuilder-widgets/issues/822

Allow users to create unequally spaced rings through keyboard from last ring
-
We can use the same approach that we use for lines in this widget to change the dialog for multiple UI views for Range Rings.

**Comment by adgiles** [comment]
See my comment in #822

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#443
