### ISSUE TITLE
GRG Widget: Allow user to dynamically resize grid

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#868]
### Widget
GRG

### Version of widget
2.0

### Enhancement
Allow a user to dynamically resize a grid at runtime.

**Comment by adgiles** [comment]
I have changed the way in which a user draws the GRG area not sure it this requirement will still be needed, @kgonzago please confirm

**Comment by kgonzago** [comment]
@adgiles Given the odd behavior with the API when resizing an existing polygon, what you have implemented is solid. Closing this issue.
