### ISSUE TITLE
Network Trace - Rename Run Trace button to Run

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#87]
![image](https://cloud.githubusercontent.com/assets/2707285/6740429/211961a4-ce56-11e4-8e36-6f7b7da42805.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS This is similar to #85 

The NLS string for "Run Trace" is `traceButtonValue: "Run Trace"`

**Comment by MikeMillerGIS** [comment]
Since the user may be placing anything, not just flags, in my test example yesterday it was sensors.  Can we just display the name of the input.  So if the gp input was Sensors, the text would be Add Sensors.  Add would come from the NLS, the rest from the parameter name or title.

Sent from my Verizon Wireless 4G LTE DROID
On Mar 20, 2015 2:56 AM, CyberTech <notifications@github.com> wrote:

@MikeMillerGIS<https://github.com/MikeMillerGIS> This is similar to #85<https://github.com/Esri/solutions-webappbuilder-widgets/issues/85>

The NLS string for "Run Trace" is traceButtonValue: "Run Trace"

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS 
Yes, we can expose this as a parameter in "Others" section of config panel.
Just wanted to mention that the "clear" button text will still be read from NLS strings.
Is this ok?

**Comment by MikeMillerGIS** [comment]
Yes

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will provide a configurable parameter in "Other" panel for display text of Run Trace button. The text for Clear button will still come from NLS strings.

We will implement this and deliver this in next release

**Comment by MikeMillerGIS** [comment]
Verified
