### ISSUE TITLE
Visibility - Improve Error Message(s)

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#872]
### Widget
Visibility

### Version of widget
1.0.0

### Bug or Enhancement
Improve error messages

### Repo Steps or Enhancement details
Whether I query outside the extent of the viewshed GP service or I configure with and query an invalid service (i.e. an elevation service), I receive the same error message:
>An error occurred whilst creating visibility. Please ensure your observer location falls within the extent of your elevation surface.

Suggest:
- [ ] Add a check during configuration to ensure that the service is valid, and an error message that explains the issue
- [ ] At the very least, add verbiage to the configuration pane that specifies the requirement for a viewshed geoprocessing service, and that an elevation service will not work
- [ ] Update the error message to: `An error occurred while analyzing visibility. Possible issues are:` or something similar, or create more than one

#### FYI @rfeuerstein @nfeuerstein @lfunkhouser @kgonzago @dfoll
*Based on customer feedback (CBP)*

**Comment by kgonzago** [comment]
@adgiles FYI

**Comment by NatalieCampos** [comment]
assigning to @nfeuerstein for priority.

**Comment by adgiles** [comment]
Added checks for a valid GP Service in both the configuration settings and the widget itself.

Within the configuration settings the user will be shown:

![untitled](https://cloud.githubusercontent.com/assets/3740334/26401345/5c10405c-407d-11e7-9773-67fb4bbfb3a5.png)

and the widget configuration will not be saved.

If somebody tries to manually change the URL in the config file, then the widget will show the following for an unreachable URL:

![untitled1](https://cloud.githubusercontent.com/assets/3740334/26401371/7edd6894-407d-11e7-9e98-1bfaae2688c8.png)

and the following for a reachable but invalid URL:

![untitled2](https://cloud.githubusercontent.com/assets/3740334/26401396/9de46f80-407d-11e7-967c-e1ab1836ba47.png)

Please can somebody verify

**Comment by nfeuerstein** [comment]
Needs to be verified, but removing the verify tag because it's confusing the waffleboard experience. We should probably look into that.

**Comment by csmoore** [comment]
This issue was moved to Esri/visibility-addin-dotnet#228
