### ISSUE TITLE
Distance and Direction: Distance and Bearing on Line tab produces an inaccurate line.

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#873]
### Widget
Distance and Direction

### Version of widget
2.0

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
Creating a line using the Distance and Bearing option produces a line that does not represent the true angle supplied by a user. Here are the steps to reproduce:
1. Select `Distance and Bearing` option
2. Create a center point
3. Set `Length` to 1000
4. Select `Kilometers` for units
5. Set `Angle` to 90
6. Click `Enter`

What is produced is a geodesic line on the map but not at a 90 degree angle. It instead produces a line that is a little more than 90 degrees; a misrepresentation of what was supplied as input parameters.

**Comment by nfeuerstein** [comment]
This is an API issue, it has been logged with Core.

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#442
