### ISSUE TITLE
Visibility Widget needs to handle async calls

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#874]
### Widget
Visibility

### Version of widget
2.0

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
Currently, the visibility widget makes a synchronous call to a viewshed service. It needs to handle both synchronous and asynchronous calls to any viewshed GP service.

For example: we allow a user to configure the widget with a custom viewhed service. If a user specifies a service that only accommodates for asynchronous calls, the widget will throw a 500 error (generic internal error).

**Comment by adgiles** [comment]
Viewshed widget now works with both synchronous and asynchronous gpservices. I have also updated the configuration experience so it guides the user to selecting an appropriate GPService

Please can somebody verify

**Comment by topowright** [comment]
@adgiles FYI testing this toolbox it does not work in 10.3.1. When we do any updates to a toolbox we have to make sure that we do it at the lowest level of the supported desktop software. I am able to fix this issue and proceed to verifying your changes. I have validated this by opening the toolbox in 10.5 and I saw that it is present. It does not show up in 10.3.1. I will post when I update this toolbox.

**Comment by adgiles** [comment]
@topowright I didnt make any changes to the toolbox only the widget code

**Comment by topowright** [comment]
Not sure what has happened since the last release, but this is what I see:

**Comment by topowright** [comment]
Here is the updated toolbox now showing up in 10.3.1: 
![image](https://cloud.githubusercontent.com/assets/5488313/26595486/688b2c00-4520-11e7-9bda-75075200d9a9.png)

This was done with the following pull request: 
https://github.com/Esri/solutions-webappbuilder-widgets/pull/886

**Comment by topowright** [comment]
@adgiles what did you change in the widget to allow async calls?

**Comment by adgiles** [comment]
All the changes can be seen here:

https://github.com/Esri/solutions-webappbuilder-widgets/commit/d8c5f086e335d39a4e1f8581a936c0684c2e83bc

**Comment by topowright** [comment]
I have verified that the widget can work with an async and sync service; however, there are issues when you try and change a service from async to sync or vise versa. If that is done this does not work.  This might be a gp issue. The way that I was able to get the tool to work was publish two different services with the different options selected at the inception of the created service.

**Comment by adgiles** [comment]
Yes the configuration file holds a Boolean variable called isSynchronous. If the gpservice mode is changed the configuration file will need to be changed either manually or through the builder.

**Comment by topowright** [comment]
@adgiles I saw that in your code, but that is not what I am referring to. I am saying that if you publish the gp service as sync and change it to async the tool will not run in the widget. It is a mood point for this release.

**Comment by adgiles** [comment]
I have moved the check for the service type out of the configuration settings and into the widget itself.
Therefore it shouldn't matter if the service type is changed the widget will still execute.

@topowright do you want to verify

**Comment by topowright** [comment]
sure

**Comment by topowright** [comment]
I have verified that the widget works. I did this by running it against an async and a sync gp services.
