### ISSUE TITLE
unable to enter FOV values  - visibility

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#877]
### Widget
Visiblity
### Version of widget
Build 1476
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
1. Copy Coordinates into the Center Point dialog 
2. Attempt to enter a value for FOV
![image](https://cloud.githubusercontent.com/assets/5116835/26131522/49b4fde6-3a4f-11e7-9fd5-7eb146132bcf.png)

I cant seem to change the value from 0 to anything else.  However, when a point is collected from the map, I can change the value.   This bug may be related to the issues #833.

**Comment by adgiles** [comment]
Good catch @NatalieCampos , I was focused on make the FOV active after dropping a point on the map I forgot about the manual entry,

Should be fixed now, if you want verify

**Comment by NatalieCampos** [comment]
Verified.
