### ISSUE TITLE
Network Trace - Placing a flag still queries all layers in the map for a pop up

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#88]
When the Add Flag and Add Barrier tool are active, disable the map click event handler to prevent non required calls to the server.  

To Repo
Open Widget
Open Fiddler
Select the Add Flag tool
Click on the screen
Watch the fiddler log(there has to be querable features services in the map)

**Comment by MikeMillerGIS** [comment]
The event is the clickEventHandle.  If you look at drawbox.js in the WAB code, you can find an example of the disableWebMapPopup and enableWebMapPopup functions

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are investigating this and will update on this soon

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have fixed this and will deliver in the upcoming release

**Comment by MikeMillerGIS** [comment]
This is still an issue.  @CTLocalGovTeam

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are not able to reproduce this issue by following the steps described above. Can you please confirm, if these are the same steps to reproduce ?

**Comment by MikeMillerGIS** [comment]
I was not able to repo today, closing
