### ISSUE TITLE
Coordinate Conversion - User should be able to select a point on the map and have the point highlight in the list

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#880]
### Coordinate Conversion

After populating multiple points in the map with the Coordinate Conversion pane, the user should then be able to select one of those points and have that coordinate highlighted in the list.

**Comment by dfoll** [comment]
@nfeuerstein @kgonzago  it looks like the milestones are not set for this repo

**Comment by kgonzago** [comment]
@dfoll Is it safe to assume the widget should behave the same as the CC add-in (Pro and ArcMap) with a list to collect multiple coordinates? Also, the UI for the widget will need to enhanced a bit to accommodate for the batch conversion/list component.

**Comment by topowright** [comment]
I think this is an issue that needs to be moved to the CC add-in

**Comment by topowright** [comment]
issue has been added the the add-in repo
