### ISSUE TITLE
Widget localization 

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#884]
**### Widget**

All supported widgets

**### Version of widget**

All

**Enhancement**

Web AppBuilder supports 20+ languages. To switch the app language you can append locale=<language code> to the end of your app URL:

http://<your app>/?locale=fr

The following language codes are supported: ar,cs,da,de,en,el,es,et,fi,fr,he,it,ja,ko,lt,lv,nb,nl,pl,pt-br,pt-pt,ro,ru,sv,th,tr,zh-cn,vi,zh-hk,zh-tw.

@nfeuerstein Should we make sure all of our widgets conform to this? If so, is there a localization team within Esri that we can send our string.js files to, for them to convert?

**Comment by lfunkhouser** [comment]
This has been done in the WAB for Coordinate Conversion and Grid Overlay. This issue needs to addressed in each of the individual widget/theme repos.
