### ISSUE TITLE
Copy all button copies bottom row as top row

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#887]
### Widget
Coordinate Conversion
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
1. Collect points
2. Use the Copy All Button to copy all
3. Paste the copied coordinates 
4. Notice that the last coordinate format is now the first format.  

I would think that the copy all should honor the order in which my coordinate formats are organized.  If my first Output coordinate is UTM then the first copied line should also be UTM. See screen capture below.

![image](https://cloud.githubusercontent.com/assets/5116835/26604883/a9448096-4540-11e7-88f9-9575df79b791.png)

**Comment by dfoll** [comment]
this looks like it was fixed
