### ISSUE TITLE
Network Trace - GP Job Fail

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#89]
When the GP job fails, please write the response as an error to the JS console to aid in debugging purposes.

Example response.
{"jobId":"j49cd5b98c1ef4f8c8521c9f18ea595db","jobStatus":"esriJobFailed","messages":[{"type":"esriJobMessageTypeInformative","description":"Submitted."},{"type":"esriJobMessageTypeInformative","description":"Executing..."},{"type":"esriJobMessageTypeError","description":"Failed."}]}

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement this and will be delivered in the next release

**Comment by MikeMillerGIS** [comment]
verified
