### ISSUE TITLE
Visibility Widget - Will not open on a number of themes

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#890]
### Widget

Visibility Widget

### Version of widget

All

### Bug or Enhancement

Bug

### Repo Steps or Enhancement details

The visibility widget throws an error if it is the first widget opened in the following themes:

- Billboard
- Box
- Dart
- LaunchPad
- Plateau

**Comment by adgiles** [comment]
The following libraries were missing from the import:

- 'dijit/form/NumberTextBox',
- 'jimu/dijit/CheckBox'

fixed in this commit: https://github.com/Esri/solutions-webappbuilder-widgets/commit/737b7a1f2006dc0cbc03a7638335d7ba84831df7

Can somebody verify please @NatalieCampos @topowright @ACueva @dfoll

**Comment by ACueva** [comment]
Verified.  It opens properly on the themes listed above.
