### ISSUE TITLE
Coordinate Conversion - Dart Theme does not display 

### ISSUE THREAD

**Issue by ACueva** [Esri/solutions-webappbuilder-widgets#891]
### Widget
Coordinate Conversion
### Version of widget
MT 1.1
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details

1. Create a new web app builder application.
2. Change the theme to "Dart Theme"
3. Add the Coordinate Conversion Widget
4. Notice the values are not showing up. (They are there, just white on white makes it not visible)
![2017-06-01_11-30-47](https://cloud.githubusercontent.com/assets/3093940/26694901/da69c32e-46bd-11e7-8fea-a0d3345b1f6a.png)
![2017-06-01_11-30-59](https://cloud.githubusercontent.com/assets/3093940/26694897/d88f90e2-46bd-11e7-968f-8a16079d313c.png)

**Comment by adgiles** [comment]
Made change to one of the css properties which has fixed the issue

@ACueva Please Verify

**Comment by ACueva** [comment]
Changes look good.
![2017-06-14_14-31-44](https://user-images.githubusercontent.com/3093940/27155556-4790c920-510e-11e7-87c3-6a1ee05088ad.png)
