### ISSUE TITLE
Distance and Direction: Input boxes on the Circle Tab are not restricted to numbers

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#892]
### Widget

Distance and Direction

### Version of widget

All

### Bug or Enhancement

The input boxes on the circle tab are not restricted to numeric input, therefore it is difficult to validate them correctly and a user can easily enter invalid value

**Comment by adgiles** [comment]
Address in PR https://github.com/Esri/solutions-webappbuilder-widgets/commit/e9928bf74b640caaee38b55f509c3e64e08219b9

Please Verify

**Comment by dfoll** [comment]
this looks fixed. the only place on the entire DD widget i could enter anything but a number was in the center point box and any of the tabs
