### ISSUE TITLE
Distance and Direction: Dart Theme CSS issues

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#893]
### Widget

Distance and Direction

### Version of widget

All

### Bug or Enhancement

There are a number of CSS issues when using the widget with the Dart theme:

![untitled](https://cloud.githubusercontent.com/assets/3740334/26722366/9024774e-4787-11e7-9b78-cbd153ca7028.png)
![untitled1](https://cloud.githubusercontent.com/assets/3740334/26722400/b619ba72-4787-11e7-9a26-bd80e3e467cc.png)

**Comment by adgiles** [comment]
Address in PR https://github.com/Esri/solutions-webappbuilder-widgets/commit/e9928bf74b640caaee38b55f509c3e64e08219b9

Please Verify

**Comment by dfoll** [comment]
fixed. closing.
