### ISSUE TITLE
Visibility Widget: Dart Theme CSS Issue

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#894]
### Widget

Visibility Widget

### Version of widget

All

### Bug or Enhancement

The text in the tooltip for the dial control cannot be seen in the Dart theme, (white on white)

![untitled](https://cloud.githubusercontent.com/assets/3740334/26724726/d612c188-4792-11e7-9235-233a106e6d70.png)

**Comment by adgiles** [comment]
Fix in commit https://github.com/Esri/solutions-webappbuilder-widgets/commit/c1f494973d21a87f2ed01496b2d430d5054cb367

Please verify

**Comment by dfoll** [comment]
verified fixed
