### ISSUE TITLE
ERG Widget - Error Message

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#896]
### Widget
ERG

### Bug or Enhancement
Bug

### Repo Steps or Enhancement details
I ran it for Chlorine, and it failed. Retried several times, it hangs and presents this window.

![image](https://user-images.githubusercontent.com/5016557/26987574-eada5752-4d00-11e7-9cd4-7f7964b93cb9.png)

Text is:
>nsecmini01.esri.com says:

>ERG Geoprocessing job status: Executing (ERG By Chemical):
ERGByChemical "Feature Set" Chlorine 45 Day Large c:\arcgisserver\directories\arcgisjobs\erg2016\ergbychemical_gpserver\jf1b154d281f6453c913e99acb42abd75\scratch\scratch.gdb\ERGByChemicalAreas7 c:\arcgisserver\directories\arcgisjobs\erg2016\ergbychemical_gpserver\jf1b154d281f6453c913e99acb42abd75\scratch\scratch.gdb\ERGByChemicalAreasLines7

**Comment by csmoore** [comment]
This issue was moved to ArcGIS/defense-solutions-proofs-of-concept#2
