### ISSUE TITLE
Place an "OK" button on the distance and direction widget

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#898]
### 2.1

Tools from the Distance and Direction widget are written such that you must press Enter, after you have populated all other inputs on the dialog before the tool will run. We should enhance this, to have an "OK" button. 

This is the reason.

![image](https://user-images.githubusercontent.com/5322669/27107963-c158a814-504f-11e7-8d55-e37cd10342d0.png)
I've got a starting point filled out as well as a length entered and an angle, I press Enter, and i get a line. After seeing the line, I want the line to be twice as long, so I change my length to 200, that should have been the only box I had to touch. However, even though I do not want to change the angle value, I need to put my cursor in that box, and press Enter to run the tool again.

Nothing is wrong with it working this way, however we should enhance the widget, to include an  an "OK" button that runs the tool anytime it is pressed assuming all values provided in the dialog are valid.
I would like to see this on all four tabs.

**Comment by adgiles** [comment]
Work completed in PR #904 

@dfoll please can you verify

**Comment by adgiles** [comment]
Further enhancements made in PR #905

@dfoll Please can you verify

**Comment by dfoll** [comment]
All changes have been made to documentation. @topowright could you please verify all topics for WAB DD widget. After you have completed your review of all topics, please use the xmetal workflow to set them to "to be reviewed". I think you are already set as the tech reviewer on most of them, but if not, please just go ahead and move them to "to be reviewed" after you have completed your review.

**Comment by topowright** [comment]
Sounds good

**Comment by adgiles** [comment]
closing issue as release has now gone out
