### ISSUE TITLE
Distance and Direction inconsistency with the Clear Graphics button

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#899]
### 2.1 

If it is possible, I would like to see the widget have the same behavior as the add-in. With the add-in, each tab has a "Clear Graphics" button that is used to clear only the graphics created from that tab. In the widget, the "Clear Graphics" button from any tab, will clear all the graphics that have been created with the widget.

**Comment by adgiles** [comment]
Work completed in PR #904 

@dfoll please can you verify

**Comment by dfoll** [comment]
verified
