### ISSUE TITLE
Network Trace - Setting GP Task URL

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#90]
This should be same as the Geoprocessing widget.  It should have the set button which loads the dialog to select it from your org or manually edit it.

![image](https://cloud.githubusercontent.com/assets/2707285/6740617/cc8d2f9c-ce57-11e4-9f85-74abbebb5c72.png)

**Comment by MikeMillerGIS** [comment]
![image](https://cloud.githubusercontent.com/assets/2707285/6740626/ea537f18-ce57-11e4-8945-a575b6d563a9.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS The current implementation of directly plugging in the gpservice URL in the configuration UI was discussed during sprint demos and also captured in the HLFS and user stories. 

We are ok to implement this change as requested. Can you please change the issue label to something appropriate like 'enhancement' or 'change'?

**Comment by MikeMillerGIS** [comment]
updated.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have implemented this and will deliver in the upcoming release

**Comment by MikeMillerGIS** [comment]
verified
