### ISSUE TITLE
medium  grey text on light grey background dialog

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#900]
### Widget
CC
### Version of widget
6/14
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
Open the set coordinate string dialog. The dialog has medium grey text over dark grey in the string format area.  The text is really hard to read/see. See below 

![image](https://user-images.githubusercontent.com/5116835/27156241-23e3f710-5111-11e7-8a1c-4168ca7e3df2.png)

**Comment by adgiles** [comment]
Fixed in PR #907, please verify.

Also applied same changes to visibility, distance and direction and GRG

**Comment by NatalieCampos** [comment]
The dialog now looks like this.  Closing issue.  
![image](https://user-images.githubusercontent.com/5116835/27396062-c8030f84-5666-11e7-9e84-79d7d4163595.png)
