### ISSUE TITLE
inconsistent icon highlighting

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#901]
### Widget
CC
### Version of widget
6/14
### Bug or Enhancement
The icons of the CC widget are inconsistent in their highlighting.  
The  add button highlights black but the gear button does not highlight at all.  This makes  it  difficult to see. 
![image](https://user-images.githubusercontent.com/5116835/27156450-fbdbf848-5111-11e7-809f-63d30b6f6bec.png)

![image](https://user-images.githubusercontent.com/5116835/27156533-4a122c8a-5112-11e7-953f-95e070f1ca52.png)

**Comment by adgiles** [comment]
@NatalieCampos Fixed please verify.

**Comment by NatalieCampos** [comment]
icon highlights now.  closing issue
