### ISSUE TITLE
dark grey icons are hard to see on dark background

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#902]
### Widget
CC
### Version of widget
6/14
### Bug or Enhancement
There is only a few color shades between the grey icons and their backdrop.  More contrast is needed for those with vision or color impairment.
![image](https://user-images.githubusercontent.com/5116835/27156696-1b96bb54-5113-11e7-8cff-f755eb5bcb84.png)

**Comment by adgiles** [comment]
Icons now white that change to black on hover.

@NatalieCampos please verify

**Comment by NatalieCampos** [comment]
Dialog now looks like this

![image](https://user-images.githubusercontent.com/5116835/27396213-3ddc9b08-5667-11e7-8a1b-f9f2cb5d62b4.png)
