### ISSUE TITLE
warning labels not red or do not stand out

### ISSUE THREAD

**Issue by NatalieCampos** [Esri/solutions-webappbuilder-widgets#903]
### Widget
DD
### Version of widget
6/14
### Bug or Enhancement
Enhancement
### Repo Steps or Enhancement details
The warnings for incorrect input are white and do not stand out as warning.  See graphic below.  In other themes the warning  is red.  

![image](https://user-images.githubusercontent.com/5116835/27158372-6dd27b12-511b-11e7-9fc4-a08578154792.png)

**Comment by adgiles** [comment]
@NatalieCampos 

It is the style of the dart theme that is overriding the color of the error/warning. I can override it again at the widget level but it will mean our widget will not behave the same way as the core widgets.

As you can see error messages on core widgets are also white:

![untitled](https://user-images.githubusercontent.com/3740334/27182822-7c88164e-51d4-11e7-935f-bdb7fdfdff1d.png)

In my opinion we should not deviate away from the behaviour of core, but I will let @nfeuerstein and @lfunkhouser have the final say.

**Comment by NatalieCampos** [comment]
@adgiles I agree on not deviating away from core behavior.  Lets see what management says.
