### ISSUE TITLE
Military Tools Widgets should support WGS84

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#908]
### Widget
Coordinate Conversion, Visibility and Distance and Direction

### Bug or Enhancement
Widgets should support WMAS and WGS84

### Description
Currently, MT widgets only support Web Mercator Auxiliary Sphere. These widgets will need to be enhanced to accommodate for WGS84 as we have customers that use basemaps in that projection.

FYI @nfeuerstein @lfunkhouser @dfoll

**Comment by adgiles** [comment]
Support added in PR #910, to the following widgets:

- Distance & Direction
- Coordinate Conversion
- Visibility

Please can somebody verify

**Comment by dfoll** [comment]
verified fixed in build 1602
