### ISSUE TITLE
FOV needs to be changed to 360

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#909]
### Widget
Visibility
### Bug or Enhancement
Bug
### Repo Steps or Enhancement details
The  visibility currently is set to have a FOV as 0 as the default. This needs to be changed to 360. When thinking about how a user would use our tools we want to capture the least amount of steps the user could take to get an answer. Most users would run this tool as a full 360 degree FOV; however, if we keep this at 0 then no matter what the user has to interact with the tool.

**Comment by adgiles** [comment]
Complete please verify

**Comment by topowright** [comment]
I have verfied that this has been changed to 360: 
![image](https://user-images.githubusercontent.com/5488313/27411246-5ea3db64-56a1-11e7-9517-03fd601b1566.png)
