### ISSUE TITLE
Network Trace - Line Length on results

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#91]
Text should not be truncate, horizontal slide bar should show so user can see a long string return
![image](https://cloud.githubusercontent.com/assets/2707285/6744364/eba10eae-ce7e-11e4-8050-5b5522dc2109.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS we see two options,
1. Add a horizontal scrollbar to the entire widget
2. Add a horizontal scrollbar only to the panel/container that overflows

We feel option 1 is undesirable and may distort the UI significantly. 
With option 2, you would see a scrollbar only in "sensor locations" panel that you see in the screenshot in previous comment. 
We will no longer display an ellipsis and display the complete text.

Please let us know if this is ok.

**Comment by MikeMillerGIS** [comment]
What also might help here, what if we remove the Zoom to button and just made clicking on the text the Zoom to.  The Skip will still get a button.  That will free up a lot room.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We can remove the zoom button. To make it apparent that each row is clickable, we will have to show them as hyperlinks.

We also thought of replacing skip button with a checkbox, but we need to change the design and event handling. This would be a significant change.

Also considering the option of showing the text in multiple lines would need a design change to make it appear like cards/tiles.

Please advise.

**Comment by MikeMillerGIS** [comment]
Could you do a graphic mockup before making any code changes to see the end result?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Following are the mockups without changing skip and highlight icons.

Option 1 - With horizontal scrollbar
 
![horizontal scrollbar](https://cloud.githubusercontent.com/assets/2959186/6864044/d2f9a3c6-d481-11e4-8d48-950572ccb8b1.png)

Option 2 - Multiple lines with tiles

![network-trace-2](https://cloud.githubusercontent.com/assets/2959186/6864047/d90063e0-d481-11e4-9543-2d56c0e4c12b.png)

**Comment by MikeMillerGIS** [comment]
Option 2 and lets make the grid clickable instead of the zoom to button.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement Option 2 and we will remove the Zoom button. Also, we will make the text in each row as hyperlink so that the user can understand that the row is clickable.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS This will be delivered in the upcoming release

**Comment by MikeMillerGIS** [comment]
verified
