### ISSUE TITLE
Tabs in the DD widget should match the tabs in the desktop application

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#911]
### Widget
Distance and Direction
### Version of widget
NA
### Bug or Enhancement
The lines tab should be changed to line
![image](https://user-images.githubusercontent.com/5488313/27447183-f254af44-5734-11e7-9bb8-bfdbec5583ca.png)

### Repo Steps or Enhancement details
open the widget and view the lines tab.

**Comment by adgiles** [comment]
@topowright Updated please verify and close

**Comment by topowright** [comment]
This has been addressed in build 06-22-2017_1603

**Comment by adgiles** [comment]
closing issue
