### ISSUE TITLE
Center point selected during an interactive session is not honored

### ISSUE THREAD

**Issue by topowright** [Esri/solutions-webappbuilder-widgets#912]
### Widget
Distance and Direction  - Circle Tab
### Version of widget
NA
### Bug or Enhancement
When a user selects a location on the map for the center point of a circle what is created after the second click is using a different center point. 
![image](https://user-images.githubusercontent.com/5488313/27447585-60c0b300-5736-11e7-9a44-364bddad0664.png)

### Repo Steps or Enhancement details
Add the widget to an app
Launch the widget 
Click a location using the interactive method of a circle

**Comment by adgiles** [comment]
@topowright Lyle, I noticed this issue this morning and thought I had fixed it. Can you confirm you are using the latest version of the widget that includes PR #908

**Comment by topowright** [comment]
@adgiles This issue has been fixed with  06-22-2017_1603.  Thanks for the quick turn around.
