### ISSUE TITLE
Military Tools D&D Rings Tab is slightly off in WAB 2.5 (pre-release)

### ISSUE THREAD

**Issue by kgonzago** [Esri/solutions-webappbuilder-widgets#913]
### Widget
Military Tools Distance and Direction

### Bug or Enhancement
The Rings tab of D&D widget is shifted to the right. See image below:
![image](https://user-images.githubusercontent.com/6391826/27544573-8e8ae472-5a5b-11e7-9d80-ec380bd43041.png)

**Comment by csmoore** [comment]
Can someone with write permissions tag this with "Distance and Direction" so we know which issue to move for #941 (ex: https://github.com/Esri/solutions-webappbuilder-widgets/labels/Distance%20and%20Direction) - thanks.

Also, I do still see this issue with latest dev:

![image](https://user-images.githubusercontent.com/3090809/29931678-e1a1334c-8e3f-11e7-9760-427931d5042a.png)

**Comment by csmoore** [comment]
This issue was moved to Esri/distance-direction-addin-dotnet#441
