### ISSUE TITLE
Visibility widget does not work in IE

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#914]
### Visibility widget does not work in IE 11.  Does seem to be fine in firefox or chrome. Experienced this with both WAB 2.3 and 2.4. 

 create an app using WAB, add the visibility widget.  Open the app in IE 11. The visibility widget is "available" but when you open the widget the pane/window is empty. Copied the url to the app between firefox/chrome/IE and used the app successfully in chrome/firefox, so it's not an issue of the app not being configured correctly.

![image](https://user-images.githubusercontent.com/5322669/27564320-a382de86-5a8b-11e7-9eaa-ab77d809c224.png)
![image](https://user-images.githubusercontent.com/5322669/27564348-d7c94b30-5a8b-11e7-88b1-b0939e62785d.png)
![image](https://user-images.githubusercontent.com/5322669/27564399-3f445d18-5a8c-11e7-9a22-1125b773c548.png)
Distance and Direction working (interactively) in IE

**Comment by dfoll** [comment]
is this being caused by the certificate error? DD and CC work fine, but they don't rely on an gp services hosted elsewhere

**Comment by adgiles** [comment]
The code is using 'strict mode' which means more error checking is performed by the browser

https://www.w3schools.com/js/js_strict.asp

The console was raising the following error 'Multiple Definitions of a Property Not Allowed in Strict Mode', and the offending piece of code was:

$("input.fov").trigger('configure',
  {
     "max": 6400,
     "units": 'mils',
     "v": 0,
     "units": 'mils',
     "milsValue": 0,
     "inputColor":"#f37371" 
   }
);

as you see units was specified twice, removing one fixed the issue. Not sure why this was only raised by  IE.

@dfoll please verify

**Comment by dfoll** [comment]
verified that the visibility widget now is available and runs properly in IE 11 for both WAB 2.3 and 2.4
