### ISSUE TITLE
OK button does not work in IE

### ISSUE THREAD

**Issue by dfoll** [Esri/solutions-webappbuilder-widgets#915]
### 
1. Create an app using either WAB 2.3 or 2.4 with the distance and direction widget. 
2. Open the app in firefox or chrome, open the DD widget, 
3.  click on the circle tab
4. enter a center point of 20UPC8821954624
5. press enter on the input box to validate the coordinate
6.  leave the defaults
7. Click OK
 circle is drawn

Repeat steps 1-7 in IE, nothing happens. 

This was the simplest illustration of repro steps, however the same behavior is happening on the circle, ellipse, and rings tabs as well for IE 11 with WAB 2.3 and 2.4

**Comment by adgiles** [comment]
Fixed please verify

**Comment by dfoll** [comment]
this looks good in IE 11 for WAB 2.3 and 2.4
