### ISSUE TITLE
Coordinate conversion widget does not work with non web-mercator projections

### ISSUE THREAD

**Issue by alexurquhart** [Esri/solutions-webappbuilder-widgets#916]
### Widget
Coordinate Conversion

### Version of widget
From v2.1 release

### Bug or Enhancement
When using a web map that does not use the web mercator projection (i.e. [Arctic Imagery](https://www.arcgis.com/home/item.html?id=7ec08e5438304dbfa1e26181503e6fa8), or [Light Grey Robinson](https://www.arcgis.com/home/item.html?id=16b9a813a70043199c83db7a5840a5f7)) the coordinates do not convert properly.

### Repo Steps or Enhancement details
<img width="641" alt="coordinates" src="https://user-images.githubusercontent.com/3111563/27612558-1858a112-5b65-11e7-8239-745b4f22dc9b.png">

**Comment by topowright** [comment]
@kgonzago @adgiles was this addressed with current fixes for the WAB version?

**Comment by adgiles** [comment]
@topowright yes

**Comment by topowright** [comment]
closing this issue based on the fixes that @adgiles  made to the WAB updates.
