### ISSUE TITLE
ERG - Filter and Sort Facilities

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#921]
### Widget
ERG

### Version of widget
1.1?

### Bug or Enhancement
Filter/Sort facilities

### Repo Steps or Enhancement details
Currently, there doesn't seem to be much rhyme or reason to the order in which the facilities tab populates. Suggest defaulting to distance from the incident, but offering the abilities to filter and sort by:

Filter:
- Type
- Geographic Area
  - Isolation Zone vs. Protection Zone
  - Political Boundary
  - Assignment _(GRG and ERG together?!?!)_
Sort:
- Distance from Event
- Size

**Comment by csmoore** [comment]
This issue was moved to ArcGIS/defense-solutions-proofs-of-concept#3
