### ISSUE TITLE
Visibility - Observer Height Measurement Default

### ISSUE THREAD

**Issue by joebayles** [Esri/solutions-webappbuilder-widgets#922]
### Widget
Visibility
### Version of widget
2.0
### Bug or Enhancement
Observer Height defaults to Kilometers
### Repo Steps or Enhancement details
Opened a brand new install of the visibility widget, observer height defaults to 2 kilometers:
![image](https://user-images.githubusercontent.com/5016557/27988748-0dd77146-63df-11e7-8c21-8a86f6eeeea2.png)

Suggest changing that to 2 meters.

#### FYI
@nfeuerstein @lfunkhouser

**Comment by topowright** [comment]
Good catch!

**Comment by adgiles** [comment]
Updated in dev branch

**Comment by lfunkhouser** [comment]
@adgiles Can you revert the change and create a branch for this change, naming it adg/#922-obs-height or something similiar. Thanks.

**Comment by adgiles** [comment]
@lfunkhouser change reverted and branch created, PR #923 waiting to be verified

**Comment by adgiles** [comment]
Please can somebody verify

**Comment by csmoore** [comment]
This issue was moved to Esri/visibility-addin-dotnet#226
