### ISSUE TITLE
Network Trace - No summary and result text for polygon results

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#93]
If a result is a polygon result, the options to set the summary text and display text

![image](https://cloud.githubusercontent.com/assets/2707285/6838213/20014716-d32c-11e4-828b-e5ca9976b084.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Summary text and display text is not applicable for output parameter which has been set as Outage Area in Outage panel. Therefore, we are not displaying these two fields for output parameter which has been set as Outage Area. For all the other parameters, Summary Text and Display text are applicable.
Also, only output parameters of type Polygon can be set as Outage area parameter in Outage panel

In the screenshot above, the "Logger_Coverage_Area" parameter must have been the only output parameter of type polygon and hence is automatically selected as Outage parameter in Outage panel. Therefore, the SummaryText and DisplayText fields are not displayed for "Logger_Coverage_Area".

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS The above explanation is no longer valid, once #95 is implemented. 
As we are redesigning Outage section of config UI, we would  now be implementing the similar experience for all the output parameters(of type polygon, point, polyline).

**Comment by MikeMillerGIS** [comment]
verified
