### ISSUE TITLE
Smart Editor - Creating new Feature and Related Records actions

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#930]
### Widget
Smart Editor
### Version of widget
2.5
### Enhancement
On new feature creation, with no related records
- [ ] Ability to add a record (use global id from parent feature)
- [ ] (optional) Actions in parent feature can cause automatic creation of related record
Then follows flow of #929

**Comment by MikeMillerGIS** [comment]
The feature action for Smart Editor has been implemented in 5.3.  I will email the code slated for release.
