### ISSUE TITLE
Smart Editor - Read Only Features with Ability to Create Related Records

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#931]
### Widget
Smart Editor
### Version of widget
2.5
### Bug or Enhancement
Read only layer but rights to create related records
-[ ] From pop up, can create related record. Only related record attributes show in attribute inspector

**Comment by MikeMillerGIS** [comment]
When traversing a relationship in the Pop up
  - Should there be a feature action on the related table pop up to load all related records to the SE
  - Feature action should be on the related records pop up to load the SE
