### ISSUE TITLE
Smart Editor - Populating Feature Attributes from other sources (Intersection)

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#932]
### Widget
Smart Editor
### Version of widget
2.5
### Enhancement
Intersection of underlying features in the map
- [ ] Predefined in the config for layers and field mappings
- [ ] After feature has been sketched, intersect layers to get value and populate attribute form fields.
- [ ] If intersected layer has 1+ records, take values from last record
- [ ] If multiple layers has the same attribute, last intersected layer will transfer its value

**Comment by MikeMillerGIS** [comment]
Add new icon to the fields to define the intersection fields.  Add rank for the rank for layers, so if a field can get a value from more than one layer, the rank will determine which value will win
![image](https://user-images.githubusercontent.com/2707285/30491184-7f56d8aa-9a0a-11e7-90c7-bf002287c970.png)
