### ISSUE TITLE
Smart Editor - Geocoding Addresses

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#935]
### Widget
Smart Editor
### Version of widget
2.5
###  Enhancement
New feature created, populate the address field if they exists.
- [ ] Use selection or intersect as first option to get address. If no address info, then this option.
- [ ] Geocoder mappings defined in the config
- [ ] Geocode the address of the digitized point (only) and add address information to the attribute fields

**Comment by MikeMillerGIS** [comment]
We should try to pull the list of valid geocoders from the search widget.  If the widget is not configured, we should only show the portals default.  If the user changes the search dijit and the SE uses one of those items, the smart editor should use the updated settings.  If the item does not exist, we should raise an error on loading the smart editor that the search was modified and the following settings need to be changed in the smart editor config

I would rather not have to recreate the search settings in the smart editor.  Of if we do, we need to be able to import from teh search widget to pull in its all its settings
