### ISSUE TITLE
Smart Editor - Attachments Enhancements

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#936]
### Widget
Smart Editor
### Version of widget
2.5
### Enhancement
- [ ] Make the attachment required or hidden based on smart actions of other fields
- [ ] Ability to replace attachments (Right now users can only add or delete)

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS 

Below is the mockup for replacing attachments.
Please let us know your views.

![image](https://user-images.githubusercontent.com/2959186/29971330-7af12628-8f45-11e7-9b24-8c3da1cfbd9b.png)

**Comment by previnWong** [comment]
Looks good, I like the icon.  Only comment is can the functions be left or right justified so it all lines up.
![image](https://user-images.githubusercontent.com/11183838/29975193-5f1a27b6-8eea-11e7-997d-6d99d8675219.png)
or (with row background color distinction)
![image](https://user-images.githubusercontent.com/11183838/29975251-87801c1a-8eea-11e7-9130-a877eecd960b.png)

**Comment by MikeMillerGIS** [comment]
Also need to think about how this will work on a device.

**Comment by MikeMillerGIS** [comment]
- Cannot update an existing attachment in the JS API, requirement for that is not valid

**Comment by MikeMillerGIS** [comment]
![image](https://user-images.githubusercontent.com/2707285/30492187-ab710ebc-9a0d-11e7-9ae3-515c13243651.png)
