### ISSUE TITLE
Smart Editor - Default values for presets

### ISSUE THREAD

**Issue by previnWong** [Esri/solutions-webappbuilder-widgets#937]
### Widget
Smart Editor
### Version of widget
2.5
###  Enhancement
- [ ] Set default preset values in the config so values can be loaded at load.  Right now, if you decide to use presets, the form fields are empty and require user input.

**Comment by CTLocalGovTeam** [comment]
@previnWong @MikeMillerGIS 

For preset, our approach is to provide a textbox (dropdown for domain values)  in the config itself (replacing checkbox). If the textbox is blank then preset will not be displayed on widget screen. If the user specifies any value in the textbox then on the widget screen, preset values will be displayed. (Mockups attached)

Please let us know your thoughts.

![image](https://user-images.githubusercontent.com/2959186/29971099-bce355e8-8f44-11e7-9315-18210a77db72.png)

**Comment by previnWong** [comment]
@CTLocalGovTeam I don't think that will work.  The default value in the preset should be optional for the admin to provide, other times, it might be blank to start with.  So it has to be some combo of checkbox and text field (or value picker - see group filter).  maybe a combo box since the space is limited.  with "no preset", "user input" as the first two values, and then typing in a value will act as a default preset (see Batch Attribute Editor run time for this similar type of behavior).
