### ISSUE TITLE
Network Trace - Saving the Overview should be optional

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#94]
No option to not save the overview

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Saving the Overview (Outage area parameter) is optional. The output parameter selected as Outage area parameter in Outage panel is also present in the Output panel, where there is a "Save to Layer" checkbox which controls whether the Outage area will be saved or not.

Also, as per #95 (Redesign of Overview), this setting would be moved to Outage panel as Outage area parameter would not be an output parameter from GP Service

**Comment by MikeMillerGIS** [comment]
verified
