### ISSUE TITLE
Move Distance and Direction widget to Distance and Direction repo

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#941]
- [x] Move associated code to https://github.com/Esri/distance-direction-addin-dotnet
- [x] Move associated open issues to https://github.com/Esri/distance-direction-addin-dotnet

**Comment by csmoore** [comment]
I don't have write permissions on this repo - but I am working on this so please assign to me.

**Comment by csmoore** [comment]
This is complete
