### ISSUE TITLE
Move Visibility widget to Visibility repo

### ISSUE THREAD

**Issue by lfunkhouser** [Esri/solutions-webappbuilder-widgets#943]
- [x] Move associated code to https://github.com/Esri/visibility-addin-dotnet/issues
- [x] Move associated open issues to https://github.com/Esri/visibility-addin-dotnet/issues

**Comment by csmoore** [comment]
This is complete 

Note: WAB issues were tagged with "V- WAB" in the repo - https://github.com/Esri/visibility-addin-dotnet/issues?q=is%3Aissue+is%3Aopen+label%3A%22V+-+WAB%22  - feel free to change this if you'd prefer some other convention
