### ISSUE TITLE
Visibility Input Point Schema - Radius 1 & 2 set as short int

### ISSUE THREAD

**Issue by adgiles** [Esri/solutions-webappbuilder-widgets#945]
### Widget

Visibility (corresponding GP Service)

### Version of widget

All

### Bug or Enhancement

The two fields Radius1 and Radius2 in the input point schema are set to number type short int which works fine until you want do perform a viewshed over 32,767 meters (which I know is a long way out for visibility) but users may want to for particular use cases.

When the python script runs it will try to calculate the input values to the Radius1 and 2 fields, if these values are larger than the field type the tool will fail.

This is an easy fix, just requires the field types to be change to long int

**Comment by csmoore** [comment]
This issue was moved to Esri/visibility-addin-dotnet#225
