### ISSUE TITLE
Read/write stored geocoding results

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#946]
**I receive updated files each quarter that I need to process with this widget. These files commonly have the same addresses with slightly modified attribute values. I use the World Geocoding service provided by Esri and I don't mind using credits for the initial locating of these features but would like a way to simply update the attributes without having to re-geocode every address each time I receive data updates. When I try to review the updated file manually prior to processing with this widget it is easy for me to overlook certain things leading to unintended errors in the final dataset.**

_As a part of the work for this widget we will support the idea of storing and re-using the results of a geocode operation. The first time they attempt to geocode an address the address and returned location will be stored in a file. The next time they attempt to locate that same address the location will be returned from the file where it was stored previously._

**Config:**
- [ ] Allow user to choose if the concept of stored results will be enabled
- [ ] Allow user to choose between storing on a server location or within the organization
- [ ] Allow user to choose a group it will be shared with if storing in organization
- [ ] Allow user to define a server location where it will be stored when not using the organization

**Runtime:**
- [ ] Ensure that the file is stored in the organization and shared with the appropriate group when organization option is used
- [ ] Ensure that the file is stored in the appropriate server location when the server option is used
- [ ] Ensure no additional credits are used when re-geocoding the same addresses using the World Geocoding service when the store options are enabled

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
We would like to evaluate if the "duplicate feature" logic could be used here rather than using a physical file.

**Comment by jmhauck** [comment]
This is tied to #954 

The idea is to determine if the feature service we are writing the results to already contains a given feature. If it already contains the given feature then no need to geocode or store the geocode result.

**Comment by jmhauck** [comment]
Moving this issue to the backlog as we decided to move forward with the concept of checking for duplicates from the destination layer rather than a separate file.

**Comment by aparveen** [comment]
This issue in not a concern anymore.
