### ISSUE TITLE
Add options for providing addresses

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#947]
**As a user of this widget I would like to have options for supplying addresses. For example when I am working on my Desktop I would like to be able to simply click/drag a file from my file system. When I am working on my tablet I would like to be able to browse to a file. In some specific situations I would also like to be able to manually enter an address and the appropriate field values.**

_The goal of this issue is to add support for each of the 3 defined options._

- [x] Support drag/drop onto the widget or the map
- [x] Support browse to file
- [ ] Support manual address entry

**The initial page should look like this when the widget first opens:**
![image](https://user-images.githubusercontent.com/2170893/29689485-980b2152-88e0-11e7-97f9-b48f9eee3d43.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
The UI is there...but they do not actually feed into the locator yet.

**Comment by jmhauck** [comment]
With the exception of the "Support manual address entry" that we decided to move away from this is complete.

**Comment by NikkiGolding** [comment]
Verified.
