### ISSUE TITLE
Create dijit for navigating through the workflow

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#948]
**As a user of this widget I need to be able to intuitively navigate between the various tasks involved in the workflow.**

_The goal of this dijit is to allow the user to quickly navigate forward, backward or to a home location. Internally it will accept a collection of pages for each of the key parts of the workflow._

- [x] Leverage the 'jimu/dijit/ViewStack' dijit somewhat like the tab container does
- [x] Support navigation in a forward or backward direction between pages
- [x] Support navigation to a defined "home" page

It should look like this:
![image](https://user-images.githubusercontent.com/2170893/31294288-87c2d870-aa97-11e7-94d3-0a08924696c8.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
The way I have started this is leveraging the 'jimu/dijit/ViewStack' somewhat like the tab container does. It will allow for a modular design. Logical chunks of code and html will be created for the key parts of the workflow:
 1) Start Page (for browse, drag drop, or manual input) 
 2) Location Type (for choosing between Address input or Coordinate input)
 3) Addresses (for options associated with single or multi field address types)
 4) Coordinates (for options associated with coordinate value input)
 5) Field Mapping (for review or definition of the appropriate field mapping)
 6) FeatureList (for reviewing the lists of features that are matched, un-matched, or potential duplicates ) 
 7) Feature (for review of mapped field information or feature geometry edit)

**Comment by jmhauck** [comment]
Awhile back I wanted to ensure that I had not overlooked an existing dijit that would already handle this and reached out to the AWAB team. They confirmed that one does not currently exist and asked if we would add to the jimu library.

**Comment by jmhauck** [comment]
This should be good and I think new issues associated with proper flow should be logged seperately from this.

**Comment by NikkiGolding** [comment]
Verified- Enhancements logged to refine.
