### ISSUE TITLE
Support download to CSV

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#949]
**After I have located all the features from my file and handled the field mapping I would like to be able to download a copy of the data for use in other internal business workflows that will not leverage the final service the data was submitted to.**

The download button in the mockup below should become active after I have completed the 2 key steps of locating the features and mapping the fields:

![image](https://user-images.githubusercontent.com/2170893/29690096-cd6f40f6-88e2-11e7-99bc-8cc8881eb3fa.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
Need to validate when is the right time to enable download to help prevent incomplete information from being downloaded or otherwise confusing the user at this point of the workflow.

**Comment by jmhauck** [comment]
@NikkiGolding the download option is there as described in this issue and should download up to 3 separate tables for each of the categories matched, unmatched, and duplicate when they are present.

**Comment by NikkiGolding** [comment]
@jessnoo  Please Verify.

**Comment by jessnoo** [comment]
@NikkiGolding will do.  simple use case was verified yesterday, i'll work on the other two in the coming days.

- [ ] located records downloaded
- [ ] duplicate records downloaded
- [ ] not located records downloaded

**Comment by NikkiGolding** [comment]
Verified and checked off items above.
