### ISSUE TITLE
Network Trace - Redesign of Overview

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#95]
1)	Remove affected area output parameter and modify its dependent code in outage parameter in both config and widget
2)	Modify panel for Outage parameter in Config UI 
3)	Implement logic to generate overview area client side 
4)	Complete testing of this functionality
5:  Option to not generate the overview
6:  Option to save the overview, saving the overview is not required to save the other results.
7:  Rename Outage setion in the configuration panel to Overview

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will implement this and deliver in the next release

**Comment by MikeMillerGIS** [comment]
verified
