### ISSUE TITLE
Add support for Excel files

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#950]
**As a frequent user of this widget I like the overall functionality of the what this tool provides but I don't like having to deal with the extra step of first exporting the excel spreadsheets I have to CSV. It would provide a better user experience if it leveraged the native file format I am more used to interacting with.**

_Support for Excel is in addition to the currently supported CSV file type._ 

- [ ] Investigate libraries for reading excel file types with JavaScript
- [ ] Support upload from Excel
- [ ] Support download to Excel

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
This is in addition to the currently supported CSV file type. We believe many of the end users of this widget will be more familiar with and leverage native excel file types with more frequency than CSV files.

**Comment by aparveen** [comment]
Will add a new issue in devtopia.

**Comment by aparveen** [comment]
New devtopia issue has been created to track this issue.
