### ISSUE TITLE
Update UI for Field Mapping

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#951]
**I need a simple way to create an association between the fields in my file and the fields that have been exposed from the final feature service.**

_The goal of this issue is to provide an intuitive approach for schema mapping between the uploaded file and the final feature service._

**The inital page to be used immediately after file upload:**
- [x] Allow the user to choose between the two workflows they will need to complete
1) ["Location Mapping" definition of what to expect from the file: address (single or multi-field) or coordinates and what fields that information should be pulled from](https://github.com/Esri/solutions-webappbuilder-widgets/issues/952)
2) "Field Mapping" definition of what fields from the file map to what fields from the final service
![image](https://user-images.githubusercontent.com/2170893/29690340-d395e60a-88e3-11e7-8299-22f07c77ac1a.png)

**When the user chooses "Field Mapping":**
- [x] Display a jimu "SimpleTable" like the mock up below
- [x] List the alias name of the field from the feature service in the first column
- [x] Provide a select control to allow the user to choose a field from the fields in the input file in the second column

![image](https://user-images.githubusercontent.com/2170893/29690364-e5c225aa-88e3-11e7-9121-6e4501d79aa0.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
@NikkiGolding The UI is there but does not read from the config yet

**Comment by jmhauck** [comment]
@NikkiGolding this is working

**Comment by NikkiGolding** [comment]
Vefrified- enhancements logged.
