### ISSUE TITLE
Update UI for Location Mapping

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#952]
**As a user of this widget I commonly need to deal with a vairiety of addresses and coordinate information in the files I recieve. At times the full address is listed in a single field, other times parts of the address are in multiple fields, and other times they will have X/Y coordinates rather than addresses.**

_The goal of this issue is to provide a collection of pages that will guide the user through defining the options for supported address or location input types._

**The inital page to be used immediately after file upload:**
- [x] Allow the user to choose between the two workflows they will need to complete
1.	"Location Mapping" definition of what to expect from the file: address (single or multi-field) or coordinates and what fields that information should be pulled from
2.	["Field Mapping" definition of what fields from the file map to what fields from the final service](https://github.com/Esri/solutions-webappbuilder-widgets/issues/951)
![image](https://user-images.githubusercontent.com/2170893/29690340-d395e60a-88e3-11e7-8299-22f07c77ac1a.png)

**When the user chooses "Location Mapping":**
- [x] Allow user to choose between address or X/Y coordinate:
![image](https://user-images.githubusercontent.com/2170893/29690651-0cd00f1c-88e5-11e7-8d2e-f6af6ec90c00.png)

**When the user chooses to locate using an address**
- [x] Support option for single address input
- [x] Allow the user to choose from fields in the input file
![image](https://user-images.githubusercontent.com/2170893/29690663-13d576da-88e5-11e7-921e-02f7a2f474d8.png)

- [x] Support option for multi-field address input
- [x] Allow user to choose the fields that contain each of the address elements
![image](https://user-images.githubusercontent.com/2170893/29690684-27d36c14-88e5-11e7-860a-eb4e1be37592.png)

**When the user chooses to locate using coordinates**
- [x] Allow user to choose from the fields that contain coordinate information in the input file
- [x] Support coordinates geographic coordinates and need to explore other options that may already exist that are being leveraged by tools like Add Data widget so we can stay in line with AGO and or platform.
![image](https://user-images.githubusercontent.com/2170893/29690734-602d16be-88e5-11e7-83d9-42cbf14c921d.png)

**Once they have provided address or coordinate information** 
_We want to provide a clear way for them to understand when one of the steps has all the information necessary to proceed. Part of the goal with this is to help guide them through the process._
- [x] Indicate when this step is complete
![image](https://user-images.githubusercontent.com/2170893/29690696-3683c614-88e5-11e7-8fc3-0ed257ccbec4.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
@NikkiGolding The UI is there but does not read from the config yet

**Comment by jmhauck** [comment]
@NikkiGolding the UI is there and it does read from the config

**Comment by NikkiGolding** [comment]
Verified UI
