### ISSUE TITLE
Support location review and update

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#953]
**After I have converted one or more addresses into geographic features I need to be able to review the feature locations including those that are identified as matched, un-matched, or potential duplicates. I need to be able to make additional updates to the features that fall in any of the 3 categories listed above prior to submitting to the final feature service.**

_The goal of this issue is to allow the user to browse through each feature and make any necessary updates_

**Review overview page:**
- [x] Should display the number of features for each category (matched, un-matched, duplicate)
- [x] Should be able to navigate between the collections of features in each catagory
- [x] UI should have additional logic that will indicate if it is an appropriate time for submit and download rather than just enabeling automatically...possibly the use of check mark as are used when field mapping and location mapping steps are complete
   **Was thinking that Submit should not be enabled unless you have at least one record in the matched list.**
   **Was thinking that Download would always be enabled.**

![image](https://user-images.githubusercontent.com/2170893/29690982-8919c454-88e6-11e7-9bc1-ef4b10b0cd12.png)

**List page:**
- [x] Access a list of features for each category
- [ ] Access all the details for any of the features listed on this page
_Need to understand the best field to use as the display value for this page. For example the mockup below shows something from a sample Name field but we will need to know the best field to display here that has a value that can be used to uniquely identify one record from the next._

![image](https://user-images.githubusercontent.com/2170893/29690986-8fccf794-88e6-11e7-88ae-a7312924c5bb.png)

**Matched record update page:**
- [x] Modifiy field values that have been derived from the source CSV
- [x] Modify the geocoded location if necessary
- [x] If the fields containing address information are modified the user should have an option to re-locate the modified address

![image](https://user-images.githubusercontent.com/2170893/29690994-9909ae9c-88e6-11e7-833f-d0c3016bbbdc.png)

**Un-matched record update page:**
- [x] Modify field values that have been derived from the source CSV
- [x] Manually place a point if necessary 
- [x] If the fields containing address information are modified the user should have an option to re-locate the modified address.

![image](https://user-images.githubusercontent.com/2170893/30283554-abcc87fa-96d5-11e7-8d45-49ccdee0cdd6.png)

**Duplicate record update page:**
[When a feature falls within a defined proximity of another feature already in the final feature service it should be identified as a potential duplicate](https://github.com/Esri/solutions-webappbuilder-widgets/issues/954). 

- [x] Choose between keeping the geometry or field values from either the final feature service, the CSV or both if they are deemed to not be duplicates

![image](https://user-images.githubusercontent.com/2170893/29691143-362455a6-88e7-11e7-9ae3-038dee735547.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
@NikkiGolding I am starting to wonder if we should have multiple symbols. So it is easy to tell the difference between matched, un-matched, and duplicate in the map.

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo the work for this comment is not complete:

"UI should have additional logic that will indicate if it is an appropriate time for submit and download rather than just enabeling automatically...possibly the use of check mark as are used when field mapping and location mapping steps are complete"

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo 

"Access all the details for any of the features listed on this page
Need to understand the best field to use as the display value for this page. For example the mockup below shows something from a sample Name field but we will need to know the best field to display here that has a value that can be used to uniquely identify one record from the next."

We should discuss this. Right now it's using the first field that is set to display from the configured destination layer fields.

**Comment by jessnoo** [comment]
@jmhauck 

for the first release, i think it's ok to use the first field in the fields list for presentation in the widget.  this is something we can document and is unlikely to cause issues for users.  

based on my review today, i think we can close this issue as implemented and address problems through new issues (which i have been submitting separately).
