### ISSUE TITLE
Handle duplicate features

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#954]
**As a frequent user of this widget I get data once each quarter that I need to use to update the final feature service. This data will commonly contain the same addresses but have slightly modified attribute values. I don't always know up front when my file contains addresses that have already been located and submitted to the final service. I need help identifying potential duplicates between my input file and the final service and intelligent options for dealing with them.**

_During our call today we discussed the possibility of needing to add support for additional considerations when handling potential duplicates. This issue is to continue and record that discussion._

**Config:**
- [ ] Accept a user defined search distance that will be used for identification of potential duplicates **REMOVED REQUIREMENT**
- [x] Allow the user to identify key field(s) that can be used to help uniquely identify potential duplicates in addtion to proximity with existing features in the final service

**Runtime:**
- [ ] Add features that fall within a user defined proximity of features that already exist in the final feature service to a list for user review - **REMOVED REQUIREMENT**
- [x] Support an option to keep the newly located feature and it's field values
   **This is supported through the option "is duplicate make changes"**
- [x] Support an option to keep the existing feature from the final feature service and only update the field values using the attributes from the newly located feature
   **This is supported through the option "is duplicate make changes"**
- [x] Support an option to keep both the newly located feature and the feature from the final feature service
   **This is supported through the option "is not duplicate"**

Questions:
> Should we incorporate a "key field" in addition to identifying duplicates based on proximity
**This can now be defined through the config experience while configuring Layer Fields**

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo Using the approach we discussed of supporting the option for the destination layer to be a search source we can understand the key fields to search from that layer. However, we will need to determine the appropriate way to allow the user to specifiy what fields from the csv file are intended to be used for this comparison. This would need to be done at runtime by the end user or the user that configures would need to be aware up front about the schema of the files that will be passed in for this to be supported. We should discuss this more.

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo as I was thinking about this some more it dawned on me that at the point we need to do this comparison the end user will have already defined the field mapping. We can use that to further understand what fields should be used to compare between the file and destination layer.

**Comment by jmhauck** [comment]
Now that we can both define key field(s) and choose between keeping the new, existing, or both I believe this issue is complete.

**Comment by jmhauck** [comment]
This issue is not complete until #979 has been implemented

**Comment by NikkiGolding** [comment]
@jmhauck  looks to me like #979 is complete. yes?

**Comment by jmhauck** [comment]
@NikkiGolding yes I believe 979 is complete.

**Comment by NikkiGolding** [comment]
Ok- given that #979 is complete, and the above comment referenced that this issue wasnt complete until #979 was, I am closing this as well.
