### ISSUE TITLE
Support commit to feature service

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#956]
**As a user of this widget I need to be able to convert one or more addresses into geographic features as well as have the ability to add additional attribute information to the feature(s) and finally submit the feature(s) to a feature service.**

_The goal of this issue is to support the committing of features to the final feature service._

**Config:**
- [x] Choose a feature service from the map to write results to
- [x] Define the fields that will be exposed for the end user to provide data to
- [x] Define a list of key names for each field exposed from the service that will be auto-selected if it exists in the user input files

**Runtime:**
- [x] Choose a field from the input file that should be mapped to the corresponding field in the feature service
- [x] Choose when is appropriate to make the final commit of the features to the service
- [x] Successfully write features and field values to the final feature service

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
The widget is responsible for three main tasks:

1) Geocoding of 1-n features
2) Providing a mechanism for mapping fields between a file and the final feature service that will be updated.
3) Comitting the features with the user defined field mapping to the feature service.

As a part of the configuartion:
 - the user should be able to select a feature service from the map.
 - define what fields will be exposed for the end user to provide data to
 - provide key names that can be automatically chosen from user input files if they exist

At runtime after a file or address has been provided and geocoded:
 - choose fields from the input file that should be mapped to the appropriate fields in the feature service
 - choose when is appropriate to make the actual commit of the features to the service

**Comment by jmhauck** [comment]
Need to ensure that we have error trapping and messaging to the user to indicate what problems arose.

**Comment by NikkiGolding** [comment]
Verified- Enhancements logged.
