### ISSUE TITLE
Support field updates for manually entered addresses

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#957]
**As a user who has manually entered an address, rather than starting with addresses in a file, I can provide values for the fields exposed from the final service.** 

_In general we think this manual workflow will mainly be used by mobile users but it will be an option for both mobile and desktop users._

- [ ] [Support manual entering of address](https://github.com/Esri/solutions-webappbuilder-widgets/issues/947)
- [ ] Show empty editable controls for entering values for all fields exposed from the final feature service 
- [ ] [Support submit to final feature service](https://github.com/Esri/solutions-webappbuilder-widgets/issues/956)

**When the user has manually entered an address and located the feature they should be presented with a page that looks like this:**
![image](https://user-images.githubusercontent.com/2170893/29691648-3089908c-88e9-11e7-83b0-133777e6b5c8.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
One option for starting a workflow with the widget is to allow the user to manually type in an address rather than browsing to or drag/drop of a file. In general we think this will be useful to mobile users of the widget to allow for a similar path to geocode an address and then submit the geocoded result to the defined feature service while allowing them to enter approriate values for the fields that have been exposed.

**Comment by jmhauck** [comment]
Moved to the backlog as we decided not to move forward with single manual address input

**Comment by aparveen** [comment]
Same as the manually entered address issue, will consolidate these two and create a new issue in devtopia.

**Comment by aparveen** [comment]
A new issue is created in devtopia.
