### ISSUE TITLE
Support use on mobile device

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#958]
**As a mobile user I still have the basic need of wanting to convert one or more addresses into geographic features as well as have the ability to add additional attribute information to the feature that will be submitted to the final service. However, I only want to see options that apply to me based on the device I am using.**

_The goal of this is not only to provide clear expectations for how they can interact with the widget but also to allow them to utilize parts of the workflow that could still make sense._ 

- [ ] Implement the standard [input type="file"](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/file) control for file upload. 
The link above can be used to test the basic experience of file browsing from any browser/OS.
More details on supported browsers can be seen [here](https://caniuse.com/#search=file%20input).
- [ ] Utilize jimu utils detectUserAgent function to understand the OS and browser
- [ ] For mobile OS avoid mentioning anything about drag/drop in widget UI

**When drag/drop is not supported but file system access is:**
- [ ] Support browse to file
- [ ] Support geocoding of input
- [ ] Support field mapping
- [ ] Support manual entering of an address and field values
- [ ] Support submit to final feature service
![image](https://user-images.githubusercontent.com/2170893/29691788-dac58344-88e9-11e7-8fdd-02ab5c3df2dc.png)

**When drag/drop and file system access is not supported (rare case):**
- [ ] Do not show file input control when the browser does not support file input
Main limitations where no file upload support options at all are Opera Mini and Android browser.
- [ ] Only support manual entering of an address and field values
- [ ] Support submit to final feature service
![image](https://user-images.githubusercontent.com/2170893/29691792-deae5d78-88e9-11e7-997c-75641fa8e613.png)

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo

**Comment by jmhauck** [comment]
The main goal of this issue is to ensure that the UI reflects only the operations supported for the given platform. For example it does not make sense to click/drag on a mobile device and if we don't have access to the file system the user should not have an option to browse. We want to ensure that the intended workflow of interacting with the widget is clear regardless of the device they are on.

**Comment by aparveen** [comment]
Will add a new issue in devtopia and wait for user feedback.

**Comment by aparveen** [comment]
New issue created in devtopia to track this issue.
