### ISSUE TITLE
Add support for geometry types other than point

### ISSUE THREAD

**Issue by jmhauck** [Esri/solutions-webappbuilder-widgets#959]
This is another discussion topic that needs additional details about the requirements. 

I do not have a clear understanding of the specific needs in this area.

**Comment by jmhauck** [comment]
Could be based on the idea of just updating attributes rather than being based on the geometry.

The expected inputs would be an excel spreadsheet.

Getting at the idea of data aggregation and service updates

**Comment by aparveen** [comment]
Will add a new issue in devtopia.

**Comment by aparveen** [comment]
New issue has been created in devtopia to track this.
