### ISSUE TITLE
Network Trace - Default Highlighter image

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#96]
Add a default highlighter image

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We can add a default highlighter image. We have following two options to specify the default image:
1. First image in images\ani folder of the widget
2. Any absolute path or URL

Please advise.

**Comment by MikeMillerGIS** [comment]
Can we rename one of the images default and just use that?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We can do that. We can rename the images\ani\Cyanglow.gif to images\ani\default.gif and pick that image. Is this ok ?

**Comment by MikeMillerGIS** [comment]
Perfect

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will rename the images\ani\Cyanglow.gif to images\ani\default.gif and deliver in the next release

**Comment by MikeMillerGIS** [comment]
verified
