### ISSUE TITLE
CF: Drag and drop onto widget causes Save As dialog to open

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#967]
### Widget: Critical Facilities

**Repro Steps:**

1. With test app in dev ext: [Critical Facilities - Emergency Shelters](http://sg-em-devext.mapsdevext.arcgis.com/apps/webappviewer/index.html?id=046a59f0a1e04f7d920a04fd9bc2734a)
2. Drag a .csv file and drop it onto the widget panel  >> A save as dialog opens

**Expected behavior:** I would begin the workflow
**Ideal Minimum Ship:** Receive message that the file needs to be dropped on the map, not the widget.  Also update instructions to reflect that

**Alternate Test:**

1. With same app, drag and drop CSV onto the map >> workflow begins as expected

**CSV Tested With**
[MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1480585/MarylandHospitals.zip)

**Comment by jmhauck** [comment]
Need to test again on this and come up with a repro case that is not on devext

**Comment by NikkiGolding** [comment]
@jmhauck  I am unable to repro this now.

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo this only seems to happen in certain circumstances. 

1) Configure the application to use the foldable theme
2) Place the DA widget in the themes controller
3) Minimize the browser so the placement of the widget is adjusted like the following:

![image](https://user-images.githubusercontent.com/2170893/35591981-e45d19a6-05c8-11e8-9167-a955eb5ca9b4.png)

4) Click and drag the csv over the widget
 * note you see the save as issue as described by this issue

When I tested the same general behavior was observed across Chrome, Firefox, and IE

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo ready to be validated

**Comment by NikkiGolding** [comment]
Verified
