### ISSUE TITLE
CF: After i finish reviewing all matched locations, don't know what to do next

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#968]
After reviewing the locations that were matched successfully -- using the Next > button, when i get to the end of the list, I'm not sure what to do next -- 

- If the home button is going to turn into a "Start Over" button, need to think of a short cut way to get the user back to the place where they can click the submit button. 
- Next takes you to the next item in the list, back takes you back to the list

![criticalfacilities_review_next](https://user-images.githubusercontent.com/6181441/32921459-85cdc7da-cae2-11e7-96ba-bb403769573b.gif)

**Comment by jmhauck** [comment]
The commit above will allow you to return to the review page (where you see all the lists for matched, unmatched, or duplicate) when you click next on the last feature in a list. However, some additional changes are required to handle this logically when features are added or removed from lists.

**Comment by jmhauck** [comment]
Some additional changes are still required to handle this logically when features are added or removed from lists such as when I duplicate fetaure is marked and "is not duplicate" or when an unmatched feature has been located and saved.

**Comment by NikkiGolding** [comment]
@jmhauck  Per your note above, are the required changes you referenced complete?

**Comment by jmhauck** [comment]
@NikkiGolding while double checking this issue this morning I did notice one other issue when features were added or removed from lists that I made an update for.

So for this issue when you get to the end of a given list of features you should be taken back to the main review page that shows all of the lists. If a feature is located and moved between lists you should be taken to the next feature in the current list.
