### ISSUE TITLE
Network Trace - Highlighter image browse to default location

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#97]
Is it possible to default to the highlighter image folder

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are investigating on implementing this using ImageChooser widget.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We have analyzed ImageChooser widget and we could not find any way to default to a particular folder path.

**Comment by MikeMillerGIS** [comment]
closing
