### ISSUE TITLE
enable "field names to recognize" to do a 'contains' query 

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#970]
Rather than requiring an exact match for the "Field name to recognize" query, can we do a contains or like query?

for example -- for a phone number field, here are my configured Field Names to Recognize: 
![image](https://user-images.githubusercontent.com/6181441/32921796-e03fd702-cae3-11e7-9012-a528f203bce6.png)

My CSV field name is `Facility_Phone` -- it'd be very useful for the configuring organiation if the widget could search within the field name string for a key word rather than requiring an exact match for this use case.

**Comment by aparveen** [comment]
Will add an issue in devtopia.

**Comment by aparveen** [comment]
New issue created in devtopia to track this.
