### ISSUE TITLE
sometimes widget content runs off the page

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#971]
with this test app in DEV: [Critical Facilities - Emergency Shelters](http://sg-em-devext.mapsdevext.arcgis.com/apps/webappviewer/index.html?id=046a59f0a1e04f7d920a04fd9bc2734a)
with this CSV: [MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1480621/MarylandHospitals.zip)

after the data are geocoded and the user enters the review process, the widget panel has to be scrolled horizontally to see the whole name and clickable arrows:

could the values word wrap in their row?
![image](https://user-images.githubusercontent.com/6181441/32922059-405d3fc0-cae5-11e7-9391-a42b853d19fd.png)

**Comment by NikkiGolding** [comment]
Verified.
