### ISSUE TITLE
Bump up text size in widget main panel instruction

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#972]
not sure if this is already captured somewhere -- this text is very small and important:

![image](https://user-images.githubusercontent.com/6181441/32922283-4e87cba0-cae6-11e7-9619-bdf3ff079d89.png)

could we bump it up?  

future enhancement would be to enable the configurer to set the text content, etc like the about widget...

**Comment by jmhauck** [comment]
Moved to issue [12859 ](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12859)in devtopia

**Comment by jmhauck** [comment]
logged a seperate issue [12860](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12860) for the comment regarding the future enhancement to make this test configurable.
