### ISSUE TITLE
UI arrows / Navigation Inconsistent

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#973]
it feels weird to me that i have arrows that allow me to dive into something specific without using the Next button in some locations but not others.

**Main Panel (after file submitted): Arrows**
![image](https://user-images.githubusercontent.com/6181441/32922462-23a79b44-cae7-11e7-8103-2143e8aaba8d.png)

**Choose Address Type: No Arrows**
![image](https://user-images.githubusercontent.com/6181441/32922396-e0148126-cae6-11e7-902a-0c08f727c83f.png)

**Review Panels: Arrows**
![image](https://user-images.githubusercontent.com/6181441/32922370-c32af766-cae6-11e7-8390-e1932a295422.png)

**Next vs Done**
In other instances -- it seems like the Next Arrow should say "Done" "Complete" or something -- because you are driven back to the "main panel" -- for example:

After setting up the location settings -- Next means "this workflow is done, go back to the main panel and choose a different workflow"
![image](https://user-images.githubusercontent.com/6181441/32922497-4c9f40f6-cae7-11e7-8768-fde60e4e8c72.png)

**Comment by jmhauck** [comment]
moved to devtopia issue [12863](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12863)
