### ISSUE TITLE
"Review matched" panel language

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#974]
Proposed words, descriptions for the the panel that shows up after you click "Add to Map" (Main Review Panel)

![image](https://user-images.githubusercontent.com/6181441/32922722-7abe3806-cae8-11e7-9314-53e037fe59c9.png)

_Panel Title_

**Review Data**
Review your data before submitting to the target layer

_Panel Sub-Workflows (?)_

**Locations Found**
Review locations which were found 

**Locations not Found**
Review locations which were not found on the map.   Items that are not corrected will not be submitted. 

**Duplicate Locations**
Review locations that were already found in the target layer.  Items that are not addressed will not be submitted. 

- rather than using target layer, can we use the layer name like is on the first panel?
- if the user does not review unmatched or duplicate locations - will those items be skipped when submitting?  If yes, we should indicate that in the UI -- this is included in the suggestions above.

**Comment by jessnoo** [comment]
related #964

**Comment by jmhauck** [comment]
@NikkiGolding and @jessnoo 

Only question I have is if we wanted to change the order the lists are displayed. I believe we have discussed that before. For example, review “Locations not found” first, “Duplicate locations” second and “Locations found” last

**Comment by jmhauck** [comment]
@NikkiGolding @jessnoo nevermind, that is question is outlined in #981

**Comment by jmhauck** [comment]
moved to devtopia issue [12861](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12861)
