### ISSUE TITLE
Config panel: Setting headings

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#975]
in the configuration panel, we should add proper names for the settings, not simply hint text.  This will help when communicating about an aspect of the configuration -- if we don't call it something, how does anyone know how to refer to it?

![image](https://user-images.githubusercontent.com/6181441/32959766-8c04be7a-cb77-11e7-8795-cabc8bf2f45a.png)

**Recommendations:**  Setting name _(hint text)_
- Target layer _(Choose the target layer for data aggregation)_
- Display symbol _(Choose a symbol for the temporary display layer)_

@NikkiGolding fyi for doc -- there are no setting titles for the first two parameters, so there's not an easy way to identify them in the doc

**Comment by jmhauck** [comment]
@NikkiGolding this seems similar to what you had mentioned and put in the box document for some changes to the settings page

**Comment by NikkiGolding** [comment]
@jmhauck  Yes, please hold for now on any changes to the config UI.

**Comment by jmhauck** [comment]
logged in detopia issue [12862](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12862)
