### ISSUE TITLE
Target Fields- High

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#978]
All target fields for a feature (eg: address information)  should be displayed in the UI  even when no source field was chosen in the Source/Target options

**Comment by jessnoo** [comment]
This applies to both Field Information and Location Information sections of the Review panel

**Comment by NikkiGolding** [comment]
This issue is complete and ready to be validated.

**Comment by jessnoo** [comment]
verified
