### ISSUE TITLE
Feature Persistence

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#979]
All save operations should store the feature information in the feature collection  (the temp stage layer) rather than saving directly to the feature service.  The user should have one submit operation that pushes all information up to the feature service at once.

FYI @jmhauck @jessnoo

**Comment by jmhauck** [comment]
the work for this has been started in the data-aggregation-dev-save branch.

**Comment by jessnoo** [comment]
This issue is being left open due to repro steps documented in #977

**Comment by NikkiGolding** [comment]
@jmhauck @jessnoo is the core need here addressed? If so, we should close this issue and move any additional issue tracking to separate issues.

**Comment by jmhauck** [comment]
@NikkiGolding I believe this core capability has been addressed and that this issue can be closed. @jessnoo please let me know if you think otherwise.

**Comment by jessnoo** [comment]
closing
