### ISSUE TITLE
Network Trace - Field Name/Parameter - Overview Area

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#98]
The formatting is not correct
![image](https://cloud.githubusercontent.com/assets/2707285/6848428/9457a57a-d3a3-11e4-87f9-5e55146d32c4.png)

**Comment by MikeMillerGIS** [comment]
I am not able to set a polygon output as a parameter(a separate output, not the overview)
![image](https://cloud.githubusercontent.com/assets/2707285/6849375/408e6220-d3a9-11e4-948f-036a79a3a6aa.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We will investigate and fix this in the next release

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Can you please provide a GP Service with two polygon output parameters for reproducing this issue?

**Comment by MikeMillerGIS** [comment]
I emailed the URL Friday.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We checked our emails and could not find it. It may happen that our email server rejected it because it contained just a URL and a small amount of text. Can you please resend it?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We are not able to reproduce the issue related to formatting. Following is the screenshot:

Screen Resolution: 1980X1080
![untitled](https://cloud.githubusercontent.com/assets/2959186/6964066/6d598d60-d963-11e4-9127-c7d63da40799.png)

Screen Resolution: 1366X768
![loggerplanner gp service](https://cloud.githubusercontent.com/assets/2959186/6964050/45411aaa-d963-11e4-8a46-e7efe6106063.jpg)

**Comment by MikeMillerGIS** [comment]
I am still getting this issue
![image](https://cloud.githubusercontent.com/assets/2707285/7399850/b0ea147c-ee86-11e4-8665-78a3e5d52d20.png)

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS We haven't provided any fix for this issue as we are not able to reproduce this yet. Can you please let us know the environment details e.g., screen resolution, browser version, OS version.

**Comment by MikeMillerGIS** [comment]
Windows 7, Chrome Version 42.0.2311.135 m, 1920x1080,

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, We tested with the same environment and still unable to reproduce this. Is this consistently being reproduced on your side? We'd like to try to reproduce this with an app published on your side. Can you please publish an app and share the link with us?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS, we tried using the gpservice that you provided after the call last week and still not able to reproduce this. Can you please share the widget's config.json and the webmap too?

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS As the UI for Save summary options is to be updated as discussed in issue #139, we feel that this issue will no longer be reproduced. We will not make any code changes to fix this issue. We can verify this in next release with the updated UI. 

![capture](https://cloud.githubusercontent.com/assets/2959186/7453677/59e47134-f289-11e4-9f3e-c5e4ef358356.PNG)

**Comment by MikeMillerGIS** [comment]
ok, closing for now
