### ISSUE TITLE
UI Text/Placement Updates - Low

### ISSUE THREAD

**Issue by NikkiGolding** [Esri/solutions-webappbuilder-widgets#981]
- [ ] rather than match/unmatched/duplicate
 
- [ ] The text should be "Locations Found" "Locations not found" and "Duplicate Locations found"

- [ ] Start Page 

- [ ] Move the hint text below the action item for Location Information and Field Information

- [ ] Panel title instructions 

- [ ] Use the text from the previous panel in bold and make the  font larger and  then show hint below

- [ ] Review matched should be listed last review un-matched first - Note text should reflect change above
 
- [x] need a tootip for pencil and save
- [ ] Need a better tooltip for Duplicate Features

FYI @jessnoo @jmhauck

**Comment by jmhauck** [comment]
moved to devtopia issue [12861](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12861)
