### ISSUE TITLE
Geocoding options

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#982]
add check boxes to these to provide a visual on the main config page on whether they have been configured or not

Do not set up any options as default, ensure the customer explicitly sets the options as part of their worklow

Disable the OK button on the config panel until one of the options is enabled

![image](https://user-images.githubusercontent.com/6181441/32963068-9fecae5a-cb83-11e7-944d-fe1113c39efd.png)

The runtime experience will reflect differing options depending on what is enabled in the config experience. 

@NikkiGolding fyi

**Comment by jmhauck** [comment]
@NikkiGolding ready to be verified

**Comment by NikkiGolding** [comment]
Verified.
