### ISSUE TITLE
Change X Y default alias

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#983]
Consider changing the default alias to also indicate Lat Lon -- as the end user may not be able to easily identify which goes with which if their fields are called LAT and LON

![image](https://user-images.githubusercontent.com/6181441/32965056-30b4497e-cb8a-11e7-9a75-6fa75cbca869.png)

**Recommendation**
X Alias: X (Longitude)
Y Alias: Y (Latitude)

**Comment by jmhauck** [comment]
Moved to devtopia issue [12858](https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/12858)
