### ISSUE TITLE
Review list - Next button behavior

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#984]
After opening the list of matched locations - clicking the Next button takes me to the "not matched" list, but i expected it to show me the first item in the list.

wanted to make sure that was the correct behavior and see if there was a workflow map for all the next buttons given the current panel shown.

**Comment by jessnoo** [comment]
@NikkiGolding fyi

**Comment by jmhauck** [comment]
@NikkiGolding this should no longer be the case.
