### ISSUE TITLE
When editing an item, "cancelling" edits doesn't work as expected

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#985]
[Test app ](http://sg-em-devext.mapsdevext.arcgis.com/apps/webappviewer/index.html?id=046a59f0a1e04f7d920a04fd9bc2734a)(ask to reset service if needed)
Test file: [MarylandHospitals.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1483679/MarylandHospitals.zip)

**Repro Steps**
1. with the app in runtime mode, upload a CSV and enter into reviewing matched locations
2. Click to edit the location
3. Change a value (can't move the location - expected?)
4. Click the edit button again to cancel changes -- ?
5. Notice that the information is not reset
6. The values are not written when submitting, it's just that the UI doesn't update to reflect that the edits were not saved.

![cf_editing_cancel](https://user-images.githubusercontent.com/6181441/32967098-3096c91a-cb91-11e7-83b5-5efbfa689acf.gif)

**Recommendation:**
- first release: reset values in UI when the edit button is unclicked
- ideal: add a cancel changes button next to save button and grey out the edit button once it's clicked

@NikkiGolding fyi

**Comment by NikkiGolding** [comment]
@jmhauck following the repro steps below, I can still see this behavior. 

- with the app in runtime mode, upload a CSV and enter into reviewing matched locations
- Click to edit the location
- Change a value (can't move the location - expected?)
- Click the edit button again to cancel changes -- ?
- Notice that the information is not reset

**Comment by jmhauck** [comment]
@NikkiGolding you should be able to move a location after editing is enabled. When I just stepped through this workflow I could modify the location when using the file referenced in this issue. I may need more information on this but I will do some more tests.

Right now, the only thing that would clear the edits is the clicking of the cancel edits button but closing the edit session could easily do the same thing.

**Comment by NikkiGolding** [comment]
@jmhauck  You can edit the location. However, per the repro steps above, the edited values are not reset when the  edit button is clicked again. In other words, the edited values (without clicking save) are persisted.

**Comment by NikkiGolding** [comment]
![edit](https://user-images.githubusercontent.com/4106968/35010445-1f5bac84-fac0-11e7-9fbd-e82ff1767a88.gif)

**Comment by jmhauck** [comment]
@NikkiGolding edits will now be undone when you stop editing

**Comment by NikkiGolding** [comment]
Verified.
