### ISSUE TITLE
Network Trace - Two Error boxes when model fails

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/solutions-webappbuilder-widgets#99]
![image](https://cloud.githubusercontent.com/assets/2707285/6849534/1fa57f16-d3aa-11e4-9778-13445ea520be.png)

**Comment by MikeMillerGIS** [comment]
Also, after this, the tools does not let me rerun, the add flags is disabled.

**Comment by CTLocalGovTeam** [comment]
@MikeMillerGIS Same as #101

**Comment by MikeMillerGIS** [comment]
verified
