### ISSUE TITLE
Review panel: locate button clickable even when grayed out

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#991]
- [ ] when first opening the review panel, it seems like i can click the Locate button and something is happening even though it's grayed out. 
- [ ] after canceling or saving edits, the button is still active. 

![cf_locatebutton2](https://user-images.githubusercontent.com/6181441/32970552-568c4958-cb9e-11e7-885f-64369c54d2f9.gif)

@NikkiGolding @jmhauck fyi

**Comment by NikkiGolding** [comment]
Verified.
