### ISSUE TITLE
Fixing an unmatched record doesn't remove it from unmatched list

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#993]
not sure if this is the same as #979 

When i fix an unmatched record, it doesn't go to the matched list.

**current behavior:** feature is saved into target layer, but item remains in unmatched list

**expected behavior:** after saving changes, feature changes are stored in temp layer and item is moved to matched list

**Comment by jessnoo** [comment]
when testing this workflow as a part of #979, after the item is pushed to the matched list, when i select it in the matched list, it doesn't zoom to the expected location.

**test csv:** [MarylandHospitals_993.zip](https://github.com/Esri/solutions-webappbuilder-widgets/files/1601639/MarylandHospitals_993.zip)

**repro steps:** 

1. with a single line locator configured - load this into the widget using FACADDR field for locating
2. click to review unmatched items
3. edit the item and update the single line input to include the city and state (baltimore, md)
![image](https://user-images.githubusercontent.com/6181441/34539043-db9347be-f083-11e7-9f01-c01a2698d5f8.png)
4. verify the new location is correct and save changes
5. note matched list now has 6 items
6. click to review list >> sometimes - i get two "John hopkins hospitals, The" in the list -- i think if i load the app fresh, this happens
![image](https://user-images.githubusercontent.com/6181441/34539110-23424fd8-f084-11e7-8250-2e53eacdbf5c.png)
7. click to review john hopkins hospital information >> it doesn't take me to the correct place
![image](https://user-images.githubusercontent.com/6181441/34539137-38e446d4-f084-11e7-84f6-4923a2fb1019.png)

**Comment by NikkiGolding** [comment]
Verified movement to matched list.
