### ISSUE TITLE
Button icons disappear in white dashboard theme

### ISSUE THREAD

**Issue by jessnoo** [Esri/solutions-webappbuilder-widgets#999]
Some UI elements are not visible with the light colored dashboard theme

![image](https://user-images.githubusercontent.com/6181441/34231465-1054f48c-e591-11e7-97fc-8c7da71dc923.png)

**Comment by aparveen** [comment]
It is being tracked in devtopia. https://devtopia.esri.com/WebGIS/arcgis-webappbuilder/issues/11849
